import {isMaster} from '../../../lib/access';
import {resolveCompanyDossier} from '../../../lib/companyDossierResolver';
const BASE=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY,ANON=process.env.SUPABASE_ANON_KEY;
const headers=()=>({'Content-Type':'application/json',apikey:KEY!,Authorization:`Bearer ${KEY}`});
async function user(req:Request){const token=req.headers.get('cookie')?.match(/escala_session=([^;]+)/)?.[1];if(!token||!BASE||!ANON)return null;const response=await fetch(`${BASE}/auth/v1/user`,{headers:{apikey:ANON,Authorization:`Bearer ${token}`}});return response.ok?response.json():null}
async function get(path:string){const response=await fetch(`${BASE}/rest/v1/${path}`,{headers:headers(),cache:'no-store'});if(!response.ok)throw new Error(await response.text());return response.json()}
async function optional(path:string){try{return await get(path)}catch(error){console.warn('[dossier] Fonte opcional indisponível:',path,error);return[]}}
const contractFields=['razao_social','nome_fantasia','cpf_cnpj','endereco','cidade','estado','cep'];
export async function GET(req:Request){try{const current=await user(req);if(!current||!await isMaster(req))return Response.json({error:'Acesso exclusivo do Usuário Master'},{status:403});const id=new URL(req.url).searchParams.get('id');if(!id)return Response.json({error:'Empresa não informada'},{status:400});const companyId=encodeURIComponent(id),planRefs=await optional(`strategic_execution_plans?empresa_id=eq.${companyId}&select=id`),planFilter=planRefs.length?planRefs.map((item:any)=>item.id).join(','):'00000000-0000-0000-0000-000000000000';const [companies,diagnostics,legacyPlans,legacyImplementations,legacyJourneys,meetings,events,executionPlans,executionActions,executionHistory,commercialSituations,evolutionProjects,catalog,officialImplementations,officialImplementationItems,marketingPlans,evolutionMeasurements,evolutionMeasurementItems]=await Promise.all([
 optional(`empresas?id=eq.${companyId}&select=*,responsaveis(*)`),optional(`diagnosticos?empresa_id=eq.${companyId}&select=*&order=data_diagnostico.asc,created_at.asc`),optional(`planos_estrategicos?empresa_id=eq.${companyId}&select=*&order=created_at.asc`),optional(`planos_implantacao?empresa_id=eq.${companyId}&select=*&order=created_at.asc`),optional(`implantacoes?empresa_id=eq.${companyId}&select=*&order=created_at.asc`),optional(`reunioes_estrategicas?empresa_id=eq.${companyId}&select=*&order=created_at.asc`),optional(`dossie_eventos?empresa_id=eq.${companyId}&select=*&order=data_evento.asc`),optional(`strategic_execution_plans?empresa_id=eq.${companyId}&select=*&order=version_number.asc`),optional(`strategic_execution_plan_actions?plan_id=in.(${planFilter})&select=*`),optional(`strategic_execution_plan_history?plan_id=in.(${planFilter})&select=*`),optional(`situacoes_comerciais_versoes?empresa_id=eq.${companyId}&select=*&order=versao.desc`),optional(`projetos_evolucao?empresa_id=eq.${companyId}&select=*,projeto_evolucao_recursos(*)&order=updated_at.desc,created_at.desc`),optional('catalogo_recursos?select=id,codigo,nome,categoria,tipo,ativo'),optional(`strategic_plan_implementations?empresa_id=eq.${companyId}&select=*&order=created_at.desc`),optional('strategic_plan_implementation_items?select=*'),optional(`planejamentos_campanhas?empresa_id=eq.${companyId}&select=*&order=updated_at.desc`),optional(`strategic_evolution_measurements?empresa_id=eq.${companyId}&select=*&order=measured_at.asc,created_at.asc`),optional('strategic_evolution_measurement_items?select=*')]);
 const company=companies[0];if(!company)return Response.json({error:'Empresa não encontrada'},{status:404});return Response.json(resolveCompanyDossier({company,diagnostics,legacyPlans,legacyImplementations,legacyJourneys,meetings,events,executionPlans,executionActions,executionHistory,commercialSituations,evolutionProjects,catalog,officialImplementations,officialImplementationItems:officialImplementationItems.filter((item:any)=>officialImplementations.some((implementation:any)=>implementation.id===item.implementation_id)),marketingPlans,evolutionMeasurements,evolutionMeasurementItems:evolutionMeasurementItems.filter((item:any)=>evolutionMeasurements.some((measurement:any)=>measurement.id===item.measurement_id))}),{headers:{'Cache-Control':'no-store, max-age=0'}})}catch(error:any){console.error('[dossier] Falha ao consolidar',error);return Response.json({error:error?.message||'Não foi possível carregar o Dossiê Executivo.'},{status:500})}}
export async function PATCH(req:Request){try{const current=await user(req);if(!current||!await isMaster(req))return Response.json({error:'Acesso exclusivo do Usuário Master'},{status:403});const body=await req.json(),id=body.id;if(!id)return Response.json({error:'Empresa não informada'},{status:400});if(body.radar_comercial_url&&!/^https?:\/\//i.test(String(body.radar_comercial_url)))return Response.json({error:'Informe uma URL válida iniciada por http:// ou https://.'},{status:400});if(body.radar_comercial_status&&!['Não configurado','Em configuração','Ativo','Inativo'].includes(body.radar_comercial_status))return Response.json({error:'Status do Dashboard Executivo inválido.'},{status:400});const allowed=['observacoes_internas','proxima_missao','consultor_responsavel','meta_ieg','status_implantacao','radar_comercial_url','radar_comercial_status',...contractFields],data:any=Object.fromEntries(allowed.filter(key=>body[key]!==undefined).map(key=>[key,body[key]]));if(contractFields.some(field=>body[field]!==undefined))data.dados_contratuais_revisados_em=new Date().toISOString();const response=await fetch(`${BASE}/rest/v1/empresas?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify({...data,updated_at:new Date().toISOString()})});return new Response(await response.text(),{status:response.status,headers:{'Content-Type':'application/json; charset=utf-8'}})}catch(error:any){return Response.json({error:error?.message||'Não foi possível atualizar o dossiê.'},{status:500})}}
