import {isMaster} from '../../../lib/access';

const URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const headers=()=>({'Content-Type':'application/json','apikey':KEY!,'Authorization':`Bearer ${KEY}`});
async function db(path:string,init?:RequestInit){const response=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:{...headers(),...(init?.headers||{})},cache:'no-store'});if(!response.ok)throw new Error(await response.text());const text=await response.text();return text?JSON.parse(text):[]}
async function auth(req:Request){if(await isMaster(req))return{role:'master',empresa_id:null};const token=req.headers.get('cookie')?.match(/escala_session=([^;]+)/)?.[1];if(!token||!URL||!process.env.SUPABASE_ANON_KEY)return null;const response=await fetch(`${URL}/auth/v1/user`,{headers:{apikey:process.env.SUPABASE_ANON_KEY,Authorization:`Bearer ${token}`}});if(!response.ok)return null;const user=await response.json(),rows=await db(`portal_usuarios?auth_user_id=eq.${encodeURIComponent(user.id)}&select=empresa_id,perfil&limit=1`);return rows[0]?{role:'cliente',empresa_id:rows[0].empresa_id}:null}
const amount=(value:unknown)=>Math.max(0,Number(value)||0);
async function context(empresaId:string){const id=encodeURIComponent(empresaId);const [versions,projects,catalog,contracts,payments]=await Promise.all([db(`situacoes_comerciais_versoes?empresa_id=eq.${id}&select=*&order=versao.desc`),db(`projetos_evolucao?empresa_id=eq.${id}&select=*,projeto_evolucao_recursos(*)&order=created_at.desc`),db('catalogo_recursos?ativo=eq.true&select=id,codigo,nome,tipo,valor_mensal,valor_avulso,ui,categoria&order=nome'),db(`contratos_growth?empresa_id=eq.${id}&select=*&order=created_at.desc&limit=1`),db(`pagamentos_growth?empresa_id=eq.${id}&select=*&order=created_at.desc&limit=1`)]);const current=versions.find((row:any)=>row.vigente)||{mensalidade:0,recursos:[],contrato_status:contracts[0]?.status||'Sem contrato vigente',status_pagamento:payments[0]?.status||'Sem cobrança vigente',prazo_meses:12};return{current,history:versions,projects,catalog}}

export async function GET(req:Request){try{const identity=await auth(req);if(!identity)return Response.json({error:'Não autorizado.'},{status:403});const requested=new URL(req.url).searchParams.get('empresa_id'),empresaId=identity.role==='master'?requested:identity.empresa_id;if(!empresaId)return Response.json({error:'Empresa não informada.'},{status:400});return Response.json(await context(empresaId))}catch(error:any){return Response.json({error:error?.message||'Não foi possível carregar o histórico comercial.'},{status:500})}}

export async function POST(req:Request){try{if(!await isMaster(req))return Response.json({error:'Acesso exclusivo do Usuário Master.'},{status:403});const body=await req.json(),empresaId=String(body.empresa_id||'');if(!empresaId)return Response.json({error:'Empresa não informada.'},{status:400});const current=(await context(empresaId)).current,monthly=amount(current.mensalidade),payload={empresa_id:empresaId,nome:String(body.nome||'Novo Projeto de Evolução'),tipo:body.tipo||'Novo recurso',descricao:body.descricao||null,objetivo:body.objetivo||null,status:'Em elaboração',mensalidade_atual:monthly,mensalidade_adicional:amount(body.mensalidade_adicional),desconto_recorrente:amount(body.desconto_recorrente),valor_implantacao_adicional:amount(body.valor_implantacao_adicional),implantacao_modalidade:body.implantacao_modalidade||'Sem cobrança',data_inicio:body.data_inicio||null,observacoes_internas:body.observacoes_internas||null,exige_contrato:Boolean(body.exige_contrato),exige_aditivo:Boolean(body.exige_aditivo),exige_aceite:body.exige_aceite!==false,exige_pagamento:Boolean(body.exige_pagamento),forma_cobranca:body.forma_cobranca||'Sem pagamento imediato',formalizacao:body.formalizacao||'Aceite eletrônico',criado_por:body.criado_por||'Usuário Master'},saved=await db('projetos_evolucao',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)}),project=saved[0];if(Array.isArray(body.recursos)&&body.recursos.length){await db('projeto_evolucao_recursos',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body.recursos.map((item:any)=>({projeto_evolucao_id:project.id,recurso_id:item.id,nome_snapshot:item.nome,tipo_snapshot:item.tipo,movimento:item.movimento||'Adicionar',valor_implantacao:amount(item.valor_implantacao),valor_mensal:amount(item.valor_mensal)})))})}return Response.json({ok:true,project}, {status:201})}catch(error:any){return Response.json({error:error?.message||'Não foi possível criar o Projeto de Evolução.'},{status:500})}}

export async function PATCH(req:Request){try{if(!await isMaster(req))return Response.json({error:'Acesso exclusivo do Usuário Master.'},{status:403});const body=await req.json(),id=String(body.id||'');if(!id)return Response.json({error:'Projeto não informado.'},{status:400});const existing=(await db(`projetos_evolucao?id=eq.${encodeURIComponent(id)}&select=*&limit=1`))[0];if(!existing)return Response.json({error:'Projeto não encontrado.'},{status:404});const action=String(body.action||'save'),now=new Date().toISOString();if(action==='formalize'){const resources=await db(`projeto_evolucao_recursos?projeto_evolucao_id=eq.${encodeURIComponent(id)}&select=*`),versions=await db(`situacoes_comerciais_versoes?empresa_id=eq.${encodeURIComponent(existing.empresa_id)}&select=versao&order=versao.desc&limit=1`);await db(`situacoes_comerciais_versoes?empresa_id=eq.${encodeURIComponent(existing.empresa_id)}&vigente=eq.true`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({vigente:false})});const start=existing.data_inicio||now.slice(0,10),renewal=new Date(`${start}T12:00:00Z`);renewal.setUTCFullYear(renewal.getUTCFullYear()+1);await db('situacoes_comerciais_versoes',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({empresa_id:existing.empresa_id,projeto_evolucao_id:id,versao:Number(versions[0]?.versao||0)+1,vigente:true,mensalidade:existing.nova_mensalidade,forma_pagamento:existing.forma_cobranca,status_pagamento:existing.exige_pagamento?'Aguardando confirmação':'Sem novo pagamento',contrato_status:'Ativo',contrato_inicio:start,prazo_meses:12,renovacao_em:renewal.toISOString().slice(0,10),recursos,snapshot:{project:existing,resources}})});await db(`projetos_evolucao?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:existing.exige_pagamento?'Aguardando pagamento':'Formalizado sem novo pagamento',formalizado_em:now,updated_at:now})});return Response.json({ok:true})}const allowed=['nome','tipo','descricao','objetivo','status','valor_implantacao_adicional','implantacao_modalidade','mensalidade_adicional','desconto_recorrente','data_inicio','observacoes_internas','exige_contrato','exige_aditivo','exige_aceite','exige_pagamento','forma_cobranca','formalizacao'],update=Object.fromEntries(allowed.filter(key=>body[key]!==undefined).map(key=>[key,body[key]]));await db(`projetos_evolucao?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({...update,updated_at:now})});return Response.json({ok:true})}catch(error:any){return Response.json({error:error?.message||'Não foi possível atualizar o Projeto de Evolução.'},{status:500})}}
