'use client';
import {useEffect,useState} from 'react';
const statuses=['Diagnóstico Concluído','Reunião Agendada','Plano Estratégico em Elaboração','Plano Estratégico Apresentado','Proposta Enviada','Implantação','Acompanhamento','Evolução','Cliente'];
export default function Consultoria(){
 const [key,setKey]=useState(''),[items,setItems]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[error,setError]=useState('');
 const call=async(url:string,init:RequestInit={})=>{const r=await fetch(url,{...init,headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`,...(init.headers||{})}});if(!r.ok)throw new Error((await r.json()).error||'Erro');return r.json()};
 const load=async()=>{try{setItems(await call('/api/diagnostics'));sessionStorage.setItem('consultoria-key',key);setError('')}catch(e:any){setError(e.message)}};
 useEffect(()=>{setKey(sessionStorage.getItem('consultoria-key')||'')},[]);
 const open=async(id:string)=>setSelected((await call('/api/diagnostics?id='+id))[0]);
 const save=async(body:any)=>{await call('/api/diagnostics',{method:'PATCH',body:JSON.stringify({id:selected.id,...body})});await open(selected.id);await load()};
 if(!items.length&&!selected)return <main className="admin-login"><div className="admin-card"><span className="eyebrow">Escala Vendas</span><h1>Consultoria</h1><p>Área interna para preparação das reuniões estratégicas.</p><input type="password" placeholder="Chave de acesso" value={key} onChange={e=>setKey(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/><button className="btn btn-primary" onClick={load}>Entrar</button>{error&&<p className="error">{error}</p>}</div></main>;
 if(selected){const plan=selected.planos_estrategicos?.[0]||{};return <main className="admin-shell"><button className="btn btn-secondary" onClick={()=>setSelected(null)}>← Diagnósticos</button><div className="admin-title"><div><span className="eyebrow">Preparação consultiva</span><h1>{selected.empresas?.nome}</h1><p>{selected.responsaveis?.nome} · IEG {selected.pontuacao_geral}/100</p></div><select value={selected.status} onChange={e=>save({status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></div><div className="admin-metrics"><b>Gargalo<span>{selected.menor_pilar}</span></b><b>Maior força<span>{selected.maior_pilar}</span></b><b>Potencial<span>{selected.potencial_crescimento}</span></b><b>Nível<span>{selected.nivel_maturidade}</span></b></div><section className="admin-section"><h2>Relatório completo</h2><pre>{JSON.stringify(selected.relatorio_snapshot,null,2)}</pre></section><section className="admin-section"><h2>Respostas e radar</h2><pre>{JSON.stringify({respostas:selected.respostas,abertas:selected.respostas_abertas,radar:selected.resultados_pilares},null,2)}</pre></section><section className="admin-section"><h2>Histórico</h2>{selected.diagnostico_status_historico?.map((x:any)=><p key={x.id}>{new Date(x.created_at).toLocaleString('pt-BR')} · {x.status}</p>)}</section><PlanEditor plan={plan} save={save}/></main>}
 return <main className="admin-shell"><div className="admin-title"><div><span className="eyebrow">Escala Vendas</span><h1>Consultoria</h1><p>Diagnósticos e preparação estratégica.</p></div></div><div className="admin-table"><div className="admin-row head"><b>Empresa</b><b>Responsável</b><b>IEG</b><b>Maior Gargalo</b><b>Potencial</b><b>Data</b><b>Status</b></div>{items.map(x=><button className="admin-row" key={x.id} onClick={()=>open(x.id)}><span>{x.empresas?.nome}</span><span>{x.responsaveis?.nome}</span><span>{x.pontuacao_geral}</span><span>{x.menor_pilar}</span><span>{x.potencial_crescimento}</span><span>{new Date(x.data_diagnostico+'T12:00:00').toLocaleDateString('pt-BR')}</span><span>{x.status}</span></button>)}</div></main>
}
function PlanEditor({plan,save}:{plan:any;save:(x:any)=>Promise<void>}){const [draft,setDraft]=useState(plan);useEffect(()=>setDraft(plan),[plan]);const fields=['resumo','situacao_atual','objetivos','prioridades','riscos','cronograma','proximos_passos','observacoes'];return <section className="admin-section plan-editor"><div><h2>Plano Estratégico Escala Growth</h2><button className="btn btn-primary" onClick={()=>save({plano:draft,observacoes:draft.observacoes})}>Salvar rascunho</button></div>{fields.map(f=><label key={f}>{f.replaceAll('_',' ')}<textarea rows={4} value={draft[f]||''} onChange={e=>setDraft({...draft,[f]:e.target.value})}/></label>)}</section>}

