import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {acquisitionReadiness,acquisitionStrategy,attractionNeed,evidenceFromAnswerMap} from '../lib/evidenceEngine.ts';

const need=(demand,predictability,strategy,reactivation)=>attractionNeed(evidenceFromAnswerMap(Object.fromEntries([['atrair-5',demand],['atrair-6',predictability],['atrair-7',strategy],['atrair-8',reactivation]].filter(([,value])=>value!==undefined))));
const readiness=(classification)=>({available:true,classification,score_base:classification==='ALTA'?80:classification==='MEDIA'?60:30,classification_before_limiters:classification,interpretation:'',components_used:[],components_missing:[],limiters:[],indicator_code:'ACQUISITION_READINESS',evidence_engine_version:'1.0',readiness_engine_version:'1.0'});

test('1. necessidade alta: maturidade 19% e necessidade 81%',()=>{const result=need(0,0,1,2);assert.equal(result.generation_maturity,19);assert.equal(result.need_score,81);assert.equal(result.classification,'ALTA')});
test('2. quatro componentes em 2 resultam em necessidade média de 50%',()=>{const result=need(2,2,2,2);assert.equal(result.generation_maturity,50);assert.equal(result.need_score,50);assert.equal(result.classification,'MEDIA')});
test('3. estrutura 4,4,3,3 resulta em necessidade baixa',()=>{const result=need(4,4,3,3);assert.equal(result.generation_maturity,88);assert.equal(result.need_score,13);assert.equal(result.classification,'BAIXA')});
test('4. demanda forte limita a necessidade ao nível máximo médio',()=>{const result=need(4,1,1,1);assert.equal(result.classification_before_rules,'MEDIA');assert.equal(result.classification,'MEDIA');assert.match(result.dominant_rules.join(' '),/Volume atual suficiente/)});
test('5. demanda e previsibilidade críticas mantêm necessidade alta',()=>{const result=need(1,1,2,2);assert.equal(result.classification,'ALTA');assert.match(result.dominant_rules.join(' '),/Baixo volume combinado/)});
test('6. quatro componentes fortes limitam necessidade ao nível baixo',()=>{const result=need(3,3,3,3);assert.equal(result.classification,'BAIXA');assert.match(result.dominant_rules.join(' '),/quatro componentes/)});
test('7. apenas dois componentes resultam em dados insuficientes',()=>{const result=need(1,1,undefined,undefined);assert.equal(result.available,false);assert.equal(result.classification,null);assert.equal(result.components_used.length,2)});
test('8. necessidade alta com prontidão baixa resulta em Estruturar para Expandir',()=>{const result=acquisitionStrategy(need(0,0,1,2),readiness('BAIXA'));assert.equal(result.status,'ESTRUTURAR PARA EXPANDIR');assert.doesNotMatch(result.reading,/Google|Meta|CRM|Landing|WhatsApp/i)});
test('9. as nove combinações estratégicas estão disponíveis sem recomendar soluções',()=>{const expected={ALTA:{ALTA:'EXPANDIR AQUISIÇÃO',MEDIA:'EXPANDIR COM AJUSTES',BAIXA:'ESTRUTURAR PARA EXPANDIR'},MEDIA:{ALTA:'OTIMIZAR AQUISIÇÃO',MEDIA:'EVOLUIR EM CONJUNTO',BAIXA:'ESTRUTURAR ANTES DE ACELERAR'},BAIXA:{ALTA:'OTIMIZAR E MONITORAR',MEDIA:'FORTALECER OPERAÇÃO',BAIXA:'ESTRUTURAR OPERAÇÃO'}};for(const [needClass,row] of Object.entries(expected))for(const [readyClass,status] of Object.entries(row)){const result=acquisitionStrategy({classification:needClass},readiness(readyClass));assert.equal(result.status,status)}const source=fs.readFileSync(new URL('../lib/evidenceEngine.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/catalogo_recursos|Gestão Google Ads|Gestão Meta Ads|CRM Comercial|Landing Page|Campanhas WhatsApp/)});
test('10. Briefing exibe os dois indicadores, a matriz e o debug da necessidade',()=>{const component=fs.readFileSync(new URL('../components/DiagnosticConsultantBriefing.tsx',import.meta.url),'utf8');assert.match(component,/Necessidade de Atrair/);assert.match(component,/Leitura estratégica da aquisição/);assert.match(component,/Fatores que aumentam a necessidade/);assert.match(component,/Pontos de maturidade a observar/);assert.match(component,/Maturidade de geração/)});
