import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
function load(file,stubs={}){const source=fs.readFileSync(file,'utf8'),js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,module={exports:{}};vm.runInNewContext(`(function(require,module,exports){${js}\n})(require,module,module.exports)`,{require:(id)=>stubs[id]||{},module,exports:module.exports,Set,Map,Error});return module.exports}
const pricing=load('lib/commercialPricingResolver.ts'),existing=load('lib/existingResourceResolver.ts',{'./commercialPricingResolver':pricing}),nimble=load('lib/nimbleStructure.ts'),dep=load('lib/commercialDependencyResolver.ts',{'./nimbleStructure':nimble,'./existingResourceResolver':existing});
const s=(id,tipo='Mensalidade',extra={})=>({id,nome:id,tipo,valor_mensal:tipo==='Implantação'?null:100,ui:tipo==='Mensalidade'?null:3,ativo:true,...extra});
test('estrutura Nimble tolera solução ainda não resolvida sem derrubar o Dossiê',()=>{assert.equal(nimble.usesNimbleStructure(undefined),false);assert.equal(nimble.usesNimbleStructure(null),false)});
test('recursos-base Nimble nunca reativam a própria estrutura',()=>{for(const codigo of ['AUT-001','TRN-001','PLA-001'])assert.equal(nimble.usesNimbleStructure(s(codigo,'Implantação',{codigo,utiliza_plataforma_nimble:true})),false)});
test('mensalidade resolve implantação e calcula UI uma vez',()=>{const impl=s('Implantação','Implantação'),crm=s('CRM','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'Implantação',obrigatoriedade:'OBRIGATORIA',ordem:1,ativo:true}]});const out=dep.resolveCommercialDependencies({selectedSolutionIds:['CRM'],catalog:[crm,impl]});assert.equal(out.length,1);assert.equal(pricing.resolveCommercialPrice(out[0].solution,250).valor_implantacao,750)});
test('dependência compartilhada é deduplicada e rastreável',()=>{const shared=s('Implantação','Implantação'),a=s('A','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'Implantação'}]}),b=s('B','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'Implantação'}]});const out=dep.resolveCommercialDependencies({selectedSolutionIds:['A','B'],catalog:[a,b,shared]});assert.equal(out.length,1);assert.deepEqual([...out[0].parent_solution_ids].sort(),['A','B'])});
test('dependência recursiva válida',()=>{const c=s('C','Implantação'),b=s('B','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'C'}]}),a=s('A','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'B'}]});assert.equal(dep.resolveCommercialDependencies({selectedSolutionIds:['A'],catalog:[a,b,c]}).map(x=>x.recurso_id).sort().join(','),'B,C')});
test('ciclo é bloqueado com erro administrativo',()=>{const a=s('A','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'B'}]}),b=s('B','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'A'}]});assert.throws(()=>dep.resolveCommercialDependencies({selectedSolutionIds:['A'],catalog:[a,b]}),/Dependência circular/)});
test('recurso mensal não gera implantação',()=>assert.equal(pricing.resolveCommercialPrice(s('Licença'),250).valor_implantacao,0));
test('CRM com estrutura Nimble resolve AUT-001, TRN-001 e PLA-001 pela fonte canônica',()=>{const crm=s('CRM','Mensalidade',{codigo:'CRM-001',valor_mensal:150,utiliza_plataforma_nimble:true}),dashboard=s('DASH','Mensalidade',{codigo:'DAT-001',valor_mensal:150}),aut=s('AUT','Implantação',{codigo:'AUT-001',ui:3}),trn=s('TRN','Implantação',{codigo:'TRN-001',ui:3}),pla=s('PLA','Mensalidade',{codigo:'PLA-001',valor_mensal:930}),out=dep.resolveCommercialDependencies({selectedSolutionIds:['CRM','DASH'],catalog:[crm,dashboard,aut,trn,pla]}),ids=out.map(x=>x.solution.codigo).sort(),implementation=out.reduce((sum,x)=>sum+pricing.resolveCommercialPrice(x.solution,250).valor_implantacao,0),monthly=[crm,dashboard,...out].reduce((sum,x)=>sum+pricing.resolveCommercialPrice(x.solution||x,250).valor_mensal,0);assert.equal(ids.join(','),'AUT-001,PLA-001,TRN-001');assert.equal(implementation,1500);assert.equal(monthly,1230);assert.ok(out.every(x=>x.parent_solution_ids.includes('CRM')));assert.ok(out.every(x=>x.dependency_source.some(source=>source.includes('ESTRUTURA_CANONICA_PLATAFORMA_NIMBLE'))));assert.equal(pricing.resolveCommercialPrice(pla,250).valor_implantacao,0)});
test('recurso Nimble já selecionado permanece deduplicado e recebe rastreabilidade',()=>{const crm=s('CRM','Mensalidade',{codigo:'CRM-001',utiliza_plataforma_nimble:true}),aut=s('AUT','Implantação',{codigo:'AUT-001'}),trn=s('TRN','Implantação',{codigo:'TRN-001'}),pla=s('PLA','Mensalidade',{codigo:'PLA-001'}),out=dep.resolveCommercialDependencies({selectedSolutionIds:['CRM','PLA'],catalog:[crm,aut,trn,pla]}),license=out.find(x=>x.recurso_id==='PLA');assert.equal(out.filter(x=>x.recurso_id==='PLA').length,1);assert.ok(license.parent_solution_ids.includes('CRM'))});
test('PLA-001 vigente permanece visível sem nova contratação ou mensalidade',()=>{const crm=s('CRM','Mensalidade',{codigo:'CRM-001',utiliza_plataforma_nimble:true}),aut=s('AUT','Implantação',{codigo:'AUT-001'}),trn=s('TRN','Implantação',{codigo:'TRN-001'}),pla=s('PLA','Mensalidade',{codigo:'PLA-001',valor_mensal:930}),resources=existing.resolveCanonicalExistingResources({catalog:[crm,aut,trn,pla],commercialResources:[{recurso_id:'PLA'}]}),out=dep.resolveCommercialDependencies({selectedSolutionIds:['CRM'],catalog:[crm,aut,trn,pla],existingResources:resources}),license=out.find(x=>x.recurso_id==='PLA');assert.equal(license.commercial_classification,'JA_EXISTENTE');assert.equal(license.existing_resource.recurring,true)});
test('PLA-001 ausente é incluída como nova contratação',()=>{const crm=s('CRM','Mensalidade',{codigo:'CRM-001',utiliza_plataforma_nimble:true}),aut=s('AUT','Implantação',{codigo:'AUT-001'}),trn=s('TRN','Implantação',{codigo:'TRN-001'}),pla=s('PLA','Mensalidade',{codigo:'PLA-001'}),out=dep.resolveCommercialDependencies({selectedSolutionIds:['CRM'],catalog:[crm,aut,trn,pla],existingResources:[]});assert.equal(out.find(x=>x.recurso_id==='PLA').commercial_classification,'NOVA_CONTRATACAO')});
test('revisão distingue implantado, parcial e evolução usando códigos canônicos',()=>{const ia=s('IA','Implantação',{codigo:'IA-001'}),dash=s('DASH','Implantação',{codigo:'DAT-001'}),pla=s('PLA','Mensalidade',{codigo:'PLA-001'}),out=existing.resolveCanonicalExistingResources({catalog:[ia,dash,pla],adaptiveRecommendations:[{recurso_codigo:'IA-001',status_recurso:'Implantado',recomendacao_validada:'Agente de IA'},{recurso_codigo:'DAT-001',status_recurso:'Parcialmente Implantado',recomendacao_validada:'Concluir Dashboard'},{recurso_codigo:'PLA-001',status_recurso:'Implantado',recomendacao_validada:'Otimizar Plataforma Nimble'}]});assert.equal(out.find(x=>x.recurso_id==='IA').state,'IMPLANTADO');assert.equal(out.find(x=>x.recurso_id==='DASH').state,'PARCIALMENTE_IMPLANTADO');assert.equal(out.find(x=>x.recurso_id==='PLA').state,'EVOLUCAO')});
