import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
function load(file,stubs={}){const source=fs.readFileSync(file,'utf8'),js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,module={exports:{}};vm.runInNewContext(`(function(require,module,exports){${js}\n})(require,module,module.exports)`,{require:(id)=>stubs[id]||{},module,exports:module.exports,Set,Map,Error});return module.exports}
const dep=load('lib/commercialDependencyResolver.ts'),pricing=load('lib/commercialPricingResolver.ts');
const s=(id,tipo='Mensalidade',extra={})=>({id,nome:id,tipo,valor_mensal:tipo==='Implantação'?null:100,ui:tipo==='Mensalidade'?null:3,ativo:true,...extra});
test('mensalidade resolve implantação e calcula UI uma vez',()=>{const impl=s('Implantação','Implantação'),crm=s('CRM','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'Implantação',obrigatoriedade:'OBRIGATORIA',ordem:1,ativo:true}]});const out=dep.resolveCommercialDependencies({selectedSolutionIds:['CRM'],catalog:[crm,impl]});assert.equal(out.length,1);assert.equal(pricing.resolveCommercialPrice(out[0].solution,250).valor_implantacao,750)});
test('dependência compartilhada é deduplicada e rastreável',()=>{const shared=s('Implantação','Implantação'),a=s('A','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'Implantação'}]}),b=s('B','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'Implantação'}]});const out=dep.resolveCommercialDependencies({selectedSolutionIds:['A','B'],catalog:[a,b,shared]});assert.equal(out.length,1);assert.deepEqual([...out[0].parent_solution_ids].sort(),['A','B'])});
test('dependência recursiva válida',()=>{const c=s('C','Implantação'),b=s('B','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'C'}]}),a=s('A','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'B'}]});assert.equal(dep.resolveCommercialDependencies({selectedSolutionIds:['A'],catalog:[a,b,c]}).map(x=>x.recurso_id).sort().join(','),'B,C')});
test('ciclo é bloqueado com erro administrativo',()=>{const a=s('A','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'B'}]}),b=s('B','Mensalidade',{dependencias_estruturadas:[{tipo:'solucao',recurso_id:'A'}]});assert.throws(()=>dep.resolveCommercialDependencies({selectedSolutionIds:['A'],catalog:[a,b]}),/Dependência circular/)});
test('recurso mensal não gera implantação',()=>assert.equal(pricing.resolveCommercialPrice(s('Licença'),250).valor_implantacao,0));
