import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
function load(file){const source=fs.readFileSync(file,'utf8'),js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,module={exports:{}},require=()=>({});vm.runInNewContext(`(function(require,module,exports){${js}\n})(require,module,module.exports)`,{require,module,exports:module.exports,Set,Map,Date,Number,String,Array,Object,Boolean,Math,console});return module.exports}
const{resolveCompanyDossier,deduplicateDossierEvents}=load('lib/companyDossierResolver.ts'),company={id:'empresa-1',nome:'Empresa',meta_ieg:85},diagnostic={id:'diag',empresa_id:'empresa-1',pontuacao_geral:70,data_diagnostico:'2026-08-01'};
const base=(patch={})=>({company,diagnostics:[diagnostic],executionPlans:[],executionActions:[],commercialSituations:[],evolutionProjects:[],catalog:[],officialImplementations:[],officialImplementationItems:[],marketingPlans:[],evolutionMeasurements:[],evolutionMeasurementItems:[],...patch});
test('PUBLISHED permanece vigente e DRAFT posterior aparece como preparação',()=>{const result=resolveCompanyDossier(base({executionPlans:[{id:'p1',status:'PUBLISHED',version_number:1,published_at:'2026-08-01',published_snapshot:{actions:[]}},{id:'p2',status:'DRAFT',version_number:2,created_at:'2026-08-02'}]}));assert.equal(result.current_plan.id,'p1');assert.equal(result.draft_plan.id,'p2');assert.equal(result.current_strategy.state,'VIGENTE')});
test('somente DRAFT nunca é chamado de vigente',()=>{const result=resolveCompanyDossier(base({executionPlans:[{id:'p2',status:'DRAFT',version_number:2,created_at:'2026-08-02'}]}));assert.equal(result.current_plan,null);assert.match(result.draft_plan.label,/ainda não publicado/);assert.equal(result.current_strategy.state,'EM_PREPARACAO')});
test('Situação vigente não recebe valores do Projeto em rascunho',()=>{const result=resolveCompanyDossier(base({commercialSituations:[{id:'s1',vigente:true,mensalidade:500,recursos:[]}],evolutionProjects:[{id:'e1',status:'Rascunho',mensalidade_adicional:300,nova_mensalidade:800,projeto_evolucao_recursos:[]}]}));assert.equal(result.current_commercial_situation.mensalidade,500);assert.equal(result.active_evolution_project.nova_mensalidade,800)});
test('recursos adicionais aparecem somente na evolução proposta',()=>{const resource={id:'r1',movimento:'Adicionar',nome_snapshot:'CRM'};const result=resolveCompanyDossier(base({commercialSituations:[{id:'s1',vigente:true,recursos:[]}],evolutionProjects:[{id:'e1',status:'Rascunho',projeto_evolucao_recursos:[resource]}]}));assert.equal(result.current_commercial_situation.resources.length,0);assert.equal(result.active_evolution_project.resources.add.length,1)});
test('Marketing de outra empresa nunca aparece',()=>{const result=resolveCompanyDossier(base({marketingPlans:[{id:'m1',empresa_id:'outra',investimento_aprovado:999}]}));assert.equal(result.marketing_summary.configured,false);assert.equal(result.marketing_summary.total_investment,0)});
test('recurso ativo resolve categoria exclusivamente por recurso_id',()=>{const result=resolveCompanyDossier(base({commercialSituations:[{vigente:true,recursos:[{recurso_id:'r1',nome_snapshot:'Antigo'}]}],catalog:[{id:'r1',nome:'CRM Comercial',categoria:'Gestão Comercial'}]}));assert.equal(result.current_commercial_situation.resources[0].nome,'CRM Comercial');assert.equal(result.current_commercial_situation.resources[0].categoria,'Gestão Comercial')});
test('implantação oficial e legado não são combinados',()=>{const result=resolveCompanyDossier(base({officialImplementations:[{id:'oficial',empresa_id:'empresa-1',created_at:'2026-08-02'}],legacyImplementations:[{id:'legado',status:'Concluído'}]}));assert.equal(result.current_implementation.id,'oficial');assert.equal(result.legacy.implementations[0].id,'legado')});
test('timeline remove evento equivalente por identidade estável',()=>{const events=deduplicateDossierEvents([{id:'1',tipo:'plano',entidade_id:'p1',evento:'publicado',titulo:'Plano',data_evento:'2026-01-01'},{id:'2',tipo:'plano',entidade_id:'p1',evento:'publicado',titulo:'Plano repetido',data_evento:'2026-01-02'}]);assert.equal(events.length,1)});
test('diagnósticos e documentos legados permanecem acessíveis e leitura é pura',()=>{const input=base({legacyPlans:[{id:'old',status:'Concluído',created_at:'2025-01-01'}],diagnostics:[{...diagnostic,relatorio_pdf:'relatorio.pdf'}]}),before=JSON.stringify(input),result=resolveCompanyDossier(input);assert.ok(result.documents.some(item=>item.url==='relatorio.pdf'));assert.ok(result.documents.some(item=>item.legacy));assert.equal(JSON.stringify(input),before)});
