import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
function load(file){const source=fs.readFileSync(file,'utf8'),js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,module={exports:{}},require=()=>({});vm.runInNewContext(`(function(require,module,exports){${js}\n})(require,module,module.exports)`,{require,module,exports:module.exports,Array,Object,String,Boolean,Set,Map});return module.exports}
const rules=load('lib/contractPreparation.ts'),completeCompany={razao_social:'Empresa Ltda',cpf_cnpj:'00.000.000/0001-00',endereco:'Rua A',cidade:'Curitiba',estado:'PR',cep:'80000-000'},completeResponsible={nome:'Pessoa',email:'pessoa@empresa.com',telefone:'41999999999'},project={formalizacao:'Termo de adesão'};
test('dados incompletos mantêm Contrato e publicação pendentes',()=>{assert.equal(rules.contractDataComplete({},{}),false);const documentReady=rules.formalizationReady(project,null,{}, {},()=>true);assert.equal(documentReady,false);assert.equal(rules.publicationReady({plan:{},project,financialReady:true,documentReady,contractDataComplete:false}),false)});
test('dados completos e formalização definida permitem preparação',()=>{const documentReady=rules.formalizationReady(project,null,completeCompany,completeResponsible,()=>true);assert.equal(documentReady,true);assert.equal(rules.publicationReady({plan:{id:'p'},project,financialReady:true,documentReady,contractDataComplete:true}),true)});
test('alteração posterior revalida e volta ao estado pendente',()=>{assert.equal(rules.contractDataComplete(completeCompany,completeResponsible),true);assert.equal(rules.contractDataComplete({...completeCompany,cep:''},completeResponsible),false)});
test('campos pré-existentes são carregados e falha preserva formulário',()=>{const component=fs.readFileSync('components/ContractDataPanel.tsx','utf8');assert.match(component,/setForm\(\{\.\.\.body\.company/);assert.doesNotMatch(component,/setForm\(\{\}\).*catch/s);assert.match(component,/Os campos foram preservados|Não foi possível salvar/)});
test('pré-visualização permanece disponível com aviso e publicação bloqueada',()=>{const api=fs.readFileSync('app/api/client-access/route.ts','utf8'),component=fs.readFileSync('components/ClientAreaPanel.tsx','utf8');assert.match(api,/preview_available:Boolean\(diagnostic\|\|project\)/);assert.match(api,/Pré-visualização disponível, mas a Área do Cliente ainda não pode ser publicada/);assert.match(component,/data\.preview_warning/)});
test('seção contratual fica entre consolidação e publicação',()=>{const component=fs.readFileSync('components/ClientAreaPanel.tsx','utf8'),consolidation=component.indexOf('<CommercialConsolidationPanel'),contract=component.indexOf('<ContractDataPanel'),publication=component.lastIndexOf('<section id="company-publication"');assert.ok(consolidation>-1&&contract>consolidation&&publication>contract)});
test('fontes comerciais, snapshots e pagamentos não foram alterados pela regra',()=>{const rulesSource=fs.readFileSync('lib/contractPreparation.ts','utf8');for(const term of ['commercial_3_0','snapshot','pagamentos_growth','situacoes_comerciais_versoes'])assert.doesNotMatch(rulesSource,new RegExp(term))});
