import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';

function load(file,stubs={}){const source=fs.readFileSync(file,'utf8'),js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,module={exports:{}};vm.runInNewContext(`(function(require,module,exports){${js}\n})(require,module,module.exports)`,{require:id=>stubs[id]||{},module,exports:module.exports,Set,Map,Error,String,Array,Object,Number,Boolean,RegExp});return module.exports}
const prescription=load('lib/resourcePrescriptionResolver.ts'),pricing=load('lib/commercialPricingResolver.ts'),nimble=load('lib/nimbleStructure.ts'),dependencies=load('lib/commercialDependencyResolver.ts',{'./nimbleStructure':nimble}),solutions=load('lib/strategicSolutionResolver.ts',{'./commercialPricingResolver':pricing,'./commercialDependencyResolver':dependencies});
const catalog=[{id:'ia',codigo:'IA-001',nome:'Ativação e Treinamento de Agente de IA',tipo:'Implantação',ui:8,ativo:true,utiliza_plataforma_nimble:true},{id:'aut',codigo:'AUT-001',nome:'Implantação Operacional',tipo:'Implantação',ui:3,ativo:true},{id:'trn',codigo:'TRN-001',nome:'Treinamento da Equipe',tipo:'Implantação',ui:3,ativo:true},{id:'pla',codigo:'PLA-001',nome:'Licença Plataforma Nimble',tipo:'Mensalidade',valor_mensal:930,ativo:true}],links=[{intervention_code:'INT_AI',solucao_id:'ia',tipo_vinculo:'PRINCIPAL',ordem:1,ativo:true}],interventions=[{intervention_code:'INT_AI',title:'Aplicar Agente de IA',dimension:'ABSORVER'}];
const materialize=(status,validated,adaptada=true)=>prescription.materializeContextualPrescriptions({prescriptions:prescription.resolvePostMeetingPrescriptions({confirmedRecommendations:['Agente de IA'],adaptiveRecommendations:[{recomendacao_original:'Agente de IA',recomendacao_validada:validated,recurso:'Agente de IA',recurso_codigo:'IA-001',status_recurso:status,adaptada}]}),catalog,links});

test('IMPLANTADO + OTIMIZAR permanece estratégico e exclui IA-001 e dependências',()=>{const context=materialize('Implantado','Otimizar utilização do Agente de IA'),item=context[0];assert.equal(item.state_code,'IMPLANTADO');assert.equal(item.commercial_eligible,false);assert.equal(item.canonical_resource_id,'ia');assert.equal(item.canonical_solution_id,null);assert.deepEqual(Array.from(item.intervention_codes),['INT_AI']);const result=solutions.resolveStrategicSolutions({interventions,links,catalog,valor_ui:250,excluded_solution_ids:[item.canonical_resource_id]});assert.equal(result.solutions.length,0);assert.equal(prescription.contextualActionIsEligible(interventions[0],context),false)});

test('NAO_IMPLANTADO + IMPLANTAR mantém IA-001 e dependências canônicas',()=>{const context=materialize('Não Implantado','Agente de IA',false),item=context[0];assert.equal(item.state_code,'NAO_IMPLANTADO');assert.equal(item.commercial_eligible,true);assert.equal(item.canonical_solution_id,'ia');const result=solutions.resolveStrategicSolutions({interventions,links,catalog,valor_ui:250,excluded_solution_ids:[]}),codes=Array.from(result.solutions,row=>row.solution.codigo).sort();assert.deepEqual(codes,['AUT-001','IA-001','PLA-001','TRN-001'])});

test('PARCIALMENTE_IMPLANTADO possui decisão própria e não assume implantação completa',()=>{const context=materialize('Parcialmente Implantado','Concluir a implantação do Agente de IA'),item=context[0];assert.equal(item.state_code,'PARCIALMENTE_IMPLANTADO');assert.equal(item.decision,'MANTER_ACAO_ESTRATEGICA');assert.equal(item.commercial_eligible,false);assert.equal(item.canonical_solution_id,null)});

test('nova lógica só grava contexto em DRAFT e não atualiza plano ou snapshot publicado',()=>{const route=fs.readFileSync('app/api/meeting-preparation/route.ts','utf8'),migration=fs.readFileSync('database/migration_v61_prescricao_contextual_plano.sql','utf8');assert.match(route,/version_number:version,status:'DRAFT'/);assert.match(route,/contextual_prescriptions:input\.contextualPrescriptions/);assert.match(route,/sourceActions\.filter/);assert.doesNotMatch(route,/strategic_execution_plans\?id=eq\.\$\{encodeURIComponent\(source\.id\)\}[\s\S]{0,120}method:'PATCH'/);assert.doesNotMatch(migration,/update\s+public\.strategic_execution_plans/i);assert.doesNotMatch(migration,/published_snapshot\s*=/i)});
