import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {acquisitionReadiness,acquisitionStrategy,attractionNeed,conversionCapacity,evidenceFromAnswerMap,growthManagementCapacity} from '../lib/evidenceEngine.ts';

const ids=['crescer-1','crescer-2','crescer-3','crescer-4','crescer-5','crescer-6','acompanhar-4'];
const capacity=(scores)=>growthManagementCapacity(evidenceFromAnswerMap(Object.fromEntries(scores.map((score,index)=>[ids[index],score]))));

test('1. sete componentes em 4 resultam em 100% e capacidade alta',()=>{const result=capacity(Array(7).fill(4));assert.equal(result.score_base,100);assert.equal(result.classification,'ALTA');assert.deepEqual(result.limiters,[])});
test('2. sete componentes em 2 resultam em 50% e capacidade média',()=>{const result=capacity(Array(7).fill(2));assert.equal(result.score_base,50);assert.equal(result.classification,'MEDIA')});
test('3. três componentes críticos limitam a capacidade a baixa',()=>{const result=capacity([1,1,3,3,1,3,3]);assert.equal(result.classification,'BAIXA');assert.match(result.limiters.join(' '),/Três ou mais/)});
test('4. meta crítica limita score matemático alto ao nível médio',()=>{const result=capacity([1,4,4,4,4,4,4]);assert.ok(result.score_base>=75);assert.equal(result.classification_before_limiters,'ALTA');assert.equal(result.classification,'MEDIA')});
test('5. relatório manual reduz score sem impedir capacidade alta',()=>{const result=capacity([4,4,4,4,4,4,0]);assert.equal(result.score_base,86);assert.equal(result.classification,'ALTA');assert.deepEqual(result.limiters,[])});
test('6. gestão sem visibilidade resulta em capacidade baixa',()=>{const result=capacity([4,4,4,1,1,1,4]);assert.equal(result.management_without_visibility,true);assert.equal(result.classification,'BAIXA');assert.match(result.limiters.join(' '),/Gestão sem visibilidade/)});
test('7. crescimento sem previsibilidade com rotina crítica resulta em baixa',()=>{const result=capacity([1,1,4,4,4,1,4]);assert.equal(result.growth_without_predictability,true);assert.equal(result.classification,'BAIXA');assert.match(result.limiters.join(' '),/Crescimento sem previsibilidade/)});
test('8. apenas quatro componentes resultam em dados insuficientes',()=>{const result=capacity([4,4,4,4]);assert.equal(result.available,false);assert.equal(result.classification,null);assert.equal(result.score_base,null)});
test('9. indicadores anteriores e cruzamento estratégico permanecem inalterados',()=>{const evidence=evidenceFromAnswerMap({'atrair-5':0,'atrair-6':0,'atrair-7':1,'atrair-8':2,'converter-5':1,'organizar-0':1,'organizar-1':1,'acompanhar-0':1,'converter-0':4,'converter-1':4,'converter-4':4,'converter-2':4,'converter-3':4,'acompanhar-2':4,'acompanhar-3':4});const readiness=acquisitionReadiness(evidence),need=attractionNeed(evidence),conversion=conversionCapacity(evidence),strategy=acquisitionStrategy(need,readiness);assert.equal(need.need_score,81);assert.equal(need.classification,'ALTA');assert.equal(readiness.classification,'BAIXA');assert.equal(conversion.classification,'MEDIA');assert.equal(strategy.status,'ESTRUTURAR PARA EXPANDIR')});
test('10. Sprint permanece analítica e não altera módulos comerciais',()=>{const source=fs.readFileSync(new URL('../lib/evidenceEngine.ts',import.meta.url),'utf8'),briefing=fs.readFileSync(new URL('../components/DiagnosticConsultantBriefing.tsx',import.meta.url),'utf8');assert.doesNotMatch(source,/Dashboard Executivo|CRM Comercial|Licença Plataforma Nimble|Agente de IA|Google Ads|Meta Ads/);assert.match(briefing,/Capacidade de Gestão do Crescimento/);assert.match(briefing,/Gestão sem visibilidade/);assert.match(briefing,/Crescimento sem previsibilidade/)});
