import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=p=>readFileSync(p,'utf8');
test('marketing separa UI gestao e investimento em midia',()=>{const sql=read('database/migration_v13_parametros_marketing.sql');for(const term of ['marketing_parametros','valor_gestao_mensal','google_investimento','meta_investimento','servicos_adicionais'])assert.ok(sql.includes(term))});
test('planejamento operacional sai do menu comercial e abre pelo Centro de Implantacao',()=>{const central=read('components/CentralApp.tsx'),clientArea=read('components/ClientAreaPanel.tsx');assert.ok(!central.includes("['Parâmetros de Marketing','/central/parametros-marketing']"));assert.ok(clientArea.includes('/central/parametros-marketing?empresa='));assert.ok(clientArea.includes('Centro de Implantação'));assert.ok(read('app/api/commercial/route.ts').includes('isMaster'))});
test('portal mostra midia separada da contratacao',()=>{const portal=read('components/PortalApp.tsx');assert.ok(portal.includes('MarketingClientCard'));assert.ok(portal.includes('Esses valores'));assert.ok(portal.includes('Escala Vendas'));assert.ok(portal.includes('Por que recomendamos um investimento inicial mensal?'))});
test('resumo interno separa receita de investimentos do cliente',()=>{const central=read('components/CentralApp.tsx');assert.ok(central.includes('Receita da Escala Vendas'));assert.ok(central.includes('Investimentos do Cliente'));assert.ok(central.includes('Total mensal recomendado'))});

test('briefing operacional e vinculado ao projeto e liberado apos kickoff',()=>{const ui=read('components/MarketingAdmin.tsx'),api=read('app/api/client-access/route.ts'),sql=read('database/migration_v47_planejamento_operacional_campanhas.sql');for(const term of ['Planejamento Operacional das Campanhas','Público-alvo','Região de atuação','Campanha pronta para publicação'])assert.ok(ui.includes(term));for(const term of ['Kickoff realizado','planejamentos_campanhas','Equipe de Implantação'])assert.ok(api.includes(term));for(const term of ['empresa_id','projeto_evolucao_id','recurso_id','checklist'])assert.ok(sql.includes(term))});
