import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import vm from 'node:vm';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),source=fs.readFileSync('lib/portalProjectEvolution.ts','utf8'),js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,module={exports:{}};vm.runInNewContext(js,{module,exports:module.exports,require});const {portalProjectEvolutionProjection:project}=module.exports;
test('mensalidade vigente vem da situação comercial, total permanece congelado e acréscimo é apenas projetado',()=>{const original={mensalidade_atual:0,mensalidade_adicional:1230,nova_mensalidade:1230},out=project({project:original,currentSituation:{vigente:true,mensalidade:930},commercialSnapshot:{financial:{valor_mensalidade:1230}}});assert.equal(out.project.mensalidade_atual,930);assert.equal(out.project.acrescimo_mensal_exibicao,300);assert.equal(out.project.nova_mensalidade,1230);assert.equal(out.financial.monthly_increase,300);assert.equal(original.mensalidade_adicional,1230)});
test('ausência da situação vigente não converte legado/default zero em mensalidade vigente',()=>{const out=project({project:{mensalidade_atual:0,mensalidade_adicional:1230,nova_mensalidade:1230}});assert.equal(out.project.mensalidade_atual,null)});
test('executor usa implantação da mesma versão publicada e vínculo canônico',()=>{const out=project({project:{projeto_evolucao_recursos:[{recurso_id:'r1',executor:'Legado'}]},officialPlan:{id:'p13',version_number:13},officialImplementation:{id:'i13',plan_id:'p13',plan_version:13},officialItems:[{implementation_id:'i13',operational_responsible:'Teófilo',origin_snapshot:{recommended:{canonical_resource_id:'r1'}}}]});assert.equal(out.project.projeto_evolucao_recursos[0].executor,'Teófilo');assert.equal(out.project.projeto_evolucao_recursos[0].executor_source,'IMPLANTACAO_OFICIAL')});
test('implantação histórica de outra versão não sobrescreve executor legado',()=>{const out=project({project:{projeto_evolucao_recursos:[{recurso_id:'r1',executor:'Legado'}]},officialPlan:{id:'p13',version_number:13},officialImplementation:{id:'i12',plan_id:'p12',plan_version:12},officialItems:[{implementation_id:'i12',operational_responsible:'Outro'}]});assert.equal(out.project.projeto_evolucao_recursos[0].executor,'Legado')});
test('vínculo por intervenção canônica resolve executores distintos sem matching textual',()=>{const out=project({project:{projeto_evolucao_recursos:[{recurso_id:'r1',parametros_snapshot:{source_interventions:['INT_A']}},{recurso_id:'r2',parametros_snapshot:{source_interventions:['INT_B']}}]},officialPlan:{id:'p13',version_number:13},officialImplementation:{id:'i13',plan_id:'p13',plan_version:13},officialItems:[{implementation_id:'i13',operational_responsible:'Ana',origin_snapshot:{recommended:{intervention_codes:['INT_A']}}},{implementation_id:'i13',operational_responsible:'Bruno',origin_snapshot:{recommended:{intervention_codes:['INT_B']}}}]});assert.equal(out.project.projeto_evolucao_recursos[0].executor,'Ana');assert.equal(out.project.projeto_evolucao_recursos[1].executor,'Bruno')});
test('Portal consulta situação vigente e implantação da versão publicada',()=>{const api=fs.readFileSync('app/api/portal/route.ts','utf8');assert.match(api,/situacoes_comerciais_versoes\?empresa_id=eq\.\$\{id\}&vigente=eq\.true/);assert.match(api,/strategic_execution_plans\?empresa_id=eq\.\$\{id\}&status=eq\.PUBLISHED/);assert.match(api,/strategic_plan_implementations\?plan_id=eq\.\$\{encodeURIComponent\(officialPlan\.id\)\}&plan_version=eq\.\$\{encodeURIComponent\(officialPlan\.version_number\)\}/);assert.match(api,/portalProjectEvolutionProjection/)});
test('Portal e telas administrativas usam Acréscimo mensal sem alterar persistência',()=>{for(const file of ['components/PortalApp.tsx','components/PortalOnboarding.tsx','components/CompanyDossierExecutive.tsx','components/CommercialEvolutionPanel.tsx'])assert.match(fs.readFileSync(file,'utf8'),/Acréscimo mensal/,file);const projection=fs.readFileSync('lib/portalProjectEvolution.ts','utf8');assert.match(projection,/frozenTotal-currentMonthly/);assert.doesNotMatch(projection,/project\.mensalidade_adicional\s*=/)});
