import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';

function load(file,stubs={}){const source=fs.readFileSync(file,'utf8'),js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,module={exports:{}};vm.runInNewContext(`(function(require,module,exports){${js}\n})(require,module,module.exports)`,{require:id=>stubs[id]||{},module,exports:module.exports,Set,Map,Error});return module.exports}
const prescription=load('lib/resourcePrescriptionResolver.ts'),pricing=load('lib/commercialPricingResolver.ts'),nimble=load('lib/nimbleStructure.ts'),dependencies=load('lib/commercialDependencyResolver.ts',{'./nimbleStructure':nimble});
const meetingRoute=fs.readFileSync('app/api/meeting-preparation/route.ts','utf8');
const catalog=[{id:'ia',codigo:'IA-001',nome:'Ativação e Treinamento de Agente de IA',tipo:'Implantação',ui:8,ativo:true,utiliza_plataforma_nimble:true},{id:'aut',codigo:'AUT-001',nome:'Implantação Operacional',tipo:'Implantação',ui:3,ativo:true},{id:'trn',codigo:'TRN-001',nome:'Treinamento da Equipe',tipo:'Implantação',ui:3,ativo:true},{id:'pla',codigo:'PLA-001',nome:'Licença Plataforma Nimble',tipo:'Mensalidade',valor_mensal:930,ativo:true}];

test('Agente implantado preserva otimização e não prescreve IA-001 nem estrutura Nimble',()=>{const result=prescription.resolvePostMeetingPrescriptions({confirmedRecommendations:['Agente de IA'],adaptiveRecommendations:[{recomendacao_original:'Agente de IA',recomendacao_validada:'Otimizar utilização do Agente de IA',recurso:'Agente de IA',status_recurso:'Implantado',adaptada:true}]});assert.equal(result[0].decision,'MANTER_ACAO_ESTRATEGICA');assert.equal(result[0].validated,'Otimizar utilização do Agente de IA');assert.equal(result[0].commercial_eligible,false);const selected=result[0].commercial_eligible?['ia']:[];assert.equal(dependencies.resolveCommercialDependencies({selectedSolutionIds:selected,catalog}).length,0);assert.ok(!selected.includes('ia'))});
test('Agente não implantado continua elegível e mantém a estrutura Nimble',()=>{const result=prescription.resolvePostMeetingPrescriptions({confirmedRecommendations:['Agente de IA'],adaptiveRecommendations:[{recomendacao_original:'Agente de IA',recomendacao_validada:'Agente de IA',recurso:'Agente de IA',status_recurso:'Não Implantado',adaptada:false}]});assert.equal(result[0].decision,'PRESCREVER_SOLUCAO');assert.equal(result[0].commercial_eligible,true);const derived=dependencies.resolveCommercialDependencies({selectedSolutionIds:['ia'],catalog});assert.equal(Array.from(derived,item=>item.solution.codigo).sort().join(','),'AUT-001,PLA-001,TRN-001');assert.equal(pricing.resolveCommercialPrice(catalog[0],250).valor_implantacao,2000)});
test('sem estrutura adaptativa preserva compatibilidade legada',()=>{const result=prescription.resolvePostMeetingPrescriptions({confirmedRecommendations:['Agente de IA']});assert.equal(result[0].commercial_eligible,true);assert.match(result[0].reason,/Compatibilidade legada/)});
test('recurso parcialmente implantado permanece ação estratégica',()=>{const result=prescription.resolvePostMeetingPrescriptions({confirmedRecommendations:['Dashboard Executivo'],adaptiveRecommendations:[{recomendacao_original:'Dashboard Executivo',recomendacao_validada:'Concluir a implantação do Dashboard',recurso:'Dashboard',status_recurso:'Parcialmente Implantado',adaptada:true}]});assert.equal(result[0].decision,'MANTER_ACAO_ESTRATEGICA');assert.equal(result[0].commercial_eligible,false)});
test('conclusão da reunião usa a prescrição antes do matching com a Biblioteca',()=>{assert.match(meetingRoute,/resolvePostMeetingPrescriptions\(\{confirmedRecommendations:sourceRecommendations,adaptiveRecommendations\}\)/);assert.match(meetingRoute,/approved=prescriptions\.filter\(item=>item\.commercial_eligible\)/);assert.match(meetingRoute,/strategicOnly=prescriptions\.filter\(item=>!item\.commercial_eligible\)/);assert.match(meetingRoute,/Ação Estratégica → \$\{item\.validated\}/)});
