import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {composeGrowthProject} from '../lib/motor-growth.ts';
const read=path=>readFileSync(path,'utf8');

test('Motor copia objetivo, investimento e regras exclusivamente da Biblioteca',()=>{const catalog=[{id:'1',nome:'Gestão Google Ads',tipo:'Mensalidade',objetivo_padrao:'Gerar oportunidades qualificadas',resultado_esperado:'Mais oportunidades qualificadas',criterios_recomendacao:['atrair'],investimento_minimo_recomendado:1800,gera_pendencias:true,abre_planejamento_operacional:true,permite_executor_terceiro:false,permite_equipe_interna:true}],result=composeGrowthProject({catalog,priority:'Atrair'}),solution=result.all.find(item=>item.nome==='Gestão Google Ads');assert.equal(solution.objetivo_padrao,'Gerar oportunidades qualificadas');assert.equal(solution.parametros_metodo.resultado_esperado,'Mais oportunidades qualificadas');assert.equal(solution.investimento_recomendado,1800);assert.equal(solution.parametros_metodo.permite_executor_terceiro,false)});

test('projeto preserva snapshot dos parâmetros utilizados na geração',()=>{const api=read('app/api/commercial-evolution/route.ts'),sql=read('database/migration_v48_parametros_biblioteca_solucoes.sql'),panel=read('components/ExecutionStrategyPanel.tsx');assert.match(api,/parametros_snapshot:parametersSnapshot/);assert.match(sql,/parametros_snapshot jsonb/);assert.match(panel,/item\.parametros_snapshot\?\.investimento_minimo_recomendado/);assert.doesNotMatch(panel,/verba_recomendada/)});

test('cadastro da Biblioteca expõe os parâmetros únicos da arquitetura congelada',()=>{const ui=read('components/CommercialAdmin.tsx'),api=read('app/api/commercial/route.ts');for(const field of ['resultado_esperado','criterios_recomendacao','treinamento_obrigatorio','gera_pendencias','abre_planejamento_operacional','permite_executor_terceiro','permite_equipe_interna','investimento_minimo_recomendado','observacoes_estrategicas','criterios_conclusao','recursos_relacionados'])assert.ok(ui.includes(field)&&api.includes(field),field);for(const removed of ['Prioridade comercial','Tipo de implantação','Faixa ideal — mínimo','Faixa ideal — máximo'])assert.ok(!ui.includes(removed),removed)});

test('tipo único controla cronograma e recorrência',()=>{const ui=read('components/CommercialAdmin.tsx'),api=read('app/api/commercial/route.ts'),motor=read('lib/motor-growth.ts'),sql=read('database/migration_v50_congelamento_biblioteca_solucoes.sql');assert.match(ui,/Implantação \+ Mensalidade/);assert.match(api,/hasImplementation=type!==\'Mensalidade\',hasMonthly=type!==\'Implantação\'/);assert.match(motor,/recorrencia_ativa_apos_implantacao:item\.tipo===\'Implantação \+ Mensalidade\'/);assert.match(sql,/drop column if exists tipo_comercial/);assert.match(sql,/drop column if exists obrigatoriedade/)});
