import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {strategicDecision,STRATEGIC_ENGINE_VERSION} from '../lib/strategicEngine.ts';

const indicator=(classification,score,kind='score_base')=>({available:classification!==null,classification,[kind]:classification===null?null:score});
const scenario=(need,readiness,conversion,management)=>strategicDecision({need:indicator(need[0],need[1],'need_score'),readiness:indicator(...readiness),conversion:indicator(...conversion),management:indicator(...management)});

test('Original: expansão controlada com Conversão primária e Gestão paralela',()=>{const result=scenario(['ALTA',81],['ALTA',75],['BAIXA',41],['BAIXA',25]);assert.equal(result.acquisition_movement,'EXPANDIR_CONTROLADAMENTE');assert.equal(result.primary_priority,'CONVERTER');assert.deepEqual(result.parallel_priorities,['GERIR']);assert.equal(result.strategic_direction,'EXPANDIR COM ESTRUTURAÇÃO COMERCIAL');assert.equal(result.main_risk,'Baixo aproveitamento comercial das oportunidades geradas.')});
test('Alfa: prontidão média produz expansão com controle e atenção em absorção',()=>{const result=scenario(['ALTA',81],['MEDIA',63],['BAIXA',41],['BAIXA',25]);assert.equal(result.acquisition_movement,'EXPANDIR_CONTROLADAMENTE');assert.equal(result.primary_priority,'CONVERTER');assert.deepEqual(result.parallel_priorities,['GERIR']);assert.equal(result.strategic_direction,'EXPANDIR COM CONTROLE');assert.equal(result.main_risk,'Baixo aproveitamento comercial das oportunidades geradas.');assert.ok(result.attention_dimensions.some(item=>item.dimension==='ABSORVER'&&item.classification==='MEDIA'))});
test('Beta: baixa absorção precede conversão e gestão',()=>{const result=scenario(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]);assert.equal(result.acquisition_movement,'ESTRUTURAR_ANTES_DE_ACELERAR');assert.equal(result.primary_priority,'ABSORVER');assert.deepEqual(result.parallel_priorities,['CONVERTER','GERIR']);assert.equal(result.strategic_direction,'ESTRUTURAR PARA EXPANDIR');assert.equal(result.main_risk,'Perda de oportunidades com aumento da demanda.')});
test('A. cenário ideal acelera aquisição',()=>{const result=scenario(['ALTA',81],['ALTA',90],['ALTA',90],['ALTA',90]);assert.equal(result.acquisition_movement,'ACELERAR');assert.equal(result.primary_priority,'ATRAIR');assert.equal(result.strategic_direction,'EXPANDIR AQUISIÇÃO')});
test('B. gestão como única fragilidade controla expansão e vira prioridade',()=>{const result=scenario(['ALTA',81],['ALTA',90],['ALTA',90],['BAIXA',25]);assert.equal(result.initial_acquisition_movement,'ACELERAR');assert.equal(result.management_rule_applied,true);assert.equal(result.acquisition_movement,'EXPANDIR_CONTROLADAMENTE');assert.equal(result.primary_priority,'GERIR');assert.equal(result.strategic_direction,'EXPANDIR COM CONTROLE')});
test('C. necessidade baixa e operação forte consolida',()=>{const result=scenario(['BAIXA',20],['ALTA',90],['ALTA',90],['ALTA',90]);assert.equal(result.acquisition_movement,'NAO_PRIORIZAR_EXPANSAO');assert.equal(result.primary_priority,'CONSOLIDAR');assert.equal(result.strategic_direction,'CONSOLIDAR E OTIMIZAR')});
test('D. necessidade baixa com conversão baixa fortalece operação',()=>{const result=scenario(['BAIXA',20],['ALTA',90],['BAIXA',40],['MEDIA',60]);assert.equal(result.acquisition_movement,'NAO_PRIORIZAR_EXPANSAO');assert.equal(result.primary_priority,'CONVERTER');assert.equal(result.strategic_direction,'FORTALECER OPERAÇÃO COMERCIAL')});
test('E. indicador incompleto impede direção definitiva',()=>{const result=scenario(['ALTA',81],['ALTA',90],[null,0],['ALTA',90]);assert.equal(result.available,false);assert.equal(result.strategic_direction,'DADOS INSUFICIENTES');assert.equal(result.primary_priority,null);assert.deepEqual(result.incomplete_indicators,['Capacidade de Conversão'])});
test('Motor não calcula média nem recomenda soluções e mantém versão própria',()=>{const source=fs.readFileSync(new URL('../lib/strategicEngine.ts',import.meta.url),'utf8');assert.equal(STRATEGIC_ENGINE_VERSION,'1.0');assert.doesNotMatch(source,/m[eé]dia ponderada|overall_score|general_score/i);assert.doesNotMatch(source,/CRM|Nimble|Agente de IA|Google Ads|Meta Ads|Dashboard Executivo|WhatsApp Oficial/)});
test('UI contém direção executiva e debug sem substituir prioridade antiga',()=>{const briefing=fs.readFileSync(new URL('../components/DiagnosticConsultantBriefing.tsx',import.meta.url),'utf8'),app=fs.readFileSync(new URL('../components/DiagnosticApp.tsx',import.meta.url),'utf8');assert.match(briefing,/Direção Estratégica/);assert.match(briefing,/Motor Estratégico 3\.0/);assert.match(briefing,/Leitura estratégica da aquisição/);assert.match(app,/strategic_engine_version:'1\.0'/);assert.doesNotMatch(app,/primary_priority.*maior_gargalo|primary_priority.*prioridades/)});
test('debug do Motor é técnico e legível, sem objetos brutos',()=>{const briefing=fs.readFileSync(new URL('../components/DiagnosticConsultantBriefing.tsx',import.meta.url),'utf8');assert.match(briefing,/MOTOR ESTRATÉGICO 3\.0/);assert.match(briefing,/Entradas do Motor/);assert.match(briefing,/Decisão do Motor/);assert.match(briefing,/Regras acionadas/);assert.match(briefing,/Dimensões de atenção/);assert.match(briefing,/Quantidade de evidências utilizadas/);assert.match(briefing,/Ver evidências técnicas/);assert.doesNotMatch(briefing,/debugJson|JSON\.stringify|Objeto completo recebido pelo template|<pre>/)});
