import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {strategicDecision} from '../lib/strategicEngine.ts';
import {STRATEGIC_INTERVENTION_CATALOG,strategicInterventions} from '../lib/strategicInterventionEngine.ts';
import {ACTION_CATALOG,STRATEGIC_ACTION_PLAN_ENGINE_VERSION,strategicActionPlan} from '../lib/strategicActionPlanEngine.ts';

const indicator=(classification,score,kind='score_base')=>({available:true,classification,[kind]:score});
const decision=(need,readiness,conversion,management)=>strategicDecision({need:indicator(need[0],need[1],'need_score'),readiness:indicator(...readiness),conversion:indicator(...conversion),management:indicator(...management)});
const evidence=(capability,score,dimension='CONVERTER')=>({evidence_code:'EV_'+capability,dimension,capability,score,severity:score<=1?'CRITICO':score===2?'ATENCAO':'ESTRUTURADO',fact:'Fato '+capability,source_question:'Pergunta '+capability,source_question_id:'q-'+capability});
const evidences=[
 evidence('VELOCIDADE_ATENDIMENTO',0),evidence('RESPONSABILIDADE',1),evidence('CONTROLE_RETORNO',0),evidence('CENTRALIZACAO',2),
 evidence('QUALIFICACAO',0),evidence('ROTINA_ACOMPANHAMENTO',1),evidence('MOTIVOS_PERDA',0),evidence('MENSURACAO_CONVERSAO',2),evidence('ETAPAS_COMERCIAIS',1),
 evidence('METAS_RESULTADOS',0,'CRESCER'),evidence('CENTRALIZACAO_INDICADORES',1,'CRESCER'),evidence('ROTINA_GESTAO',1,'CRESCER'),evidence('RELATORIOS_AUTOMATIZADOS',4,'CRESCER'),
 evidence('ESTRATEGIA_AQUISICAO',1,'ATRAIR'),evidence('PREVISIBILIDADE_AQUISICAO',1,'ATRAIR'),evidence('CLIENTE_IDEAL',2,'ATRAIR'),evidence('RASTREABILIDADE_AQUISICAO',2,'ATRAIR')
];
const build=(d,items=evidences)=>{const interventions=strategicInterventions(d,items);return{interventions,plan:strategicActionPlan(d,interventions)}};

test('ACTION_CATALOG cobre todas as 30 intervenções canônicas e mantém versão 1.0',()=>{assert.equal(STRATEGIC_ACTION_PLAN_ENGINE_VERSION,'1.0');assert.equal(ACTION_CATALOG.length,30);assert.deepEqual(new Set(ACTION_CATALOG.map(item=>item.intervention_code)),new Set(STRATEGIC_INTERVENTION_CATALOG.map(item=>item.intervention_code)))});
test('A. nenhuma ação existe sem intervention_code e rastreabilidade completa',()=>{const {plan}=build(decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]));for(const action of plan.all_actions){assert.ok(action.intervention_code);assert.ok(action.source_evidence_code);assert.ok(action.source_question_id);assert.ok(action.strategic_priority_source)}});
test('B. sem intervenção ativa não existe ação',()=>{const d=decision(['BAIXA',20],['ALTA',90],['ALTA',90],['ALTA',90]),interventions=strategicInterventions(d,[evidence('RELATORIOS_AUTOMATIZADOS',4,'CRESCER')]),plan=strategicActionPlan(d,interventions);assert.equal(plan.total_actions,0);assert.equal(plan.all_actions.length,0)});
test('C. ação sem meta permanece válida e UI informa definição com consultor',()=>{const {plan}=build(decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]),[evidence('VELOCIDADE_ATENDIMENTO',0)]);assert.equal(plan.now_actions[0].initial_target,null);const ui=fs.readFileSync(new URL('../components/DiagnosticConsultantBriefing.tsx',import.meta.url),'utf8');assert.match(ui,/Meta inicial:<\/strong>.*a definir com o consultor/s)});
test('D. Beta envia aquisição para QUANDO_ESTIVER_PRONTO e nunca para AGORA',()=>{const d=decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]),{plan}=build(d);assert.equal(d.acquisition_movement,'ESTRUTURAR_ANTES_DE_ACELERAR');assert.ok(plan.when_ready_actions.length>0);assert.ok(plan.when_ready_actions.every(item=>item.dimension==='ATRAIR'));assert.ok(plan.now_actions.every(item=>item.dimension!=='ATRAIR'))});
test('E. expansão controlada posiciona aquisição em DEPOIS sem substituir P1',()=>{const d=decision(['ALTA',81],['MEDIA',63],['BAIXA',41],['BAIXA',25]),{plan}=build(d);assert.equal(d.acquisition_movement,'EXPANDIR_CONTROLADAMENTE');assert.ok(plan.now_actions.every(item=>item.priority_level==='P1'));assert.ok(plan.later_actions.some(item=>item.dimension==='ATRAIR'))});
test('F. strength é preservada sem gerar ação corretiva',()=>{const d=decision(['ALTA',81],['ALTA',75],['BAIXA',41],['BAIXA',25]),{plan}=build(d,[evidence('RELATORIOS_AUTOMATIZADOS',4,'CRESCER')]);assert.equal(plan.total_actions,0);assert.equal(plan.strengths_to_preserve[0].capability,'RELATORIOS_AUTOMATIZADOS')});
test('G. card limita três ações por horizonte e debug preserva todas',()=>{const d=decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]),{plan}=build(d);assert.ok(plan.now_actions.length<=3);assert.ok(plan.later_actions.length<=3);assert.ok(plan.when_ready_actions.length<=3);assert.ok(plan.all_actions.length>plan.now_actions.length+plan.later_actions.length+plan.when_ready_actions.length);assert.ok(plan.hidden_actions.every(item=>item.reason==='limite do card'))});
test('H. regressão mantém resultados estratégicos Beta, Alfa e Original',()=>{const scenarios=[[['BAIXA',50],['BAIXA',38],'ESTRUTURAR PARA EXPANDIR','ABSORVER','ESTRUTURAR_ANTES_DE_ACELERAR'],[['MEDIA',63],['BAIXA',41],'EXPANDIR COM CONTROLE','CONVERTER','EXPANDIR_CONTROLADAMENTE'],[['ALTA',75],['BAIXA',41],'EXPANDIR COM ESTRUTURAÇÃO COMERCIAL','CONVERTER','EXPANDIR_CONTROLADAMENTE']];for(const [readiness,conversion,direction,primary,movement] of scenarios){const d=decision(['ALTA',81],readiness,conversion,['BAIXA',25]);strategicActionPlan(d,strategicInterventions(d,evidences));assert.equal(d.strategic_direction,direction);assert.equal(d.primary_priority,primary);assert.equal(d.acquisition_movement,movement)}});
test('Beta posiciona absorção em AGORA, paralelas em DEPOIS e aquisição no horizonte futuro',()=>{const d=decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]),{plan}=build(d);assert.deepEqual(plan.now_actions.map(item=>item.capability),['VELOCIDADE_ATENDIMENTO','CONTROLE_RETORNO','RESPONSABILIDADE']);assert.ok(plan.later_actions.every(item=>['CONVERTER','GERIR'].includes(item.dimension)));assert.ok(plan.when_ready_actions.every(item=>item.dimension==='ATRAIR'));assert.match(plan.action_plan_summary,/absorção das oportunidades/i)});
test('Alfa e Original iniciam por CONVERTER e levam gestão e aquisição controlada para DEPOIS',()=>{for(const readiness of [['MEDIA',63],['ALTA',75]]){const d=decision(['ALTA',81],readiness,['BAIXA',41],['BAIXA',25]),{plan}=build(d);assert.ok(plan.now_actions.every(item=>item.dimension==='CONVERTER'));assert.ok(plan.later_actions.some(item=>item.dimension==='GERIR'));assert.ok(plan.later_actions.some(item=>item.dimension==='ATRAIR'));assert.equal(plan.when_ready_actions.length,0)}});
test('motor é neutro, sem prazo, cronograma ou produto',()=>{const source=fs.readFileSync(new URL('../lib/strategicActionPlanEngine.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/Nimble|Google Ads|Meta Ads|WhatsApp Oficial|Dashboard Executivo|Agente de IA|Landing Page|Webchat/);assert.doesNotMatch(source,/30 dias|60 dias|90 dias|semanas|horas|custo de implantação/)});
test('card e debug administrativos estão presentes sem JSON bruto',()=>{const source=fs.readFileSync(new URL('../components/DiagnosticConsultantBriefing.tsx',import.meta.url),'utf8');assert.match(source,/Plano de Ação Estratégico/);assert.match(source,/MOTOR DO PLANO DE AÇÃO 1\.0/);assert.match(source,/Ações não exibidas no card/);assert.doesNotMatch(source,/JSON\.stringify\(actionPlan|<pre>\{actionPlan/)});
