import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';

function load(file,stubs={}){const source=fs.readFileSync(file,'utf8'),js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,module={exports:{}};vm.runInNewContext(`(function(require,module,exports){${js}\n})(require,module,module.exports)`,{require:id=>stubs[id]||{},module,exports:module.exports,Set,Map,Error,String,Array,Object,Number,Boolean,RegExp,Date});return module.exports}
const execution=load('lib/strategicExecutionPlan.ts'),prescriptions=load('lib/resourcePrescriptionResolver.ts'),interventions=load('lib/strategicInterventionEngine.ts'),actions=load('lib/strategicActionPlanEngine.ts'),revision=load('lib/strategicRevisionExecution.ts',{'./strategicInterventionEngine':interventions,'./strategicActionPlanEngine':actions,'./strategicExecutionPlan':execution,'./resourcePrescriptionResolver':prescriptions});
const decision={available:true,strategic_direction:'EXPANDIR COM CONTROLE',primary_priority:'GERIR',parallel_priorities:[],acquisition_movement:'EXPANDIR_CONTROLADAMENTE',initial_acquisition_movement:'EXPANDIR_CONTROLADAMENTE',management_rule_applied:false,main_risk:'',strategic_rationale:'',attention_dimensions:[],rules_triggered:[],incomplete_indicators:[],engine_version:'1.0'};
const evidence=(capability,score=1)=>({evidence_code:'EVD_'+capability,capability,score,severity:'CRITICO',source_question_id:'q-'+capability,source_answer:score,source_answer_label:'Baixo',business_meaning:'',business_risk:'',engine_version:'1.0'});
const contextual=(eligible=false)=>({original:'Agente de IA',validated:'Otimizar utilização do Agente de IA',resource:'Agente de IA',resource_status:'Implantado',adapted:true,commercial_eligible:eligible,decision:eligible?'PRESCREVER_SOLUCAO':'MANTER_ACAO_ESTRATEGICA',reason:'Decisão vigente',canonical_resource_id:'ia',canonical_solution_id:eligible?'ia':null,canonical_solution_code:'IA-001',intervention_codes:['INT_ACQ_DEMAND'],superseded_intervention_codes:[],state_code:'IMPLANTADO',context_version:'1.0'});

test('prioridade Atrair rematerializa ações canônicas de aquisição',()=>{const result=revision.currentStrategicArtifacts({baseDecision:decision,evidences:[evidence('DEMANDA'),evidence('ESTRATEGIA_AQUISICAO')],primaryPriority:'Atrair'});assert.equal(result.decision.primary_priority,'ATRAIR');assert.ok(result.actionPlan.all_actions.some(item=>item.dimension==='ATRAIR'));assert.ok(result.actionPlan.all_actions.some(item=>item.action_code==='ACT_ACQ_DEMAND'))});
test('mudança de prioridade usa o contexto da revisão e não o cabeçalho anterior',()=>{const result=revision.currentStrategicArtifacts({baseDecision:decision,evidences:[evidence('DEMANDA')],primaryPriority:'Atrair',parallelPriorities:['Converter']});assert.equal(result.decision.primary_priority,'ATRAIR');assert.deepEqual(Array.from(result.decision.parallel_priorities),['CONVERTER']);assert.equal(result.actionPlan.primary_priority,'ATRAIR')});
test('elegibilidade comercial falsa ou verdadeira não elimina a ação estratégica',()=>{const plan=revision.currentStrategicArtifacts({baseDecision:decision,evidences:[evidence('DEMANDA')],primaryPriority:'Atrair'}).actionPlan;for(const eligible of [false,true]){const rows=revision.reconcileRevisionActions({actionPlan:plan,contextualPrescriptions:[contextual(eligible)]});assert.ok(rows.some(item=>item.source_action_code==='ACT_ACQ_DEMAND'));assert.equal(rows.filter(item=>item.action_origin==='CONTEXTUAL').length,1)}});
test('ação manual independente é preservada; contexto antigo não é herdado nem duplicado',()=>{const plan=revision.currentStrategicArtifacts({baseDecision:decision,evidences:[evidence('DEMANDA')],primaryPriority:'Atrair'}).actionPlan,manual={...execution.manualAction(),id:'manual-1',agreed_title:'Decisão do consultor',agreed_objective:'Objetivo'},oldContext={...execution.manualAction(),action_origin:'CONTEXTUAL',contextual_action_key:'old'};const once=revision.reconcileRevisionActions({sourceActions:[manual,oldContext],actionPlan:plan,contextualPrescriptions:[contextual(false),contextual(false)]}),twice=revision.reconcileRevisionActions({sourceActions:once,actionPlan:plan,contextualPrescriptions:[contextual(false)]});assert.equal(once.filter(item=>item.action_origin==='MANUAL').length,1);assert.equal(once.filter(item=>item.action_origin==='CONTEXTUAL').length,1);assert.equal(twice.filter(item=>item.action_origin==='CONTEXTUAL').length,1)});
test('publicação exige cobertura da prioridade ou justificativa explícita',()=>{const unrelated={...execution.manualAction(),agreed_title:'Ação',agreed_objective:'Objetivo',strategic_dimension:'GERIR'};assert.match(execution.validatePublication([unrelated],{primaryPriority:'ATRAIR'}).errors.join(' '),/prioridade principal/);assert.equal(execution.validatePublication([unrelated],{primaryPriority:'ATRAIR',priorityCoverageJustification:'Decisão registrada com o cliente.'}).errors.length,0)});
test('migração e reconciliação não reescrevem planos publicados ou snapshots',()=>{const migration=fs.readFileSync('database/migration_v63_contexto_estrategico_plano_executavel.sql','utf8'),route=fs.readFileSync('app/api/meeting-preparation/route.ts','utf8');assert.doesNotMatch(migration,/update\s+public\./i);assert.doesNotMatch(route,/published_snapshot\s*:/);assert.match(route,/status:'DRAFT'/)});
