import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const api=fs.readFileSync(new URL('../app/api/strategic-execution-plan/route.ts',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../components/StrategicExecutionPlan.tsx',import.meta.url),'utf8');
test('cascata executa somente as três camadas posteriores permitidas',()=>{assert.match(api,/strategicDecision\(/);assert.match(api,/strategicInterventions\(decision,evidences\)/);assert.match(api,/strategicActionPlan\(decision,interventions\)/);assert.doesNotMatch(api,/acquisitionReadiness\(|attractionNeed\(|conversionCapacity\(|growthManagementCapacity\(/)});
test('resultado persistido é reutilizado sem recálculo',()=>{assert.match(api,/existing&&String\(existing\.engine_version/);assert.match(api,/materialized:false,[^}]*source:'PERSISTED'/)});
test('materialização é sob demanda, ordenada e persiste versões canônicas',()=>{assert.match(api,/operation==='ensure-action-plan'/);assert.ok(api.indexOf("materializedLayers.push('Motor Estratégico 3.0')")<api.indexOf("materializedLayers.push('Motor de Intervenções 1.0')"));assert.ok(api.indexOf("materializedLayers.push('Motor de Intervenções 1.0')")<api.indexOf("materializedLayers.push('Motor do Plano de Ação 1.0')"));for(const version of ['strategic_engine_version','strategic_intervention_engine_version','strategic_action_plan_engine_version'])assert.match(api,new RegExp(version))});
test('camadas ausentes informam camada e entradas exatas',()=>{assert.match(api,/missing_layer:'Motor Estratégico 3.0'/);assert.match(api,/missing_inputs:missing/);assert.match(api,/missing_layer:'Motor de Intervenções 1.0'/);assert.match(api,/Evidências Estruturadas/)});
test('Sprint 9 inicializa plano vazio depois da materialização',()=>{assert.match(ui,/operation:'ensure-action-plan'/);assert.match(ui,/operation:'initialize'/);assert.doesNotMatch(ui,/agreedFromEngine\(recommended\).*initialize/s)});
test('nenhum backfill global ou publicação automática foi criado',()=>{assert.doesNotMatch(api,/diagnosticos\?select=\*/);assert.doesNotMatch(ui,/compatibility[\s\S]{0,200}operation:'publish'/)});
test('URL do Supabase não sombreia o construtor global URL',()=>{assert.match(api,/const SUPABASE_URL=process\.env\.SUPABASE_URL/);assert.doesNotMatch(api,/const URL=process\.env\.SUPABASE_URL/)});
