import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {strategicDecision} from '../lib/strategicEngine.ts';
import {STRATEGIC_INTERVENTION_CATALOG,STRATEGIC_INTERVENTION_ENGINE_VERSION,strategicInterventions} from '../lib/strategicInterventionEngine.ts';

const indicator=(classification,score,kind='score_base')=>({available:true,classification,[kind]:score});
const decision=(need,readiness,conversion,management)=>strategicDecision({need:indicator(need[0],need[1],'need_score'),readiness:indicator(...readiness),conversion:indicator(...conversion),management:indicator(...management)});
const evidence=(capability,score,dimension='CONVERTER',suffix='A')=>({evidence_code:'EV_'+capability+'_'+suffix,dimension,capability,score,severity:score<=1?'CRITICO':score===2?'ATENCAO':'ESTRUTURADO',fact:'Fato canônico para '+capability,source_question:'Pergunta '+capability,source_question_id:'q-'+capability+'-'+suffix});
const operational=[
 evidence('VELOCIDADE_ATENDIMENTO',0),evidence('CENTRALIZACAO',2),evidence('RESPONSABILIDADE',1),evidence('DISTRIBUICAO',3),
 evidence('QUALIFICACAO',0),evidence('ROTINA_ACOMPANHAMENTO',1),evidence('ETAPAS_COMERCIAIS',2),evidence('MENSURACAO_CONVERSAO',3),
 evidence('METAS_RESULTADOS',0,'CRESCER'),evidence('CENTRALIZACAO_INDICADORES',1,'CRESCER'),evidence('RELATORIOS_AUTOMATIZADOS',4,'CRESCER'),
 evidence('DEMANDA',0,'ATRAIR'),evidence('PREVISIBILIDADE_AQUISICAO',1,'ATRAIR'),evidence('ESTRATEGIA_AQUISICAO',2,'ATRAIR'),evidence('REATIVACAO_BASE',3,'ATRAIR')
];

test('A. capability estruturada não gera intervenção corretiva',()=>{const result=strategicInterventions(decision(['ALTA',81],['ALTA',75],['BAIXA',41],['BAIXA',25]),[evidence('RELATORIOS_AUTOMATIZADOS',4,'CRESCER')]);assert.equal(result.all_interventions.length,0);assert.equal(result.strengths_to_preserve[0].capability,'RELATORIOS_AUTOMATIZADOS')});
test('B. crítica da prioridade principal precede atenção da mesma dimensão',()=>{const result=strategicInterventions(decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]),[evidence('CENTRALIZACAO',2),evidence('VELOCIDADE_ATENDIMENTO',0)]);assert.deepEqual(result.primary_interventions.map(item=>item.capability),['VELOCIDADE_ATENDIMENTO','CENTRALIZACAO'])});
test('C. dimensão paralela não ultrapassa intervenção crítica primária',()=>{const result=strategicInterventions(decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]),[evidence('VELOCIDADE_ATENDIMENTO',0),evidence('QUALIFICACAO',0)]);assert.equal(result.all_interventions[0].priority_level,'P1');assert.equal(result.all_interventions[0].capability,'VELOCIDADE_ATENDIMENTO');assert.equal(result.all_interventions[1].priority_level,'P2')});
test('D. uma capability não gera duas intervenções ativas',()=>{const result=strategicInterventions(decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]),[evidence('CONTROLE_RETORNO',2,'CONVERTER','A'),evidence('CONTROLE_RETORNO',0,'CONVERTER','B')]);assert.equal(result.all_interventions.filter(item=>item.capability==='CONTROLE_RETORNO').length,1);assert.ok(result.discarded_interventions.some(item=>item.reason==='duplicidade'))});
test('E. estruturar antes de acelerar mantém aquisição como posterior',()=>{const result=strategicInterventions(decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]),[evidence('ESTRATEGIA_AQUISICAO',0,'ATRAIR')]);assert.equal(result.acquisition_interventions[0].timing,'POSTERIOR');assert.doesNotMatch(result.acquisition_interventions[0].title,/Acelerar aquisição/i)});
test('F. acelerar não apaga intervenção operacional crítica',()=>{const result=strategicInterventions(decision(['ALTA',81],['ALTA',90],['ALTA',90],['ALTA',90]),[evidence('VELOCIDADE_ATENDIMENTO',0),evidence('ESTRATEGIA_AQUISICAO',1,'ATRAIR')]);assert.ok(result.all_interventions.some(item=>item.capability==='VELOCIDADE_ATENDIMENTO'));assert.ok(result.all_interventions.some(item=>item.capability==='ESTRATEGIA_AQUISICAO'))});
test('G. toda intervenção possui rastreabilidade completa',()=>{const result=strategicInterventions(decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]),operational);for(const item of result.all_interventions){assert.ok(item.source_evidence_code);assert.ok(item.source_question_id);assert.ok(item.capability);assert.ok(item.strategic_priority_source)}});
test('Beta prioriza absorção, mantém conversão e gestão paralelas e aquisição posterior',()=>{const result=strategicInterventions(decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]),operational);assert.ok(result.primary_interventions.every(item=>item.dimension==='ABSORVER'));assert.ok(result.parallel_interventions.some(item=>item.dimension==='CONVERTER'));assert.ok(result.parallel_interventions.some(item=>item.dimension==='GERIR'));assert.ok(result.acquisition_interventions.every(item=>item.timing==='POSTERIOR'))});
test('Beta usa nomenclatura natural, resumo dimensional e limita os três blocos executivos',()=>{const result=strategicInterventions(decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]),[...operational,evidence('CONTROLE_RETORNO',0),evidence('ROTINA_GESTAO',1,'CRESCER'),evidence('CLIENTE_IDEAL',1,'ATRAIR'),evidence('RASTREABILIDADE_AQUISICAO',2,'ATRAIR')]);assert.equal(result.primary_interventions[0].title,'Estruturar padrão de primeira resposta');assert.match(result.intervention_summary,/A prioridade inicial é fortalecer a capacidade de absorção das oportunidades/i);assert.doesNotMatch(result.intervention_summary,/A primeira capacidade a evoluir/i);assert.ok(result.primary_interventions.length<=3);assert.ok(result.parallel_interventions.length<=3);assert.ok(result.acquisition_interventions.length<=3);assert.ok(result.strengths_to_preserve.length<=3);assert.ok(result.discarded_interventions.some(item=>item.reason==='limite do card'))});
test('aquisição respeita severity e score antes do impacto estratégico e mantém máximo três',()=>{const result=strategicInterventions(decision(['ALTA',81],['BAIXA',50],['BAIXA',38],['BAIXA',25]),[evidence('MENSURACAO_AQUISICAO',0,'ATRAIR'),evidence('DEMANDA',1,'ATRAIR'),evidence('ESTRATEGIA_AQUISICAO',2,'ATRAIR'),evidence('PREVISIBILIDADE_AQUISICAO',2,'ATRAIR'),evidence('CLIENTE_IDEAL',2,'ATRAIR')]);assert.deepEqual(result.acquisition_interventions.map(item=>item.capability),['MENSURACAO_AQUISICAO','DEMANDA','ESTRATEGIA_AQUISICAO']);assert.equal(result.acquisition_interventions.length,3);assert.ok(result.all_interventions.length>result.acquisition_interventions.length)});
test('Alfa e Original priorizam conversão, mantêm gestão paralela e aquisição controlada',()=>{for(const readiness of [['MEDIA',63],['ALTA',75]]){const result=strategicInterventions(decision(['ALTA',81],readiness,['BAIXA',41],['BAIXA',25]),operational);assert.ok(result.primary_interventions.every(item=>item.dimension==='CONVERTER'));assert.ok(result.parallel_interventions.some(item=>item.dimension==='GERIR'));assert.ok(result.acquisition_interventions.every(item=>item.timing==='PARALELO'))}});
test('catálogo é canônico, neutro e versionado',()=>{const source=fs.readFileSync(new URL('../lib/strategicInterventionEngine.ts',import.meta.url),'utf8');assert.equal(STRATEGIC_INTERVENTION_ENGINE_VERSION,'1.0');assert.equal(new Set(STRATEGIC_INTERVENTION_CATALOG.map(item=>item.capability)).size,STRATEGIC_INTERVENTION_CATALOG.length);assert.doesNotMatch(source,/Nimble|Google Ads|Meta Ads|WhatsApp Oficial|Dashboard Executivo|Agente de IA|Landing Page|Webchat/)});
test('UI insere card entre direção e leitura e debug sem JSON bruto',()=>{const source=fs.readFileSync(new URL('../components/DiagnosticConsultantBriefing.tsx',import.meta.url),'utf8');assert.match(source,/StrategicDirectionCard decision=\{decision\}\/\><StrategicInterventionsCard/);assert.match(source,/StrategicInterventionsCard[\s\S]*Leitura estratégica da aquisição/);assert.match(source,/MOTOR DE INTERVENÇÕES 1\.0/);assert.doesNotMatch(source,/JSON\.stringify\(interventions|<pre>\{interventions/)});
