
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>fs.readFileSync(new URL('../'+path,import.meta.url),'utf8');
test('migration creates structural mapping with constraints and RLS',()=>{const sql=read('database/migration_v58_integracao_motor_biblioteca.sql');assert.match(sql,/create table if not exists public\.intervencao_solucoes/);assert.match(sql,/unique \(intervention_code, solucao_id\)/);assert.match(sql,/references public\.catalogo_recursos\(id\)/);assert.match(sql,/enable row level security/)});
test('3.0 pricing uses UI and canonical monthly value, never default implantation price',()=>{const source=read('lib/commercialPricingResolver.ts');assert.match(source,/ui\*unit/);assert.match(source,/solution\.valor_mensal/);assert.doesNotMatch(source,/solution\.valor_implantacao_padrao/)});
test('solution resolver deduplicates by solution id and preserves source interventions',()=>{const source=read('lib/strategicSolutionResolver.ts');assert.match(source,/direct=new Map/);assert.match(source,/current\.source\.add\(link\.intervention_code\)/);assert.match(source,/source_interventions:\[\.\.\.g\.source\]/);assert.match(source,/resolveCommercialDependencies/);assert.match(source,/unmapped_interventions/)});
test('commercial bridge is master-only and does not publish or contract',()=>{const source=read('app/api/strategic-commercial/route.ts');assert.match(source,/isMaster\(req\)/);assert.doesNotMatch(source,/financeiro_growth|contratos_growth|aceites_growth|pagamentos_growth|published_snapshot/)});
test('strategic commercial API does not shadow the Web API URL constructor',()=>{const source=read('app/api/strategic-commercial/route.ts');assert.doesNotMatch(source,/const URL=process\.env\.SUPABASE_URL/);assert.match(source,/const SUPABASE_URL=process\.env\.SUPABASE_URL/);assert.match(source,/new globalThis\.URL\(req\.url\)/)});
test('commercial composition is reachable from the real company dossier flow',()=>{const dossier=read('components/CentralApp.tsx'),area=read('components/ClientAreaPanel.tsx'),evolution=read('components/CommercialEvolutionPanel.tsx');assert.match(dossier,/ClientAccessCard companyId=\{companyId\}/);assert.match(area,/ExecutionStrategySummary companyId=\{companyId\}\/><CommercialEvolutionPanel companyId=\{companyId\}/);assert.match(evolution,/<StrategicCommercialComposition companyId=\{companyId\}/);assert.doesNotMatch(evolution,/\{situation&&<StrategicCommercialComposition/)});
test('composition is isolated by company, latest diagnostic and matching executable plan version',()=>{const api=read('app/api/strategic-commercial/route.ts');assert.match(api,/diagnosticos\?empresa_id=eq\./);assert.match(api,/strategic_execution_plans\?empresa_id=eq\./);assert.match(api,/diagnostico_id=eq\./);assert.match(api,/order=version_number\.desc/);assert.match(api,/plan_id:plan\?\.id/);assert.match(api,/plan_version:plan\?\.version_number/);assert.match(api,/intervencao_solucoes\?select=/)});
test('composition remains review-only until explicit application and stays out of the client portal',()=>{const composition=read('components/StrategicCommercialComposition.tsx'),portal=read('components/PortalApp.tsx'),effectLine=composition.split('\n').find(line=>line.includes('useEffect('))||'';assert.match(composition,/onClick=\{apply\}/);assert.match(composition,/apenas prepara o rascunho/);assert.match(composition,/window\.prompt\('Informe a justificativa/);assert.doesNotMatch(effectLine,/onApply/);assert.doesNotMatch(composition,/contratos_growth|aceites_growth|pagamentos_growth|published_snapshot/);assert.doesNotMatch(portal,/StrategicCommercialComposition|Composição Comercial/)});

test('applying composition persists and reopens the exact strategic draft',()=>{const api=read('app/api/commercial-evolution/route.ts'),panel=read('components/CommercialEvolutionPanel.tsx');assert.match(api,/action==='prepare-strategic-draft'/);assert.match(api,/strategic_context:strategicContext/);assert.match(api,/diagnostic_id===diagnosticId/);assert.match(api,/plan_id===planId/);assert.match(api,/plan_version\)===planVersion/);assert.match(api,/projeto_evolucao_id:project\.id/);assert.match(api,/empresa_id=eq\.\$\{encodeURIComponent\(empresaId\)\}/);assert.match(panel,/REVISAR PROJETO DE EVOLUÇÃO/);assert.match(panel,/editProject\(preparedProject\)/);assert.doesNotMatch(panel,/\{situation&&<section id="evolution-project-editor"/)});
test('strategic draft preparation is idempotent and does not publish or formalize',()=>{const source=read('app/api/commercial-evolution/route.ts'),start=source.indexOf("if(body.action==='prepare-strategic-draft')"),end=source.indexOf('const currentContext=await context(empresaId),duplicate=',start),branch=source.slice(start,end);assert.match(branch,/if\(existing\)/);assert.match(branch,/method:'PATCH'/);assert.match(branch,/status:'Rascunho'/);assert.doesNotMatch(branch,/contratos_growth|aceites_growth|pagamentos_growth|published_snapshot|status:'Publicado'|formalizado_em/)});
test('strategic 3.0 draft is explicitly identified and keeps its commercial snapshot',()=>{const api=read('app/api/commercial-evolution/route.ts');assert.match(api,/flow:'ESTRATEGICO_3_0'/);assert.match(api,/commercial_snapshot:\{valor_implantacao:amount\(body\.valor_implantacao_adicional\),valor_mensal:amount\(body\.mensalidade_adicional\)/);assert.match(api,/strategic_direction:body\.strategic_direction/);assert.match(api,/primary_priority:body\.primary_priority/)});
test('strategic editor never merges or renders Growth Motor 1.0 for the same project',()=>{const panel=read('components/CommercialEvolutionPanel.tsx');assert.match(panel,/motorItems=isStrategicProject\(form\)\?\[\]:list\(data\?\.motor\?\.all\)/);assert.match(panel,/strategic\?<StrategicProjectOverview project=\{form\}\/\>:<MotorOverview motor=\{data\.motor\}\/\>/);assert.match(panel,/Projeto originado|Composição Comercial validada/);assert.match(panel,/list\(data\?\.projects\)\.some\(\(project:any\)=>project\.status==='Rascunho'&&isStrategicProject\(project\)\)/)});
test('strategic draft uses persisted resources and frozen values after reopening',()=>{const panel=read('components/CommercialEvolutionPanel.tsx');assert.match(panel,/setForm\(payload\.project\)/);assert.match(panel,/projeto_evolucao_recursos/);assert.match(panel,/parametros_snapshot\?\.flow==='ESTRATEGICO_3_0'/);assert.match(panel,/setStrategicResources\(strategic\?Object\.fromEntries\(included\.map/);assert.match(panel,/valor_implantacao_adicional:context\.totals\.implantacao/);assert.match(panel,/mensalidade_adicional:context\.totals\.mensal/);assert.match(panel,/snapshot\.valor_implantacao\?\?project\.valor_implantacao_adicional/);assert.match(panel,/snapshot\.valor_mensal\?\?project\.mensalidade_adicional/)});
test('legacy drafts retain Growth Motor 1.0 behavior',()=>{const panel=read('components/CommercialEvolutionPanel.tsx');assert.match(panel,/function MotorOverview/);assert.match(panel,/Motor de Crescimento 1\.0/);assert.match(panel,/strategic\?.*:<MotorOverview/)});

