const URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY,ANON=process.env.SUPABASE_ANON_KEY;
const h=()=>({apikey:KEY!,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'});
async function authorized(req:Request){const t=req.headers.get('cookie')?.match(/escala_session=([^;]+)/)?.[1];if(!t||!URL||!ANON)return false;return (await fetch(`${URL}/auth/v1/user`,{headers:{apikey:ANON,Authorization:`Bearer ${t}`}})).ok}
const out=async(r:Response)=>new Response(await r.text(),{status:r.status,headers:{'Content-Type':'application/json; charset=utf-8'}});
export async function GET(req:Request){if(!await authorized(req))return Response.json({error:'Não autorizado'},{status:401});const u=new URL(req.url),resource=u.searchParams.get('resource');if(resource==='config')return out(await fetch(`${URL}/rest/v1/configuracoes?select=*&limit=1`,{headers:h()}));if(resource==='meetings')return out(await fetch(`${URL}/rest/v1/reunioes_estrategicas?select=*&order=data.desc`,{headers:h()}));if(resource==='versions')return out(await fetch(`${URL}/rest/v1/plano_estrategico_versoes?diagnostico_id=eq.${u.searchParams.get('id')}&select=*&order=versao.desc`,{headers:h()}));return Response.json({error:'Recurso inválido'},{status:400})}
export async function POST(req:Request){if(!await authorized(req))return Response.json({error:'Não autorizado'},{status:401});const u=new URL(req.url),resource=u.searchParams.get('resource');if(resource==='logo'){const form=await req.formData(),file=form.get('logo') as File;if(!file||file.size>3*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))return Response.json({error:'Use PNG, JPG ou WEBP com até 3 MB.'},{status:400});const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg',path=`branding/logo-escala-vendas.${ext}`;const upload=await fetch(`${URL}/storage/v1/object/${path}`,{method:'POST',headers:{apikey:KEY!,Authorization:`Bearer ${KEY}`,'Content-Type':file.type,'x-upsert':'true'},body:await file.arrayBuffer()});if(!upload.ok)return out(upload);const publicUrl=`${URL}/storage/v1/object/public/${path}`;await upsertConfig({logo_url:publicUrl});return Response.json({logo_url:publicUrl})}const body=await req.json();if(resource==='config'){await upsertConfig(body);return Response.json({ok:true})}if(resource==='meetings')return out(await fetch(`${URL}/rest/v1/reunioes_estrategicas`,{method:'POST',headers:{...h(),Prefer:'return=representation'},body:JSON.stringify(body)}));if(resource==='versions'){const versions=await fetch(`${URL}/rest/v1/plano_estrategico_versoes?diagnostico_id=eq.${body.diagnostico_id}&select=versao&order=versao.desc&limit=1`,{headers:h()}).then(r=>r.json());body.versao=(versions[0]?.versao||0)+1;return out(await fetch(`${URL}/rest/v1/plano_estrategico_versoes`,{method:'POST',headers:{...h(),Prefer:'return=representation'},body:JSON.stringify(body)}))}return Response.json({error:'Recurso inválido'},{status:400})}
export async function PATCH(req:Request){if(!await authorized(req))return Response.json({error:'Não autorizado'},{status:401});const u=new URL(req.url),resource=u.searchParams.get('resource'),body=await req.json(),id=body.id;delete body.id;const table=resource==='meetings'?'reunioes_estrategicas':'configuracoes';return out(await fetch(`${URL}/rest/v1/${table}?id=eq.${id}`,{method:'PATCH',headers:{...h(),Prefer:'return=representation'},body:JSON.stringify({...body,updated_at:new Date().toISOString()})}))}
export async function DELETE(req:Request){if(!await authorized(req))return Response.json({error:'Não autorizado'},{status:401});const u=new URL(req.url);return out(await fetch(`${URL}/rest/v1/reunioes_estrategicas?id=eq.${u.searchParams.get('id')}`,{method:'DELETE',headers:h()}))}
async function upsertConfig(data:any){const rows=await fetch(`${URL}/rest/v1/configuracoes?select=id&limit=1`,{headers:h()}).then(r=>r.json());if(rows[0])return fetch(`${URL}/rest/v1/configuracoes?id=eq.${rows[0].id}`,{method:'PATCH',headers:h(),body:JSON.stringify({...data,updated_at:new Date().toISOString()})});return fetch(`${URL}/rest/v1/configuracoes`,{method:'POST',headers:h(),body:JSON.stringify(data)})}

