import {access} from '@/lib/access';
import {implementationManagement} from '@/lib/implementation-management';

const SUPABASE_URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const headers=()=>({apikey:KEY!,Authorization:'Bearer '+KEY,'Content-Type':'application/json'});
const ready=()=>Boolean(SUPABASE_URL&&KEY);
class DatabaseError extends Error{code:string;details:string;hint:string;status:number;constructor(message:string,code='',details='',hint='',status=500){super(message);this.code=code;this.details=details;this.hint=hint;this.status=status}}
async function db(path:string,options:RequestInit={}){const response=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...options,headers:{...headers(),...(options.headers||{})},cache:'no-store'}),text=await response.text();if(!response.ok){let parsed:any={};try{parsed=JSON.parse(text)}catch{}throw new DatabaseError(parsed.message||parsed.error||text||'O banco não confirmou a operação.',parsed.code||'',parsed.details||'',parsed.hint||'',response.status)}if(!text.trim())return[];return JSON.parse(text)}
async function master(req:Request){const profile=await access(req);if(profile?.role!=='master')return null;return profile}
function managedImplementation(implementation:any,items:any[]){const management=implementationManagement(items);return{...implementation,status:management.summary.status,items:management.items,management:management.summary}}
async function bundle(id:string){const implementations=await db('strategic_plan_implementations?id=eq.'+encodeURIComponent(id)+'&select=*&limit=1'),implementation=implementations[0];if(!implementation)return null;const [items,history,companies]=await Promise.all([db('strategic_plan_implementation_items?implementation_id=eq.'+encodeURIComponent(id)+'&select=*&order=created_at'),db('strategic_plan_implementation_history?implementation_id=eq.'+encodeURIComponent(id)+'&select=*&order=created_at.desc'),db('empresas?id=eq.'+encodeURIComponent(implementation.empresa_id)+'&select=id,nome&limit=1')]);return{...managedImplementation(implementation,items),company:companies[0]||null,history}}
async function listContext(){const [plans,implementations,items,companies]=await Promise.all([db('strategic_execution_plans?status=in.(PUBLISHED,SUPERSEDED)&published_snapshot=not.is.null&select=id,empresa_id,diagnostico_id,version_number,status,strategic_direction,published_at,published_snapshot,created_at&order=published_at.desc'),db('strategic_plan_implementations?select=*&order=created_at.desc'),db('strategic_plan_implementation_items?select=*&order=created_at'),db('empresas?select=id,nome&order=nome')]);const companyMap=new Map(companies.map((item:any)=>[item.id,item])),managed=implementations.map((implementation:any)=>({...managedImplementation(implementation,items.filter((item:any)=>item.implementation_id===implementation.id)),company:companyMap.get(implementation.empresa_id)||null}));return{published_plans:plans.map((plan:any)=>({...plan,company:companyMap.get(plan.empresa_id)||null,implementation:managed.find((item:any)=>item.plan_id===plan.id&&Number(item.plan_version)===Number(plan.version_number))||null})),implementations:managed}}

export async function GET(req:Request){try{if(!ready())return Response.json({error:'Persistência não configurada.'},{status:503});if(!await master(req))return Response.json({error:'Não autorizado.'},{status:401});const id=new URL(req.url).searchParams.get('id');return Response.json(id?{implementation:await bundle(id)}:await listContext())}catch(error:any){console.error('[strategic-implementations] Falha ao carregar',error);return Response.json({error:'Não foi possível carregar as Implantações.'},{status:500})}}

export async function POST(req:Request){let stage='entrada',audit:any={};try{if(!ready())return Response.json({ok:false,error:{code:'PERSISTENCE_NOT_CONFIGURED',message:'Persistência não configurada.',technical_detail:'SUPABASE_URL ou SUPABASE_SERVICE_ROLE_KEY ausente.',stage}},{status:503});const profile=await master(req);if(!profile)return Response.json({ok:false,error:{code:'UNAUTHORIZED',message:'Não autorizado.',technical_detail:'O usuário autenticado não possui perfil Master.',stage}},{status:401});const body=await req.json();audit.plan_id=body.plan_id||null;if(body.operation!=='create'||!body.plan_id)return Response.json({ok:false,error:{code:'PLAN_REQUIRED',message:'Selecione uma versão publicada do Plano.',technical_detail:'operation=create e plan_id são obrigatórios.',stage}},{status:400});
 stage='validação do plano e snapshot';const plan=(await db('strategic_execution_plans?id=eq.'+encodeURIComponent(body.plan_id)+'&select=id,empresa_id,diagnostico_id,version_number,status,published_snapshot&limit=1'))[0];audit={...audit,plan_version:plan?.version_number??null,diagnostic_id:plan?.diagnostico_id??null,status:plan?.status??null,published_snapshot:Boolean(plan?.published_snapshot),snapshot_actions:Array.isArray(plan?.published_snapshot?.actions)?plan.published_snapshot.actions.length:0};if(!plan)return Response.json({ok:false,error:{code:'PLAN_NOT_FOUND',message:'Plano Estratégico Executável não localizado.',technical_detail:'Nenhum registro encontrado para o plan_id recebido.',stage,debug:audit}},{status:404});
 stage='verificação de duplicidade';const existing=(await db('strategic_plan_implementations?plan_id=eq.'+encodeURIComponent(body.plan_id)+'&plan_version=eq.'+encodeURIComponent(plan.version_number)+'&select=id&limit=1'))[0];audit.existing_implementation_id=existing?.id||null;if(existing){const implementation=await bundle(existing.id);return Response.json({ok:true,existing:true,implementation_id:existing.id,message:'Esta versão publicada já possui uma Implantação.',implementation,debug:{...audit,stage:'implantação existente',status:'OK'}},{status:200})}
 stage='execução da função SQL';const rpcArguments={p_plan_id:body.plan_id,p_actor:profile.email||'Usuário Master'};audit.rpc_arguments=rpcArguments;const result=await db('rpc/create_strategic_plan_implementation',{method:'POST',body:JSON.stringify(rpcArguments)}),id=Array.isArray(result)?result[0]:result;audit.rpc_raw_result=result;if(!id)throw new DatabaseError('A função SQL não retornou o identificador da Implantação.','EMPTY_RPC_RESULT');
 stage='confirmação dos itens';const implementation=await bundle(String(id));audit.implementation_id=String(id);audit.created_items=implementation?.items?.length||0;audit.horizons=(implementation?.items||[]).reduce((map:any,item:any)=>({...map,[item.agreed_horizon]:(map[item.agreed_horizon]||0)+1}),{});return Response.json({ok:true,existing:false,implementation_id:String(id),message:'Implantação criada com sucesso.',implementation,debug:{...audit,stage,status:'OK'}},{status:200})
 }catch(error:any){const technical=[error?.message,error?.details,error?.hint].filter(Boolean).join(' | ');console.error('[strategic-implementations] Falha ao criar',{stage,audit,code:error?.code,status:error?.status,technical});return Response.json({ok:false,error:{code:error?.code||'IMPLEMENTATION_CREATION_FAILED',message:'Não foi possível criar a Implantação.',technical_detail:technical||'Falha não detalhada pelo banco.',stage,debug:audit}},{status:error?.status>=400&&error?.status<500?error.status:500})}}

export async function PATCH(req:Request){
 try{
  if(!ready())return Response.json({error:'Persistência não configurada.'},{status:503});
  const profile=await master(req);if(!profile)return Response.json({error:'Não autorizado.'},{status:401});
  const body=await req.json();if(body.operation!=='update-item'||!body.item_id)return Response.json({error:'Item de Implantação não informado.'},{status:400});
  const original=(await db('strategic_plan_implementation_items?id=eq.'+encodeURIComponent(body.item_id)+'&select=*&limit=1'))[0];if(!original)return Response.json({error:'Item de Implantação não localizado.'},{status:404});
  const allowed=['operational_responsible','operational_due_date','status','started_at','completed_at','execution_notes','execution_evidence'],changes:any={updated_at:new Date().toISOString()};for(const field of allowed)if(body[field]!==undefined)changes[field]=body[field]||null;
  const now=new Date().toISOString();if(['IN_PROGRESS','COMPLETED'].includes(changes.status)&&!changes.started_at&&!original.started_at)changes.started_at=now;if(changes.status==='COMPLETED'&&!changes.completed_at&&!original.completed_at)changes.completed_at=now;if(changes.status!=='COMPLETED'&&body.status!==undefined)changes.completed_at=null;
  const effectiveStarted=changes.started_at??original.started_at,effectiveCompleted=changes.completed_at??original.completed_at;if(effectiveStarted&&effectiveCompleted&&new Date(effectiveCompleted)<new Date(effectiveStarted))return Response.json({error:'A data de conclusão não pode ser anterior à data de início.'},{status:400});
  const saved=(await db('strategic_plan_implementation_items?id=eq.'+encodeURIComponent(original.id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(changes)}))[0];
  const items=await db('strategic_plan_implementation_items?implementation_id=eq.'+encodeURIComponent(original.implementation_id)+'&select=*'),management=implementationManagement(items),completed=management.summary.status==='COMPLETED',started=management.summary.status!=='PLANNED',currentImplementation=(await db('strategic_plan_implementations?id=eq.'+encodeURIComponent(original.implementation_id)+'&select=started_at,completed_at,status&limit=1'))[0],implementationChanges:any={status:management.summary.status,updated_at:now,completed_at:completed?(currentImplementation?.completed_at||now):null};if(started&&!currentImplementation?.started_at)implementationChanges.started_at=now;
  await db('strategic_plan_implementations?id=eq.'+encodeURIComponent(original.implementation_id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(implementationChanges)});
  const labels:Record<string,string>={operational_responsible:'Responsável operacional',operational_due_date:'Prazo operacional',status:'Status',started_at:'Data de início',completed_at:'Data de conclusão',execution_notes:'Observação de execução',execution_evidence:'Evidência textual'},events:any[]=[];for(const field of allowed)if(original[field]!==saved[field]){const reopened=field==='status'&&original.status==='COMPLETED'&&saved.status!=='COMPLETED';events.push({event_type:reopened?'ITEM_REOPENED':field==='status'?(saved.status==='IN_PROGRESS'?'ITEM_STARTED':saved.status==='COMPLETED'?'ITEM_COMPLETED':'STATUS_CHANGED'):'FIELD_CHANGED',description:reopened?'Ação reaberta.':labels[field]+' alterado.',metadata:{field,before:original[field],after:saved[field]}})}
  if(currentImplementation?.status!==management.summary.status)events.push({event_type:'IMPLEMENTATION_STATUS_CHANGED',description:'Status consolidado da Implantação alterado.',metadata:{field:'implementation_status',before:currentImplementation?.status,after:management.summary.status}});
  if(events.length){const historyRows=events.map(event=>({implementation_id:original.implementation_id,item_id:original.id,...event,actor:profile.email||'Usuário Master'}));await db('strategic_plan_implementation_history',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(historyRows)})}
  return Response.json({ok:true,message:'Item da Implantação salvo com sucesso.',implementation:await bundle(original.implementation_id)});
 }catch(error){console.error('[strategic-implementations] Falha ao atualizar item',error);return Response.json({error:'Não foi possível salvar o item da Implantação.'},{status:500})}
}
