'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';

const rows=(value:any):any[]=>Array.isArray(value)?value:[];
const labels:Record<string,string>={proposta_publicacoes:'Propostas Comerciais',financeiro_growth:'Financeiro',contratos_growth:'Contratos ou Termos',aceites_growth:'Aceites e evidências',pagamentos_growth:'Pagamentos'};
const date=(value:any)=>value?new Date(value).toLocaleString('pt-BR'):'—';
const links=(value:any):string[]=>{const found:string[]=[];const visit=(item:any)=>{if(typeof item==='string'&&/^https:\/\//i.test(item))found.push(item);else if(Array.isArray(item))item.forEach(visit);else if(item&&typeof item==='object')Object.values(item).forEach(visit)};visit(value);return [...new Set(found)]};

function Documents({documents}:{documents:Record<string,any[]>}){return <div className="archived-documents">{Object.entries(labels).map(([table,label])=>{const records=rows(documents?.[table]);return <details key={table}><summary>{label} <b>{records.length}</b></summary>{records.length?records.map(record=><article key={record.id}><span>{record.status||record.metodo||'Registro histórico'}</span><small>{date(record.updated_at||record.created_at||record.aceito_em||record.publicada_em)}</small>{links(record).map((link,index)=><a href={link} target="_blank" rel="noreferrer" key={link}>Abrir evidência {index+1} ↗</a>)}</article>):<p>Nenhum registro vinculado.</p>}</details>})}</div>}

export function ArchivedFormalizations(){
 const[data,setData]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/companies?archived=true',{cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'Não foi possível carregar o arquivo.');setData(rows(body))}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[]);
 return <main className="archived-page"><header><div><span className="eyebrow">Arquivo administrativo</span><h1>Formalizações Arquivadas</h1></div><Link className="btn btn-secondary" href="/central/empresas">← Voltar para Empresas</Link></header><p className="separation-note">Área exclusiva do Administrador. O conteúdo é somente leitura e não está disponível no Portal do Cliente.</p>{loading?<div className="loading-state">Carregando histórico documental...</div>:error?<div className="loading-state error-state">{error}</div>:data.length===0?<div className="loading-state">Nenhuma empresa arquivada.</div>:<section className="archived-formalizations">{data.map(company=><article className="admin-section" key={company.id}><span className="status-pill">EMPRESA ARQUIVADA</span><h2>{company.nome}</h2><p>Arquivada em {date(company.arquivada_em)} · Motivo: {company.motivo_arquivamento||'EMPRESA_EXCLUIDA'}</p>{rows(company.formalizacoes).map(formalization=><section className="archived-formalization" key={formalization.id}><h3>{formalization.origem==='IMPLANTACAO_FERRAMENTAS'?'Implantação de Ferramentas':'Escala Growth'} · Versão {formalization.versao}</h3><p>Formalização {formalization.id} · <b>{formalization.status}</b></p><Documents documents={formalization.documents}/></section>)}{Object.values(company.legado_sem_formalizacao||{}).some(value=>rows(value).length>0)&&<section className="archived-formalization legacy"><h3>Histórico sem formalização identificada</h3><p>Preservado sem associação automática para revisão administrativa.</p><Documents documents={company.legado_sem_formalizacao}/></section>}</article>)}</section>}</main>
}
