"use client";
import {useEffect,useState} from 'react';
import styles from './ClientStrategicView.module.css';

const date=(value:any)=>value?new Date(/^\d{4}-\d{2}-\d{2}$/.test(String(value))?String(value)+'T12:00:00':value).toLocaleDateString('pt-BR'):'A definir';
const value=(raw:any)=>raw===null||raw===undefined||raw===''?'Sem medição':`${Number(raw)}%`;

export function ClientStrategicView(){
 const [tab,setTab]=useState('overview'),[data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{const company=new URLSearchParams(location.search).get('empresa');fetch('/api/portal-strategic'+(company?'?empresa='+encodeURIComponent(company):''),{cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body.view)}).catch(reason=>setError(reason?.message||'Não foi possível carregar a Visão Estratégica.'))},[]);
 if(error)return <section className="portal-card"><h2>Não foi possível abrir a Visão Estratégica</h2><p>{error}</p></section>;
 if(!data)return <section className="portal-card"><p>Preparando sua visão estratégica...</p></section>;
 if(!data?.available)return <section className="portal-card"><span className="eyebrow">Visão Estratégica</span><h2>Seu plano está em preparação</h2><p>Assim que o Plano Estratégico for publicado, esta área apresentará sua direção, implantação e evolução.</p></section>;
 const plan=data.plan,implementation=data.implementation,evolution=data.evolution;
 return <div className={styles.root}><nav className="strategic-tabs" aria-label="Visão Estratégica">{[['overview','Visão Geral'],['plan','Plano Estratégico'],['implementation','Implantação'],['evolution','Evolução']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
 {tab==='overview'&&<><section className="portal-hero strategic-hero"><div><span>Direção estratégica</span><h2>{plan.direction||'Evoluir com consistência'}</h2><p>Prioridade atual: {plan.priority||'A definir'}</p></div><div><small>Plano vigente</small><b>Versão {plan.version}</b></div></section><div className="portal-summary"><article><small>Implantação</small><b>{implementation?.status||'Ainda não iniciada'}</b></article><article><small>Progresso</small><b>{implementation?implementation.summary.progress_percentage+'%':'Sem implantação'}</b></article><article><small>Última medição</small><b>{evolution.has_measurement?date(evolution.latest.measured_at):'Sem medição'}</b></article></div><ExecutiveLists data={data}/></>}
 {tab==='plan'&&<section className="portal-card"><span className="eyebrow">Plano Estratégico Executável</span><h2>Plano vigente · Versão {plan.version}</h2><p>{plan.notes||'Direcionamento consolidado para a evolução da empresa.'}</p>{Object.entries(data.actions||{}).map(([key,items]:any)=><section className="strategic-action-group" key={key}><h3>{items[0]?.horizon_label||({'AGORA':'Agora','DEPOIS':'Depois','QUANDO_ESTIVER_PRONTO':'Quando estiver pronto'} as any)[key]}</h3>{items.length?items.map((item:any)=><article key={item.id||item.agreed_title}><b className="strategic-action-title">{item.agreed_title}</b>{item.agreed_objective&&<p>{item.agreed_objective}</p>}<dl className="strategic-agreement"><div><dt>Responsável acordado</dt><dd>{item.agreed_responsible||'A definir'}</dd></div><div><dt>Prazo acordado</dt><dd>{item.agreed_due_date?date(item.agreed_due_date):item.agreed_horizon==='QUANDO_ESTIVER_PRONTO'?'Sem prazo aplicável':'Sem prazo definido'}</dd></div></dl></article>):<p>Nenhuma ação definida para este horizonte.</p>}</section>)}</section>}
 {tab==='implementation'&&<section className="portal-card"><span className="eyebrow">Implantação</span><h2>{implementation?implementation.status:'Ainda não iniciada'}</h2>{implementation?<><div className="implementation-progress"><i style={{width:implementation.summary.progress_percentage+'%'}}/><b>{implementation.summary.progress_percentage}% concluído</b></div><div className="strategic-items">{implementation.items.map((item:any)=><article key={item.id}><div><b>{item.agreed_title}</b><small>{item.horizon_label} · {item.status_label}</small></div><span>{item.operational_responsible||'Responsável a definir'}<br/>{date(item.operational_due_date)}</span></article>)}</div></>:<p>A implantação será apresentada aqui quando for iniciada a partir do Plano Estratégico vigente.</p>}</section>}
 {tab==='evolution'&&<section className="portal-card"><span className="eyebrow">Evolução</span><h2>Evolução da maturidade comercial</h2>{evolution.has_measurement?<div className="evolution-history">{evolution.timeline.map((measurement:any)=><article key={measurement.id}><b>{date(measurement.measured_at)}</b><div>{measurement.reading.map((item:any)=><span key={item.key}><small>{item.label}</small><strong>{value(item.current)}</strong></span>)}</div></article>)}</div>:<p>Sem medição de evolução registrada até o momento.</p>}</section>}
 </div>;
}

function ExecutiveLists({data}:{data:any}){return <div className="strategic-executive-grid"><section className="portal-card"><span className="eyebrow">Próximos passos</span><h2>O que vem agora</h2>{data.next_steps.length?data.next_steps.map((item:any)=><article className="executive-line" key={item.title}><div><b>{item.title}</b><small>{item.responsible} · {date(item.due_date)}</small></div><span>{item.status}</span></article>):<p>Nenhuma ação pendente no momento.</p>}</section><section className="portal-card"><span className="eyebrow">Pontos de atenção</span><h2>Acompanhamento</h2>{data.attention_points.length?<ul>{data.attention_points.map((item:string)=><li key={item}>{item}</li>)}</ul>:<p>A implantação segue sem alertas operacionais relevantes no momento.</p>}</section></div>}
