'use client';

import {useEffect,useMemo,useState} from 'react';
import {CommercialEvolutionPanel} from './CommercialEvolutionPanel';

type ChecklistItem={label:string;done:boolean};

const labels={
 preparation:['Plano Estratégico concluído','Proposta de Implantação aprovada','Financeiro configurado'],
 release:['Área do Cliente publicada','Primeiro acesso realizado','Proposta aceita','Contrato assinado','Pagamento confirmado'],
 implementation:['Kickoff realizado','Implantação técnica concluída','Método Escala Growth iniciado']
};

function ChecklistGroup({title,items}:{title:string;items:{label:string;done:boolean}[]}){
 return <section className="client-area-checklist-group"><h3>{title}</h3>{items.map(item=><div key={item.label} className={item.done?'done':'pending'}><b>{item.done?'✔':'☐'}</b><span>{item.label}</span></div>)}</section>
}

export function ClientAreaPanel({companyId,company}:{companyId:string;company:any}){
 const responsible=Array.isArray(company?.responsaveis)?company.responsaveis[0]||{}:{};
 const [data,setData]=useState<any>(null),[form,setForm]=useState<any>({nome:responsible.nome||'',email:responsible.email||'',telefone:responsible.telefone||''}),[message,setMessage]=useState(''),[pending,setPending]=useState<string[]>([]),[busy,setBusy]=useState(false);
 const load=async()=>{const response=await fetch('/api/client-access?empresa_id='+companyId,{cache:'no-store'}),payload=await response.json();setData(payload);setForm((current:any)=>({nome:payload.access?.nome||payload.responsible?.nome||responsible.nome||current.nome,email:payload.access?.email||payload.responsible?.email||responsible.email||current.email,telefone:payload.access?.telefone||payload.responsible?.telefone||responsible.telefone||current.telefone}))};
 useEffect(()=>{load()},[companyId]);
 const act=async(action:string,extra:Record<string,unknown>={})=>{if(action==='publish'&&(!form.nome||!form.email)){setMessage('Informe o nome e o e-mail do responsável.');return}if(['deactivate','reset'].includes(action)&&!confirm(action==='deactivate'?'Bloquear o acesso deste cliente?':'Gerar um novo convite e permitir a redefinição da senha?'))return;setBusy(true);setMessage('');setPending([]);const response=await fetch('/api/client-access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,empresa_id:companyId,...form,...extra})}),payload=await response.json().catch(()=>({}));setBusy(false);if(response.ok){setMessage(payload.message||'Ação concluída.');if(payload.link)await navigator.clipboard.writeText(payload.link);await load()}else{setMessage(payload.error||'Não foi possível concluir a ação.');setPending(Array.isArray(payload.pending)?payload.pending:[])}};
 const journey=useMemo(()=>{const checks=(data?.checklist||[]) as ChecklistItem[],done=(index:number)=>Boolean(checks[index]?.done),preparation=[done(0),done(1),done(2)],published=done(3),accessed=done(4),accepted=done(5),contractSigned=Boolean(data?.contract_signed??accepted),paid=done(6),kickoff=done(7),implementationDone=done(8),active=done(9),allPrepared=preparation.every(Boolean);let status='Preparando Proposta',next='Concluir a preparação da proposta.';if(allPrepared){status='Aguardando Publicação';next='Aguardando publicação da Área do Cliente.'}if(published){status='Aguardando Primeiro Acesso';next='Aguardando primeiro acesso do cliente.'}if(accessed){status='Aguardando Aceite';next='Aguardando aceite da proposta.'}if(accepted){status='Aguardando Assinatura do Contrato';next='Aguardando assinatura do contrato.'}if(contractSigned){status='Aguardando Pagamento';next='Aguardando confirmação do pagamento.'}if(paid){status='Implantação em andamento';next='Realizar Kickoff.'}if(kickoff)next='Concluir implantação técnica.';if(implementationDone)next='Iniciar Método Escala Growth.';if(active){status='Método Escala Growth iniciado';next='Acompanhar a evolução contínua da empresa.'}const groups={preparation:labels.preparation.map((label,index)=>({label,done:preparation[index]})),release:[{label:labels.release[0],done:published},{label:labels.release[1],done:accessed},{label:labels.release[2],done:accepted},{label:labels.release[3],done:contractSigned},{label:labels.release[4],done:paid}],implementation:[{label:labels.implementation[0],done:kickoff},{label:labels.implementation[1],done:implementationDone},{label:labels.implementation[2],done:active}]};const timeline=[{label:'Preparação',done:allPrepared,started:preparation.some(Boolean)},{label:'Área do Cliente',done:published&&accessed,started:published},{label:'Aceite',done:accepted&&contractSigned,started:accessed},{label:'Pagamento',done:paid,started:contractSigned},{label:'Implantação',done:implementationDone,started:kickoff||paid},{label:'Método Escala Growth',done:active,started:implementationDone}];return{status,next,groups,timeline,published,accessed,paid,kickoff,implementationDone,active}},[data]);
 if(!data)return <section id="company-publication" className="admin-section"><p>Preparando Área do Cliente...</p></section>;
 const access=data.access,publication=data.publication,accessStatus=!access?'Não criado':!access.ativo?'Acesso bloqueado':access.primeiro_acesso_em?'Primeiro acesso realizado':access.status_acesso||'Convite pendente',tone=journey.active?'completed':journey.status==='Preparando Proposta'||journey.status==='Implantação em andamento'?'progress':'waiting';
 return <><CommercialEvolutionPanel companyId={companyId}/><section id="company-publication" className="admin-section client-access-card publication-panel client-area-panel">
  <span className="eyebrow">Área do Cliente</span><h2>Área do Cliente</h2><p>Gerencie a liberação da Área do Cliente e acompanhe todas as etapas do onboarding até o início do Método Escala Growth.</p>
  <div className="detail-metrics client-area-metrics">{[['Situação do acesso',accessStatus],['Versão publicada',publication?.versao?'Versão '+publication.versao:'—'],['Data da publicação',publication?.publicada_em?new Date(publication.publicada_em).toLocaleString('pt-BR'):'—'],['Primeiro acesso',access?.primeiro_acesso_em?new Date(access.primeiro_acesso_em).toLocaleString('pt-BR'):'—'],['Último acesso',access?.ultimo_acesso_em?new Date(access.ultimo_acesso_em).toLocaleString('pt-BR'):'—']].map(([label,value])=><div key={label}><small>{label}</small><b>{value}</b></div>)}<div className={'journey-status-card '+tone}><small>Status da Jornada</small><b>{journey.status}</b></div></div>
  <section className={'client-area-next '+tone}><small>Próxima Ação</small><h3>{journey.next}</h3></section>
  <div className="client-area-timeline">{journey.timeline.map((step,index)=><div key={step.label} className={step.done?'completed':step.started?'progress':'pending'}><i>{step.done?'✓':step.started?'●':'○'}</i><span>{step.label}</span>{index<journey.timeline.length-1&&<b>→</b>}</div>)}</div>
  <div className="client-area-checklists"><ChecklistGroup title="Preparação" items={journey.groups.preparation}/><ChecklistGroup title="Liberação da Área do Cliente" items={journey.groups.release}/><ChecklistGroup title="Implantação" items={journey.groups.implementation}/></div>
  <div className="financial-form"><label>Nome do responsável<input value={form.nome} onChange={event=>setForm({...form,nome:event.target.value})}/></label><label>E-mail<input type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>Telefone<input value={form.telefone} onChange={event=>setForm({...form,telefone:event.target.value})}/></label><label>Empresa<input value={data.company?.nome||company?.nome||''} readOnly/></label></div>
  {pending.length>0&&<div className="publication-pending"><b>Conclua estas informações antes de publicar:</b><ul>{pending.map(item=><li key={item}>{item.replace('Plano de Implantação','Proposta de Implantação')}</li>)}</ul></div>}
  <section className="client-area-stage-action"><span className="eyebrow">Ação da etapa</span>{!journey.published?<><button className="btn btn-primary" disabled={busy} onClick={()=>act('publish')}>{busy?'Validando publicação...':'🚀 Publicar Área do Cliente'}</button><p>Publica o Plano Estratégico, a Proposta de Implantação, o Contrato e o Plano de Implantação na Área do Cliente, cria o usuário de acesso e envia o e-mail de boas-vindas.</p><div className="publication-content-note"><b>Ao publicar, o cliente receberá acesso à sua Área do Cliente contendo:</b><ul><li>Plano Estratégico</li><li>Proposta de Implantação</li><li>Contrato</li><li>Plano de Implantação</li><li>Orientações para início do projeto</li></ul></div></>:!journey.accessed?<><button className="btn btn-secondary" disabled>Registrar Primeiro Acesso</button><p>O primeiro acesso já é reconhecido automaticamente quando o cliente cria a senha. O controle permanece preparado para futuras automações.</p></>:journey.paid&&!journey.kickoff?<button className="btn btn-primary" disabled={busy} onClick={()=>confirm('Confirmar que o Kickoff foi realizado?')&&act('operational_stage',{stage:'kickoff'})}>Registrar Kickoff</button>:journey.kickoff&&!journey.implementationDone?<button className="btn btn-primary" disabled={busy} onClick={()=>confirm('Confirmar que a implantação técnica foi concluída?')&&act('operational_stage',{stage:'implementation'})}>Finalizar Implantação Técnica</button>:journey.implementationDone&&!journey.active?<button className="btn btn-primary" disabled={busy} onClick={()=>confirm('Confirmar o início oficial do Método Escala Growth?')&&act('operational_stage',{stage:'active'})}>Iniciar Método Escala Growth</button>:journey.active?<p className="success">A jornada de acompanhamento contínuo está ativa.</p>:<p>Esta etapa depende de uma ação do cliente. Acompanhe a Próxima Ação acima.</p>}</section>
  {access&&<div className="detail-actions client-area-access-tools"><button className="btn btn-secondary" disabled={busy} onClick={()=>act('resend')}>Reenviar convite</button>{access.convite_link&&<button className="btn btn-secondary" onClick={()=>navigator.clipboard.writeText(access.convite_link)}>Copiar link de acesso</button>}<button className="btn btn-secondary" disabled={busy} onClick={()=>act('reset')}>Redefinir senha / novo convite</button>{access.ativo!==false?<button className="btn btn-secondary" disabled={busy} onClick={()=>act('deactivate')}>Bloquear acesso</button>:<button className="btn btn-secondary" disabled={busy} onClick={()=>act('reactivate')}>Reativar acesso</button>}</div>}
  {message&&<p className={message.startsWith('Não')||message.startsWith('Informe')||message.includes('pendências')?'error':'success'}>{message.replaceAll('Portal','Área do Cliente')}</p>}
 </section></>
}
