'use client';

import {useEffect,useMemo,useState} from 'react';
import {CommercialEvolutionPanel} from './CommercialEvolutionPanel';
import {ExecutionStrategySummary} from './ExecutionStrategySummary';

type ChecklistItem={label:string;done:boolean;detail?:string};

const labels={
 preparation:['Plano Estratégico concluído','Projeto de Evolução preparado','Financeiro configurado','Contrato/Termo preparado','Área pronta para publicação'],
 release:['Área publicada','Primeiro acesso','Aceite','Contrato/Termo','Pagamento','Formalização'],
 implementation:['Kickoff realizado','Implantação técnica concluída','Método Escala Growth iniciado']
};

function ChecklistGroup({title,items}:{title:string;items:ChecklistItem[]}){
 return <section className="client-area-checklist-group"><h3>{title}</h3>{items.map(item=><div key={item.label} className={item.done?'done':'pending'}><b>{item.done?'✔':'☐'}</b><span>{item.label}{item.detail&&<small>Tipo: {item.detail}</small>}</span></div>)}</section>
}

export function ClientAreaPanel({companyId,company}:{companyId:string;company:any}){
 const responsible=Array.isArray(company?.responsaveis)?company.responsaveis[0]||{}:{};
 const [data,setData]=useState<any>(null),[form,setForm]=useState<any>({nome:responsible.nome||'',email:responsible.email||'',telefone:responsible.telefone||''}),[message,setMessage]=useState(''),[pending,setPending]=useState<string[]>([]),[busy,setBusy]=useState(false);
 const load=async()=>{const response=await fetch('/api/client-access?empresa_id='+companyId,{cache:'no-store'}),payload=await response.json();setData(payload);setForm((current:any)=>({nome:payload.access?.nome||payload.responsible?.nome||responsible.nome||current.nome,email:payload.access?.email||payload.responsible?.email||responsible.email||current.email,telefone:payload.access?.telefone||payload.responsible?.telefone||responsible.telefone||current.telefone}))};
 useEffect(()=>{load()},[companyId]);
 const act=async(action:string,extra:Record<string,unknown>={})=>{if(action==='publish'&&(!form.nome||!form.email)){setMessage('Informe o nome e o e-mail do responsável.');return}if(['deactivate','reset'].includes(action)&&!confirm(action==='deactivate'?'Bloquear o acesso deste cliente?':'Gerar um novo convite e permitir a redefinição da senha?'))return;setBusy(true);setMessage('');setPending([]);const response=await fetch('/api/client-access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,empresa_id:companyId,...form,...extra})}),payload=await response.json().catch(()=>({}));setBusy(false);if(response.ok){setMessage(payload.message||'Ação concluída.');if(payload.link)await navigator.clipboard.writeText(payload.link);await load()}else if(payload.code==='INTELLIGENT_PENDENCIES'&&confirm(`${payload.error}\n\nDeseja publicar mesmo assim?`)){await act(action,{...extra,confirm_pendencies:true})}else{setMessage(payload.error||'Não foi possível concluir a ação.');setPending(Array.isArray(payload.pending)?payload.pending:[])}};
 const journey=useMemo(()=>{const checks=(data?.checklist||[]) as ChecklistItem[],done=(index:number)=>Boolean(checks[index]?.done),preparation=[done(0),done(1),done(2),done(3),done(4)],published=done(5),accessed=done(6),accepted=done(7),contractSigned=done(8),paid=done(9),formalized=done(10),kickoff=done(11),implementationDone=done(12),active=done(13),allPrepared=preparation.every(Boolean);let status='Preparando Publicação',next='Concluir a preparação do Projeto de Evolução.';if(allPrepared){status='Pronto para Publicação';next='Publicar a Área do Cliente.'}if(published){status='Aguardando Primeiro Acesso';next='Aguardando primeiro acesso do cliente.'}if(accessed){status='Aguardando Aceite';next='Aguardando aceite.'}if(accepted){status='Aguardando Formalização';next='Aguardando formalização.'}if(formalized){status='Projeto Formalizado';next='Iniciar implantação.'}if(kickoff){status='Implantação em andamento';next='Concluir implantação técnica.'}if(implementationDone)next='Iniciar Método Escala Growth.';if(active){status='Cliente Ativo';next='Acompanhar a evolução contínua da empresa.'}const groups={preparation:labels.preparation.map((label,index)=>({label,done:preparation[index],detail:checks[index]?.detail})),release:[{label:labels.release[0],done:published},{label:labels.release[1],done:accessed},{label:labels.release[2],done:accepted},{label:labels.release[3],done:contractSigned},{label:labels.release[4],done:paid,detail:checks[9]?.detail},{label:labels.release[5],done:formalized}],implementation:[{label:labels.implementation[0],done:kickoff},{label:labels.implementation[1],done:implementationDone},{label:labels.implementation[2],done:active}]};const timeline=[{label:'Preparação',done:allPrepared,started:preparation.some(Boolean)},{label:'Área do Cliente',done:published&&accessed,started:published},{label:'Aceite',done:accepted,started:accessed},{label:'Formalização',done:formalized,started:accepted},{label:'Implantação',done:implementationDone,started:kickoff||formalized},{label:'Cliente Ativo',done:active,started:implementationDone}];return{status,next,groups,timeline,published,accessed,accepted,formalized,paid,kickoff,implementationDone,active}},[data]);
 if(!data)return <section id="company-publication" className="admin-section"><p>Preparando Área do Cliente...</p></section>;
 const access=data.access,publication=data.publication,accessStatus=!access?'Não criado':!access.ativo?'Acesso bloqueado':access.primeiro_acesso_em?'Primeiro acesso realizado':access.status_acesso||'Convite pendente',tone=journey.active?'completed':journey.status==='Preparando Proposta'||journey.status==='Implantação em andamento'?'progress':'waiting';
 return <><CommercialEvolutionPanel companyId={companyId}/><ExecutionStrategySummary companyId={companyId}/><section id="company-publication" className="admin-section client-access-card publication-panel client-area-panel">
  <span className="eyebrow">Publicação e Acesso</span><h2>Publicação e Acesso</h2><p>Publique exatamente o Projeto de Evolução preparado pelo consultor e acompanhe o fluxo até a ativação do cliente.</p>
  <div className="detail-metrics client-area-metrics">{[['Situação do acesso',accessStatus],['Versão publicada',publication?.versao?'Versão '+publication.versao:'—'],['Data da publicação',publication?.publicada_em?new Date(publication.publicada_em).toLocaleString('pt-BR'):'—'],['Primeiro acesso',access?.primeiro_acesso_em?new Date(access.primeiro_acesso_em).toLocaleString('pt-BR'):'—'],['Último acesso',access?.ultimo_acesso_em?new Date(access.ultimo_acesso_em).toLocaleString('pt-BR'):'—']].map(([label,value])=><div key={label}><small>{label}</small><b>{value}</b></div>)}<div className={'journey-status-card '+tone}><small>Status da Jornada</small><b>{journey.status}</b></div></div>
  <section className={'client-area-next '+tone}><small>Próxima Ação</small><h3>{journey.next}</h3></section>
  <div className="detail-actions client-area-preview-actions">
   {data.preview_available&&<a className="btn btn-secondary" href={`/portal?empresa=${companyId}`} target="_blank" rel="noreferrer">👁 Pré-visualizar Portal do Cliente</a>}
   <span className="status-pill">{data.contract_status||'Não iniciado'}</span>
   {data.contract&&data.contract_status==='Contrato/Termo disponível para revisão'&&<button className="btn btn-primary" disabled={busy} onClick={()=>act('review_contract')}>Confirmar revisão do Contrato/Termo</button>}
  </div>
  <div className="client-area-timeline">{journey.timeline.map((step,index)=><div key={step.label} className={step.done?'completed':step.started?'progress':'pending'}><i>{step.done?'✓':step.started?'●':'○'}</i><span>{step.label}</span>{index<journey.timeline.length-1&&<b>→</b>}</div>)}</div>
  <div className="client-area-checklists"><ChecklistGroup title="Preparação" items={journey.groups.preparation}/><ChecklistGroup title="Pendências Inteligentes" items={(data.intelligent_pendencies||[]).map((item:any)=>({label:item.titulo,done:item.status==='Concluída',detail:item.categoria}))}/><ChecklistGroup title="Liberação da Área do Cliente" items={journey.groups.release}/><ChecklistGroup title="Implantação" items={journey.groups.implementation}/></div>
  <div className="financial-form"><label>Nome do responsável<input value={form.nome} onChange={event=>setForm({...form,nome:event.target.value})}/></label><label>E-mail<input type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>Telefone<input value={form.telefone} onChange={event=>setForm({...form,telefone:event.target.value})}/></label><label>Empresa<input value={data.company?.nome||company?.nome||''} readOnly/></label></div>
  {pending.length>0&&<div className="publication-pending"><b>Conclua estas informações antes de publicar:</b><ul>{pending.map(item=><li key={item}>{item}</li>)}</ul></div>}
  <section className="client-area-stage-action"><span className="eyebrow">Ação da etapa</span>{!journey.published?<><button className="btn btn-primary" disabled={busy} onClick={()=>act('publish')}>{busy?'Validando publicação...':'🚀 Publicar Área do Cliente'}</button><p>Publica, em uma única versão, o Plano Estratégico, o Projeto de Evolução, o Contrato/Termo e as orientações iniciais; cria o acesso e envia o convite.</p><div className="publication-content-note"><b>O cliente visualizará somente:</b><ul><li>Plano Estratégico</li><li>Projeto de Evolução</li><li>Contrato/Termo</li><li>Aceite</li><li>Próximos Passos</li></ul></div></>:!journey.accessed?<><button className="btn btn-secondary" disabled>Primeiro acesso automático</button><p>O primeiro acesso é registrado automaticamente quando o cliente define a senha.</p></>:journey.formalized&&!journey.kickoff?<button className="btn btn-primary" disabled={busy} onClick={()=>confirm('Confirmar que o Kickoff foi realizado?')&&act('operational_stage',{stage:'kickoff'})}>Iniciar Implantação</button>:journey.kickoff&&!journey.implementationDone?<button className="btn btn-primary" disabled={busy} onClick={()=>confirm('Confirmar que a implantação técnica foi concluída?')&&act('operational_stage',{stage:'implementation'})}>Finalizar Implantação Técnica</button>:journey.implementationDone&&!journey.active?<button className="btn btn-primary" disabled={busy} onClick={()=>confirm('Confirmar o início oficial do Método Escala Growth?')&&act('operational_stage',{stage:'active'})}>Ativar Cliente</button>:journey.active?<p className="success">A jornada de acompanhamento contínuo está ativa.</p>:<p>Esta etapa depende do aceite ou da formalização administrativa. Acompanhe a Próxima Ação acima.</p>}</section>
  {access&&<div className="detail-actions client-area-access-tools"><button className="btn btn-secondary" disabled={busy} onClick={()=>act('resend')}>Reenviar convite</button>{access.convite_link&&<button className="btn btn-secondary" onClick={()=>navigator.clipboard.writeText(access.convite_link)}>Copiar link de acesso</button>}<button className="btn btn-secondary" disabled={busy} onClick={()=>act('reset')}>Redefinir senha / novo convite</button>{access.ativo!==false?<button className="btn btn-secondary" disabled={busy} onClick={()=>act('deactivate')}>Bloquear acesso</button>:<button className="btn btn-secondary" disabled={busy} onClick={()=>act('reactivate')}>Reativar acesso</button>}</div>}
  {message&&<p className={message.startsWith('Não')||message.startsWith('Informe')||message.includes('pendências')?'error':'success'}>{message.replaceAll('Portal','Área do Cliente')}</p>}
 </section></>
}
