'use client';
import {useEffect,useMemo,useState} from 'react';

const money=(value:unknown)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const types=['Adesão ao Método','Novo recurso','Expansão','Upgrade','Substituição','Ajuste contratual','Renovação','Outro'];
const empty={nome:'',tipo:'Novo recurso',descricao:'',objetivo:'',valor_implantacao_adicional:0,implantacao_modalidade:'Sem cobrança',mensalidade_adicional:0,desconto_recorrente:0,data_inicio:'',observacoes_internas:'',exige_contrato:false,exige_aditivo:false,exige_aceite:true,exige_pagamento:false,forma_cobranca:'Sem pagamento imediato',formalizacao:'Aceite eletrônico'};

export function CommercialEvolutionPanel({companyId}:{companyId:string}){
 const [data,setData]=useState<any>(null),[form,setForm]=useState<any>(empty),[selected,setSelected]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{const response=await fetch(`/api/commercial-evolution?empresa_id=${companyId}`,{cache:'no-store'}),payload=await response.json();setData(response.ok?payload:{error:payload.error})};
 useEffect(()=>{load()},[companyId]);
 const added=useMemo(()=>data?.catalog?.filter((item:any)=>selected[item.id])||[],[data,selected]);
 const additionalMonthly=added.filter((item:any)=>item.tipo==='Mensalidade').reduce((sum:number,item:any)=>sum+Number(item.valor_mensal||0),0),newMonthly=Number(data?.current?.mensalidade||0)+additionalMonthly-Number(form.desconto_recorrente||0);
 const create=async()=>{if(!form.nome.trim()){setMessage('Informe o nome do Projeto de Evolução.');return}setBusy(true);const response=await fetch('/api/commercial-evolution',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,empresa_id:companyId,mensalidade_adicional:additionalMonthly,recursos:added.map((item:any)=>({...item,movimento:'Adicionar',valor_mensal:item.valor_mensal||0,valor_implantacao:0}))})}),payload=await response.json().catch(()=>({}));setBusy(false);setMessage(response.ok?'Projeto de Evolução criado e preservado no histórico.':payload.error||'Não foi possível criar o projeto.');if(response.ok){setForm(empty);setSelected({});load()}};
 const formalize=async(id:string)=>{if(!confirm('Formalizar este projeto e criar uma nova versão da situação comercial?'))return;const response=await fetch('/api/commercial-evolution',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action:'formalize'})}),payload=await response.json().catch(()=>({}));setMessage(response.ok?'Projeto formalizado. A situação comercial vigente foi atualizada sem apagar o histórico.':payload.error||'Não foi possível formalizar.');if(response.ok)load()};
 if(!data)return <section className="admin-section"><p>Preparando histórico comercial...</p></section>;
 if(data.error)return <section className="admin-section"><p className="error">{data.error}</p></section>;
 const current=data.current||{};
 return <section className="admin-section commercial-evolution-panel"><span className="eyebrow">Evolução comercial</span><h2>Projetos de Evolução</h2><p>Expanda a relação comercial sem substituir contratos, propostas ou situações anteriores.</p>
  <h3>Situação Comercial Atual</h3><div className="commercial-summary">{[['Mensalidade vigente',money(current.mensalidade)],['Pagamento',current.status_pagamento||'Sem cobrança vigente'],['Contrato',current.contrato_status||'Sem contrato vigente'],['Renovação',current.renovacao_em?new Date(current.renovacao_em+'T12:00:00').toLocaleDateString('pt-BR'):'—']].map(([label,value])=><article key={label}><small>{label}</small><b>{value}</b></article>)}</div>
  <h3>Novo Projeto de Evolução</h3><div className="financial-form"><label>Nome<input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></label><label>Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}>{types.map(type=><option key={type}>{type}</option>)}</select></label><label className="wide">Descrição<textarea rows={3} value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></label><label className="wide">Objetivo<textarea rows={3} value={form.objetivo} onChange={e=>setForm({...form,objetivo:e.target.value})}/></label><label>Implantação adicional<input type="number" min="0" value={form.valor_implantacao_adicional} onChange={e=>setForm({...form,valor_implantacao_adicional:e.target.value})}/></label><label>Modalidade<select value={form.implantacao_modalidade} onChange={e=>setForm({...form,implantacao_modalidade:e.target.value})}>{['Cobrança normal','Sem cobrança','Isenta','Já realizada'].map(x=><option key={x}>{x}</option>)}</select></label><label>Desconto recorrente<input type="number" min="0" value={form.desconto_recorrente} onChange={e=>setForm({...form,desconto_recorrente:e.target.value})}/></label><label>Início<input type="date" value={form.data_inicio} onChange={e=>setForm({...form,data_inicio:e.target.value})}/></label><label>Forma de cobrança<select value={form.forma_cobranca} onChange={e=>setForm({...form,forma_cobranca:e.target.value})}>{['Sem pagamento imediato','Recorrência existente','PIX','Cartão','Assinatura','Transferência'].map(x=><option key={x}>{x}</option>)}</select></label><label>Formalização<select value={form.formalizacao} onChange={e=>setForm({...form,formalizacao:e.target.value})}>{['Aceite eletrônico','Novo contrato','Aditivo contratual','Sem novo documento'].map(x=><option key={x}>{x}</option>)}</select></label></div>
  <h3>Soluções a adicionar</h3><div className="evolution-resource-grid">{data.catalog.map((item:any)=><label key={item.id}><input type="checkbox" checked={Boolean(selected[item.id])} onChange={e=>setSelected({...selected,[item.id]:e.target.checked})}/><span><b>{item.nome}</b><small>{item.tipo} · {item.tipo==='Mensalidade'?money(item.valor_mensal):`${item.ui||0} UI`}</small></span></label>)}</div>
  <div className="commercial-summary">{[['Mensalidade atual',money(current.mensalidade)],['Adicional',money(additionalMonthly)],['Desconto',money(form.desconto_recorrente)],['Nova mensalidade',money(newMonthly)]].map(([label,value])=><article key={label}><small>{label}</small><b>{value}</b></article>)}</div>
  <div className="evolution-checks"><label><input type="checkbox" checked={form.exige_aceite} onChange={e=>setForm({...form,exige_aceite:e.target.checked})}/> Exige aceite</label><label><input type="checkbox" checked={form.exige_pagamento} onChange={e=>setForm({...form,exige_pagamento:e.target.checked})}/> Exige pagamento</label><label><input type="checkbox" checked={form.exige_contrato} onChange={e=>setForm({...form,exige_contrato:e.target.checked})}/> Exige contrato</label><label><input type="checkbox" checked={form.exige_aditivo} onChange={e=>setForm({...form,exige_aditivo:e.target.checked})}/> Exige aditivo</label></div><label>Observações internas<textarea rows={4} value={form.observacoes_internas} onChange={e=>setForm({...form,observacoes_internas:e.target.value})}/></label><button className="btn btn-primary" disabled={busy} onClick={create}>{busy?'Salvando...':'Criar Projeto de Evolução'}</button>
  <h3>Histórico Comercial</h3><div className="diagnostic-history">{data.projects.length?data.projects.map((project:any)=><article key={project.id}><div><b>{project.nome}</b><span>{project.tipo} · {new Date(project.created_at).toLocaleDateString('pt-BR')}</span></div><span className="status-pill">{project.status}</span><div><b>{money(project.nova_mensalidade)}</b><small> nova mensalidade</small></div>{!['Formalizado sem novo pagamento','Ativo','Concluído','Cancelado','Arquivado'].includes(project.status)&&<button onClick={()=>formalize(project.id)}>Formalizar</button>}</article>):<p>Nenhum Projeto de Evolução criado.</p>}</div>{message&&<p className={message.startsWith('Não')||message.startsWith('Informe')?'error':'success'}>{message}</p>}
 </section>
}
