"use client";
import {useEffect,useState} from 'react';
import {StrategicSolutionMappingAdmin} from './StrategicSolutionMappingAdmin';
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const solutionDraftKey='escala-growth-solution-draft';
const legend=[[1,'Muito Baixo','Configuração simples.'],[2,'Baixo','Configuração padrão.'],[3,'Médio','Personalização moderada.'],[5,'Alto','Implantação estratégica.'],[8,'Muito Alto','Integrações complexas.'],[13,'Projeto Especial','Grande esforço de implantação.']];
function useCommercial(){const [data,setData]=useState<any>(null),[error,setError]=useState('');const load=async()=>{setError('');try{const r=await fetch('/api/commercial',{cache:'no-store'}),x=await r.json();if(!r.ok)throw new Error(x.error);setData(x)}catch(e:any){setError(e?.message||'Não foi possível carregar os parâmetros.')}};useEffect(()=>{load()},[]);return{data,error,load}}
export function CommercialParameters(){
 const {data,error,load}=useCommercial(),[editing,setEditing]=useState<any>(()=>{try{const saved=sessionStorage.getItem(solutionDraftKey);return saved?JSON.parse(saved):null}catch{return null}}),[message,setMessage]=useState(''),[formError,setFormError]=useState(''),[tab,setTab]=useState<'services'|'method-links'|'financial'>('services'),[solutionTab,setSolutionTab]=useState<'commercial'|'method'|'implementation'|'automation'>('commercial');
 useEffect(()=>{try{if(editing)sessionStorage.setItem(solutionDraftKey,JSON.stringify(editing));else sessionStorage.removeItem(solutionDraftKey)}catch{}},[editing]);
 if(error)return <section className="admin-section"><h2>Parâmetros Comerciais</h2><p className="error">{error}</p></section>;
 if(!data)return <div className="loading-state">Preparando parâmetros comerciais...</div>;
 const p=data.parameters||{valor_ui:350,desconto_pix:10,prazo_contratual:12,validade_proposta:15,reajuste_indice:'IPCA',reajuste_periodicidade:12,reajuste_mes_base:1};
 const saveParams=async(e:any)=>{e.preventDefault();setFormError('');const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/commercial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'parameters',...body})}),x=await r.json();if(!r.ok){setFormError(x.error);return}setMessage('Configurações financeiras salvas com sucesso.');load()};
 const saveResource=async()=>{setFormError('');if(editing.utiliza_investimento_recomendado===true&&Number(editing.investimento_minimo_recomendado)<0){setFormError('O investimento mínimo recomendado deve ser igual ou superior a zero.');return}const r=await fetch('/api/commercial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'resource',...editing})}),x=await r.json();if(!r.ok){setFormError(x.error);return}setEditing(null);setMessage('Produto/serviço salvo com sucesso.');load()};
 const remove=async(id:string)=>{if(confirm('Arquivar este solução?')){await fetch('/api/commercial?id='+id,{method:'DELETE'});load()}};
 const normalizeResource=(x:any)=>({...x,tipo:['Implantação','Mensalidade','Implantação + Mensalidade'].includes(x.tipo)?x.tipo:'Implantação',classificacao_comercial:x.classificacao_comercial==='Obrigatório'?'Obrigatória':x.classificacao_comercial||'Opcional',utiliza_investimento_recomendado:x.utiliza_investimento_recomendado===true,criterios_recomendacao:Array.isArray(x.criterios_recomendacao)?x.criterios_recomendacao:[],criterios_conclusao:Array.isArray(x.criterios_conclusao)?x.criterios_conclusao.map((item:any)=>item.titulo||item).join('\n'):(x.criterio_conclusao||''),dependencias_configuradas:Array.isArray(x.dependencias_estruturadas)?x.dependencias_estruturadas.filter((item:any)=>item.tipo==='solucao').map((item:any,index:number)=>({recurso_id:item.recurso_id,obrigatoriedade:item.obrigatoriedade==='OPCIONAL'?'OPCIONAL':'OBRIGATORIA',ordem:Number(item.ordem)||index+1,ativo:item.ativo!==false})):[],dependencias_condicoes:Array.isArray(x.dependencias_estruturadas)?x.dependencias_estruturadas.filter((item:any)=>item.tipo==='condicao').map((item:any)=>item.descricao).join('\n'):(x.dependencias||''),recursos_relacionados:Array.isArray(x.recursos_relacionados)?x.recursos_relacionados:[]});
 const openResource=(x:any)=>{setSolutionTab('commercial');setEditing(normalizeResource(x))};
 const newResource=()=>openResource({codigo:'',categoria:'',nome:'',descricao:'',beneficios:[],objetivo_padrao:'',resultado_esperado:'',criterios_recomendacao:[],quando_recomendar:'',quando_nao_recomendar:'',entregas_padrao:[],recursos_envolvidos:[],recursos_relacionados:[],pre_requisitos:'',criterios_conclusao:'',ordem_implantacao:'',semana_sugerida:'Semana 1',tempo_medio_implantacao:7,dependencias_condicoes:'',dependencias_configuradas:[],descricao_tecnica:'',utiliza_plataforma_nimble:false,tipo:'Implantação',classificacao_comercial:'Opcional',ui:1,valor_mensal:'',valor_avulso:'',valor_implantacao_padrao:'',valor_mensalidade_padrao:'',responsavel:'Escala Vendas',treinamento_obrigatorio:false,gera_pendencias:false,abre_planejamento_operacional:false,permite_executor_terceiro:true,permite_equipe_interna:true,impacta_financeiro:true,impacta_cronograma:true,impacta_implantacao:true,cria_checklist:false,disponivel_evolucao_futura:true,utiliza_investimento_recomendado:false,investimento_minimo_recomendado:0,observacoes_estrategicas:'',observacoes:'',ativo:true});
 return <><div className="admin-section catalog-tabs"><button className={tab==='services'?'active':''} onClick={()=>setTab('services')}>Serviços</button><button className={tab==='method-links'?'active':''} onClick={()=>setTab('method-links')}>Vínculos com o Método</button><button className={tab==='financial'?'active':''} onClick={()=>setTab('financial')}>Configurações Financeiras</button></div>{tab==='method-links'&&<StrategicSolutionMappingAdmin/>}{tab==='financial'&&<section className="admin-section"><span className="eyebrow">Administração · acesso Master</span><h2>Configurações Financeiras</h2><p>Fonte única das regras comerciais utilizadas em implantação, proposta, mensalidades e contrato.</p><form className="parameter-form" onSubmit={saveParams}>
  <label>Valor da UI<input name="valor_ui" type="number" min="0.01" step="0.01" defaultValue={p.valor_ui}/></label>
  <label>Desconto para pagamento da Implantação via PIX (%)<input name="desconto_pix" type="number" min="0" max="100" step="0.01" defaultValue={p.desconto_pix}/></label>
  <label>Prazo Contratual (meses)<input name="prazo_contratual" type="number" value={12} readOnly/><small>Prazo institucional único da Escala Growth.</small></label>
  <label>Validade da Proposta (dias)<input name="validade_proposta" type="number" min="1" defaultValue={p.validade_proposta}/></label>
  <label>Índice de reajuste<select name="reajuste_indice" defaultValue={p.reajuste_indice||'IPCA'}><option>IPCA</option><option>IGP-M</option></select></label>
  <label>Periodicidade<select name="reajuste_periodicidade" defaultValue={p.reajuste_periodicidade||12}><option value="12">12 meses</option></select></label>
  <label>Mês-base do reajuste<select name="reajuste_mes_base" defaultValue={p.reajuste_mes_base||1}>{months.map((m,i)=><option value={i+1} key={m}>{m}</option>)}</select></label>
  
  <label>Juros por atraso (% ao mês)<input name="juros_atraso" type="number" min="0" step="0.01" defaultValue={p.juros_atraso??''} placeholder="Opcional"/></label>
  <label>Dias de tolerância<input name="dias_tolerancia" type="number" min="0" defaultValue={p.dias_tolerancia??''} placeholder="Opcional"/></label>
  <button className="btn btn-primary">Salvar configurações financeiras</button>
 </form>{message&&<p className="success">{message}</p>}{formError&&<p className="error">{formError}</p>}</section>}
 {tab==='services'&&<><section className="admin-section"><div className="module-toolbar"><div><span className="eyebrow">Base de conhecimento</span><h2>Biblioteca de Soluções Escala Growth</h2></div><button className="btn btn-primary" onClick={newResource}>Nova solução</button></div>
 <div className="resource-admin-list">{data.resources.map((x:any)=><article key={x.id} className={!x.ativo?'inactive':''}><b>{x.codigo}</b><span>{x.tipo}</span><strong>{x.nome}</strong><span>{x.tipo==='Implantação'?x.ui+' UI':x.tipo==='Mensalidade'?money(x.valor_mensal):`${x.ui||0} UI · ${money(x.valor_mensal)}/mês`}</span><span className={'service-class '+String(x.classificacao_comercial||'Opcional').toLowerCase().replace(' ','-')}>{x.classificacao_comercial||'Opcional'}</span><span>{x.responsavel}</span><button onClick={()=>openResource(x)}>Editar</button><button onClick={()=>remove(x.id)}>Arquivar</button></article>)}</div></section>
 <section className="admin-section ui-legend"><span className="eyebrow">Ajuda interna</span><h2>Legenda Oficial da UI</h2><p>A UI é exclusiva dos serviços de Implantação e representa esforço relativo, nunca horas, custo ou preço final.</p><div>{legend.map(([ui,title,text])=><article key={ui}><b>{ui} UI</b><strong>{title}</strong><span>{text}</span></article>)}</div></section></>}
 {editing&&<div className="modal"><section><h2>{editing.id?'Editar':'Nova'} solução</h2><div className="catalog-tabs solution-editor-tabs"><button className={solutionTab==='commercial'?'active':''} onClick={()=>setSolutionTab('commercial')}>1 · Comercial</button><button className={solutionTab==='method'?'active':''} onClick={()=>setSolutionTab('method')}>2 · Método</button><button className={solutionTab==='implementation'?'active':''} onClick={()=>setSolutionTab('implementation')}>3 · Implantação</button><button className={solutionTab==='automation'?'active':''} onClick={()=>setSolutionTab('automation')}>4 · Automações</button></div><div className="solution-template-form">
  {solutionTab==='commercial'&&<fieldset><legend>Comercial</legend><div className="resource-form">
   <label>Código<input value={editing.codigo||''} onChange={e=>setEditing({...editing,codigo:e.target.value})}/></label>
   <label>Nome da solução<input value={editing.nome||''} onChange={e=>setEditing({...editing,nome:e.target.value})}/></label>
   <label>Categoria<input value={editing.categoria||''} onChange={e=>setEditing({...editing,categoria:e.target.value})}/></label>
   <label className="wide">Descrição Comercial<textarea rows={4} value={editing.descricao||''} onChange={e=>setEditing({...editing,descricao:e.target.value})}/></label>
   <label className="wide">Benefícios <small className="field-help">Um benefício por linha.</small><textarea rows={4} value={Array.isArray(editing.beneficios)?editing.beneficios.join('\n'):editing.beneficios||''} onChange={e=>setEditing({...editing,beneficios:e.target.value})}/></label>
   <label>Tipo<select value={editing.tipo||'Implantação'} onChange={e=>{const tipo=e.target.value,implantacao=tipo!=='Mensalidade',mensalidade=tipo!=='Implantação';setEditing({...editing,tipo,ui:implantacao?(editing.ui||1):null,valor_mensalidade_padrao:mensalidade?(editing.valor_mensalidade_padrao??''):'',ordem_implantacao:implantacao?editing.ordem_implantacao:'',semana_sugerida:implantacao?editing.semana_sugerida:'',tempo_medio_implantacao:implantacao?(editing.tempo_medio_implantacao||7):''})}}><option>Implantação</option><option>Mensalidade</option><option>Implantação + Mensalidade</option></select></label>
   <label>Classificação<select value={editing.classificacao_comercial||'Opcional'} onChange={e=>setEditing({...editing,classificacao_comercial:e.target.value})}><option>Obrigatória</option><option>Complementar</option><option>Opcional</option></select></label>
   {editing.tipo!=='Mensalidade'&&<label>UI (Unidade de Implantação)<input type="number" min="0.01" step="0.01" value={editing.ui??''} onChange={e=>setEditing({...editing,ui:e.target.value})}/></label>}
   {editing.tipo!=='Mensalidade'&&<label>Valor de implantação padrão<input type="number" min="0" step="0.01" value={editing.valor_implantacao_padrao??''} onChange={e=>setEditing({...editing,valor_implantacao_padrao:e.target.value})}/></label>}
   {editing.tipo!=='Implantação'&&<label>Valor de mensalidade padrão<input type="number" min="0" step="0.01" value={editing.valor_mensalidade_padrao??''} onChange={e=>setEditing({...editing,valor_mensalidade_padrao:e.target.value})}/></label>}
   <label>Status<select value={editing.ativo===false?'Inativo':'Ativo'} onChange={e=>setEditing({...editing,ativo:e.target.value==='Ativo'})}><option>Ativo</option><option>Inativo</option></select></label>
   <label className="wide validation-option"><input type="checkbox" disabled={['AUT-001','TRN-001','PLA-001'].includes(String(editing.codigo||'').toUpperCase())} checked={!['AUT-001','TRN-001','PLA-001'].includes(String(editing.codigo||'').toUpperCase())&&editing.utiliza_plataforma_nimble===true} onChange={e=>setEditing({...editing,utiliza_plataforma_nimble:e.target.checked})}/><span>Utiliza a estrutura da Plataforma Nimble<small className="field-help">Quando selecionado, o projeto incluirá automaticamente AUT-001, TRN-001 e PLA-001. Os próprios recursos-base não podem reativar esta estrutura.</small></span></label>
  </div></fieldset>}
  {solutionTab==='method'&&<fieldset><legend>Método</legend><div className="resource-form">
   <label className="wide">Objetivo padrão<textarea rows={5} value={editing.objetivo_padrao||''} onChange={e=>setEditing({...editing,objetivo_padrao:e.target.value})}/></label>
   <label className="wide">Resultado esperado<textarea rows={4} value={editing.resultado_esperado||''} onChange={e=>setEditing({...editing,resultado_esperado:e.target.value})}/></label>
   <label className="wide">Critérios de recomendação <small className="field-help">Uma palavra, evidência ou pilar por linha.</small><textarea rows={5} value={Array.isArray(editing.criterios_recomendacao)?editing.criterios_recomendacao.join('\n'):editing.criterios_recomendacao||''} onChange={e=>setEditing({...editing,criterios_recomendacao:e.target.value})}/></label>
   <label>Quando recomendar<textarea rows={4} value={editing.quando_recomendar||''} onChange={e=>setEditing({...editing,quando_recomendar:e.target.value})}/></label>
   <label>Quando não recomendar<textarea rows={4} value={editing.quando_nao_recomendar||''} onChange={e=>setEditing({...editing,quando_nao_recomendar:e.target.value})}/></label>
    <label className="wide validation-option"><input type="checkbox" checked={editing.utiliza_investimento_recomendado===true} onChange={e=>setEditing({...editing,utiliza_investimento_recomendado:e.target.checked,investimento_minimo_recomendado:e.target.checked?(editing.investimento_minimo_recomendado??0):0})}/><span>Utiliza investimento estratégico recomendado<small className="field-help">Ative apenas para estratégias que dependem de verba externa recomendada, como mídia paga.</small></span></label>
    {editing.utiliza_investimento_recomendado===true&&<label className="wide">Investimento mínimo recomendado<input type="number" min="0" step="0.01" value={editing.investimento_minimo_recomendado??0} onChange={e=>setEditing({...editing,investimento_minimo_recomendado:e.target.value})}/><small>Valor mínimo recomendado pelo Método Escala Growth para que esta estratégia tenha viabilidade operacional e possibilidade consistente de geração de resultados.</small></label>}
   <label className="wide">Observações estratégicas<textarea rows={4} value={editing.observacoes_estrategicas||''} onChange={e=>setEditing({...editing,observacoes_estrategicas:e.target.value})}/></label>
  </div></fieldset>}
  {solutionTab==='implementation'&&<fieldset><legend>Implantação</legend><div className="resource-form planning-fields">
   {editing.tipo==='Mensalidade'?<p className="wide field-help">Serviços recorrentes não fazem parte do cronograma de implantação. Ordem, semana e tempo médio não se aplicam a este tipo.</p>:<>
    <label>Tempo médio de implantação (dias)<input type="number" min="1" value={editing.tempo_medio_implantacao??''} onChange={e=>setEditing({...editing,tempo_medio_implantacao:e.target.value})}/></label>
    <label>Ordem de implantação<input required type="number" min="1" step="1" value={editing.ordem_implantacao??''} onChange={e=>setEditing({...editing,ordem_implantacao:e.target.value})}/></label>
    <label>Semana sugerida<input required list="solution-weeks" placeholder="Ex.: Semana 1" value={editing.semana_sugerida||''} onChange={e=>setEditing({...editing,semana_sugerida:e.target.value})}/><datalist id="solution-weeks">{[1,2,3,4,5,6,7,8,9,10,11,12].map(x=><option value={'Semana '+x} key={x}/>)}<option value="Personalizado"/></datalist></label>
   </>}
   <label>Entregas padrão<textarea rows={5} value={Array.isArray(editing.entregas_padrao)?editing.entregas_padrao.join('\n'):editing.entregas_padrao||''} onChange={e=>setEditing({...editing,entregas_padrao:e.target.value})}/></label>
   <label>Critérios de conclusão <small className="field-help">Um item de checklist por linha.</small><textarea rows={5} value={editing.criterios_conclusao||''} onChange={e=>setEditing({...editing,criterios_conclusao:e.target.value})}/></label>
   <label className="wide">Pré-requisitos<textarea rows={3} value={editing.pre_requisitos||''} onChange={e=>setEditing({...editing,pre_requisitos:e.target.value})}/></label>
   <label className="wide">Condições e dependências<textarea rows={3} value={editing.dependencias_condicoes||''} onChange={e=>setEditing({...editing,dependencias_condicoes:e.target.value})}/></label>
   <div className="wide simulator-resources"><b>Soluções relacionadas</b>{data.resources.filter((x:any)=>x.id!==editing.id).map((x:any)=><label key={x.id}><input type="checkbox" checked={(editing.recursos_relacionados||[]).includes(x.id)} onChange={e=>setEditing({...editing,recursos_relacionados:e.target.checked?[...(editing.recursos_relacionados||[]),x.id]:(editing.recursos_relacionados||[]).filter((id:string)=>id!==x.id)})}/><span>{x.nome}</span></label>)}</div>
   <div className="wide dependency-editor"><b>Dependências da solução</b><p><small>Selecione recursos da Biblioteca. Não é necessário informar UUID.</small></p>{data.resources.filter((x:any)=>x.id!==editing.id).map((x:any)=>{const current=(editing.dependencias_configuradas||[]).find((d:any)=>d.recurso_id===x.id);return <div className="dependency-editor-row" key={x.id}><label><input type="checkbox" checked={Boolean(current)} onChange={e=>setEditing({...editing,dependencias_configuradas:e.target.checked?[...(editing.dependencias_configuradas||[]),{recurso_id:x.id,obrigatoriedade:'OBRIGATORIA',ordem:(editing.dependencias_configuradas||[]).length+1,ativo:true}]:(editing.dependencias_configuradas||[]).filter((d:any)=>d.recurso_id!==x.id)})}/><span>{x.nome}</span></label>{current&&<><select value={current.obrigatoriedade} onChange={e=>setEditing({...editing,dependencias_configuradas:editing.dependencias_configuradas.map((d:any)=>d.recurso_id===x.id?{...d,obrigatoriedade:e.target.value}:d)})}><option value="OBRIGATORIA">Obrigatória</option><option value="OPCIONAL">Opcional</option></select><input type="number" min="0" aria-label="Ordem da dependência" value={current.ordem} onChange={e=>setEditing({...editing,dependencias_configuradas:editing.dependencias_configuradas.map((d:any)=>d.recurso_id===x.id?{...d,ordem:Number(e.target.value)}:d)})}/><label><input type="checkbox" checked={current.ativo!==false} onChange={e=>setEditing({...editing,dependencias_configuradas:editing.dependencias_configuradas.map((d:any)=>d.recurso_id===x.id?{...d,ativo:e.target.checked}:d)})}/><span>Ativa</span></label></>}</div>})}</div>
   <label>Responsável padrão<input value={editing.responsavel||''} onChange={e=>setEditing({...editing,responsavel:e.target.value})}/></label>
   <label className="wide">Descrição técnica<textarea rows={5} value={editing.descricao_tecnica||''} onChange={e=>setEditing({...editing,descricao_tecnica:e.target.value})}/></label>
   <label className="wide">Observações internas<textarea rows={4} value={editing.observacoes||''} onChange={e=>setEditing({...editing,observacoes:e.target.value})}/></label>
  </div></fieldset>}
   {solutionTab==='automation'&&<fieldset><legend>Automações</legend><div className="resource-form automation-fields">
    <div className="wide automation-options">{[['gera_pendencias','Gera pendências'],['abre_planejamento_operacional','Abre Planejamento Operacional'],['permite_executor_terceiro','Permite executor terceiro'],['permite_equipe_interna','Permite equipe interna'],['treinamento_obrigatorio','Treinamento obrigatório'],['impacta_financeiro','Impacta Financeiro'],['impacta_cronograma','Impacta Cronograma'],['impacta_implantacao','Impacta Implantação'],['cria_checklist','Cria checklist'],['disponivel_evolucao_futura','Disponível para evolução futura']].map(([key,label])=><label className="validation-option automation-option" key={key}><input type="checkbox" checked={editing[key]===true} onChange={e=>setEditing({...editing,[key]:e.target.checked})}/><span>{label}</span></label>)}</div>
    {editing.gera_pendencias===true&&<div className="wide pending-default-fields">
     <label>Título da pendência padrão<input value={editing.titulo_pendencia_padrao||''} onChange={e=>setEditing({...editing,titulo_pendencia_padrao:e.target.value})} placeholder="Ex.: Configurar Parâmetros de Marketing"/></label>
     <label>Código da pendência<input value={editing.codigo_pendencia_padrao||''} onChange={e=>setEditing({...editing,codigo_pendencia_padrao:e.target.value})} placeholder="Ex.: MARKETING_PARAMETROS"/></label>
     <label className="wide">Rota de configuração padrão<input value={editing.rota_configuracao_padrao||''} onChange={e=>setEditing({...editing,rota_configuracao_padrao:e.target.value})} placeholder="Ex.: /central/planejamento-operacional"/></label>
    </div>}
  </div></fieldset>}
 </div>{formError&&<p className="error">{formError}</p>}<div className="detail-actions"><button className="btn btn-secondary" onClick={()=>{setEditing(null);setFormError('')}}>Cancelar</button><button className="btn btn-primary" onClick={saveResource}>Salvar solução</button></div></section></div>}</>
}
export function CommercialSimulator(){
 const {data,error}=useCommercial(),[selected,setSelected]=useState<string[]>([]);
 if(error)return <section className="admin-section"><p className="error">{error}</p></section>;
 if(!data)return <div className="loading-state">Preparando simulador...</div>;
 const resources=data.resources.filter((x:any)=>x.ativo),chosen=resources.filter((x:any)=>selected.includes(x.id)),params=data.parameters||{};
 const implantation=chosen.filter((x:any)=>x.tipo!=='Mensalidade'),monthly=chosen.filter((x:any)=>x.tipo!=='Implantação'),extras:any[]=[];
 const totalUi=implantation.reduce((n:number,x:any)=>n+Number(x.ui||0),0),implant=totalUi*Number(params.valor_ui||0),monthlyValue=monthly.reduce((n:number,x:any)=>n+Number(x.valor_mensal||0),0),extraValue=extras.reduce((n:number,x:any)=>n+Number(x.valor_avulso||0),0),pix=implant*(1-Number(params.desconto_pix||0)/100);
 return <><section className="admin-section"><span className="eyebrow">Ferramenta interna</span><h2>Simulador Comercial</h2><p>Monte cenários sem vincular a uma empresa ou proposta.</p><div className="simulator-resources">{resources.map((x:any)=><label key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(e.target.checked?[...selected,x.id]:selected.filter(id=>id!==x.id))}/><span><b>{x.nome}</b><small>{x.tipo} · {x.tipo!=='Mensalidade'?(x.ui||0)+' UI':''}{x.tipo==='Implantação + Mensalidade'?' · ':''}{x.tipo!=='Implantação'?money(x.valor_mensal)+'/mês':''} · {x.classificacao_comercial||'Opcional'}</small></span></label>)}</div></section>
 <section className="admin-section simulator-summary"><h2>Resumo da Simulação</h2><div className="commercial-summary">{[['Quantidade de UI',totalUi],['Valor da UI',money(params.valor_ui)],['Investimento Inicial',money(implant)],['PIX',money(pix)],['Mensalidade',money(monthlyValue)],['Serviços Adicionais',money(extraValue)],['Primeiro investimento',money(implant+monthlyValue+extraValue)]].map(([a,b])=><article key={a}><small>{a}</small><b>{b}</b></article>)}</div><h3>Composição</h3><p><b>Implantação:</b> {implantation.map((x:any)=>x.nome).join(' · ')||'Nenhum item'}</p><p><b>Mensalidade:</b> {monthly.map((x:any)=>x.nome).join(' · ')||'Nenhum item'}</p><p><b>Serviços adicionais:</b> {extras.map((x:any)=>x.nome).join(' · ')||'Nenhum item'}</p></section></>
}


