'use client';
import {useState} from 'react';

export function CompanyDeleteModal({company,onCancel,onDeleted}:{company:{id:string;name:string};onCancel:()=>void;onDeleted:(message:string)=>void}){
 const [confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const remove=async()=>{setBusy(true);setError('');try{const response=await fetch('/api/companies',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:company.id,confirmacao:confirmation})}),body=await response.json();if(!response.ok)throw new Error(body.error||'Não foi possível excluir a empresa.');onDeleted(body.message)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const items=['Empresa','Diagnósticos','Reuniões Estratégicas','Preparações de Reunião','Planos Estratégicos','Planos de Implantação','Investimentos','Contratações','Cronogramas','Indicadores','Timeline','Pipeline','Documentos','Usuários vinculados exclusivamente a esta empresa','Demais registros relacionados'];
 return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onCancel()}}><section className="delete-company-modal" role="dialog" aria-modal="true" aria-labelledby="delete-company-title"><span className="danger-icon">🗑</span><h2 id="delete-company-title">Excluir Empresa</h2><p>Você está prestes a excluir permanentemente <b>{company.name}</b>.</p><p>Todos os dados relacionados também serão removidos.</p><strong className="irreversible-warning">Essa ação NÃO poderá ser desfeita.</strong><div className="delete-items"><small>Itens que serão excluídos:</small><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></div><label>Para confirmar a exclusão, digite exatamente:<b>EXCLUIR</b><input autoFocus value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder="EXCLUIR" autoComplete="off"/></label>{error&&<p className="error" role="alert">{error}</p>}<div className="modal-actions"><button className="btn btn-secondary" disabled={busy} onClick={onCancel}>Cancelar</button><button className="btn danger-button" disabled={confirmation!=='EXCLUIR'||busy} onClick={remove}>{busy?'Excluindo...':'Excluir Permanentemente'}</button></div></section></div>
}

