'use client';
import {useEffect,useMemo,useState} from 'react';
import {Answers,calculate,openQuestions,pillars,recs} from '@/lib/diagnostic';
type Company={company:string;name:string;email:string;phone:string;segment:string;city:string;state:string;date:string;consent:boolean};
const initial={company:'',name:'',email:'',phone:'',segment:'',city:'',state:'',date:new Date().toISOString().slice(0,10),consent:false};
const priorityCopy:Record<string,string>={atrair:'Falta clareza sobre os canais que trazem as melhores oportunidades.',organizar:'Informações e responsabilidades precisam de um padrão mais claro.',acompanhar:'Oportunidades podem parar sem que a equipe perceba a tempo.',converter:'Falta clareza sobre o que faz uma negociação avançar ou ser perdida.',crescer:'Indicadores e metas ainda não sustentam decisões previsíveis.'};
const weeks=[['Semana 1 — Mapear','Canais, fluxo, responsáveis e oportunidades ativas'],['Semana 2 — Organizar','Etapas, informações, distribuição e registros'],['Semana 3 — Acompanhar','Retornos, oportunidades paradas e indicadores'],['Semana 4 — Melhorar','Resultados, conversão, falhas e evolução']];
export function DiagnosticApp(){
 const [screen,setScreen]=useState('home'),[step,setStep]=useState(0),[company,setCompany]=useState<Company>(initial),[answers,setAnswers]=useState<Answers>({}),[open,setOpen]=useState<Record<number,string>>({}),[error,setError]=useState('');
 useEffect(()=>{try{const s=localStorage.getItem('escala-growth');if(s){const d=JSON.parse(s);setCompany(d.company);setAnswers(d.answers);setOpen(d.open)}}catch{}},[]);
 useEffect(()=>{localStorage.setItem('escala-growth',JSON.stringify({company,answers,open}))},[company,answers,open]);
 const result=useMemo(()=>calculate(answers),[answers]); const top=()=>scrollTo(0,0);
 const identify=()=>{if(!company.company||!company.name||!company.email||!company.consent){setError('Preencha empresa, responsável, e-mail e confirme o consentimento.');return}setError('');setScreen('quiz');top()};
 const next=()=>{const p=pillars[step];if(p.questions.some((_,i)=>answers[`${p.id}-${i}`]===undefined)){setError('Responda todas as perguntas deste pilar.');return}setError('');if(step<4)setStep(step+1);else setScreen('open');top()};
 const reset=()=>{localStorage.removeItem('escala-growth');setCompany(initial);setAnswers({});setOpen({});setStep(0);setScreen('home');top()};
 return <main className="shell"><header className="nav"><div className="brand"><span className="brandmark">E</span>Escala Vendas</div><span className="tag">Toda oportunidade conta.</span></header>
 {screen==='home'&&<div className="container hero"><section><span className="eyebrow">Diagnóstico comercial</span><h1>Diagnóstico<br/>Escala Growth</h1><p className="lead">Descubra onde sua empresa está perdendo oportunidades e quais áreas precisam de mais organização, controle e visibilidade.</p><div className="hero-actions"><button className="btn btn-primary" onClick={()=>{setScreen('company');top()}}>Iniciar diagnóstico →</button></div><p className="quote">Organização gera controle. Controle gera previsibilidade.</p></section><aside className="preview-card"><span className="eyebrow">Visão da operação</span><div className="preview-score">68%</div>{[['Atrair',76],['Organizar',62],['Acompanhar',48],['Converter',70],['Crescer',58]].map(([l,v])=><div className="mini-row" key={l}><div className="mini-label"><span>{l}</span><b>{v}%</b></div><div className="mini-track"><div className="mini-fill" style={{width:`${v}%`}}/></div></div>)}</aside></div>}
 {screen==='company'&&<Flow title="Conte um pouco sobre sua empresa" sub="Essas informações ajudam a contextualizar o diagnóstico." active={0}><div className="field-grid">{[['company','Nome da empresa *'],['name','Nome do responsável *'],['email','E-mail *'],['phone','Telefone'],['segment','Segmento'],['city','Cidade'],['state','Estado']].map(([k,l])=><div className="field" key={k}><label>{l}</label><input type={k==='email'?'email':'text'} value={String(company[k as keyof Company]??'')} onChange={e=>setCompany({...company,[k]:e.target.value})}/></div>)}<div className="field"><label>Data do diagnóstico</label><input type="date" value={company.date} onChange={e=>setCompany({...company,date:e.target.value})}/></div><div className="field full"><label style={{display:'flex',gap:10,fontWeight:500}}><input style={{width:18}} type="checkbox" checked={company.consent} onChange={e=>setCompany({...company,consent:e.target.checked})}/>Autorizo o armazenamento local para gerar este diagnóstico.</label></div></div>{error&&<p className="error">{error}</p>}<Actions back={()=>setScreen('home')} next={identify} label="Começar avaliação"/></Flow>}
 {screen==='quiz'&&<Flow title={`${step+1}. ${pillars[step].label}`} sub={`Pilar ${step+1} de 5 · escolha de 0 (não existe) a 4 (organizado e melhorado).`} active={step+1}>{pillars[step].questions.map((q,i)=>{const key=`${pillars[step].id}-${i}`;return <div className="question" key={key}><div className="question-title">{i+1}. {q}</div><div className="scale">{[0,1,2,3,4].map(n=><button className={`scale-btn ${answers[key]===n?'selected':''}`} onClick={()=>setAnswers({...answers,[key]:n})} key={n}>{n}</button>)}</div><div className="scale-help"><span>Não existe</span><span>Organizado e melhorado</span></div></div>})}{error&&<p className="error">{error}</p>}<Actions back={()=>step?setStep(step-1):setScreen('company')} next={next} label={step===4?'Concluir avaliação':'Próximo pilar'}/></Flow>}
 {screen==='open'&&<Flow title="Antes do resultado..." sub="Conte, em suas palavras, o que mais importa para sua empresa." active={6}>{openQuestions.map((q,i)=><div className="field" style={{marginBottom:18}} key={q}><label>{q}</label><textarea rows={3} value={open[i]??''} onChange={e=>setOpen({...open,[i]:e.target.value})}/></div>)}<Actions back={()=>{setScreen('quiz');setStep(4)}} next={()=>{setScreen('result');top()}} label="Ver meu resultado"/></Flow>}
 {screen==='result'&&<section className="container" style={{paddingTop:20}}><div className="panel" style={{maxWidth:1000}}><div className="result-top"><div><span className="eyebrow" style={{color:'#8fdaa9'}}>Diagnóstico concluído</span><h2>{company.company}</h2><p>{result.maturity[0]}</p></div><div className="score-big">{result.percent}<small>%</small></div></div><div className="panel-body"><div className="notice"><b>Agora você possui uma visão mais clara.</b> {result.maturity[1]}</div><div className="result-grid"><div className="card"><h3>Desempenho por pilar</h3>{result.results.map(p=><div className="bar-row" key={p.id}><b>{p.label}</b><div className="bar-track"><div className="bar-fill" style={{width:`${p.percent}%`}}/></div><span>{p.percent}%</span></div>)}</div><div className="card"><h3>Leitura principal</h3><p><b>Maior força:</b> {result.highest.label} ({result.highest.percent}%)</p><p><b>Principal gargalo:</b> {result.lowest.label} ({result.lowest.percent}%)</p><p><b>Diferença:</b> {result.difference} pontos</p><p style={{color:'var(--muted)',lineHeight:1.55}}>Sua empresa não precisa apenas de mais oportunidades. Precisa acompanhar melhor cada uma delas.</p></div></div><div className="result-grid"><div className="card"><h3>Três prioridades</h3>{result.priorities.map((p,i)=><div className="priority" key={p.id}><span className="number">{i+1}</span><div><b>{p.label}</b><p>{priorityCopy[p.id]}</p></div></div>)}</div><div className="card"><h3>Recomendações</h3><ul className="recommendations">{result.priorities.flatMap(p=>recs[p.id].slice(0,2)).map(x=><li key={x}>{x}</li>)}</ul></div></div><div className="card report-section"><h3>Plano de ação · 30 dias</h3><div className="week-grid">{weeks.map(w=><div className="week" key={w[0]}><b>{w[0]}</b><p>{w[1]}</p></div>)}</div></div><div className="card report-section"><h3>Observações do consultor</h3><div style={{height:80,borderBottom:'1px solid #ccd8d0'}}/><p style={{fontSize:13,color:'var(--muted)'}}>Escala Vendas · {new Date(company.date+'T12:00:00').toLocaleDateString('pt-BR')} · Tecnologia é o meio. Crescimento é o resultado.</p></div><div className="panel-actions no-print"><button className="btn btn-secondary" onClick={reset}>Refazer diagnóstico</button><button className="btn btn-primary" onClick={()=>window.print()}>Baixar relatório em PDF</button></div></div></div></section>}
 </main>}
function Flow({title,sub,active,children}:{title:string;sub:string;active:number;children:React.ReactNode}){return <div className="container" style={{paddingTop:18}}><section className="panel"><div className="panel-head"><span className="eyebrow">Diagnóstico Escala Growth</span><h2 style={{fontSize:28,margin:'10px 0 7px'}}>{title}</h2><p style={{margin:0,color:'var(--muted)'}}>{sub}</p><div className="steps">{[0,1,2,3,4,5,6].map(n=><span className={`step ${n<=active?'on':''}`} key={n}/>)}</div></div><div className="panel-body">{children}</div></section></div>}
function Actions({back,next,label}:{back:()=>void;next:()=>void;label:string}){return <div className="panel-actions"><button className="btn btn-secondary" onClick={back}>Voltar</button><button className="btn btn-primary" onClick={next}>{label} →</button></div>}

