import {answerEvidence} from '@/lib/diagnostic';
import {diagnosticReading,officialDiagnosticPriority} from '@/lib/diagnosticBriefing';
import {acquisitionReadiness,evidenceFromStoredAnswers,type Evidence} from '@/lib/evidenceEngine';

const asList=(value:any)=>Array.isArray(value)?value:[];
const text=(value:any)=>String(value??'').trim()||'Não informado';
const contextOf=(data:any)=>data.contexto_operacional||data.relatorio_snapshot?.contexto_operacional||{};
const strategicOrder=['Atrair','Converter','Crescer','Organizar','Acompanhar'];
const scored=(answer:any)=>answer.resposta_numerica===null||answer.resposta_numerica===undefined?undefined:Number(answer.resposta_numerica);

export function DiagnosticResponsesGrouped({answers}:{answers:any[]}){
 const grouped=strategicOrder.map(pillar=>({pillar,items:asList(answers).filter(answer=>String(answer.pilar).toLowerCase()===pillar.toLowerCase())})).filter(group=>group.items.length);
 if(!grouped.length)return <p>Não informado.</p>;
 return <div className="diagnostic-answer-groups">{grouped.map(group=><section key={group.pillar} className="diagnostic-answer-group"><h4>{group.pillar.toUpperCase()}</h4>{group.items.map((answer:any,index:number)=>{const value=scored(answer),evidence=answerEvidence(value),reading=diagnosticReading(answer.pergunta,value);return <article key={answer.id||`${group.pillar}-${index}`}><div><b>{answer.pergunta}</b><p>{reading.interpretation}</p></div><aside><strong>{value===undefined?'Não informado':`${value} / 4`}</strong><span className={`evidence-label ${evidence.className}`}>{evidence.label}</span></aside></article>})}</section>)}</div>
}

export function DiagnosticConsultantBriefing({data}:{data:any}){
 const answers=asList(data.respostas),open=asList(data.respostas_abertas),radar=asList(data.resultados_pilares),context=contextOf(data),objective=open.find((item:any)=>String(item.pergunta).toLowerCase().includes('resultado deseja'))?.resposta,priority=officialDiagnosticPriority(data),ranked=answers.map((item:any)=>({item,value:scored(item)})).filter(entry=>entry.value!==undefined).sort((left,right)=>Number(left.value)-Number(right.value)),relevant=ranked.slice(0,6),evidence=relevant.map(entry=>({...entry,reading:diagnosticReading(entry.item.pergunta,entry.value),evidence:answerEvidence(entry.value)})),pains=evidence.filter(entry=>Number(entry.value)<=2).slice(0,4),risks=Array.from(new Set(pains.map(entry=>entry.reading.risk))).slice(0,3),investigations=Array.from(new Set(evidence.filter(entry=>Number(entry.value)<=2).map(entry=>entry.reading.investigation))).slice(0,4),hypotheses=Array.from(new Set(evidence.filter(entry=>Number(entry.value)<=2).map(entry=>entry.reading.hypothesis))).slice(0,3),structuredEvidence:Evidence[]=asList(data.relatorio_snapshot?.evidencias_estruturadas).length?asList(data.relatorio_snapshot.evidencias_estruturadas):evidenceFromStoredAnswers(answers,data.id),readiness=data.relatorio_snapshot?.indicadores_derivados?.prontidao_aquisicao||acquisitionReadiness(structuredEvidence);
 return <section className="consultant-briefing"><header><span className="eyebrow">Uso interno do consultor</span><h3>Briefing para Reunião</h3><p>Leitura estruturada das respostas para apoiar a preparação e orientar o que precisa ser validado com o cliente.</p></header>
  <div className="briefing-section"><h4>Visão estratégica</h4><div className="briefing-summary-grid">{[['Empresa',data.empresas?.nome],['Segmento',data.empresas?.segmento],['Objetivo declarado pelo cliente',objective],['Maior força',data.maior_pilar],['Principal gargalo',priority],['Prioridade sugerida',priority]].map(([label,value])=><article key={label}><small>{label}</small><b>{text(value)}</b></article>)}</div></div>
  <div className="briefing-section"><h4>Pontuação dos pilares/dimensões</h4><div className="briefing-pillars">{radar.length?radar.map((item:any)=><span key={item.id||item.pilar}><b>{item.pilar}</b> {item.percentual}%</span>):<span>Não informado.</span>}</div></div>
  <div className="briefing-section"><h4>Evidências relevantes</h4><div className="briefing-evidence">{evidence.length?evidence.map((entry,index)=><article key={entry.item.id||index}><span className={`evidence-label ${entry.evidence.className}`}>{entry.evidence.label}</span><h5>{entry.reading.topic}</h5><p>{entry.reading.interpretation}</p></article>):<p>Não informado.</p>}</div></div>
  <div className="briefing-insights"><article><h4>Principais dores identificadas</h4>{pains.length?pains.map(entry=><p key={entry.item.id||entry.item.pergunta}>• {entry.reading.interpretation}</p>):<p>Não informado.</p>}</article><article><h4>Principais riscos</h4>{risks.length?risks.map(risk=><p key={risk}>• {risk}</p>):<p>Não informado.</p>}</article><article><h4>Pontos que merecem investigação</h4>{investigations.length?investigations.map(question=><p key={question}>• {question}</p>):<p>Não informado.</p>}</article></div>
  <div className="briefing-section briefing-hypotheses"><h4>Hipóteses levantadas pelo Diagnóstico</h4><p>Hipóteses automáticas para confirmação ou refutação durante a reunião:</p>{hypotheses.length?hypotheses.map(hypothesis=><p key={hypothesis}>• {hypothesis}</p>):<p>Não informado.</p>}</div>
  <div className="briefing-section derived-indicators"><h4>Indicadores derivados</h4><article className={`readiness-card readiness-${String(readiness.classification||'indisponivel').toLowerCase()}`}><span className="eyebrow">Prontidão para Aquisição</span><h3>{readiness.classification==='MEDIA'?'MÉDIA':readiness.classification||'NÃO CALCULADA'}</h3><b>Score base: {readiness.score_base===null?'Não disponível':`${readiness.score_base}%`}</b><p>{readiness.interpretation}</p><h5>Principais fatores</h5>{readiness.components_used.length?readiness.components_used.map((item:any)=><p key={item.capability}>• {item.fact}</p>):<p>Informações insuficientes para calcular o indicador.</p>}<h5>Limitadores acionados</h5>{readiness.limiters.length?readiness.limiters.map((item:string)=><p key={item}>• {item}</p>):<p>Nenhum.</p>}{readiness.components_missing.length>0&&<small>Componentes ausentes: {readiness.components_missing.length}. Eles não foram considerados como zero.</small>}</article></div>
  <details className="briefing-technical-debug"><summary>Inspeção técnica das evidências <small>Administrador/desenvolvimento</small></summary><div className="technical-evidence-table"><table><thead><tr><th>Pergunta</th><th>Question ID</th><th>Score</th><th>Evidence Code</th><th>Dimensão</th><th>Capability</th><th>Severity</th><th>Fato</th></tr></thead><tbody>{structuredEvidence.map(item=><tr key={item.source_question_id}><td>{item.source_question}</td><td>{item.source_question_id}</td><td>{item.score}</td><td>{item.evidence_code}</td><td>{item.dimension}</td><td>{item.capability}</td><td>{item.severity}</td><td>{item.fact}</td></tr>)}</tbody></table></div><h5>Prontidão para Aquisição</h5><p>Score base: {readiness.score_base}% · Antes dos limitadores: {readiness.classification_before_limiters} · Final: {readiness.classification}</p>{readiness.components_used.map((item:any)=><p key={item.capability}>{item.capability}: {item.score}/{item.max_score}</p>)}</details>
  <div className="briefing-section"><h4>Contexto operacional</h4><div className="briefing-context-grid"><p><b>Volume mensal:</b> {text(context.volume_contatos)}</p><p><b>Pessoas no atendimento/comercial:</b> {text(context.quantidade_pessoas)}</p><p><b>Canais atuais:</b> {asList(context.canais).length?context.canais.join(', '):'Não informado'}</p><p><b>Ferramentas atuais:</b> {asList(context.ferramentas).length?context.ferramentas.join(', '):'Não informado'}{context.ferramenta_atual?` — ${context.ferramenta_atual}`:''}</p><p><b>Indicadores acompanhados:</b> {asList(context.indicadores).length?context.indicadores.join(', '):'Não informado'}</p></div></div>
 </section>
}
