'use client';
import {useEffect,useMemo,useRef,useState} from 'react';

const recommendedNames=['CRM Comercial','Agente de IA','WhatsApp Oficial','Dashboard Executivo'];
const editableFields=['hipotese_inicial','perguntas_especificas','problema_principal','prioridades_confirmadas','ajustes_diagnostico','recomendacoes_aprovadas','recomendacoes_removidas','novas_recomendacoes','informacoes_complementares','missao_definida','indicadores_sugeridos','parecer_consultor','observacoes_consultor'];
const editableDraft=(record:any,validations:any)=>({...Object.fromEntries(editableFields.map(key=>[key,record[key]??''])),validacoes_reuniao:validations||{}});
function StructuredValidation({title,question,options,value,onChange,fields=[],showWhen=[]}:{title:string;question:string;options:string[];value:any;onChange:(x:any)=>void;fields?:[string,string][];showWhen?:string[]}){
 const current=value&&typeof value==='object'?value:{};const visible=!showWhen.length||showWhen.includes(current.resposta);
 return <section className="structured-validation"><span className="eyebrow">{title}</span><p>{question}</p><div className="validation-options">{options.map(option=><label key={option}><input type="radio" name={title} checked={current.resposta===option} onChange={()=>onChange({...current,resposta:option})}/>{option}</label>)}</div>{visible&&fields.map(([key,label])=><label key={key}>{label}<textarea rows={2} value={current[key]||''} onChange={e=>onChange({...current,[key]:e.target.value})}/></label>)}</section>
}
export function MeetingPreparation({data,onComplete}:{data:any;onComplete:()=>void}){
 const [record,setRecord]=useState<any>({}),[validations,setValidations]=useState<any>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[autoStatus,setAutoStatus]=useState('Salvo');
 const savedSignature=useRef(''),versionRef=useRef(0),requestSequence=useRef(0),timerRef=useRef<ReturnType<typeof setTimeout>|null>(null),dirtyRef=useRef(false);
 const meeting=record.meeting,meetingId=meeting?.id||record.reuniao_id||data._meeting_id,report=data.relatorio_snapshot||{},company=data.empresas||{},responsible=data.responsaveis||{};
 const recommendations=useMemo(()=>{const saved=Array.isArray(record.recomendacoes)?record.recomendacoes:[];if(saved.length)return saved;const resources=(data.planos_implantacao?.[0]?.recursos||[]).filter((x:any)=>['Recomendado','Contratado'].includes(x.status)).map((x:any)=>x.nome);return resources.length?resources:recommendedNames},[record.recomendacoes,data.planos_implantacao]);
 const form=()=>({...editableDraft(record,validations),empresa_id:data.empresa_id,diagnostico_id:data.id,reuniao_id:meetingId,recomendacoes:recommendations});
 const signature=()=>JSON.stringify(form());
 useEffect(()=>{setLoaded(false);fetch('/api/meeting-preparation?id='+data.id+(data._meeting_id?'&meeting_id='+data._meeting_id:''),{cache:'no-store'}).then(async r=>{const x=await r.json();if(r.ok){const nextValidations=x.validacoes_reuniao||{};setRecord(x);setValidations(nextValidations);versionRef.current=Number(x.autosave_version||x.meeting?.autosave_version||0);savedSignature.current=JSON.stringify({...editableDraft(x,nextValidations),empresa_id:data.empresa_id,diagnostico_id:data.id,reuniao_id:x.reuniao_id||x.meeting?.id,recomendacoes:Array.isArray(x.recomendacoes)&&x.recomendacoes.length?x.recomendacoes:recommendedNames});dirtyRef.current=false;setAutoStatus('Salvo');setLoaded(true)}else setMessage(x.error||'Não foi possível abrir a reunião.')})},[data.id,data._meeting_id,data.empresa_id]);
 const persist=async(manual=false,keepalive=false)=>{if(!loaded||!meetingId)return false;if(timerRef.current){clearTimeout(timerRef.current);timerRef.current=null}const payload=form(),sentSignature=JSON.stringify(payload),sequence=++requestSequence.current,version=++versionRef.current;if(manual)setBusy(true);setAutoStatus('Salvando...');try{const r=await fetch('/api/meeting-preparation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,autosave_version:version}),keepalive}),x=await r.json().catch(()=>({}));if(sequence!==requestSequence.current)return r.ok;if(!r.ok){if(x.current_version)versionRef.current=Math.max(versionRef.current,Number(x.current_version));setAutoStatus('Erro ao salvar. Tentar novamente.');if(manual)setMessage(x.error||'Não foi possível salvar a reunião.');return false}versionRef.current=Math.max(versionRef.current,Number(x.autosave_version||version));savedSignature.current=sentSignature;const stillCurrent=signature()===sentSignature;dirtyRef.current=!stillCurrent;setAutoStatus(stillCurrent?'Salvo':'Alterações pendentes');if(manual)setMessage('Reunião salva com sucesso.');return true}catch{if(sequence===requestSequence.current)setAutoStatus('Erro ao salvar. Tentar novamente.');return false}finally{if(manual)setBusy(false)}};
 useEffect(()=>{if(!loaded||!meetingId)return;const current=signature();if(current===savedSignature.current){dirtyRef.current=false;return}dirtyRef.current=true;setAutoStatus('Alterações pendentes');if(timerRef.current)clearTimeout(timerRef.current);timerRef.current=setTimeout(()=>{void persist(false)},1000);return()=>{if(timerRef.current)clearTimeout(timerRef.current)}},[loaded,meetingId,record,validations,recommendations]);
 useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(!dirtyRef.current)return;void persist(false,true);event.preventDefault();event.returnValue=''};const hide=()=>{if(dirtyRef.current)void persist(false,true)};window.addEventListener('beforeunload',leave);window.addEventListener('pagehide',hide);return()=>{window.removeEventListener('beforeunload',leave);window.removeEventListener('pagehide',hide)}},[loaded,meetingId,record,validations,recommendations]);
 const save=async()=>persist(true);
 const conclude=async()=>{if(!meetingId){setMessage('Não foi possível localizar a reunião agendada. Volte à Agenda e abra novamente.');return}if(!confirm('Concluir a Reunião Estratégica e consolidar o Plano Estratégico?'))return;requestSequence.current++;if(timerRef.current)clearTimeout(timerRef.current);if(!await persist(true)){setMessage('A reunião não foi concluída porque o salvamento falhou. Tente novamente.');return}setBusy(true);setMessage('');const r=await fetch('/api/meeting-preparation',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form(),autosave_version:versionRef.current})}),x=await r.json().catch(()=>({}));setBusy(false);if(r.ok){dirtyRef.current=false;setMessage('Reunião concluída. O Plano Estratégico está em consolidação.');onComplete()}else setMessage(x.error||'Não foi possível concluir a reunião.')};
 return <section className="meeting-preparation admin-section"><div className="meeting-title-row"><div><span className="eyebrow">Método Escala Growth</span><h2>Reunião Estratégica</h2></div><button type="button" className={"autosave-status "+(autoStatus.startsWith("Erro")?"error":"")} onClick={()=>autoStatus.startsWith("Erro")&&persist(true)}>{autoStatus}</button></div>
  <details className="meeting-preparation-details"><summary>Preparação da Reunião <small>Uso interno</small></summary><div className="meeting-preparation-content">
   <div className="detail-metrics">{[['Empresa',company.nome],['Segmento',company.segmento||'Não informado'],['Responsável',responsible.nome||'Não informado'],['IEG',`${data.pontuacao_geral}/100`],['Principal força',data.maior_pilar],['Principal gargalo',data.menor_pilar]].map(([a,b])=><div key={a}><small>{a}</small><b>{b}</b></div>)}</div>
   <div className="detail-grid"><div><h3>Resumo do Diagnóstico</h3><p>{data.parecer||report.parecer}</p></div><div><h3>Recomendações Automáticas</h3>{recommendations.map((x:string)=><p key={x}>✓ {x}</p>)}</div></div>
   <label><b>Hipótese inicial do consultor</b><textarea rows={4} value={record.hipotese_inicial||''} onChange={e=>setRecord({...record,hipotese_inicial:e.target.value})}/></label>
   <label><b>Perguntas específicas preparadas</b><textarea rows={3} value={record.perguntas_especificas||''} onChange={e=>setRecord({...record,perguntas_especificas:e.target.value})}/></label>
  </div></details>
  <div className="meeting-conduction"><h3>Validação da Reunião</h3><p>Confirme, ajuste e consolide as decisões da conversa com o cliente.</p>
   <StructuredValidation title="Principal Problema" question="O principal problema identificado foi confirmado?" options={['Confirmado','Confirmado com ajustes','Não confirmado']} value={validations.problema} onChange={x=>setValidations({...validations,problema:x})} fields={[['observacoes','Observações ou ajustes realizados']]}/><label>Problema principal consolidado *<textarea rows={3} value={record.problema_principal||''} onChange={e=>setRecord({...record,problema_principal:e.target.value})}/></label>
   <StructuredValidation title="Prioridades" question="O cliente concorda com as prioridades?" options={['Sim','Parcialmente','Não']} value={validations.prioridades} onChange={x=>setValidations({...validations,prioridades:x})} fields={[['alteracoes','Quais prioridades foram alteradas?']]}/><label>Prioridades confirmadas *<textarea rows={3} value={record.prioridades_confirmadas||''} onChange={e=>setRecord({...record,prioridades_confirmadas:e.target.value})}/></label>
   <StructuredValidation title="Projeto em Andamento" question="Existe algum projeto relacionado em andamento?" options={['Sim','Não','Não informado']} value={validations.projeto} onChange={x=>setValidations({...validations,projeto:x})} showWhen={['Sim']} fields={[['descricao','Descreva o projeto em andamento']]}/>
   <StructuredValidation title="CRM" question="A empresa já utiliza CRM?" options={['Sim','Não']} value={validations.crm} onChange={x=>setValidations({...validations,crm:x})} showWhen={['Sim']} fields={[['nome','Nome do CRM'],['uso','Como ele é utilizado atualmente'],['futuro','Pretende manter ou substituir']]}/>
   <StructuredValidation title="Campanhas Pagas" question="A empresa utiliza campanhas pagas?" options={['Sim','Não']} value={validations.midia} onChange={x=>setValidations({...validations,midia:x})} showWhen={['Sim']} fields={[['canais','Canais utilizados'],['responsavel','Responsável pela gestão'],['verba','Verba mensal aproximada'],['resultados','Resultados percebidos']]}/>
   <StructuredValidation title="Equipe Comercial" question="A empresa possui equipe comercial?" options={['Sim','Não']} value={validations.equipe} onChange={x=>setValidations({...validations,equipe:x})} showWhen={['Sim']} fields={[['quantidade','Quantidade de pessoas'],['funcoes','Funções principais'],['distribuicao','Como os leads são distribuídos'],['acompanhamento','Quem acompanha as oportunidades']]}/>
   <label>Ajustes realizados no diagnóstico<textarea rows={3} value={record.ajustes_diagnostico||''} onChange={e=>setRecord({...record,ajustes_diagnostico:e.target.value})}/></label>
   <div className="detail-grid"><label>Soluções recomendadas<textarea rows={4} value={record.recomendacoes_aprovadas||''} onChange={e=>setRecord({...record,recomendacoes_aprovadas:e.target.value})}/></label><label>Soluções removidas<textarea rows={4} value={record.recomendacoes_removidas||''} onChange={e=>setRecord({...record,recomendacoes_removidas:e.target.value})}/></label></div>
   <label>Novas soluções incluídas<textarea rows={3} value={record.novas_recomendacoes||''} onChange={e=>setRecord({...record,novas_recomendacoes:e.target.value})}/></label><label>Informações complementares<textarea rows={4} value={record.informacoes_complementares||''} onChange={e=>setRecord({...record,informacoes_complementares:e.target.value})}/></label><label>Missão definida *<textarea rows={3} value={record.missao_definida||''} onChange={e=>setRecord({...record,missao_definida:e.target.value})}/></label><label>Indicadores sugeridos<textarea rows={4} value={record.indicadores_sugeridos||''} onChange={e=>setRecord({...record,indicadores_sugeridos:e.target.value})}/></label>
   <label><b>Parecer do Consultor</b><span>Conteúdo oficial que poderá ser apresentado ao cliente no Plano Estratégico.</span><textarea rows={5} value={record.parecer_consultor||''} onChange={e=>setRecord({...record,parecer_consultor:e.target.value})}/></label><label className="internal-meeting-notes"><b>Observações do Consultor</b><span>Conteúdo interno. Não aparece para o cliente.</span><textarea rows={6} value={record.observacoes_consultor||''} onChange={e=>setRecord({...record,observacoes_consultor:e.target.value})}/></label>
  </div><div className="detail-actions"><button className="btn btn-secondary" disabled={busy||!loaded} onClick={save}>{busy?'Salvando...':'💾 Salvar Reunião'}</button><button className="btn btn-primary" disabled={busy||!loaded} onClick={conclude}>✅ Concluir Reunião Estratégica</button></div>{message&&<p className={message.startsWith('Não')||message.startsWith('Preencha')?'error':'success'}>{message}</p>}</section>
}
