'use client';
import {useEffect,useMemo,useRef,useState} from 'react';

const recommendedNames=['CRM Comercial','Agente de IA','WhatsApp Oficial','Dashboard Executivo'];
const editableFields=['hipotese_inicial','perguntas_especificas','problema_principal','prioridades_confirmadas','ajustes_diagnostico','recomendacoes_aprovadas','recomendacoes_removidas','novas_recomendacoes','informacoes_complementares','missao_definida','indicadores_sugeridos','parecer_consultor','observacoes_consultor'];
const editableDraft=(record:any,validations:any)=>({...Object.fromEntries(editableFields.map(key=>[key,record[key]??''])),validacoes_reuniao:validations||{}});
const friendlyLabel=(value:string)=>value.replace(/[_-]+/g,' ').replace(/\b\w/g,char=>char.toUpperCase());
const friendlyLines=(value:any):string[]=>{if(value===null||value===undefined||value==='')return[];if(typeof value==='string'){const trimmed=value.trim();if(!trimmed)return[];if((trimmed.startsWith('{')||trimmed.startsWith('['))){try{return friendlyLines(JSON.parse(trimmed))}catch{}}return trimmed.split(/\r?\n/).map(line=>line.replace(/^[-•*✓✔\s]+/,'').trim()).filter(Boolean)}if(typeof value==='number'||typeof value==='boolean')return[String(value)];if(Array.isArray(value))return value.flatMap(friendlyLines);if(typeof value==='object')return Object.entries(value).flatMap(([key,item])=>{if(['id','created_at','updated_at','status'].includes(key)||item===null||item===undefined||item==='')return[];if(typeof item==='string'||typeof item==='number'||typeof item==='boolean')return[`${friendlyLabel(key)}: ${item}`];return friendlyLines(item)});return[]};
const textOf=(value:any,fallback='Não identificado no diagnóstico.')=>friendlyLines(value).join('\n')||fallback;
const opportunityCards=(value:any)=>{if(value&&typeof value==='object'&&!Array.isArray(value))return Object.entries(value).map(([title,items])=>({title:friendlyLabel(title),items:friendlyLines(items)})).filter(group=>group.items.length);if(Array.isArray(value)&&value.some(item=>item&&typeof item==='object'))return value.map((item:any,index:number)=>({title:item.titulo||item.nome||item.etapa||`Grupo ${index+1}`,items:friendlyLines(item.oportunidades||item.itens||item.descricao||item)})).filter(group=>group.items.length);const items=friendlyLines(value);return items.length?[{title:'Oportunidades sugeridas',items}]:[]};
function StructuredValidation({title,question,options,value,onChange,fields=[],showWhen=[]}:{title:string;question:string;options:string[];value:any;onChange:(x:any)=>void;fields?:[string,string][];showWhen?:string[]}){
 const current=value&&typeof value==='object'?value:{};const visible=!showWhen.length||showWhen.includes(current.resposta);
 return <section className="structured-validation"><span className="eyebrow">{title}</span><p>{question}</p><div className="validation-options">{options.map(option=><label key={option}><input type="radio" name={title} checked={current.resposta===option} onChange={()=>onChange({...current,resposta:option})}/>{option}</label>)}</div>{visible&&fields.map(([key,label])=><label key={key}>{label}<textarea rows={2} value={current[key]||''} onChange={e=>onChange({...current,[key]:e.target.value})}/></label>)}</section>
}
export function MeetingPreparation({data,onComplete}:{data:any;onComplete:()=>void}){
 const [record,setRecord]=useState<any>({}),[validations,setValidations]=useState<any>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[autoStatus,setAutoStatus]=useState('Carregando...');
 const savedSignature=useRef(''),versionRef=useRef(0),requestSequence=useRef(0),timerRef=useRef<ReturnType<typeof setTimeout>|null>(null),dirtyRef=useRef(false),latestPayloadRef=useRef<any>(null);
 const meeting=record.meeting,meetingId=meeting?.id||record.reuniao_id||data._meeting_id,report=data.relatorio_snapshot||{},company=data.empresas||{},responsible=data.responsaveis||{};
 const recommendations=useMemo(()=>{const saved=Array.isArray(record.recomendacoes)?record.recomendacoes:[];if(saved.length)return saved;const resources=(data.planos_implantacao?.[0]?.recursos||[]).filter((x:any)=>['Recomendado','Contratado'].includes(x.status)).map((x:any)=>x.nome);return resources.length?resources:recommendedNames},[record.recomendacoes,data.planos_implantacao]);
 const diagnosticReality=textOf(report.situacao_atual||report.parecer||data.parecer);
 const opportunityGroups=useMemo(()=>opportunityCards(report.oportunidades||report.plano_acao||data.plano_acao||report.prioridades),[report.oportunidades,report.plano_acao,data.plano_acao,report.prioridades]);
 const suggestedPriorityItems=useMemo(()=>friendlyLines(report.prioridades||data.prioridades||report.proximos_passos),[report.prioridades,data.prioridades,report.proximos_passos]);
 const opportunityKeys=useMemo(()=>opportunityGroups.flatMap((group:any,groupIndex:number)=>group.items.map((item:string,itemIndex:number)=>`${groupIndex}:${itemIndex}:${item}`)),[opportunityGroups]);
 const preparedQuestions=useMemo(()=>String(record.perguntas_especificas||'').split(/\r?\n/).map((item:string)=>item.replace(/^[-•*\d.)\s]+/,'').trim()).filter(Boolean),[record.perguntas_especificas]);
 const form=()=>({...editableDraft(record,validations),empresa_id:data.empresa_id,diagnostico_id:data.id,reuniao_id:meetingId,recomendacoes:recommendations});
 const signature=()=>JSON.stringify(form());
 latestPayloadRef.current={payload:form(),signature:signature(),meetingId};
 useEffect(()=>{const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),10000);setLoaded(false);setAutoStatus('Carregando...');(async()=>{try{const r=await fetch('/api/meeting-preparation?id='+data.id+(data._meeting_id?'&meeting_id='+data._meeting_id:''),{cache:'no-store',signal:controller.signal}),text=await r.text();let x:any={};try{x=text?JSON.parse(text):{}}catch{x={error:text||'Resposta inválida do servidor.'}}if(!r.ok)throw new Error(x.error||'Não foi possível abrir a reunião.');const nextValidations=x.validacoes_reuniao||{};setRecord(x);setValidations(nextValidations);versionRef.current=Number(x.autosave_version||x.meeting?.autosave_version||0);savedSignature.current=JSON.stringify({...editableDraft(x,nextValidations),empresa_id:data.empresa_id,diagnostico_id:data.id,reuniao_id:x.reuniao_id||x.meeting?.id,recomendacoes:recommendations});dirtyRef.current=false;setAutoStatus('Salvo')}catch(error:any){savedSignature.current=signature();dirtyRef.current=false;setAutoStatus('Erro ao carregar. Digite para salvar.');setMessage(error?.name==='AbortError'?'O carregamento demorou mais de 10 segundos. Você ainda pode preencher e salvar esta reunião.':error?.message||'Não foi possível carregar a reunião.')}finally{clearTimeout(timeout);setLoaded(true)}})();return()=>{clearTimeout(timeout);controller.abort()}},[data.id,data._meeting_id,data.empresa_id]);
 const persist=async(manual=false,keepalive=false,retry=true)=>{if(!meetingId){setAutoStatus('Erro ao salvar. Tentar novamente.');setMessage('Vínculo da reunião não localizado.');return false}if(timerRef.current){clearTimeout(timerRef.current);timerRef.current=null}const payload=form(),sentSignature=JSON.stringify(payload),sequence=++requestSequence.current,version=++versionRef.current;if(manual)setBusy(true);setAutoStatus('Salvando...');try{const r=await fetch('/api/meeting-preparation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,autosave_version:version,autosave:!manual}),keepalive}),x=await r.json().catch(()=>({}));if(sequence!==requestSequence.current)return r.ok;if(!r.ok){if(x.current_version)versionRef.current=Math.max(versionRef.current,Number(x.current_version));if(r.status===409&&retry&&x.current_version!==undefined)return await persist(manual,keepalive,false);setAutoStatus('Erro ao salvar. Tentar novamente.');setMessage(x.error||'Não foi possível salvar a reunião.');return false}if(String(x.id)!==String(meetingId)){setAutoStatus('Erro ao salvar. Tentar novamente.');setMessage('O servidor respondeu com uma reunião diferente da que está aberta. Nenhum dado local foi apagado.');return false}versionRef.current=Math.max(versionRef.current,Number(x.autosave_version||version));savedSignature.current=sentSignature;const stillCurrent=signature()===sentSignature;dirtyRef.current=!stillCurrent;setAutoStatus(stillCurrent?'Salvo':'Alterações pendentes');if(manual)setMessage('Reunião salva com sucesso.');return true}catch(error:any){if(sequence===requestSequence.current){setAutoStatus('Erro ao salvar. Tentar novamente.');setMessage(error?.message||'Falha de comunicação ao salvar a reunião.')}return false}finally{if(manual)setBusy(false)}};
 useEffect(()=>{if(!loaded||!meetingId)return;const current=signature();if(current===savedSignature.current){dirtyRef.current=false;return}dirtyRef.current=true;setAutoStatus('Alterações pendentes');if(timerRef.current)clearTimeout(timerRef.current);timerRef.current=setTimeout(()=>{void persist(false)},1000);return()=>{if(timerRef.current)clearTimeout(timerRef.current)}},[loaded,meetingId,record,validations,recommendations]);
 useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(!dirtyRef.current)return;void persist(false,true);event.preventDefault();event.returnValue=''};const hide=()=>{if(dirtyRef.current)void persist(false,true)};window.addEventListener('beforeunload',leave);window.addEventListener('pagehide',hide);return()=>{window.removeEventListener('beforeunload',leave);window.removeEventListener('pagehide',hide)}},[loaded,meetingId,record,validations,recommendations]);
 useEffect(()=>()=>{const latest=latestPayloadRef.current;if(!dirtyRef.current||!latest?.meetingId)return;const version=++versionRef.current;void fetch('/api/meeting-preparation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...latest.payload,autosave_version:version,autosave:true}),keepalive:true})},[]);
 const save=async()=>persist(true);
 const conclude=async()=>{if(!meetingId){setMessage('Não foi possível localizar a reunião agendada. Volte à Agenda e abra novamente.');return}if(!confirm('Concluir a Reunião Estratégica e consolidar o Plano Estratégico?'))return;requestSequence.current++;if(timerRef.current)clearTimeout(timerRef.current);if(!await persist(true)){setMessage('A reunião não foi concluída porque o salvamento falhou. Tente novamente.');return}setBusy(true);setMessage('');const r=await fetch('/api/meeting-preparation',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form(),autosave_version:versionRef.current})}),x=await r.json().catch(()=>({}));setBusy(false);if(r.ok){dirtyRef.current=false;setMessage('Reunião concluída. O Plano Estratégico está em consolidação.');onComplete()}else setMessage(x.error||'Não foi possível concluir a reunião.')};
 return <section className="meeting-preparation admin-section" onBlurCapture={()=>{if(dirtyRef.current)void persist(false,true)}}><div className="meeting-title-row"><div><span className="eyebrow">Método Escala Growth</span><h2>Reunião Estratégica</h2></div><div className="meeting-save-reference"><small>Referência da reunião: {meetingId?String(meetingId).slice(0,8):"Vínculo não localizado"}</small><button type="button" className={"autosave-status "+(autoStatus.startsWith("Erro")?"error":"")} onClick={()=>autoStatus.startsWith("Erro")&&persist(true)}>{autoStatus}</button>{autoStatus.startsWith("Erro")&&message&&<small className="autosave-detail">{message}</small>}</div></div>
  <details className="meeting-preparation-details"><summary>Preparação da Reunião <small>Uso interno</small></summary><div className="meeting-preparation-content">
   <div className="detail-metrics">{[['Empresa',company.nome],['Segmento',company.segmento||'Não informado'],['Responsável',responsible.nome||'Não informado'],['IEG',`${data.pontuacao_geral}/100`],['Principal força',data.maior_pilar],['Principal gargalo',data.menor_pilar]].map(([a,b])=><div key={a}><small>{a}</small><b>{b}</b></div>)}</div>
   <div className="detail-grid"><div><h3>Resumo do Diagnóstico</h3><p>{data.parecer||report.parecer}</p></div><div><h3>Recomendações Automáticas</h3>{recommendations.map((x:string)=><p key={x}>✓ {x}</p>)}</div></div>
   <label><b>Hipótese inicial do consultor</b><textarea rows={4} value={record.hipotese_inicial||''} onChange={e=>setRecord({...record,hipotese_inicial:e.target.value})}/></label>
   <label><b>Perguntas específicas preparadas</b><textarea rows={3} value={record.perguntas_especificas||''} onChange={e=>setRecord({...record,perguntas_especificas:e.target.value})}/></label>
  </div></details>
  <div className="meeting-conduction guided-meeting"><div className="guided-meeting-header"><div><h3>Roteiro da Reunião Estratégica</h3><p>Valide com o cliente as informações levantadas e registre as conclusões da conversa.</p></div><div className="guided-column-labels"><b>Informações do Diagnóstico</b><b>Validação com o Cliente</b></div></div>
   <section className="guided-block"><div className="guided-source"><span className="eyebrow">Bloco 1</span><h3>Recomendações Automáticas</h3><p>Recomendações originadas no diagnóstico.</p></div><div className="guided-validation"><h3>Validação das Recomendações</h3><p>Confirme o tratamento de cada recomendação.</p></div>
    {recommendations.map((name:string)=>{const item=validations.recomendacoes?.[name]||{};return <div className="recommendation-validation-row" key={name}><div className="guided-source"><b>• {name}</b></div><div className="guided-validation"><div className="validation-options">{['Confirmada','Não necessária','Adiar'].map(status=><label key={status}><input type="radio" name={'recommendation-'+name} checked={item.status===status} onChange={()=>setValidations({...validations,recomendacoes:{...(validations.recomendacoes||{}),[name]:{...item,status}}})}/>{status}</label>)}</div><label>Observações<textarea rows={2} value={item.observacoes||''} onChange={e=>setValidations({...validations,recomendacoes:{...(validations.recomendacoes||{}),[name]:{...item,observacoes:e.target.value}}})}/></label></div></div>})}
   </section>
   <section className="guided-block"><div className="guided-source"><span className="eyebrow">Bloco 2</span><h3>Realidade Atual da Empresa</h3><p className="diagnostic-source-text">{diagnosticReality}</p></div><div className="guided-validation"><h3>Validação com o Cliente</h3><p>O cliente confirmou a realidade identificada?</p><div className="validation-options">{['Sim','Parcialmente','Não'].map(option=><label key={option}><input type="radio" name="realidade-confirmada" checked={validations.realidade?.confirmada===option} onChange={()=>setValidations({...validations,realidade:{...(validations.realidade||{}),confirmada:option}})}/>{option}</label>)}</div><label>Novas informações<textarea rows={3} value={validations.realidade?.novas_informacoes||''} onChange={e=>setValidations({...validations,realidade:{...(validations.realidade||{}),novas_informacoes:e.target.value}})}/></label><label>Ajustes<textarea rows={3} value={validations.realidade?.ajustes||''} onChange={e=>setValidations({...validations,realidade:{...(validations.realidade||{}),ajustes:e.target.value}})}/></label><label>Observações<textarea rows={3} value={validations.realidade?.observacoes||''} onChange={e=>setValidations({...validations,realidade:{...(validations.realidade||{}),observacoes:e.target.value}})}/></label></div></section>
   <section className="guided-block"><div className="guided-source"><span className="eyebrow">Bloco 3</span><h3>Hipótese do Consultor</h3><p className="diagnostic-source-text">{record.hipotese_inicial||'Nenhuma hipótese registrada na preparação.'}</p></div><div className="guided-validation"><h3>Resposta do Cliente</h3><label>Registre a validação, complemento ou ajuste apresentado pelo cliente.<textarea rows={6} value={validations.hipotese_resposta||''} onChange={e=>setValidations({...validations,hipotese_resposta:e.target.value})}/></label></div></section>
   <section className="guided-block"><div className="guided-source"><span className="eyebrow">Bloco 4</span><h3>Perguntas Preparadas</h3>{preparedQuestions.length?preparedQuestions.map((question:string,index:number)=><p key={index} className="prepared-question">{index+1}. {question}</p>):<p>Nenhuma pergunta registrada na preparação.</p>}</div><div className="guided-validation"><h3>Respostas do Cliente</h3>{preparedQuestions.length?preparedQuestions.map((question:string,index:number)=><label key={index}>{index+1}. {question}<textarea rows={3} value={validations.respostas_perguntas?.[String(index)]||''} onChange={e=>setValidations({...validations,respostas_perguntas:{...(validations.respostas_perguntas||{}),[String(index)]:e.target.value}})}/></label>):<p>Registre perguntas na Preparação da Reunião para habilitar as respostas individuais.</p>}</div></section>
   <section className="guided-block"><div className="guided-source"><span className="eyebrow">Bloco 5</span><h3>Oportunidades Identificadas</h3>{opportunityGroups.length?opportunityGroups.map((group:any,groupIndex:number)=><article className="opportunity-card" key={group.title+groupIndex}><h4>{group.title}</h4>{group.items.map((item:string,itemIndex:number)=><p key={itemIndex}>☐ {item}</p>)}</article>):<p>Nenhuma oportunidade sugerida automaticamente.</p>}</div><div className="guided-validation"><h3>Validação das Oportunidades</h3>{opportunityKeys.length>0&&<label className="confirm-all"><input type="checkbox" checked={opportunityKeys.every((key:string)=>(validations.oportunidades?.confirmadas||[]).includes(key))} onChange={e=>setValidations({...validations,oportunidades:{...(validations.oportunidades||{}),confirmadas:e.target.checked?opportunityKeys:[]}})}/>Confirmar todas</label>}{opportunityGroups.map((group:any,groupIndex:number)=><article className="opportunity-validation-card" key={group.title+groupIndex}><h4>{group.title}</h4>{group.items.map((item:string,itemIndex:number)=>{const key=`${groupIndex}:${itemIndex}:${item}`,selected=validations.oportunidades?.confirmadas||[];return <label key={key}><input type="checkbox" checked={selected.includes(key)} onChange={e=>setValidations({...validations,oportunidades:{...(validations.oportunidades||{}),confirmadas:e.target.checked?[...selected,key]:selected.filter((current:string)=>current!==key)}})}/>{item}</label>})}</article>)}<label>Nova oportunidade<textarea rows={4} value={validations.oportunidades?.nova||''} onChange={e=>setValidations({...validations,oportunidades:{...(validations.oportunidades||{}),nova:e.target.value}})}/></label><label>Observações<textarea rows={3} value={validations.oportunidades?.observacoes||''} onChange={e=>setValidations({...validations,oportunidades:{...(validations.oportunidades||{}),observacoes:e.target.value}})}/></label></div></section>
   <section className="guided-block"><div className="guided-source"><span className="eyebrow">Bloco 6</span><h3>Prioridades Sugeridas</h3><div className="priority-suggestion-list">{suggestedPriorityItems.length?suggestedPriorityItems.map((item:string,index:number)=><div className="priority-suggestion-card" key={index}><span>{index+1}</span><b>{item}</b></div>):<p>Nenhuma prioridade sugerida automaticamente.</p>}</div></div><div className="guided-validation"><h3>Prioridade Validada</h3><p>Selecione a prioridade definida junto ao cliente.</p><div className="priority-radio-list">{['Converter','Crescer','Acompanhar','Outra'].map(option=><label key={option}><input type="radio" name="prioridade-validada" checked={validations.prioridade?.selecionada===option} onChange={()=>setValidations({...validations,prioridade:{...(validations.prioridade||{}),selecionada:option}})}/>{option}</label>)}</div>{validations.prioridade?.selecionada==='Outra'&&<label>Descreva a prioridade<textarea rows={3} value={validations.prioridade?.outra||''} onChange={e=>setValidations({...validations,prioridade:{...(validations.prioridade||{}),outra:e.target.value}})}/></label>}<label>Observações opcionais<textarea rows={3} value={validations.prioridade?.observacoes||''} onChange={e=>setValidations({...validations,prioridade:{...(validations.prioridade||{}),observacoes:e.target.value}})}/></label></div></section>
   <section className="meeting-conclusion"><span className="eyebrow">Bloco 7 · Obrigatório</span><h3>Conclusão da Reunião Estratégica</h3><div className="detail-grid"><label>Qual é hoje o principal desafio da empresa? *<textarea rows={4} value={validations.conclusao?.desafio||''} onChange={e=>setValidations({...validations,conclusao:{...(validations.conclusao||{}),desafio:e.target.value}})}/></label><label>Qual foi a maior oportunidade identificada? *<textarea rows={4} value={validations.conclusao?.oportunidade_principal||''} onChange={e=>setValidations({...validations,conclusao:{...(validations.conclusao||{}),oportunidade_principal:e.target.value}})}/></label><label>Qual deve ser a prioridade número 1 para os próximos 90 dias? *<textarea rows={4} value={validations.conclusao?.prioridade_90_dias||''} onChange={e=>setValidations({...validations,conclusao:{...(validations.conclusao||{}),prioridade_90_dias:e.target.value}})}/></label><label>Existe alguma restrição importante? *<textarea rows={4} value={validations.conclusao?.restricoes||''} onChange={e=>setValidations({...validations,conclusao:{...(validations.conclusao||{}),restricoes:e.target.value}})}/></label></div><label>Resumo Executivo da Reunião *<span>Registre o cenário da empresa, as decisões tomadas e a direção estratégica definida junto ao cliente.</span><textarea rows={7} value={validations.conclusao?.resumo_executivo||''} onChange={e=>setValidations({...validations,conclusao:{...(validations.conclusao||{}),resumo_executivo:e.target.value}})}/></label></section>
   <label className="internal-meeting-notes"><b>Observações do Consultor</b><span>Conteúdo interno. Não aparece para o cliente.</span><textarea rows={6} value={record.observacoes_consultor||''} onChange={e=>setRecord({...record,observacoes_consultor:e.target.value})}/></label>
  </div><div className="detail-actions"><button className="btn btn-secondary" disabled={busy||!meetingId} onClick={save}>{busy?'Salvando...':'💾 Salvar Reunião'}</button><button className="btn btn-primary" disabled={busy||!meetingId} onClick={conclude}>✅ Concluir Reunião Estratégica</button></div>{message&&<p className={message.startsWith('Não')||message.startsWith('Preencha')?'error':'success'}>{message}</p>}</section>
}
