'use client';
import {useEffect,useState} from 'react';

const actions=[
 ['Diagnóstico','Regenerar Diagnóstico','Recalcula a leitura estratégica sem alterar respostas ou pontuação.'],
 ['Plano Estratégico','Atualizar para a Versão Atual do Método','Aplica oficialmente a versão mais recente do Método Escala Growth.'],
 ['Projeto de Evolução','Regenerar Projeto de Evolução','Atualiza a composição recomendada para a evolução.'],
 ['Cronograma','Regenerar Cronograma','Reorganiza as fases conforme a estrutura vigente.'],
 ['Recomendações','Atualizar Recomendações','Reavalia prioridades e recomendações estratégicas.'],
 ['Biblioteca de Soluções','Atualizar Biblioteca de Soluções','Sincroniza o documento com a biblioteca vigente.']
];
const safeArray=(value:any)=>Array.isArray(value)?value:[];
const displayDate=(value:string)=>value?new Date(value).toLocaleString('pt-BR'):'—';

function Comparison({data}:{data:any}){const groups=[['Novos recursos',data?.novos_recursos],['Novas recomendações',data?.novas_recomendacoes],['Evoluções futuras',data?.evolucoes_futuras],['Mudanças',data?.mudancas]];return <div className="regeneration-comparison">{groups.map(([label,items]:any)=><article key={label}><h4>{label}</h4>{safeArray(items).length?<ul>{items.map((item:string)=><li key={item}>{item}</li>)}</ul>:<p>Nenhuma alteração nesta categoria.</p>}</article>)}</div>}

export function RegenerationCenter(){
 const [companies,setCompanies]=useState<any[]>([]),[companyId,setCompanyId]=useState(''),[context,setContext]=useState<any>(null),[selected,setSelected]=useState('Plano Estratégico');
 const [reason,setReason]=useState('Atualização para a versão mais recente do Método Escala Growth.'),[options,setOptions]=useState({atualizar_cronograma:true,atualizar_recomendacoes:true,atualizar_biblioteca:true,manter_parecer:true,gerar_parecer_ia:false});
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[result,setResult]=useState<any>(null),[comparison,setComparison]=useState<any>(null),[preview,setPreview]=useState(false);
 const read=async(response:Response)=>{const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Não foi possível concluir a operação.');return payload};
 const loadCompanies=async()=>{try{setLoading(true);const payload=await read(await fetch('/api/regeneration',{cache:'no-store'}));setCompanies(payload.companies||[]);if(payload.companies?.length)setCompanyId((current:string)=>current||payload.companies[0].id)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const loadContext=async(id:string)=>{if(!id)return;try{setLoading(true);setError('');const payload=await read(await fetch(`/api/regeneration?empresa_id=${encodeURIComponent(id)}`,{cache:'no-store'}));setContext(payload)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{loadCompanies()},[]);
 useEffect(()=>{if(companyId)loadContext(companyId)},[companyId]);
 const regenerate=async()=>{try{setBusy(true);setError('');setMessage('');setResult(null);if(!reason.trim())throw new Error('Informe o motivo da atualização.');const payload=await read(await fetch('/api/regeneration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:companyId,tipo:selected,motivo:reason,confirm_active:true,...options})}));setPreview(false);setResult(payload);setMessage(payload.message);await loadContext(companyId)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const selectedAction=actions.find(action=>action[0]===selected)!;
 if(loading&&!companies.length)return <div className="loading-state">Preparando Central de Regeneração...</div>;
 return <section className="regeneration-center">
  <div className="regeneration-intro"><div><span className="eyebrow">Ferramentas Administrativas</span><h2>Central de Regeneração Inteligente</h2><p>Recalcule documentos com a versão atual do método sem apagar diagnósticos, reuniões, anotações, documentos ou histórico.</p></div><label>Empresa<select value={companyId} onChange={event=>setCompanyId(event.target.value)}><option value="">Selecione</option>{companies.map(company=><option key={company.id} value={company.id}>{company.nome}</option>)}</select></label></div>
  <div className="regeneration-actions">{actions.map(([type,label,description])=><button key={type} className={selected===type?'active':''} onClick={()=>{setSelected(type);setMessage('');setError('');setResult(null)}}><b>↻ {label}</b><span>{description}</span></button>)}</div>
  <div className="regeneration-workspace"><div><span className="eyebrow">Ação selecionada</span><h3>{selectedAction[1]}</h3><p>O {selected} será atualizado utilizando a versão mais recente do Método Escala Growth.</p><div className="regeneration-options"><label><input type="checkbox" checked={options.atualizar_cronograma} onChange={e=>setOptions({...options,atualizar_cronograma:e.target.checked})}/> Atualizar Cronograma</label><label><input type="checkbox" checked={options.atualizar_recomendacoes} onChange={e=>setOptions({...options,atualizar_recomendacoes:e.target.checked})}/> Atualizar Recomendações</label><label><input type="checkbox" checked={options.atualizar_biblioteca} onChange={e=>setOptions({...options,atualizar_biblioteca:e.target.checked})}/> Atualizar Biblioteca de Soluções</label><label><input type="checkbox" checked={options.manter_parecer} onChange={e=>setOptions({...options,manter_parecer:e.target.checked})}/> Manter Parecer Final do Consultor</label><label className="disabled"><input type="checkbox" checked={options.gerar_parecer_ia} disabled/> Gerar novo Parecer utilizando IA <small>Em preparação</small></label></div><label className="regeneration-reason">Motivo<textarea value={reason} onChange={e=>setReason(e.target.value)} /></label><button className="btn btn-primary" disabled={busy||!companyId||(selected==='Plano Estratégico'&&!context?.method?.update_available)} onClick={()=>setPreview(true)}>{selected==='Plano Estratégico'&&!context?.method?.update_available?'✓ Plano atualizado':selectedAction[1]}</button>{message&&<p className="success">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}</div><aside><span className="eyebrow">Contexto atual</span><h3>{context?.company?.nome||'Selecione uma empresa'}</h3><dl><div><dt>Plano Estratégico · versão utilizada</dt><dd>{context?.method?.plan_version||'—'}</dd></div><div><dt>Versão atual do Método</dt><dd>{context?.method?.current?.versao||'—'}</dd></div><div><dt>Situação</dt><dd className={context?.method?.update_available?'method-update':'method-current'}>{context?.method?.update_available?'⚠ Atualização disponível':'✓ Plano atualizado'}</dd></div><div><dt>Última atualização</dt><dd>{context?.method?.last_update?`${displayDate(context.method.last_update.created_at)} · ${context.method.last_update.usuario}`:'Nenhuma atualização registrada'}</dd></div>{context?.method?.last_update&&<div><dt>Versões</dt><dd>{context.method.last_update.versao_metodo_anterior||'—'} → {context.method.last_update.versao_metodo_nova||context.method.last_update.metodo_versao}</dd></div>}</dl>{context?.method?.execution_started&&<p className="active-method-warning">Este projeto já iniciou sua execução. Recomendamos criar um novo Projeto de Evolução; somente o Administrador pode confirmar esta atualização.</p>}</aside></div>
  {result&&<section className="regeneration-result"><span className="eyebrow">Comparação concluída</span><h3>Versão anterior → Versão {result.version}</h3><Comparison data={result.comparison}/></section>}
  <section className="regeneration-history"><div><span className="eyebrow">Versões do Método</span><h3>Histórico de Atualizações do Método</h3></div>{safeArray(context?.history).length?<div>{context.history.map((item:any)=><article key={item.id}><header><div><b>{item.versao_metodo_anterior||item.versao_anterior?.metodo_versao||'—'} → {item.versao_metodo_nova||item.metodo_versao}</b><small>{displayDate(item.created_at)} · {item.usuario}</small></div><span>{item.tipo}</span></header><p><strong>Motivo:</strong> {item.motivo}</p><button onClick={()=>setComparison(comparison?.id===item.id?null:item)}>{comparison?.id===item.id?'Fechar comparação':'Comparar versões'}</button>{comparison?.id===item.id&&<div className="version-comparison"><section><h4>Versão anterior</h4><p><b>Método:</b> {item.versao_metodo_anterior||item.versao_anterior?.metodo_versao||'—'}</p><p><b>Prioridade:</b> {item.versao_anterior?.prioridades||'—'}</p></section><section><h4>Nova versão</h4><p><b>Método:</b> {item.versao_metodo_nova||item.metodo_versao}</p><p><b>Prioridade:</b> {item.versao_nova?.prioridades||'—'}</p></section><Comparison data={item.comparacao}/></div>}</article>)}</div>:<p className="empty-state">Nenhuma atualização do método registrada para esta empresa.</p>}</section>
  {preview&&<div className="method-update-backdrop" role="dialog" aria-modal="true" aria-labelledby="method-update-title"><section className="method-update-modal"><span className="eyebrow">Atualização disponível</span><h2 id="method-update-title">{selectedAction[1]}</h2><div className="method-version-flow"><article><small>Versão utilizada</small><b>Método Escala Growth</b><strong>Versão {context?.method?.plan_version}</strong></article><span>→</span><article><small>Versão disponível</small><b>Método Escala Growth</b><strong>Versão {context?.method?.current?.versao}</strong></article></div><div className="method-update-lists"><article><h3>Novidades que serão incorporadas</h3>{safeArray(context?.method?.current?.novidades).map((item:string)=><p key={item}>✓ {item}</p>)}</article><article><h3>Conteúdo preservado</h3>{['Diagnóstico','Reunião Estratégica','Anotações','Histórico','Documentos',`Parecer Final do Consultor ${options.manter_parecer?'(preservado)':'(conforme opção selecionada)'}`].map(item=><p key={item}>✓ {item}</p>)}</article></div>{context?.method?.execution_started&&<p className="active-method-warning">Este projeto já iniciou sua execução. Recomendamos criar um novo Projeto de Evolução em vez de atualizar o Plano Estratégico. Como Administrador, você ainda pode confirmar a atualização.</p>}<div className="detail-actions"><button className="btn btn-secondary" disabled={busy} onClick={()=>setPreview(false)}>Cancelar</button><button className="btn btn-primary" disabled={busy} onClick={regenerate}>{busy?'Atualizando...':selectedAction[1]}</button></div></section></div>}
 </section>
}
