'use client';
import {useEffect,useState} from 'react';

const actions=[
 ['Diagnóstico','Regenerar Diagnóstico','Recalcula a leitura estratégica sem alterar respostas ou pontuação.'],
 ['Plano Estratégico','Regenerar Plano Estratégico','Aplica a versão mais recente do Método Escala Growth.'],
 ['Projeto de Evolução','Regenerar Projeto de Evolução','Atualiza a composição recomendada para a evolução.'],
 ['Cronograma','Regenerar Cronograma','Reorganiza as fases conforme a estrutura vigente.'],
 ['Recomendações','Atualizar Recomendações','Reavalia prioridades e recomendações estratégicas.'],
 ['Biblioteca de Soluções','Atualizar Biblioteca de Soluções','Sincroniza o documento com a biblioteca vigente.']
];
const safeArray=(value:any)=>Array.isArray(value)?value:[];
const displayDate=(value:string)=>value?new Date(value).toLocaleString('pt-BR'):'—';

function Comparison({data}:{data:any}){const groups=[['Novos recursos',data?.novos_recursos],['Novas recomendações',data?.novas_recomendacoes],['Evoluções futuras',data?.evolucoes_futuras],['Mudanças',data?.mudancas]];return <div className="regeneration-comparison">{groups.map(([label,items]:any)=><article key={label}><h4>{label}</h4>{safeArray(items).length?<ul>{items.map((item:string)=><li key={item}>{item}</li>)}</ul>:<p>Nenhuma alteração nesta categoria.</p>}</article>)}</div>}

export function RegenerationCenter(){
 const [companies,setCompanies]=useState<any[]>([]),[companyId,setCompanyId]=useState(''),[context,setContext]=useState<any>(null),[selected,setSelected]=useState('Plano Estratégico');
 const [reason,setReason]=useState('Atualização para a versão mais recente do Método Escala Growth.'),[options,setOptions]=useState({atualizar_cronograma:true,atualizar_recomendacoes:true,atualizar_biblioteca:true,manter_parecer:true,gerar_parecer_ia:false});
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[result,setResult]=useState<any>(null),[comparison,setComparison]=useState<any>(null);
 const read=async(response:Response)=>{const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Não foi possível concluir a operação.');return payload};
 const loadCompanies=async()=>{try{setLoading(true);const payload=await read(await fetch('/api/regeneration',{cache:'no-store'}));setCompanies(payload.companies||[]);if(payload.companies?.length)setCompanyId((current:string)=>current||payload.companies[0].id)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const loadContext=async(id:string)=>{if(!id)return;try{setLoading(true);setError('');const payload=await read(await fetch(`/api/regeneration?empresa_id=${encodeURIComponent(id)}`,{cache:'no-store'}));setContext(payload)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{loadCompanies()},[]);
 useEffect(()=>{if(companyId)loadContext(companyId)},[companyId]);
 const regenerate=async()=>{try{setBusy(true);setError('');setMessage('');setResult(null);if(!reason.trim())throw new Error('Informe o motivo da regeneração.');const payload=await read(await fetch('/api/regeneration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:companyId,tipo:selected,motivo:reason,...options})}));setResult(payload);setMessage(payload.message);await loadContext(companyId)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const selectedAction=actions.find(action=>action[0]===selected)!;
 if(loading&&!companies.length)return <div className="loading-state">Preparando Central de Regeneração...</div>;
 return <section className="regeneration-center">
  <div className="regeneration-intro"><div><span className="eyebrow">Ferramentas Administrativas</span><h2>Central de Regeneração Inteligente</h2><p>Recalcule documentos com a versão atual do método sem apagar diagnósticos, reuniões, anotações, documentos ou histórico.</p></div><label>Empresa<select value={companyId} onChange={event=>setCompanyId(event.target.value)}><option value="">Selecione</option>{companies.map(company=><option key={company.id} value={company.id}>{company.nome}</option>)}</select></label></div>
  <div className="regeneration-actions">{actions.map(([type,label,description])=><button key={type} className={selected===type?'active':''} onClick={()=>{setSelected(type);setMessage('');setError('');setResult(null)}}><b>↻ {label}</b><span>{description}</span></button>)}</div>
  <div className="regeneration-workspace"><div><span className="eyebrow">Ação selecionada</span><h3>{selectedAction[1]}</h3><p>O {selected} será recalculado utilizando a versão mais recente do Método Escala Growth.</p><div className="regeneration-options"><label><input type="checkbox" checked={options.atualizar_cronograma} onChange={e=>setOptions({...options,atualizar_cronograma:e.target.checked})}/> Atualizar Cronograma</label><label><input type="checkbox" checked={options.atualizar_recomendacoes} onChange={e=>setOptions({...options,atualizar_recomendacoes:e.target.checked})}/> Atualizar Recomendações</label><label><input type="checkbox" checked={options.atualizar_biblioteca} onChange={e=>setOptions({...options,atualizar_biblioteca:e.target.checked})}/> Atualizar Biblioteca de Soluções</label><label><input type="checkbox" checked={options.manter_parecer} onChange={e=>setOptions({...options,manter_parecer:e.target.checked})}/> Manter Parecer Final do Consultor</label><label className="disabled"><input type="checkbox" checked={options.gerar_parecer_ia} disabled/> Gerar novo Parecer utilizando IA <small>Em preparação</small></label></div><label className="regeneration-reason">Motivo<textarea value={reason} onChange={e=>setReason(e.target.value)} /></label><button className="btn btn-primary" disabled={busy||!companyId} onClick={regenerate}>{busy?'Regenerando...':selectedAction[1]}</button>{message&&<p className="success">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}</div><aside><span className="eyebrow">Contexto atual</span><h3>{context?.company?.nome||'Selecione uma empresa'}</h3><dl><div><dt>Método</dt><dd>Versão 2.3</dd></div><div><dt>Diagnóstico</dt><dd>{context?.diagnostic?'Preservado':'Não localizado'}</dd></div><div><dt>Plano</dt><dd>{context?.plan?.status||'Não localizado'}</dd></div><div><dt>Regenerações</dt><dd>{safeArray(context?.history).length}</dd></div></dl></aside></div>
  {result&&<section className="regeneration-result"><span className="eyebrow">Comparação concluída</span><h3>Versão anterior → Versão {result.version}</h3><Comparison data={result.comparison}/></section>}
  <section className="regeneration-history"><div><span className="eyebrow">Versões</span><h3>Histórico de regenerações</h3></div>{safeArray(context?.history).length?<div>{context.history.map((item:any)=><article key={item.id}><header><div><b>{item.tipo} · Versão {item.versao}</b><small>{displayDate(item.created_at)} · {item.usuario}</small></div><span>Método {item.metodo_versao}</span></header><p><strong>Motivo:</strong> {item.motivo}</p><button onClick={()=>setComparison(comparison?.id===item.id?null:item)}>{comparison?.id===item.id?'Fechar comparação':'Comparar versões'}</button>{comparison?.id===item.id&&<div className="version-comparison"><section><h4>Versão anterior</h4><p><b>Prioridade:</b> {item.versao_anterior?.prioridades||'—'}</p><p><b>Status:</b> {item.versao_anterior?.status||'—'}</p></section><section><h4>Versão nova</h4><p><b>Prioridade:</b> {item.versao_nova?.prioridades||'—'}</p><p><b>Status:</b> {item.versao_nova?.status||'—'}</p></section><Comparison data={item.comparacao}/></div>}</article>)}</div>:<p className="empty-state">Nenhuma regeneração registrada para esta empresa.</p>}</section>
 </section>
}
