import {splitConsultantContent} from '../lib/strategic-plan-content';

const activeStatuses=['Contratado','Recomendado','Aprovado','Aprovada','Incluído','Selecionado','Obrigatório'];
const clean=(value:any)=>String(value||'').replace(/^\s*(?:grupo\s*\d+|title\s*:|semana\s*\d+)\s*[—–:\-]?\s*/i,'').replace(/^\s*[•✓✔\-]+\s*/,'').trim();
const lines=(value:any)=>Array.isArray(value)?value.map(clean).filter(Boolean):String(value||'').split(/\r?\n|;/).map(clean).filter(Boolean);

const objectiveDescriptions:Record<string,string>={
 Organizar:'Estruturar processos, responsabilidades e informações para criar uma operação comercial mais clara e consistente.',
 Converter:'Aumentar a capacidade de transformar oportunidades qualificadas em vendas com um processo comercial mais consistente.',
 Atrair:'Criar previsibilidade na geração de oportunidades alinhadas ao perfil de cliente ideal da empresa.',
 Crescer:'Consolidar uma operação previsível, mensurável e preparada para sustentar o crescimento da empresa.',
 Acompanhar:'Dar visibilidade à jornada comercial e garantir continuidade no acompanhamento de cada oportunidade.'
};

function objectiveName(plan:any,diagnostic:any){const source=String(plan.objetivos||diagnostic?.menor_pilar||'Organizar');return Object.keys(objectiveDescriptions).find(item=>source.toLowerCase().includes(item.toLowerCase()))||clean(source.split(/[:—–\-]/)[0])||'Organizar'}
function evolutionItems(plan:any,objective:string){const source=lines(plan.prioridades).filter(item=>!/^prioridade\s+\d+$|^prioridade validada|^principal oportunidade|^oportunidades confirmadas/i.test(item));const fallbacks=[`Organizar os processos ligados a ${objective}`,'Estabelecer uma rotina de acompanhamento','Medir resultados e consolidar a evolução'];return(source.length?source:fallbacks).slice(0,3).map((item,index)=>{const title=clean(item.split(/\s+[—–]\s+|:\s+/)[0])||fallbacks[index],detail=clean(item.replace(title,'').replace(/^\s*[—–:]\s*/,''));return{title,description:detail||'Transformar esta prioridade em uma rotina clara, com responsáveis e critérios de acompanhamento definidos.',result:index===0?'Mais organização e clareza sobre a execução.':index===1?'Maior controle sobre oportunidades e decisões.':'Evolução mensurável e mais previsibilidade operacional.'}})}
function scheduleItems(plan:any){const source=lines(plan.cronograma);return[30,60,90].map((days,index)=>{const match=source.find(item=>new RegExp(`\\b${days}\\s*dias?\\b`,'i').test(item)),objective=clean((match||'').replace(new RegExp(`^${days}\\s*dias?\\s*[—–:\-]?\\s*`,'i'),''))||['Organizar prioridades, responsáveis e indicadores essenciais.','Executar as ações priorizadas e acompanhar a adoção.','Consolidar a rotina, medir a evolução e definir o próximo ciclo.'][index];return{days,objective,result:['Direção de trabalho validada e plano de ação organizado.','Processos prioritários em execução e acompanhados.','Resultados avaliados e evolução preparada para continuidade.'][index]}})}
function benefitLines(solution:any){return lines(solution.beneficios||solution.principais_beneficios)}

export function StrategicPlanDocument({data}:{data:any}){
 const plan=data.plan||{},diagnostic=data.latest||{},company=data.company||{},consultant=splitConsultantContent(plan.parecer_consultor),objective=objectiveName(plan,diagnostic),objectiveDescription=objectiveDescriptions[objective]||`Concentrar a evolução da empresa em ${objective}, com prioridades claras e acompanhamento consistente.`,evolution=evolutionItems(plan,objective),schedule=scheduleItems(plan),solutions=(Array.isArray(data.implementation?.recursos)?data.implementation.recursos:[]).filter((item:any)=>activeStatuses.includes(item.status)||(!item.status&&item.selecionado!==false)),dateValue=plan.updated_at||plan.created_at||diagnostic.data_diagnostico||diagnostic.created_at,formattedDate=dateValue?new Date(dateValue).toLocaleDateString('pt-BR'):'A definir',consultantName=company.consultor_responsavel||'Teófilo Oliveira Fagundes';
 return <div className="strategic-executive-document">
  <header className="strategic-cover"><span className="eyebrow">Método Escala Growth</span><h2>Plano Estratégico Escala Growth</h2><div>{[['Empresa',company.nome||'Empresa'],['Consultor',consultantName],['Data',formattedDate],['Status',plan.status||'Em preparação']].map(([label,value])=><article key={label}><small>{label}</small><b>{value}</b></article>)}</div></header>
  <section className="strategic-executive-section"><span>01</span><div><h3>Visão Executiva</h3><p>Após a realização do Diagnóstico Escala Growth e da Reunião Estratégica, identificamos que a principal oportunidade da empresa está em <b>{objective.toLowerCase()}</b>, criando uma operação comercial mais organizada, acompanhável e previsível.</p><p>{objectiveDescription} Este Plano Estratégico apresenta as prioridades e ações recomendadas para conduzir essa evolução.</p></div></section>
  <section className="strategic-executive-section"><span>02</span><div><h3>Objetivo Estratégico</h3><div className="strategic-objective"><b>{objective}</b><p>{objectiveDescription}</p></div></div></section>
  <section className="strategic-executive-section"><span>03</span><div><h3>Plano de Evolução</h3><div className="strategic-evolution-grid">{evolution.map((item,index)=><article key={`${item.title}-${index}`}><small>Prioridade {index+1}</small><h4>{item.title}</h4><p>{item.description}</p><b>Resultado esperado</b><p>{item.result}</p></article>)}</div></div></section>
  <section className="strategic-executive-section"><span>04</span><div><h3>Cronograma</h3><div className="strategic-schedule">{schedule.map(item=><article key={item.days}><strong>{item.days} dias</strong><small>Objetivo</small><p>{item.objective}</p><small>Resultado esperado</small><p>{item.result}</p></article>)}</div></div></section>
  {solutions.length>0&&<section className="strategic-executive-section"><span>05</span><div><h3>Soluções Recomendadas</h3><div className="strategic-client-solutions">{solutions.map((solution:any)=>{const benefits=benefitLines(solution),expected=solution.resultado_esperado||solution.parametros_metodo?.resultado_esperado;return <article key={solution.id||solution.nome}><h4>{solution.nome}</h4><p><b>Objetivo</b><br/>{solution.objetivo||solution.objetivo_padrao||`Apoiar a execução da prioridade estratégica definida para ${objective}.`}</p>{expected&&<p><b>Resultado esperado</b><br/>{expected}</p>}{benefits.length>0&&<><b>Principais benefícios</b><ul>{benefits.slice(0,3).map(item=><li key={item}>{item}</li>)}</ul></>}<details><summary>Ver detalhes</summary>{(solution.descricao_tecnica||solution.descricao)&&<p>{solution.descricao_tecnica||solution.descricao}</p>}{benefits.length>0&&<><b>Benefícios</b><ul>{benefits.map(item=><li key={item}>{item}</li>)}</ul></>}<p><b>Objetivo</b><br/>{solution.objetivo||solution.objetivo_padrao||'Apoiar a evolução estratégica da empresa.'}</p></details></article>})}</div></div></section>}
  <section className="strategic-executive-section"><span>06</span><div><h3>Parecer Final do Consultor</h3><blockquote>{consultant.opinion||'O parecer final será disponibilizado após a conclusão do Plano Estratégico.'}</blockquote></div></section>
  <section className="strategic-executive-section"><span>07</span><div><h3>Próximos Passos</h3><div className="strategic-journey">{['Plano Estratégico','Proposta de Implantação','Aceite','Contrato','Pagamento','Implantação','Área do Cliente','Método Escala Growth'].map((item,index)=><div key={item}><i>{index+1}</i><b>{item}</b>{index<7&&<span>↓</span>}</div>)}</div></div></section>
 </div>
}
