'use client';
import {useEffect,useMemo,useState} from 'react';
const money=(value:any)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const labels:any={PRINCIPAL:'Soluções principais',COMPLEMENTAR:'Soluções complementares',PRE_REQUISITO:'Pré-requisitos',EVOLUCAO_FUTURA:'Evoluções futuras'};

export function StrategicCommercialComposition({companyId,onApply}:{companyId:string;onApply:(resources:any[],context:any)=>void}){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[selected,setSelected]=useState<Record<string,boolean>>({}),[manual,setManual]=useState(''),[justifications,setJustifications]=useState<Record<string,string>>({});
 useEffect(()=>{fetch(`/api/strategic-commercial?empresa_id=${companyId}`,{cache:'no-store'}).then(async response=>{const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Não foi possível preparar a composição.');setData(payload);if(payload.flow==='ESTRATEGICO_3_0')setSelected(Object.fromEntries(payload.composition.solutions.map((item:any)=>[item.solucao_id,item.selected])))}).catch(error=>setError(error.message))},[companyId]);
 const solutions=useMemo(()=>data?.composition?.solutions||[],[data]),selectedSolutions=solutions.filter((item:any)=>selected[item.solucao_id]),totals=selectedSolutions.reduce((sum:any,item:any)=>({implantacao:sum.implantacao+item.pricing.valor_implantacao,mensal:sum.mensal+item.pricing.valor_mensal}),{implantacao:0,mensal:0});
 const addManual=()=>{const solution=data.catalog?.find((item:any)=>item.id===manual);if(!solution||solutions.some((item:any)=>item.solucao_id===manual))return;const type=solution.tipo,ui=type==='Mensalidade'?0:Number(solution.ui||0),unit=Number(data.parameters?.valor_ui||0),monthly=type==='Implantação'?0:Number(solution.valor_mensal||0),item={solucao_id:solution.id,solution,tipo_vinculo:'COMPLEMENTAR',link_types:['COMPLEMENTAR'],source_interventions:[],origem:'MANUAL_CONSULTOR',selected:true,future:false,dependencies:[],pricing:{ui_utilizada:ui,valor_ui_utilizado:unit,valor_implantacao:ui*unit,valor_mensal:monthly,fonte_mensalidade:type==='Implantação'?'NAO_APLICAVEL':'catalogo_recursos.valor_mensal'},parametros_snapshot:{flow:'ESTRATEGICO_3_0',solution_id:solution.id,solution_code:solution.codigo,solution_name:solution.nome,tipo,ui_utilizada:ui,valor_ui_utilizado:unit,valor_implantacao_calculado:ui*unit,valor_mensal_utilizado:monthly,source_interventions:[],tipo_vinculo:'COMPLEMENTAR',dependencias_resolvidas:[],origem:'MANUAL_CONSULTOR',generated_at:new Date().toISOString()}};setData({...data,composition:{...data.composition,solutions:[...solutions,item]}});setSelected({...selected,[solution.id]:true});setManual('')};
 const apply=()=>onApply(selectedSolutions.map((item:any)=>({...item.solution,id:item.solucao_id,valor_implantacao:item.pricing.valor_implantacao,valor_mensal:item.pricing.valor_mensal,classificacao:item.tipo_vinculo==='PRE_REQUISITO'?'Obrigatório':item.tipo_vinculo==='EVOLUCAO_FUTURA'?'Opcional':'Recomendado',origem:item.origem==='DEPENDENCIA'?'DEPENDENCIA':item.origem,fase:labels[item.tipo_vinculo],recomendado_metodo:item.origem!=='MANUAL_CONSULTOR',implantar_nesta_fase:item.future?false:null,parametros_snapshot:{...item.parametros_snapshot,justificativa_consultor:justifications[item.solucao_id]||null}})),{decision:data.decision,diagnostic_id:data.diagnostic_id,totals});
 if(error)return <section className="strategic-composition"><p className="error">{error}</p></section>;if(!data)return <div className="loading-state">Preparando composição comercial...</div>;if(data.flow!=='ESTRATEGICO_3_0')return <section className="strategic-composition"><h3>Composição Comercial</h3><p>{data.message} O fluxo comercial legado permanece disponível.</p></section>;
 return <section className="strategic-composition"><span className="eyebrow">Motor Estratégico 3.0 → Biblioteca</span><h3>Composição Comercial</h3><div className="composition-direction"><div><small>Direção estratégica</small><b>{data.decision?.strategic_direction||'—'}</b></div><div><small>Prioridade principal</small><b>{data.decision?.primary_priority||'—'}</b></div></div>{(['PRINCIPAL','COMPLEMENTAR','PRE_REQUISITO','EVOLUCAO_FUTURA'] as const).map(type=><div className="composition-group" key={type}><h4>{labels[type]}</h4>{solutions.filter((item:any)=>item.tipo_vinculo===type).length?solutions.filter((item:any)=>item.tipo_vinculo===type).map((item:any)=><article key={item.solucao_id}><label><input type="checkbox" checked={Boolean(selected[item.solucao_id])} onChange={event=>setSelected({...selected,[item.solucao_id]:event.target.checked})}/><span><b>{item.solution.nome}</b><small>{item.solution.tipo} · {item.solution.classificacao_comercial}</small></span></label><div><small>Origem estratégica</small><span>{item.source_interventions.join(' · ')||item.origem}</span></div><div><small>UI / Implantação</small><b>{item.pricing.ui_utilizada} UI · {money(item.pricing.valor_implantacao)}</b></div><div><small>Mensalidade</small><b>{money(item.pricing.valor_mensal)}</b></div>{!selected[item.solucao_id]&&<input placeholder="Justificativa para retirada" value={justifications[item.solucao_id]||''} onChange={e=>setJustifications({...justifications,[item.solucao_id]:e.target.value})}/>}</article>):<p>Nenhuma solução nesta categoria.</p>}</div>)}{data.composition.unmapped_interventions.length>0&&<div className="composition-unmapped"><h4>Sem solução mapeada</h4>{data.composition.unmapped_interventions.map((item:any)=><p key={item.intervention_code}><b>{item.title}</b><small>{item.intervention_code}</small></p>)}</div>}<div className="manual-solution"><label>Adicionar solução manualmente<select value={manual} onChange={e=>setManual(e.target.value)}><option value="">Selecione</option>{data.catalog.filter((item:any)=>item.ativo&&!solutions.some((resolved:any)=>resolved.solucao_id===item.id)).map((item:any)=><option value={item.id} key={item.id}>{item.nome}</option>)}</select></label><button className="btn btn-secondary" onClick={addManual} disabled={!manual}>Adicionar</button></div><div className="commercial-summary"><article><small>Total de implantação</small><b>{money(totals.implantacao)}</b></article><article><small>Total mensal</small><b>{money(totals.mensal)}</b></article><article><small>Valor da UI congelado</small><b>{money(data.parameters?.valor_ui)}</b></article></div><button className="btn btn-primary" onClick={apply}>Usar composição no Projeto de Evolução</button><p><small>Esta ação apenas prepara o rascunho. Não publica, contrata, aceita ou registra pagamento.</small></p></section>}

