'use client';
import {useEffect,useMemo,useState} from 'react';

const list=(value:any):any[]=>Array.isArray(value)?value:[];
const statusLabel:Record<string,string>={PLANNED:'Planejada',IN_PROGRESS:'Em andamento',COMPLETED:'Concluída'};
const horizonLabel:Record<string,string>={AGORA:'Agora',DEPOIS:'Depois',QUANDO_ESTIVER_PRONTO:'Quando estiver pronto'};
const dimensionLabel:Record<string,string>={ATRAIR:'Atrair',ABSORVER:'Absorver',CONVERTER:'Converter',GERIR:'Gerir'};
const formatDate=(value:any)=>value?new Date(String(value).length===10?value+'T12:00:00':value).toLocaleDateString('pt-BR'):'—';
async function payload(response:Response){const text=await response.text();if(!text.trim())return{};try{return JSON.parse(text)}catch{return{error:'O servidor retornou uma resposta inválida.'}}}
function debugValue(value:any){if(!value||typeof value!=='object')return String(value??'—');return Object.entries(value).map(([key,item])=>`${key}: ${String(item??'—')}`).join(' · ')}
function creationFailure(error:any){const detail=error&&typeof error==='object'?error:{};return <><span>{detail.message||'Não foi possível criar a Implantação.'}</span><details className="implementation-creation-debug"><summary>Detalhe da criação da Implantação</summary><dl><div><dt>Etapa</dt><dd>{detail.stage||'Não identificada'}</dd></div><div><dt>Código</dt><dd>{detail.code||'IMPLEMENTATION_CREATION_FAILED'}</dd></div><div><dt>Mensagem técnica</dt><dd>{detail.technical_detail||'O servidor não informou detalhes.'}</dd></div>{Object.entries(detail.debug||{}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{debugValue(value)}</dd></div>)}</dl></details></>}

export function StrategicImplementationCenter(){const[data,setData]=useState<any>({published_plans:[],implementations:[]}),[selectedPlan,setSelectedPlan]=useState(''),[implementation,setImplementation]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState<any>('');
 const load=async()=>{setLoading(true);setError('');try{const response=await fetch('/api/strategic-implementations',{cache:'no-store'}),result=await payload(response);if(!response.ok)throw new Error(result.error||'Não foi possível carregar as Implantações.');setData(result)}catch(reason:any){setError(reason.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const open=async(id:string)=>{setBusy(true);setError('');try{const response=await fetch('/api/strategic-implementations?id='+encodeURIComponent(id),{cache:'no-store'}),result=await payload(response);if(!response.ok)throw new Error(result.error||'Não foi possível abrir a Implantação.');setImplementation(result.implementation)}catch(reason:any){setError(reason.message)}finally{setBusy(false)}};
 const create=async()=>{if(!selectedPlan){setError('Selecione uma versão publicada.');return}const existing=list(data.published_plans).find((item:any)=>item.id===selectedPlan)?.implementation;if(existing){setMessage('Esta versão já possui uma Implantação.');open(existing.id);return}setBusy(true);setError('');setMessage('Criando Implantação...');try{const response=await fetch('/api/strategic-implementations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'create',plan_id:selectedPlan})}),result=await payload(response);if(!response.ok){setError(creationFailure(result.error));setMessage('');return}setImplementation(result.implementation);setMessage(result.message);await load()}catch(reason:any){setError(creationFailure({code:'NETWORK_ERROR',message:'Não foi possível criar a Implantação.',technical_detail:reason.message,stage:'comunicação com a API'}));setMessage('')}finally{setBusy(false)}};
 if(loading)return <div className="loading-state">Preparando Implantações...</div>;
 if(implementation)return <ImplementationDetail value={implementation} busy={busy} setBusy={setBusy} message={message} setMessage={setMessage} error={error} setError={setError} back={()=>{setImplementation(null);setMessage('');setError('');load()}} refresh={setImplementation}/>;
 const selected=list(data.published_plans).find((item:any)=>item.id===selectedPlan);
 return <div className="strategic-implementation-page"><section className="admin-section implementation-create"><span className="eyebrow">Plano publicado → execução</span><h2>Criar Implantação</h2><p>A Implantação nasce exclusivamente do snapshot imutável de uma versão publicada do Plano Estratégico Executável.</p><label>Versão publicada<select value={selectedPlan} onChange={event=>setSelectedPlan(event.target.value)}><option value="">Selecione</option>{list(data.published_plans).map((plan:any)=><option key={plan.id} value={plan.id}>{plan.company?.nome||'Empresa'} · Plano V{plan.version_number} · {plan.strategic_direction||'Direção não informada'}{plan.implementation?' · Implantação existente':''}</option>)}</select></label>{selected&&<div className="implementation-source-summary"><div><small>Empresa</small><b>{selected.company?.nome||'—'}</b></div><div><small>Plano</small><b>Versão {selected.version_number}</b></div><div><small>Direção estratégica</small><b>{selected.strategic_direction||'—'}</b></div><div><small>Ações acordadas</small><b>{list(selected.published_snapshot?.actions).length}</b></div></div>}<button className="btn btn-primary" disabled={busy||!selectedPlan} onClick={create}>{selected?.implementation?'Abrir Implantação existente':busy?'Criando...':'Criar Implantação'}</button>{message&&<p className="success">{message}</p>}{error&&<p className="error">{error}</p>}</section><section className="admin-section"><span className="eyebrow">Histórico operacional</span><h2>Implantações criadas</h2><div className="implementation-list">{list(data.implementations).map((item:any)=><article key={item.id}><div><b>{item.company?.nome||'Empresa'}</b><span>Plano V{item.plan_version} · {formatDate(item.created_at)}</span></div><span className={'status-pill status-'+String(item.status).toLowerCase()}>{statusLabel[item.status]||item.status}</span><button className="btn btn-secondary" onClick={()=>open(item.id)}>Abrir</button></article>)}{!list(data.implementations).length&&<p className="empty-state">Nenhuma Implantação criada.</p>}</div></section></div>}

function ImplementationDetail({value,busy,setBusy,message,setMessage,error,setError,back,refresh}:{value:any;busy:boolean;setBusy:(value:boolean)=>void;message:string;setMessage:(value:string)=>void;error:string;setError:(value:string)=>void;back:()=>void;refresh:(value:any)=>void}){const items=list(value.items),counts=useMemo(()=>({total:items.length,planned:items.filter(item=>item.status==='PLANNED').length,progress:items.filter(item=>item.status==='IN_PROGRESS').length,completed:items.filter(item=>item.status==='COMPLETED').length}),[items]);return <div className="strategic-implementation-page"><section className="admin-section implementation-header"><div className="detail-actions"><button className="btn btn-secondary" onClick={back}>← Voltar</button></div><div><span className="eyebrow">Implantação do Plano Estratégico Executável</span><h2>{value.company?.nome||'Empresa'}</h2><p>Direção de origem: <b>{value.strategic_direction||'—'}</b></p></div><div className="implementation-source-summary">{[['Versão do Plano','V'+value.plan_version],['Status',statusLabel[value.status]||value.status],['Criada em',formatDate(value.created_at)],['Total de ações',counts.total],['Planejadas',counts.planned],['Em andamento',counts.progress],['Concluídas',counts.completed]].map(([label,content])=><div key={label}><small>{label}</small><b>{content}</b></div>)}</div>{message&&<p className="success">{message}</p>}{error&&<p className="error">{error}</p>}</section>{['AGORA','DEPOIS','QUANDO_ESTIVER_PRONTO'].map(horizon=><section className="admin-section" key={horizon}><span className="eyebrow">{horizonLabel[horizon]}</span><div className="implementation-item-grid">{items.filter(item=>item.agreed_horizon===horizon).map(item=><ImplementationItem key={item.id} item={item} busy={busy} save={async changes=>{setBusy(true);setError('');setMessage('Salvando item...');try{const response=await fetch('/api/strategic-implementations',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'update-item',item_id:item.id,...changes})}),result=await payload(response);if(!response.ok)throw new Error(result.error||'Não foi possível salvar o item.');refresh(result.implementation);setMessage(result.message)}catch(reason:any){setError(reason.message);setMessage('')}finally{setBusy(false)}}}/>)}{!items.some(item=>item.agreed_horizon===horizon)&&<p className="empty-state">Nenhuma ação neste horizonte.</p>}</div></section>)}<ImplementationHistory items={list(value.history)}/><ImplementationDebug implementation={value}/></div>}

function ImplementationItem({item,busy,save}:{item:any;busy:boolean;save:(changes:any)=>Promise<void>}){const[draft,setDraft]=useState({operational_responsible:item.operational_responsible||'',operational_due_date:item.operational_due_date||'',status:item.status||'PLANNED',started_at:item.started_at?.slice(0,10)||'',completed_at:item.completed_at?.slice(0,10)||'',execution_notes:item.execution_notes||'',execution_evidence:item.execution_evidence||''});useEffect(()=>setDraft({operational_responsible:item.operational_responsible||'',operational_due_date:item.operational_due_date||'',status:item.status||'PLANNED',started_at:item.started_at?.slice(0,10)||'',completed_at:item.completed_at?.slice(0,10)||'',execution_notes:item.execution_notes||'',execution_evidence:item.execution_evidence||''}),[item]);return <article className="implementation-item"><header><div><small>{dimensionLabel[item.dimension]||item.dimension||'Ação operacional'}</small><h3>{item.agreed_title}</h3></div><span className={'status-pill status-'+String(draft.status).toLowerCase()}>{statusLabel[draft.status]}</span></header><p>{item.agreed_objective||'Objetivo não informado.'}</p><dl><div><dt>Indicador</dt><dd>{item.agreed_indicator||'—'}</dd></div><div><dt>Meta acordada</dt><dd>{item.agreed_target||'—'}</dd></div><div><dt>Responsável acordado</dt><dd>{item.agreed_responsible||'—'}</dd></div><div><dt>Prazo acordado</dt><dd>{formatDate(item.agreed_due_date)}</dd></div></dl><div className="implementation-fields"><label>Responsável operacional<input value={draft.operational_responsible} onChange={event=>setDraft({...draft,operational_responsible:event.target.value})}/></label><label>Status<select value={draft.status} onChange={event=>setDraft({...draft,status:event.target.value})}>{Object.entries(statusLabel).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Prazo operacional<input type="date" value={draft.operational_due_date} onChange={event=>setDraft({...draft,operational_due_date:event.target.value})}/></label><label>Data de início<input type="date" value={draft.started_at} onChange={event=>setDraft({...draft,started_at:event.target.value})}/></label><label>Data de conclusão<input type="date" value={draft.completed_at} onChange={event=>setDraft({...draft,completed_at:event.target.value})}/></label><label className="wide">Observação de execução<textarea rows={3} value={draft.execution_notes} onChange={event=>setDraft({...draft,execution_notes:event.target.value})}/></label><label className="wide">Evidência textual<textarea rows={3} value={draft.execution_evidence} onChange={event=>setDraft({...draft,execution_evidence:event.target.value})}/></label></div><button className="btn btn-primary" disabled={busy} onClick={()=>save(draft)}>Salvar item</button></article>}

function ImplementationHistory({items}:{items:any[]}){return <details className="admin-section"><summary>Histórico da Implantação</summary>{items.length?<div className="technical-evidence-table"><table><thead><tr><th>Data</th><th>Usuário</th><th>Evento</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString('pt-BR')}</td><td>{item.actor||'Usuário Master'}</td><td>{item.description}</td></tr>)}</tbody></table></div>:<p>Nenhum evento registrado.</p>}</details>}
function ImplementationDebug({implementation}:{implementation:any}){return <details className="admin-section implementation-debug"><summary>Implantação — Debug administrativo</summary><div className="execution-debug"><p><b>implantation_id:</b> {implementation.id}</p><p><b>diagnostic_id:</b> {implementation.diagnostico_id}</p><p><b>plan_id:</b> {implementation.plan_id}</p><p><b>plan_version:</b> {implementation.plan_version}</p><p><b>status:</b> {implementation.status}</p><p><b>quantidade de itens:</b> {list(implementation.items).length}</p></div><div className="technical-evidence-table"><table><thead><tr><th>action_code</th><th>Horizonte</th><th>Responsável acordado</th><th>Responsável operacional</th><th>Status</th></tr></thead><tbody>{list(implementation.items).map(item=><tr key={item.id}><td>{item.source_action_code||'—'}</td><td>{item.agreed_horizon}</td><td>{item.agreed_responsible||'—'}</td><td>{item.operational_responsible||'—'}</td><td>{item.status}</td></tr>)}</tbody></table></div></details>}
