'use client';

import {useMemo,useState} from 'react';
import {joinConsultantContent,splitConsultantContent} from '../lib/strategic-plan-content';
import {currentPlatformResources,currentRevisionNextSteps,resolveCurrentStrategicRevision} from '../lib/strategicRevisionResolver';

const list=(value:any):any[]=>Array.isArray(value)?value:[];
const text=(value:any,fallback='Não informado durante a Reunião Estratégica.')=>String(value||'').trim()||fallback;
const readableLines=(value:any)=>Array.isArray(value)?value.map(item=>typeof item==='string'?item:item?.label||item?.nome||item?.descricao).filter(Boolean).join('\n'):text(value);

function meetingConsolidation(data:any,plan:any){
 const meeting=resolveCurrentStrategicRevision(list(data.reunioes_estrategicas),plan.revisao_estrategica_id)||{};
 const meetingData=meeting.dados_reuniao||{},validations=meetingData.validacoes_reuniao||meeting.validacoes_reuniao||{};
 const resources=currentPlatformResources(meeting).map(item=>`${item.name}: ${item.status}`);
 const opportunities=list(validations.oportunidades?.confirmadas).map((item:any)=>String(item).split(':').slice(2).join(':')||String(item)).filter(Boolean);
 if(validations.oportunidades?.nova)opportunities.push(validations.oportunidades.nova);
 const answers=Object.values(validations.respostas_perguntas||{}).map(String).filter(value=>value.trim());
 const hypotheses=[validations.hipotese_resposta,meetingData.hipotese_inicial,meeting.consultant_initial_hypothesis].filter(Boolean).join('\n\n');
 const validatedPriority=validations.prioridade?.selecionada==='Outra'?validations.prioridade?.outra:validations.prioridade?.selecionada;
 const hasNewerRevision=Number(meeting.revisao_numero||1)>1||Boolean(plan.revisao_estrategica_id);
 const currentSteps=hasNewerRevision?currentRevisionNextSteps(meeting,''):'';
 return {resumo:text(validations.conclusao?.resumo_executivo||plan.resumo||data.parecer),situacao:text(plan.situacao_atual||validations.realidade?.novas_informacoes||validations.realidade?.observacoes),hipoteses:text(hypotheses),objetivo:text(plan.objetivos||validatedPriority||data.menor_pilar),prioridades:text(plan.prioridades||validatedPriority||readableLines(data.relatorio_snapshot?.prioridades)),recursos:text(resources.join('\n')),oportunidades:text(opportunities.join('\n')),informacoes:text(answers.join('\n\n')||validations.realidade?.novas_informacoes||meetingData.informacoes_complementares),cronograma:text(plan.cronograma),proximosPassos:text(currentSteps||(hasNewerRevision?'Nenhum novo próximo passo de aquisição foi definido nesta revisão.':plan.proximos_passos))};
}

export function StrategicPlanValidation({data,plan}:{data:any;plan:any;update?:(id:string,body:any)=>void}){
 const existing=splitConsultantContent(plan.parecer_consultor),consolidated=useMemo(()=>meetingConsolidation(data,plan),[data,plan]);
 const inherited=useMemo(()=>({resumo:consolidated.resumo,situacao_atual:consolidated.situacao,objetivos:consolidated.objetivo,prioridades:consolidated.prioridades,riscos:plan.riscos||'',cronograma:consolidated.cronograma,proximos_passos:consolidated.proximosPassos}),[consolidated,plan.riscos]);
 const sections=[['Resumo Executivo',consolidated.resumo],['Situação Atual da Empresa',consolidated.situacao],['Hipóteses Validadas',consolidated.hipoteses],['Objetivo Estratégico',consolidated.objetivo],['Prioridades',consolidated.prioridades],['Recursos já Implantados',consolidated.recursos],['Oportunidades Confirmadas',consolidated.oportunidades],['Informações Confirmadas pelo Cliente',consolidated.informacoes],['Próximos Passos',consolidated.proximosPassos],['Cronograma',consolidated.cronograma]];
 const [opinion,setOpinion]=useState(existing.opinion),[status,setStatus]=useState(['Plano Concluído','Concluído'].includes(plan.status)?'Plano Concluído':['Plano Liberado ao Cliente','Liberado ao cliente'].includes(plan.status)?'Plano Liberado ao Cliente':'Em Consolidação'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const complete=async()=>{if(!opinion.trim()){setMessage('Registre o Parecer Final do Consultor antes de concluir o Plano Estratégico.');return}if(!confirm('Concluir o Plano Estratégico e gerar a versão oficial do documento?'))return;setBusy(true);setMessage('Gerando a versão oficial do Plano Estratégico...');const currentPlan={...inherited,parecer_consultor:joinConsultantContent(opinion,existing.observations)};try{const saved=await fetch('/api/central?resource=strategic-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plano_id:plan.id||null,diagnostico_id:data.id,empresa_id:data.empresa_id,...currentPlan,status:'Plano Concluído'})}),result=await saved.json().catch(()=>({}));if(!saved.ok)throw new Error(result.error||'Não foi possível salvar o Plano Estratégico.');const mirror=await fetch('/api/diagnostics',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:data.id,plano:currentPlan})});if(!mirror.ok){const error=await mirror.json().catch(()=>({}));throw new Error(error.error||'O Plano foi salvo, mas a confirmação de persistência falhou.')}const version=await fetch('/api/central?resource=versions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plano_id:result.plan?.id||plan.id||null,diagnostico_id:data.id,consultor:'Teófilo Oliveira Fagundes',conteudo:currentPlan,status:'Plano Concluído'})});const workflow=await fetch('/api/central?resource=workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({diagnostico_id:data.id,action:'complete'})});setStatus('Plano Concluído');const warnings=[];if(!version.ok)warnings.push('o histórico de versões não foi atualizado');if(!workflow.ok)warnings.push('a jornada não foi atualizada');setMessage(warnings.length?'Plano Estratégico concluído. Atenção: '+warnings.join(' e ')+'.':'Plano Estratégico concluído e versão oficial gerada com sucesso.')}catch(error:any){setMessage(error?.message||'Não foi possível concluir o Plano Estratégico.')}finally{setBusy(false)}};
 return <section className="admin-section plan-premium strategic-validation" id="plan-editor"><div className="document-brand"><img src="/logo-escala-vendas.png" alt="Escala Vendas"/><span>Plano Estratégico Escala Growth</span></div><div className="plan-toolbar no-print"><span className="status-pill">{status}</span><p>Documento executivo automático. Revise abaixo a consolidação automática do Diagnóstico e da Reunião Estratégica. Em seguida registre apenas seu Parecer Final como consultor antes da conclusão do Plano Estratégico.</p></div><div className="strategic-consolidated-content">{sections.map(([title,content],index)=><section className="strategic-readonly" key={title}><span className="eyebrow">{String(index+1).padStart(2,'0')}</span><h3>{title}</h3><p>{content}</p></section>)}</div><label className="strategic-final-field"><b>Parecer Final do Consultor <em>Obrigatório</em></b><span>Registre sua análise estratégica final antes da conclusão do Plano Estratégico.</span><small>Este é o único conteúdo manual desta etapa. A consolidação acima permanece fiel ao Diagnóstico e à Reunião Estratégica.</small><textarea id="parecer-consultor" rows={8} value={opinion} onChange={event=>setOpinion(event.target.value)} placeholder="Após análise do diagnóstico e validação realizada durante a reunião estratégica, identificamos que..."/></label><div className="detail-actions no-print"><button className="btn btn-primary" disabled={busy||status==='Plano Liberado ao Cliente'} onClick={complete}>{busy?'Gerando Plano Estratégico...':'✅ Concluir Plano Estratégico'}</button></div>{message&&<p className={message.startsWith('Plano Estratégico concluído')?'success':'error'}>{message}</p>}</section>
}
