'use client';
import {useEffect,useMemo,useState} from 'react';

const types=['PRINCIPAL','COMPLEMENTAR','PRE_REQUISITO','EVOLUCAO_FUTURA'];
const friendly=(value:string)=>({PRINCIPAL:'Principal',COMPLEMENTAR:'Complementar',PRE_REQUISITO:'Pré-requisito',EVOLUCAO_FUTURA:'Evolução futura'} as any)[value]||value;

export function StrategicSolutionMappingAdmin(){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[form,setForm]=useState<any>({intervention_code:'',solucao_id:'',tipo_vinculo:'PRINCIPAL',ordem:0,ativo:true});
 const load=async()=>{const response=await fetch('/api/strategic-commercial',{cache:'no-store'}),payload=await response.json().catch(()=>({}));if(!response.ok)setError(payload.error||'Não foi possível carregar os vínculos.');else{setData(payload);setError('');setForm((current:any)=>({...current,intervention_code:current.intervention_code||payload.interventions?.[0]?.intervention_code||'',solucao_id:current.solucao_id||payload.catalog?.find((item:any)=>item.ativo)?.id||''}))}};
 useEffect(()=>{load()},[]);const interventionMap=useMemo(()=>new Map((data?.interventions||[]).map((item:any)=>[item.intervention_code,item])),[data]);
 const save=async()=>{setMessage('');const response=await fetch('/api/strategic-commercial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save-link',...form})}),payload=await response.json().catch(()=>({}));setMessage(response.ok?'Vínculo salvo com sucesso.':payload.error||'Não foi possível salvar.');if(response.ok)await load()};
 const remove=async(id:string)=>{if(!confirm('Remover este vínculo estratégico?'))return;const response=await fetch('/api/strategic-commercial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete-link',id})});if(response.ok){setMessage('Vínculo removido.');await load()}};
 if(error)return <section className="admin-section"><p className="error">{error}</p></section>;if(!data)return <div className="loading-state">Preparando vínculos do Método...</div>;
 return <><section className="admin-section"><span className="eyebrow">Método Escala Growth</span><h2>Vínculos com o Método Escala Growth</h2><p>Associe intervenções canônicas do Motor às soluções comerciais sem usar correspondência por texto.</p><div className="method-coverage"><article><small>Intervenções canônicas</small><b>{data.coverage.total}</b></article><article><small>Mapeadas</small><b>{data.coverage.mapped}</b></article><article><small>Sem mapeamento</small><b>{data.coverage.unmapped.length}</b></article></div><div className="mapping-form"><label>Intervenção<select value={form.intervention_code} onChange={e=>setForm({...form,intervention_code:e.target.value})}>{data.interventions.map((item:any)=><option key={item.intervention_code} value={item.intervention_code}>{item.title} · {item.dimension} · {item.intervention_code}</option>)}</select></label><label>Solução<select value={form.solucao_id} onChange={e=>setForm({...form,solucao_id:e.target.value})}>{data.catalog.filter((item:any)=>item.ativo).map((item:any)=><option key={item.id} value={item.id}>{item.nome} · {item.tipo}</option>)}</select></label><label>Tipo de vínculo<select value={form.tipo_vinculo} onChange={e=>setForm({...form,tipo_vinculo:e.target.value})}>{types.map(type=><option key={type} value={type}>{friendly(type)}</option>)}</select></label><label>Ordem<input type="number" min="0" value={form.ordem} onChange={e=>setForm({...form,ordem:e.target.value})}/></label><button className="btn btn-primary" onClick={save}>Salvar vínculo</button></div>{message&&<p className={message.includes('sucesso')||message.includes('removido')?'success':'error'}>{message}</p>}</section><section className="admin-section"><h2>Intervenção → soluções associadas</h2><div className="mapping-list">{data.links.length?data.links.map((link:any)=>{const intervention:any=interventionMap.get(link.intervention_code),solution=data.catalog.find((item:any)=>item.id===link.solucao_id);return <article key={link.id}><div><b>{intervention?.title||link.intervention_code}</b><small>{link.intervention_code} · {intervention?.dimension||'—'}</small></div><strong>{solution?.nome||'Solução indisponível'}</strong><span>{friendly(link.tipo_vinculo)} · ordem {link.ordem}</span><span className="status-pill">{link.ativo?'Ativo':'Inativo'}</span><button onClick={()=>remove(link.id)}>Remover</button></article>}):<p>Nenhum vínculo cadastrado.</p>}</div></section><section className="admin-section"><h2>Cobertura Motor → Biblioteca</h2>{data.coverage.unmapped.length?<div className="unmapped-list">{data.coverage.unmapped.map((item:any)=><article key={item.intervention_code}><b>{item.title}</b><small>{item.dimension} · {item.intervention_code}</small><span>Sem solução mapeada na Biblioteca.</span></article>)}</div>:<p className="success">A Biblioteca cobre 100% das intervenções canônicas.</p>}</section></>}

