'use client';
/* eslint-disable @typescript-eslint/no-explicit-any */
import {useEffect,useState} from 'react';
import {brandLogo} from '@/components/brand';
import styles from './ToolImplementationAdmin.module.css';

const money=(value:any)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const names:Record<string,string>={CRM:'CRM',AI_AGENT:'Agente de Inteligência Artificial',SERVICE_AUTOMATION:'Automação de Atendimento',PROCESS_AUTOMATION:'Automação de Processos',SYSTEM_INTEGRATION:'Integração entre Sistemas'};
const labels:Record<string,string>={users:'Usuários',use:'Uso principal',current:'Situação atual',current_name:'Ferramenta atual',area:'Área',channels:'Canais',functions:'Funções',people:'Pessoas no atendimento',summary:'Processo',uses_system:'Utiliza sistema existente',system:'Sistema',systems:'Sistemas',expected_flow:'Fluxo esperado'};
const configurationRows=(configuration:any)=>Object.entries(configuration||{}).filter(([key])=>!['solutions','area_interesse'].includes(key)).flatMap(([group,value]:any)=>Object.entries(value||{}).filter(([,item])=>item!==null&&item!==''&&(!Array.isArray(item)||item.length)).map(([key,item])=>({label:labels[key]||key.replaceAll('_',' '),value:Array.isArray(item)?item.join(', '):String(item),group:names[group.toUpperCase()]||group.replaceAll('_',' ')})));

export function ToolImplementationPresentation(){const[data,setData]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{const query=new URLSearchParams(location.search),projectId=query.get('projeto_id'),proposalId=query.get('pre_proposta_id');if(!projectId||!proposalId)returnfetch(`/api/tool-implementation?id=${encodeURIComponent(projectId)}`,{cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'Não foi possível abrir a apresentação.');const project=body[0],proposal=(project?.pre_propostas_implantacao||[]).find((item:any)=>item.id===proposalId);if(!project||!proposal)throw new Error('Pré-proposta não encontrada.');setData({project,proposal})}).catch(reason=>setError(reason.message))},[]);if(error)return <main className={styles.presentationState}><h1>Não foi possível abrir a apresentação</h1><p>{error}</p></main>;if(!data)return <main className={styles.presentationState}><p>Preparando apresentação...</p></main>;const{project,proposal}=data,solutions=proposal.configuracao?.solutions||[],configuration=configurationRows(proposal.configuracao);return <div className={styles.presentation}><header><img src={brandLogo} alt="Escala Vendas"/><span>Em validação</span></header><main><small>Solução proposta para</small><h1>{project.empresas?.nome}</h1><p>Configuração inicial preparada a partir das informações fornecidas.</p><section><h2>O que entendemos</h2><p>{proposal.sintese}</p></section><section><h2>Solução recomendada</h2><div className={styles.presentationCards}>{solutions.map((item:any,index:number)=><article key={index}><h3>{item.name||names[item.id]||'Solução'}</h3><p>{item.quantity>1?`Quantidade inicial: ${item.quantity}`:'Incluído na configuração inicial.'}</p></article>)}</div></section>{configuration.length>0&&<section><h2>Configuração da solução</h2><div className={styles.configuration}>{configuration.map((item:any,index:number)=><article key={`${item.group}-${item.label}-${index}`}><small>{item.group}</small><b>{item.label}</b><span>{item.value}</span></article>)}</div></section>}<section><h2>O que será implantado</h2><ul>{(proposal.itens_implantacao||[]).map((item:string)=><li key={item}>{item}</li>)}</ul></section><section className={styles.investment}><article><small>Investimento inicial</small><b>{proposal.financeiro?.investimento_inicial==null?'A validar':money(proposal.financeiro.investimento_inicial)}</b><p>Implantação e configuração da solução</p></article><article><small>Licenças de uso</small><b>{proposal.financeiro?.licencas_mensais==null?'A validar':`${money(proposal.financeiro.licencas_mensais)} / mês`}</b><p>Recursos e licenças utilizados pela solução</p></article></section>{proposal.financeiro?.condicoes&&<section><h2>Condições comerciais</h2><p>{proposal.financeiro.condicoes}</p></section>}</main></div>}
