import {isMaster} from '../../../lib/access';
import {canonicalResource,commercialFingerprint,isStrategicCommercialProject} from '../../../lib/commercialConsolidation';
import {loadGrowthFinancial,saveGrowthFinancial} from '../../../lib/financialContext';

const SUPABASE_URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const headers=()=>({'Content-Type':'application/json',apikey:KEY!,Authorization:`Bearer ${KEY}`});
async function db(path:string,init:RequestInit={}){const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{...headers(),...(init.headers||{})},cache:'no-store'});if(!response.ok)throw new Error(await response.text());const text=await response.text();return text?JSON.parse(text):null}
async function project(id:string){return(await db(`projetos_evolucao?id=eq.${encodeURIComponent(id)}&select=*,projeto_evolucao_recursos(*)&limit=1`))?.[0]}
// A commercial update may live in a new draft row. Publication lineage is
// company-scoped and cannot depend only on the draft UUID.
async function publication(row:any){return(await db(`proposta_publicacoes?empresa_id=eq.${encodeURIComponent(row.empresa_id)}&status=eq.PUBLICADA&select=versao,publicada_em,publicada_por,projeto_evolucao_id,snapshot&order=versao.desc&limit=1`).catch(()=>[]))?.[0]||null}

async function view(row:any){
 if(!row)return null;
 if(!isStrategicCommercialProject(row))return{project_id:row.id,flow:'LEGACY',status:null};
 const [fingerprint,published]=await Promise.all([commercialFingerprint(row),publication(row)]),stored=row.commercial_3_0_fingerprint,snapshot=row.commercial_3_0_snapshot;
 const baseStatus=!snapshot?'PENDENTE':stored!==fingerprint?'DESATUALIZADO':row.commercial_3_0_status||'PENDENTE';
 const publishedFingerprint=published?.snapshot?.commercial_3_0?.fingerprint||null,publishedResourceCount=(published?.snapshot?.commercial_3_0?.resources||[]).length,snapshotResourceCount=(snapshot?.resources||[]).length,resourceIntegrity=!(publishedResourceCount>0&&snapshotResourceCount===0),updatePending=Boolean(published&&baseStatus==='PRONTO'&&resourceIntegrity&&snapshot?.fingerprint&&snapshot.fingerprint!==publishedFingerprint);
 const financial=(await loadGrowthFinancial(db,{companyId:row.empresa_id,projectEvolutionId:row.id}))?.financial||{};
 // After a publication, the live financial row intentionally keeps the prior
 // client version. Consistency of the pending update is therefore checked
 // against the new frozen snapshot, never against the still-published values.
 const comparisonFinancial=published?(snapshot?.financial||{}):financial;
 return{project_id:row.id,project_status:row.status,flow:'ESTRATEGICO_3_0',status:!resourceIntegrity?'RECURSOS_INCONSISTENTES':updatePending?'ATUALIZACAO_PENDENTE':baseStatus,has_publication:Boolean(published),publication_project_id:published?.projeto_evolucao_id||null,publication_version:published?.versao||null,publication_at:published?.publicada_em||null,update_pending:updatePending,resource_integrity:resourceIntegrity,published_resource_count:publishedResourceCount,fingerprint,consolidated_at:row.commercial_3_0_consolidated_at,consolidated_by:row.commercial_3_0_consolidated_by,snapshot,comparison:{implantation:{project:Number(row.valor_implantacao_adicional||0),financial:Number(comparisonFinancial.valor_implantacao||0),ok:Number(row.valor_implantacao_adicional||0)===Number(comparisonFinancial.valor_implantacao||0)},monthly:{project:Number(row.nova_mensalidade||0),financial:Number(comparisonFinancial.valor_mensalidade||0),ok:Number(row.nova_mensalidade||0)===Number(comparisonFinancial.valor_mensalidade||0)},resources:{project:(row.projeto_evolucao_recursos||[]).length,snapshot:snapshot?.resources?.length||0,ok:(row.projeto_evolucao_recursos||[]).length===(snapshot?.resources?.length||0)}}};
}

export async function GET(req:Request){try{if(!await isMaster(req))return Response.json({error:'Acesso exclusivo do Usuário Master.'},{status:403});const url=new globalThis.URL(req.url),empresaId=url.searchParams.get('empresa_id'),projectId=url.searchParams.get('project_id');if(!empresaId&&!projectId)return Response.json({error:'Empresa ou projeto não informado.'},{status:400});const row=projectId?await project(projectId):(await db(`projetos_evolucao?empresa_id=eq.${encodeURIComponent(empresaId!)}&select=*,projeto_evolucao_recursos(*)&order=updated_at.desc&limit=1`))?.[0],consolidation=await view(row);return Response.json({consolidation:consolidation||{flow:'LEGACY'}})}catch(error:any){return Response.json({error:error?.message||'Não foi possível carregar a Consolidação Comercial 3.0.'},{status:500})}}

export async function POST(req:Request){try{
 if(!await isMaster(req))return Response.json({error:'Acesso exclusivo do Usuário Master.'},{status:403});
 const body=await req.json(),row=await project(String(body.project_id||''));
 if(!row)return Response.json({error:'Projeto de Evolução não localizado.'},{status:404});
 if(row.empresa_id!==body.empresa_id)return Response.json({error:'O projeto não pertence à empresa informada.'},{status:409});
 if(row.status!=='Rascunho')return Response.json({error:'Somente um Projeto em Rascunho pode ser consolidado.'},{status:409});
 if(!isStrategicCommercialProject(row))return Response.json({error:'Este projeto utiliza o fluxo Legacy e não exige Consolidação Comercial 3.0.'},{status:409});
 const previous=await publication(row),currentResources=row.projeto_evolucao_recursos||[],previousResources=previous?.snapshot?.commercial_3_0?.resources||[];
 if(!currentResources.length&&previousResources.length)return Response.json({error:`A atualização foi bloqueada porque o projeto atual não possui recursos, enquanto a versão publicada possui ${previousResources.length}. Revise os vínculos canônicos da Composição Comercial 3.0 antes de consolidar.`,code:'EMPTY_RESOURCE_REGRESSION'},{status:409});
 const [company,financialContext,parameters,configuration]=await Promise.all([db(`empresas?id=eq.${encodeURIComponent(row.empresa_id)}&select=*&limit=1`).then(x=>x?.[0]),loadGrowthFinancial(db,{companyId:row.empresa_id,projectEvolutionId:row.id}),db('parametros_comerciais?select=*&limit=1').then(x=>x?.[0]||{}),db('configuracoes?select=*&limit=1').then(x=>x?.[0]||{})]),financial:any=financialContext?.financial||{};
 const now=new Date().toISOString(),fingerprint=await commercialFingerprint(row),resources=currentResources.map(canonicalResource),snapshot={version:'3.0',source:'PROJETO_EVOLUCAO',fingerprint,consolidated_at:now,consolidated_by:String(body.usuario||'Usuário Master'),project:{projeto_evolucao_id:row.id,nome:row.nome,descricao:row.descricao,objetivo:row.objetivo,direcao_estrategica:row.checklist?.strategic_context?.strategic_direction||null,prioridade:row.checklist?.strategic_context?.primary_priority||null,origem:'ESTRATEGICO_3_0',plan_version:row.checklist?.strategic_context?.plan_version||null},financial:{valor_implantacao:Number(row.valor_implantacao_adicional||0),modalidade_implantacao:row.implantacao_modalidade,valor_mensalidade:Number(row.nova_mensalidade||0),desconto_recorrente:Number(row.desconto_recorrente||0),prazo_contratual:Number(financial.prazo_contratual||parameters.prazo_contratual||12),validade_proposta:Number(financial.validade_proposta||parameters.validade_proposta||15),desconto_pix:Number(financial.desconto_pix??parameters.desconto_pix??0)},resources,document:{company:{razao_social:company?.razao_social||null,nome_fantasia:company?.nome_fantasia||company?.nome||null,cpf_cnpj:company?.cpf_cnpj||null,endereco:company?.endereco||null,cidade:company?.cidade||null,estado:company?.estado||null,cep:company?.cep||null},formalizacao:row.formalizacao,prazo_contratual:Number(financial.prazo_contratual||parameters.prazo_contratual||12),reajuste_indice:parameters.reajuste_indice||'IPCA',condicoes_comerciais:{modalidade_implantacao:row.implantacao_modalidade,desconto_pix:Number(financial.desconto_pix??parameters.desconto_pix??0)},clausulas_configuradas:Boolean(configuration)}};
 const financialPayload={empresa_id:row.empresa_id,valor_implantacao:snapshot.financial.valor_implantacao,valor_mensalidade:snapshot.financial.valor_mensalidade,prazo_contratual:snapshot.financial.prazo_contratual,validade_proposta:snapshot.financial.validade_proposta,desconto_pix:snapshot.financial.desconto_pix,status:financial.status||'Em elaboração',updated_at:now};
 if(!previous)await saveGrowthFinancial(db,{companyId:row.empresa_id,projectEvolutionId:row.id,payload:financialPayload});
 await db(`projetos_evolucao?id=eq.${encodeURIComponent(row.id)}&empresa_id=eq.${encodeURIComponent(row.empresa_id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({commercial_3_0_status:'PRONTO',commercial_3_0_snapshot:snapshot,commercial_3_0_fingerprint:fingerprint,commercial_3_0_consolidated_at:now,commercial_3_0_consolidated_by:String(body.usuario||'Usuário Master')})});
 return Response.json({ok:true,message:previous?'Consolidação concluída. A atualização está pendente de envio explícito ao cliente.':'Consolidação Comercial 3.0 concluída. Projeto pronto para publicação.',consolidation:await view(await project(row.id))});
 }catch(error:any){return Response.json({error:error?.message||'Não foi possível consolidar o Projeto.'},{status:500})}}
