import type { CommercialSolution } from './commercialPricingResolver';
import {NIMBLE_STRUCTURE_SOURCE,resolveNimbleStructure,usesNimbleStructure} from './nimbleStructure';
export type DependencyRequirement = 'OBRIGATORIA' | 'OPCIONAL';
export type CommercialDependencyRule = { tipo:'solucao'; recurso_id:string; obrigatoriedade:DependencyRequirement; ordem:number; ativo:boolean };
export type ResolvedCommercialDependency = { recurso_id:string; solution:CommercialSolution; parent_solution_ids:string[]; dependency_source:string[]; obrigatoriedade:DependencyRequirement; ordem:number };
const list=(value:unknown):any[]=>Array.isArray(value)?value:[];
export function commercialDependencyRules(solution:CommercialSolution,catalog:CommercialSolution[]=[]):CommercialDependencyRule[]{const configured=list(solution.dependencias_estruturadas).flatMap((item:any)=>item?.tipo!=='solucao'||typeof item.recurso_id!=='string'||item.ativo===false?[]:[{tipo:'solucao' as const,recurso_id:item.recurso_id,obrigatoriedade:item.obrigatoriedade==='OPCIONAL'?'OPCIONAL' as const:'OBRIGATORIA' as const,ordem:Math.max(0,Number(item.ordem)||0),ativo:true}]);const structural=usesNimbleStructure(solution)?resolveNimbleStructure(catalog).map((item,index)=>({tipo:'solucao' as const,recurso_id:item.id,obrigatoriedade:'OBRIGATORIA' as const,ordem:index+1,ativo:true})):[];return[...configured,...structural].filter((rule,index,rules)=>rules.findIndex(item=>item.recurso_id===rule.recurso_id)===index);}
/** Resolve somente relações cadastradas na Biblioteca, sem regras por nome ou código. */
export function resolveCommercialDependencies(input:{selectedSolutionIds:string[];catalog:CommercialSolution[]}):ResolvedCommercialDependency[]{
 const catalog=new Map(input.catalog.map(item=>[item.id,item])),roots=[...new Set(input.selectedSolutionIds)],resolved=new Map<string,{solution:CommercialSolution;parents:Set<string>;sources:Set<string>;required:boolean;order:number}>();
 const visit=(currentId:string,rootId:string,path:string[])=>{const current=catalog.get(currentId);if(!current)return;const nextPath=[...path,currentId];for(const rule of commercialDependencyRules(current,input.catalog)){const dependency=catalog.get(rule.recurso_id);if(!dependency||dependency.ativo===false)continue;if(nextPath.includes(dependency.id))throw new Error(`Dependência circular na Biblioteca: ${[...nextPath,dependency.id].map(id=>catalog.get(id)?.nome||id).join(' → ')}.`);const value=resolved.get(dependency.id)||{solution:dependency,parents:new Set<string>(),sources:new Set<string>(),required:false,order:rule.ordem};value.parents.add(rootId);value.sources.add(usesNimbleStructure(current)&&resolveNimbleStructure(input.catalog).some(item=>item.id===dependency.id)?`${NIMBLE_STRUCTURE_SOURCE}:${current.id}:${dependency.id}`:`${current.id}:${dependency.id}`);value.required||=rule.obrigatoriedade==='OBRIGATORIA';value.order=Math.min(value.order,rule.ordem);resolved.set(dependency.id,value);visit(dependency.id,rootId,nextPath)}};
 roots.forEach(root=>visit(root,root,[]));return[...resolved.values()].map(value=>({recurso_id:value.solution.id,solution:value.solution,parent_solution_ids:[...value.parents],dependency_source:[...value.sources],obrigatoriedade:value.required?'OBRIGATORIA':'OPCIONAL',ordem:value.order})).sort((a,b)=>a.ordem-b.ordem||a.solution.nome.localeCompare(b.solution.nome,'pt-BR'));
}
