const normalize=(value:any)=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const list=(value:any)=>Array.isArray(value)?value:[];

export type InvestigationQuestion={id:string;text:string;source_question:string;source:'DIAGNOSTIC_INVESTIGATION'};
export type PreparedQuestion={id:string;text:string;source:'DIAGNOSTIC_INVESTIGATION'|'CONSULTANT'};
const scored=(answer:any)=>answer?.resposta_numerica===null||answer?.resposta_numerica===undefined?undefined:Number(answer.resposta_numerica);
const stableKey=(value:string)=>normalize(value).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120);
const stableHash=(value:string)=>{let hash=2166136261;for(const char of normalize(value))hash=Math.imul(hash^char.charCodeAt(0),16777619);return(hash>>>0).toString(36)};
const stableIdentity=(prefix:string,value:string)=>`${prefix}:${stableKey(value).slice(0,72)}:${stableHash(value)}`;
export const normalizedQuestion=(value:any)=>normalize(value).replace(/[^a-z0-9]+/g,' ').trim();

type ReadingRule={match:string[];topic:string;low:string;attention:string;structured:string;risk:string;question:string;hypothesis:string};

const rules:ReadingRule[]=[
 {match:['quais canais vem'],topic:'Origem das oportunidades',low:'Não identifica de quais canais vêm as oportunidades.',attention:'A origem das oportunidades é identificada apenas parcialmente.',structured:'A origem das oportunidades é identificada de forma consistente.',risk:'A falta de identificação da origem pode direcionar esforço e investimento para canais pouco eficientes.',question:'Como vocês identificam atualmente quais canais originam as melhores oportunidades?',hypothesis:'A geração de oportunidades pode estar limitada pela baixa visibilidade sobre os canais de origem.'},
 {match:['acoes geram melhores resultados'],topic:'Mensuração de resultados',low:'Não identifica quais ações geram melhores resultados.',attention:'Identifica apenas parcialmente quais ações geram melhores resultados.',structured:'Identifica e compara as ações que geram melhores resultados.',risk:'A ausência de mensuração dificulta decidir onde concentrar investimento comercial e de marketing.',question:'Como vocês identificam quais canais ou ações trazem os melhores resultados?',hypothesis:'A baixa mensuração pode dificultar decisões sobre onde concentrar esforços e investimentos.'},
 {match:['cliente ideal'],topic:'Cliente ideal',low:'Cliente ideal ainda pouco definido.',attention:'O perfil de cliente ideal está definido apenas parcialmente.',structured:'O perfil de cliente ideal está claramente definido.',risk:'A falta de clareza sobre o cliente ideal pode gerar contatos com baixa aderência ao negócio.',question:'Quais critérios definem hoje o cliente ideal da empresa?',hypothesis:'A qualidade das oportunidades pode estar relacionada à definição ainda parcial do cliente ideal.'},
 {match:['custo por oportunidade'],topic:'Custo de aquisição',low:'Não mede o custo por oportunidade.',attention:'O custo por oportunidade é acompanhado apenas parcialmente.',structured:'O custo por oportunidade é acompanhado de forma consistente.',risk:'Sem conhecer o custo por oportunidade, a empresa pode investir sem avaliar a eficiência da aquisição.',question:'Como vocês calculam atualmente o custo de geração de cada oportunidade?',hypothesis:'A ausência de mensuração do custo pode limitar decisões de investimento em aquisição.'},
 {match:['informacoes para iniciar'],topic:'Qualidade dos contatos',low:'Os contatos chegam sem informações suficientes para iniciar o atendimento.',attention:'Os contatos chegam com informações apenas parciais.',structured:'Os contatos chegam com informações adequadas para iniciar o atendimento.',risk:'Informações insuficientes podem atrasar o atendimento e prejudicar a qualificação.',question:'Quais informações chegam junto com um novo contato comercial?',hypothesis:'A velocidade e a qualidade do atendimento podem estar sendo afetadas por informações iniciais insuficientes.'},
 {match:['volume de novas oportunidades'],topic:'Volume de oportunidades',low:'O volume de novas oportunidades está abaixo da necessidade comercial.',attention:'O volume de oportunidades atende apenas parcialmente à necessidade comercial.',structured:'O volume de oportunidades é consistente com as metas comerciais.',risk:'Um volume insuficiente de oportunidades pode comprometer o atingimento das metas de vendas.',question:'Qual volume de novas oportunidades seria necessário para sustentar as metas atuais?',hypothesis:'A meta de crescimento pode estar limitada pelo volume atual de novas oportunidades.'},
 {match:['forma previsivel'],topic:'Previsibilidade de aquisição',low:'Baixa previsibilidade na geração de oportunidades.',attention:'A geração de oportunidades é apenas parcialmente previsível.',structured:'A geração de oportunidades ocorre de forma previsível.',risk:'A baixa previsibilidade de aquisição pode comprometer as metas de crescimento comercial.',question:'O que hoje impede a empresa de gerar oportunidades com maior previsibilidade?',hypothesis:'A empresa aparenta depender de fontes pouco previsíveis para gerar novas oportunidades.'},
 {match:['estrategia ativa'],topic:'Estratégia de aquisição',low:'Não existe uma estratégia ativa e contínua para gerar novas oportunidades.',attention:'A estratégia de aquisição ocorre por ações isoladas, sem processo contínuo.',structured:'Existe estratégia ativa e contínua para gerar novas oportunidades.',risk:'A ausência de estratégia ativa pode tornar o crescimento dependente de indicações ou acontecimentos ocasionais.',question:'Quais ações de geração de oportunidades são executadas de forma contínua?',hypothesis:'A geração comercial pode estar dependente de ações pontuais em vez de uma estratégia contínua.'},
 {match:['aproveita sua base atual'],topic:'Base de contatos',low:'A base atual de contatos e clientes não é utilizada para gerar novas oportunidades.',attention:'A base atual é utilizada apenas parcialmente para gerar novas oportunidades.',structured:'A base atual é trabalhada regularmente para gerar novas oportunidades.',risk:'O baixo aproveitamento da base pode deixar oportunidades de relacionamento e reativação sem exploração.',question:'Como a empresa trabalha hoje sua base de contatos e clientes para gerar novas oportunidades?',hypothesis:'Existe potencial de geração de oportunidades na base atual que merece validação.'},
 {match:['conversas ficam centralizadas'],topic:'Centralização do atendimento',low:'As conversas comerciais não ficam centralizadas.',attention:'As conversas são centralizadas apenas parcialmente.',structured:'As conversas comerciais ficam centralizadas.',risk:'Conversas dispersas podem causar perda de contexto e continuidade no atendimento.',question:'Onde ficam registradas as conversas realizadas com cada oportunidade?',hypothesis:'A dispersão das conversas pode estar dificultando a continuidade do atendimento.'},
 {match:['oportunidade tem responsavel'],topic:'Responsabilidade comercial',low:'As oportunidades não possuem responsáveis claramente definidos.',attention:'A responsabilidade pelas oportunidades é definida apenas parcialmente.',structured:'Cada oportunidade possui responsável definido.',risk:'A ausência de responsável pode gerar atrasos, duplicidade ou oportunidades sem atendimento.',question:'Como é definido o responsável por cada nova oportunidade?',hypothesis:'O acompanhamento pode estar sendo prejudicado por responsabilidades pouco claras.'},
 {match:['processo de distribuicao'],topic:'Distribuição de oportunidades',low:'Não existe processo definido para distribuir oportunidades.',attention:'A distribuição acontece com critérios apenas parciais.',structured:'Existe processo definido para distribuir oportunidades.',risk:'Uma distribuição sem padrão pode atrasar o primeiro contato e desequilibrar a equipe.',question:'Como as novas oportunidades são distribuídas entre as pessoas da equipe?',hypothesis:'A velocidade de atendimento pode estar relacionada à ausência de um processo de distribuição.'},
 {match:['historico do cliente'],topic:'Histórico do cliente',low:'A equipe não visualiza o histórico completo do cliente.',attention:'O histórico do cliente está disponível apenas parcialmente.',structured:'A equipe visualiza o histórico do cliente.',risk:'Sem histórico acessível, o atendimento pode ser repetitivo, desconectado ou sem contexto.',question:'Que histórico a equipe consegue consultar antes de atender um contato?',hypothesis:'A falta de histórico pode estar reduzindo a qualidade e a continuidade do atendimento.'},
 {match:['padrao para registrar'],topic:'Padronização de registros',low:'Não existe padrão para registrar informações comerciais.',attention:'Os registros seguem um padrão apenas parcial.',structured:'Existe padrão consistente para registrar informações.',risk:'Registros sem padrão podem gerar informações incompletas e dificultar análises futuras.',question:'Quais informações a equipe deve registrar obrigatoriamente em cada atendimento?',hypothesis:'A baixa padronização dos registros pode estar comprometendo a visibilidade da operação.'},
 {match:['aguarda retorno'],topic:'Controle de retornos',low:'Não existe visibilidade confiável sobre quem aguarda retorno.',attention:'O controle de retornos é apenas parcialmente estruturado.',structured:'Existe visibilidade clara sobre quem aguarda retorno.',risk:'Oportunidades podem ser perdidas por falta de acompanhamento e retorno.',question:'Como vocês controlam atualmente os contatos que aguardam retorno?',hypothesis:'Perdas de oportunidades podem estar relacionadas a um controle de retornos pouco estruturado.'},
 {match:['todas as oportunidades em andamento'],topic:'Visibilidade do funil',low:'Não existe visão completa das oportunidades em andamento.',attention:'A visão das oportunidades em andamento é apenas parcial.',structured:'Existe visão completa das oportunidades em andamento.',risk:'Sem visão do funil, negociações podem ficar paradas sem que o gestor perceba.',question:'Onde o gestor consulta todas as oportunidades que estão em andamento?',hypothesis:'A baixa visibilidade do funil pode estar dificultando decisões e priorização.'},
 {match:['etapas comerciais definidas'],topic:'Etapas comerciais',low:'Não existem etapas comerciais claramente definidas.',attention:'As etapas comerciais estão definidas apenas parcialmente.',structured:'As etapas comerciais estão claramente definidas.',risk:'Sem etapas claras, a equipe pode conduzir negociações de formas diferentes e sem próximo passo definido.',question:'Quais etapas uma oportunidade percorre desde a entrada até a venda?',hypothesis:'A inconsistência na condução das oportunidades pode estar relacionada à ausência de etapas claras.'},
 {match:['oportunidades paradas'],topic:'Oportunidades paradas',low:'A empresa não identifica oportunidades paradas com segurança.',attention:'Oportunidades paradas são identificadas apenas parcialmente.',structured:'A empresa identifica e acompanha oportunidades paradas.',risk:'Oportunidades podem esfriar ou ser perdidas sem uma ação de retomada.',question:'Como vocês identificam e retomam oportunidades que ficaram paradas?',hypothesis:'Parte das perdas pode estar relacionada a oportunidades paradas sem rotina de retomada.'},
 {match:['relatorios manuais'],topic:'Visibilidade gerencial',low:'O acompanhamento do gestor depende de levantamentos manuais.',attention:'A visão gerencial ainda depende parcialmente de relatórios manuais.',structured:'O gestor acompanha a operação sem depender de relatórios manuais.',risk:'A dependência de levantamentos manuais pode atrasar decisões e gerar informações desatualizadas.',question:'Quanto esforço é necessário hoje para o gestor obter uma visão da operação?',hypothesis:'A tomada de decisão pode estar sendo atrasada pela dependência de consolidações manuais.'},
 {match:['qualificar oportunidades'],topic:'Qualificação',low:'Não existe processo consistente para qualificar oportunidades.',attention:'A qualificação acontece com critérios apenas parciais.',structured:'Existe processo consistente para qualificar oportunidades.',risk:'Sem qualificação, a equipe pode investir tempo em contatos com baixa probabilidade de compra.',question:'Quais critérios a equipe utiliza para qualificar uma oportunidade?',hypothesis:'A conversão pode estar sendo afetada por critérios de qualificação pouco claros.'},
 {match:['rotina de acompanhamento'],topic:'Rotina de acompanhamento',low:'Não existe rotina consistente de acompanhamento comercial.',attention:'A rotina de acompanhamento é apenas parcialmente estruturada.',structured:'Existe rotina consistente de acompanhamento comercial.',risk:'A ausência de rotina pode deixar oportunidades sem contato no momento adequado.',question:'Qual rotina a equipe segue para acompanhar oportunidades abertas?',hypothesis:'Perdas comerciais podem estar relacionadas a uma rotina de acompanhamento inconsistente.'},
 {match:['motivos de perda'],topic:'Motivos de perda',low:'Os motivos de perda não são registrados.',attention:'Os motivos de perda são registrados apenas parcialmente.',structured:'Os motivos de perda são registrados e acompanhados.',risk:'Sem motivos de perda, problemas recorrentes podem continuar sem correção.',question:'Como a empresa registra e analisa os motivos pelos quais perde vendas?',hypothesis:'A repetição de perdas pode estar relacionada à ausência de aprendizado estruturado sobre seus motivos.'},
 {match:['mede a conversao'],topic:'Conversão comercial',low:'A conversão de oportunidades em vendas não é medida.',attention:'A conversão é medida apenas parcialmente.',structured:'A conversão de oportunidades em vendas é medida.',risk:'Sem medir conversão, a empresa não consegue localizar com precisão onde as vendas são perdidas.',question:'Qual é a conversão atual de oportunidades em vendas e como ela é calculada?',hypothesis:'A evolução comercial pode estar limitada pela baixa visibilidade sobre a conversão.'},
 {match:['proximo passo de cada negociacao'],topic:'Próximo passo',low:'A equipe não possui clareza sobre o próximo passo de cada negociação.',attention:'O próximo passo é definido apenas em parte das negociações.',structured:'A equipe conhece o próximo passo de cada negociação.',risk:'Negociações podem ficar sem avanço quando o próximo passo não está definido.',question:'A equipe utiliza algum processo para registrar o próximo passo de cada oportunidade?',hypothesis:'Negociações paradas podem estar relacionadas à ausência de próximos passos claros.'},
 {match:['primeira resposta'],topic:'Tempo de primeira resposta',low:'O tempo de primeira resposta é alto ou não possui padrão definido.',attention:'O tempo de primeira resposta requer atenção.',structured:'A primeira resposta ocorre com boa agilidade.',risk:'A demora na primeira resposta pode reduzir o interesse e a conversão dos novos contatos.',question:'O que determina hoje o tempo necessário para responder um novo contato?',hypothesis:'A conversão inicial pode estar sendo afetada pelo tempo de primeira resposta.'},
 {match:['acompanha indicadores regularmente'],topic:'Acompanhamento de indicadores',low:'Os indicadores comerciais não são acompanhados regularmente.',attention:'Os indicadores são acompanhados apenas ocasionalmente.',structured:'Os indicadores comerciais são acompanhados regularmente.',risk:'Sem acompanhamento regular, desvios podem ser percebidos tarde demais.',question:'Com que frequência os indicadores comerciais são analisados?',hypothesis:'A tomada de decisão pode estar ocorrendo sem uma rotina consistente de indicadores.'},
 {match:['clareza de metas'],topic:'Metas comerciais',low:'Não existe clareza suficiente sobre metas e resultados.',attention:'As metas e resultados estão definidos apenas parcialmente.',structured:'Existe clareza sobre metas e resultados.',risk:'Metas pouco claras podem dificultar a priorização e a avaliação do desempenho.',question:'Quais metas comerciais estão definidas e como a equipe acompanha sua evolução?',hypothesis:'A execução comercial pode estar sendo prejudicada por metas pouco claras.'},
 {match:['prever oportunidades e vendas'],topic:'Previsibilidade comercial',low:'A empresa não consegue prever oportunidades e vendas com segurança.',attention:'A previsibilidade comercial é apenas parcial.',structured:'A empresa consegue prever oportunidades e vendas.',risk:'A baixa previsibilidade pode dificultar planejamento, contratação e decisões de investimento.',question:'Quais dados são utilizados hoje para prever oportunidades e vendas futuras?',hypothesis:'O planejamento de crescimento pode estar limitado pela baixa previsibilidade comercial.'},
 {match:['sem depender do empresario'],topic:'Dependência do empresário',low:'O crescimento ainda depende fortemente da atuação direta do empresário.',attention:'A operação ainda depende parcialmente do empresário.',structured:'A operação consegue crescer sem depender diretamente do empresário.',risk:'A dependência do empresário pode limitar escala, velocidade e continuidade da operação.',question:'Quais decisões ou atividades comerciais ainda dependem diretamente do empresário?',hypothesis:'A capacidade de escala pode estar limitada pela dependência da atuação direta do empresário.'},
 {match:['usa dados para tomar'],topic:'Decisões orientadas por dados',low:'As decisões comerciais não utilizam dados de forma consistente.',attention:'Os dados apoiam apenas parte das decisões comerciais.',structured:'As decisões comerciais são orientadas por dados.',risk:'Decisões sem dados podem aumentar erros de prioridade e investimento.',question:'Quais dados são consultados antes de uma decisão comercial importante?',hypothesis:'Decisões de crescimento podem estar sendo tomadas com evidências insuficientes.'},
 {match:['indicadores comerciais em um unico lugar'],topic:'Centralização de indicadores',low:'Os indicadores estão dispersos ou não são acompanhados.',attention:'Os indicadores estão centralizados apenas parcialmente.',structured:'Os principais indicadores estão centralizados e atualizados.',risk:'Indicadores dispersos podem gerar análises incompletas e decisões tardias.',question:'Onde os principais indicadores comerciais são consultados atualmente?',hypothesis:'A baixa centralização dos indicadores pode estar dificultando uma visão confiável da operação.'},
 {match:['rotina de gestao'],topic:'Rotina de gestão',low:'Não existe rotina consistente para analisar resultados e definir melhorias.',attention:'A rotina de análise e melhoria acontece apenas ocasionalmente.',structured:'Existe rotina estruturada de análise e acompanhamento das melhorias.',risk:'Sem rotina de gestão, problemas podem se repetir sem responsáveis ou ações corretivas.',question:'Como os resultados são analisados e transformados em ações de melhoria?',hypothesis:'A evolução dos resultados pode estar limitada pela ausência de uma rotina estruturada de gestão.'}
];

export function diagnosticReading(question:string,value:number|undefined){
 if(value===undefined)return{topic:'Não informado',interpretation:'Não informado.',risk:'Não informado.',investigation:'Não informado.',hypothesis:'Não informado.'};
 const normalized=normalize(question),rule=rules.find(item=>item.match.some(term=>normalized.includes(term)));
 if(!rule){const subject=String(question||'Esta dimensão').replace(/[?!.]+$/,'');return{topic:'Dimensão avaliada',interpretation:value<=1?`${subject}: situação muito frágil.`:value===2?`${subject}: situação parcialmente estruturada.`:`${subject}: situação estruturada.`,risk:`A fragilidade identificada em “${subject.toLowerCase()}” merece acompanhamento.`,investigation:`Como funciona atualmente: ${subject.toLowerCase()}?`,hypothesis:`A resposta sobre “${subject.toLowerCase()}” sugere um ponto que merece validação na reunião.`}}
 return{topic:rule.topic,interpretation:value<=1?rule.low:value===2?rule.attention:rule.structured,risk:rule.risk,investigation:rule.question,hypothesis:rule.hypothesis};
}

export function investigationQuestions(answers:any[]):InvestigationQuestion[]{
 const ranked=list(answers).map((item:any,index:number)=>({item,index,value:scored(item)})).filter(entry=>entry.value!==undefined).sort((left,right)=>Number(left.value)-Number(right.value)||left.index-right.index).slice(0,6);
 const seen=new Set<string>(),result:InvestigationQuestion[]=[];
 for(const entry of ranked){
  if(Number(entry.value)>2)continue;
  const text=diagnosticReading(String(entry.item?.pergunta||''),entry.value).investigation,key=normalizedQuestion(text);
  if(!key||key===normalizedQuestion('Não informado.')||seen.has(key))continue;
  seen.add(key);result.push({id:stableIdentity('investigation',String(entry.item?.pergunta||text)),text,source_question:String(entry.item?.pergunta||''),source:'DIAGNOSTIC_INVESTIGATION'});
  if(result.length===4)break;
 }
 return result;
}

export function preparedQuestionsFromText(value:any,existing:any[]=[]):PreparedQuestion[]{
 const lines=String(value||'').split(/\r?\n/).map(item=>item.replace(/^[-•*\d.)\s]+/,'').trim()).filter(Boolean),previous=list(existing).filter(item=>item&&String(item.text||'').trim()),used=new Set<string>(),seen=new Set<string>();
 return lines.flatMap((text,index)=>{
  const normalized=normalizedQuestion(text);if(!normalized||seen.has(normalized))return[];seen.add(normalized);
  let match=previous.find(item=>!used.has(String(item.id))&&normalizedQuestion(item.text)===normalized);
  if(!match){const positional=previous[index];if(positional&&!used.has(String(positional.id)))match=positional}
  const id=String(match?.id||stableIdentity('consultant',text)),source=match?.source==='DIAGNOSTIC_INVESTIGATION'?'DIAGNOSTIC_INVESTIGATION':'CONSULTANT';used.add(id);
  return[{id,text,source} as PreparedQuestion];
 });
}

export function officialDiagnosticPriority(data:any){
 const direct=String(data?.menor_pilar||'').trim();if(direct)return direct;
 const radar=list(data?.resultados_pilares).filter(item=>Number.isFinite(Number(item.percentual))).sort((a,b)=>Number(a.percentual)-Number(b.percentual));
 return String(radar[0]?.pilar||data?.relatorio_snapshot?.prioridades?.[0]?.label||'').trim()||'Não informado';
}

export function officialPriorityRanking(data:any){
 const official=officialDiagnosticPriority(data),radar=list(data?.resultados_pilares).map((item,index)=>({label:String(item.pilar),percent:Number(item.percentual)||0,index})).sort((a,b)=>a.percent-b.percent||a.index-b.index),report=list(data?.relatorio_snapshot?.prioridades).map((item,index)=>({label:String(item.label||item.pilar||item),percent:Number(item.percent)||0,index})),source=radar.length?radar:report,seen=new Set<string>(),ordered=[{label:official,percent:source.find(item=>normalize(item.label)===normalize(official))?.percent||0,index:-1},...source].filter(item=>{const key=normalize(item.label);if(!key||seen.has(key))return false;seen.add(key);return true;});return ordered.slice(0,3);
}
