export const pillars=[
{id:'atrair',label:'Atrair',questions:['Sua empresa sabe de quais canais vêm as oportunidades?','Identifica quais ações geram melhores resultados?','Existe definição do cliente ideal?','Mede o custo por oportunidade?','Os contatos têm informações para iniciar o atendimento?']},
{id:'organizar',label:'Organizar',questions:['As conversas ficam centralizadas?','Cada oportunidade tem responsável?','Existe processo de distribuição?','A equipe vê o histórico do cliente?','Há padrão para registrar informações?']},
{id:'acompanhar',label:'Acompanhar',questions:['É possível saber quem aguarda retorno?','Visualiza todas as oportunidades em andamento?','Existem etapas comerciais definidas?','Identifica oportunidades paradas?','O gestor acompanha sem relatórios manuais?']},
{id:'converter',label:'Converter',questions:['Existe processo para qualificar oportunidades?','Existe rotina de acompanhamento?','Registra motivos de perda?','Mede a conversão em vendas?','A equipe sabe o próximo passo de cada negociação?']},
{id:'crescer',label:'Crescer',questions:['Acompanha indicadores regularmente?','Existe clareza de metas e resultados?','Consegue prever oportunidades e vendas?','A operação cresce sem depender do empresário?','Usa dados para tomar decisões?']}];
export const openQuestions=['Qual é hoje o maior desafio comercial da empresa?','Onde você acredita que mais oportunidades são perdidas?','O que mais preocupa você na operação comercial atualmente?','Qual resultado deseja alcançar nos próximos seis meses?','O que mudaria se tivesse mais controle e previsibilidade?'];
export const recs={atrair:['Revisar canais de aquisição','Definir o perfil de cliente ideal','Acompanhar a origem das oportunidades'],organizar:['Centralizar informações','Definir responsáveis','Padronizar registros'],acompanhar:['Criar etapas comerciais','Definir rotina de retorno','Identificar oportunidades paradas'],converter:['Estruturar qualificação','Registrar motivos de perda','Acompanhar a conversão'],crescer:['Definir indicadores e metas','Criar rotina de análise','Reduzir dependência do empresário']} as Record<string,string[]>;
export type Answers=Record<string,number>;
export function maturity(p:number){if(p<=20)return['Nível 1 — Operação sem visibilidade','As oportunidades existem, mas falta processo para acompanhar o que acontece.'];if(p<=40)return['Nível 2 — Operação reativa','A empresa depende de esforço manual, memória e ações isoladas.'];if(p<=60)return['Nível 3 — Operação em organização','Existem controles, mas ainda há falhas de acompanhamento e padronização.'];if(p<=80)return['Nível 4 — Operação controlada','Há organização e visibilidade para acompanhar a maioria das oportunidades.'];return['Nível 5 — Operação preparada para crescer','Há processos, indicadores e capacidade de crescer com previsibilidade.']}
export function calculate(a:Answers){const results=pillars.map(p=>{const score=p.questions.reduce((s,_,i)=>s+(a[`${p.id}-${i}`]??0),0);return{...p,score,percent:score*5}}),total=results.reduce((s,p)=>s+p.score,0),ordered=[...results].sort((a,b)=>a.percent-b.percent);return{results,total,percent:total,maturity:maturity(total),lowest:ordered[0],highest:ordered[4],difference:ordered[4].percent-ordered[0].percent,priorities:ordered.slice(0,3)}}

