export const pillars=[
{id:'atrair',label:'Atrair',questions:['Sua empresa sabe de quais canais vêm as oportunidades?','Identifica quais ações geram melhores resultados?','Existe definição do cliente ideal?','Mede o custo por oportunidade?','Os contatos têm informações para iniciar o atendimento?']},
{id:'organizar',label:'Organizar',questions:['As conversas ficam centralizadas?','Cada oportunidade tem responsável?','Existe processo de distribuição?','A equipe vê o histórico do cliente?','Há padrão para registrar informações?']},
{id:'acompanhar',label:'Acompanhar',questions:['É possível saber quem aguarda retorno?','Visualiza todas as oportunidades em andamento?','Existem etapas comerciais definidas?','Identifica oportunidades paradas?','O gestor acompanha sem relatórios manuais?']},
{id:'converter',label:'Converter',questions:['Existe processo para qualificar oportunidades?','Existe rotina de acompanhamento?','Registra motivos de perda?','Mede a conversão em vendas?','A equipe sabe o próximo passo de cada negociação?']},
{id:'crescer',label:'Crescer',questions:['Acompanha indicadores regularmente?','Existe clareza de metas e resultados?','Consegue prever oportunidades e vendas?','A operação cresce sem depender do empresário?','Usa dados para tomar decisões?']}];
export const openQuestions=['Qual é hoje o maior desafio comercial da empresa?','Onde você acredita que mais oportunidades são perdidas?','O que mais preocupa você na operação comercial atualmente?','Qual resultado deseja alcançar nos próximos seis meses?','O que mudaria se tivesse mais controle e previsibilidade?'];
export type Answers=Record<string,number>;
type Result={id:string;label:string;score:number;percent:number};
const intelligence:Record<string,{reading:string;diagnosis:string;impact:string;recommendation:string;benefit:string;actions:string[]}>= {
atrair:{reading:'A operação precisa aumentar a clareza sobre como as oportunidades são geradas. Sem distinguir origem, qualidade e perfil ideal, o crescimento tende a consumir mais esforço e orçamento do que o necessário.',diagnosis:'A empresa recebe oportunidades, mas ainda não transforma a aquisição em um processo mensurável e replicável.',impact:'Recursos podem ser direcionados a canais pouco produtivos e contatos sem aderência ao negócio.',recommendation:'Mapear a origem de cada oportunidade, definir o cliente ideal e comparar volume, qualidade e custo por canal.',benefit:'Mais oportunidades qualificadas, menor desperdício e decisões de investimento mais seguras.',actions:['Mapear todos os canais de entrada','Definir o perfil de cliente ideal','Criar registro de origem e qualidade']},
organizar:{reading:'O principal desafio está na organização da operação. Informações dispersas e responsabilidades pouco claras dificultam o controle e aumentam a dependência da memória da equipe.',diagnosis:'A operação funciona, mas o conhecimento e os registros ainda não seguem um padrão único.',impact:'Oportunidades podem ser duplicadas, esquecidas ou atendidas sem contexto suficiente.',recommendation:'Centralizar informações, definir responsáveis e padronizar os registros essenciais de cada contato.',benefit:'Mais controle, continuidade no atendimento e menor perda por falhas internas.',actions:['Centralizar informações comerciais','Definir responsáveis por oportunidade','Padronizar registros e etapas']},
acompanhar:{reading:'A empresa gera e organiza oportunidades, mas perde visibilidade durante o acompanhamento. O maior ganho virá de saber quem precisa de retorno, qual negociação está parada e qual deve ser o próximo passo.',diagnosis:'Faltam rotinas e sinais claros para acompanhar oportunidades ao longo do processo.',impact:'Boas oportunidades podem esfriar por ausência de retorno ou falta de atenção no momento certo.',recommendation:'Implantar etapas comerciais, rotina de retornos e revisão periódica das oportunidades paradas.',benefit:'Menos esquecimentos, mais velocidade comercial e maior aproveitamento da demanda existente.',actions:['Definir etapas comerciais visíveis','Criar rotina diária de retornos','Revisar oportunidades paradas semanalmente']},
converter:{reading:'O gargalo está na transformação de oportunidades em vendas. A empresa precisa tornar qualificação, próximos passos e motivos de perda parte de um processo claro e acompanhado.',diagnosis:'As negociações avançam mais pela experiência individual do que por um método comercial consistente.',impact:'A conversão oscila, perdas se repetem e o gestor não consegue identificar o que precisa ser corrigido.',recommendation:'Padronizar qualificação, próximos passos, cadência de retorno e registro dos motivos de perda.',benefit:'Conversão mais previsível, aprendizado contínuo e melhor desempenho da equipe.',actions:['Definir critérios de qualificação','Padronizar próximos passos','Registrar e analisar motivos de perda']},
crescer:{reading:'A operação possui base para funcionar, mas ainda precisa transformar dados em previsibilidade. O foco deve estar em indicadores, metas e crescimento sustentável, reduzindo decisões baseadas apenas na percepção.',diagnosis:'A empresa opera, porém ainda não converte suas informações em uma visão confiável do futuro.',impact:'Metas perdem força, decisões chegam tarde e o crescimento continua dependente do esforço do empresário.',recommendation:'Criar indicadores de oportunidades, conversão e resultados, com metas e uma rotina de análise.',benefit:'Decisões mais rápidas, maior controle e crescimento com previsibilidade.',actions:['Definir três indicadores essenciais','Estabelecer metas comerciais','Realizar análise semanal dos resultados']}};
export function maturity(p:number){if(p<=20)return['Nível 1 — Operação sem visibilidade','As oportunidades existem, mas falta processo para acompanhar o que acontece.'];if(p<=40)return['Nível 2 — Operação reativa','A empresa depende de esforço manual, memória e ações isoladas.'];if(p<=60)return['Nível 3 — Operação em organização','Existem controles, mas ainda há falhas de acompanhamento e padronização.'];if(p<=80)return['Nível 4 — Operação controlada','Há organização e visibilidade para acompanhar a maioria das oportunidades.'];return['Nível 5 — Operação preparada para crescer','Há processos, indicadores e capacidade de crescer com previsibilidade.']}
function executiveMessage(ieg:number){if(ieg<=20)return 'Sua empresa já deu o passo mais importante: decidiu enxergar a operação. Agora, o caminho é criar visibilidade e transformar esforço em direção.';if(ieg<=40)return 'Sua empresa demonstra energia comercial e potencial de evolução. O próximo passo é transformar iniciativas isoladas em uma rotina confiável.';if(ieg<=60)return 'Sua empresa possui uma base operacional em construção. O próximo passo é conectar organização, acompanhamento e decisões mais previsíveis.';if(ieg<=80)return 'Sua empresa possui uma base operacional capaz de sustentar o crescimento. O próximo passo é transformar organização em previsibilidade.';return 'Sua empresa já opera com maturidade e visão de crescimento. O próximo passo é ampliar a previsibilidade sem perder consistência e controle.'}
function growthPotential(total:number,diff:number,riskLevel:string,highest:number,lowest:number){const rw=({Baixo:10,Médio:25,Alto:40,Crítico:55} as Record<string,number>)[riskLevel];const score=(100-total)*.3+(100-lowest)*.2+diff*.15+highest*.2+rw*.15;return score>=60?'Muito Alto':score>=45?'Alto':score>=30?'Moderado':'Baixo'}
function balance(diff:number){return diff<=10?'Excelente':diff<=25?'Bom':diff<=40?'Regular':'Crítico'}
function risk(total:number,lowest:number,diff:number){const score=(100-total)*.4+(100-lowest)*.4+diff*.2;return score<20?'Baixo':score<40?'Médio':score<65?'Alto':'Crítico'}
export function calculate(a:Answers){const results:Result[]=pillars.map(p=>{const score=p.questions.reduce((s,_,i)=>s+(a[`${p.id}-${i}`]??0),0);return{id:p.id,label:p.label,score,percent:score*5}}),total=results.reduce((s,p)=>s+p.score,0),ordered=[...results].sort((a,b)=>a.percent-b.percent),difference=ordered[4].percent-ordered[0].percent,priorities=ordered.slice(0,3),level=maturity(total),main=intelligence[ordered[0].id];const recommendations=priorities.map(p=>({pillar:p.label,...intelligence[p.id]}));const weeks=priorities.map((p,i)=>({title:`Semana ${i+1} — ${p.label}`,items:intelligence[p.id].actions}));weeks.push({title:'Semana 4 — Consolidar',items:['Revisar os primeiros indicadores','Corrigir falhas percebidas','Definir o próximo ciclo de evolução']});const riskLevel=risk(total,ordered[0].percent,difference);const consultant=ordered[4].label+' é uma força importante e demonstra capacidades para sustentar a evolução. O ponto que merece atenção agora é '+ordered[0].label.toLowerCase()+'. O caminho recomendado é '+main.recommendation.toLowerCase();return{results,total,percent:total,maturity:level,lowest:ordered[0],highest:ordered[4],difference,priorities,balance:balance(difference),risk:riskLevel,main,recommendations,weeks,consultant,executiveMessage:executiveMessage(total),growthPotential:growthPotential(total,difference,riskLevel,ordered[4].percent,ordered[0].percent),gains:[main.benefit,'Mais previsibilidade nas decisões','Maior aproveitamento das oportunidades','Crescimento sustentável'],history:{previous:null,current:total,status:'baseline'}}}

