export const pillars=[
{id:'atrair',label:'Atrair',questions:['Sua empresa sabe de quais canais vÃªm as oportunidades?','Identifica quais aÃ§Ãµes geram melhores resultados?','Existe definiÃ§Ã£o do cliente ideal?','Mede o custo por oportunidade?','Os contatos tÃªm informaÃ§Ãµes para iniciar o atendimento?']},
{id:'organizar',label:'Organizar',questions:['As conversas ficam centralizadas?','Cada oportunidade tem responsÃ¡vel?','Existe processo de distribuiÃ§Ã£o?','A equipe vÃª o histÃ³rico do cliente?','HÃ¡ padrÃ£o para registrar informaÃ§Ãµes?']},
{id:'acompanhar',label:'Acompanhar',questions:['Ã‰ possÃ­vel saber quem aguarda retorno?','Visualiza todas as oportunidades em andamento?','Existem etapas comerciais definidas?','Identifica oportunidades paradas?','O gestor acompanha sem relatÃ³rios manuais?']},
{id:'converter',label:'Converter',questions:['Existe processo para qualificar oportunidades?','Existe rotina de acompanhamento?','Registra motivos de perda?','Mede a conversÃ£o em vendas?','A equipe sabe o prÃ³ximo passo de cada negociaÃ§Ã£o?']},
{id:'crescer',label:'Crescer',questions:['Acompanha indicadores regularmente?','Existe clareza de metas e resultados?','Consegue prever oportunidades e vendas?','A operaÃ§Ã£o cresce sem depender do empresÃ¡rio?','Usa dados para tomar decisÃµes?']}];
export const openQuestions=['Qual Ã© hoje o maior desafio comercial da empresa?','Onde vocÃª acredita que mais oportunidades sÃ£o perdidas?','O que mais preocupa vocÃª na operaÃ§Ã£o comercial atualmente?','Qual resultado deseja alcanÃ§ar nos prÃ³ximos seis meses?','O que mudaria se tivesse mais controle e previsibilidade?'];
export type Answers=Record<string,number>;
type Result={id:string;label:string;score:number;percent:number};
const intelligence:Record<string,{reading:string;diagnosis:string;impact:string;recommendation:string;benefit:string;actions:string[]}>= {
atrair:{reading:'A operaÃ§Ã£o precisa aumentar a clareza sobre como as oportunidades sÃ£o geradas. Sem distinguir origem, qualidade e perfil ideal, o crescimento tende a consumir mais esforÃ§o e orÃ§amento do que o necessÃ¡rio.',diagnosis:'A empresa recebe oportunidades, mas ainda nÃ£o transforma a aquisiÃ§Ã£o em um processo mensurÃ¡vel e replicÃ¡vel.',impact:'Recursos podem ser direcionados a canais pouco produtivos e contatos sem aderÃªncia ao negÃ³cio.',recommendation:'Mapear a origem de cada oportunidade, definir o cliente ideal e comparar volume, qualidade e custo por canal.',benefit:'Mais oportunidades qualificadas, menor desperdÃ­cio e decisÃµes de investimento mais seguras.',actions:['Mapear todos os canais de entrada','Definir o perfil de cliente ideal','Criar registro de origem e qualidade']},
organizar:{reading:'O principal desafio estÃ¡ na organizaÃ§Ã£o da operaÃ§Ã£o. InformaÃ§Ãµes dispersas e responsabilidades pouco claras dificultam o controle e aumentam a dependÃªncia da memÃ³ria da equipe.',diagnosis:'A operaÃ§Ã£o funciona, mas o conhecimento e os registros ainda nÃ£o seguem um padrÃ£o Ãºnico.',impact:'Oportunidades podem ser duplicadas, esquecidas ou atendidas sem contexto suficiente.',recommendation:'Centralizar informaÃ§Ãµes, definir responsÃ¡veis e padronizar os registros essenciais de cada contato.',benefit:'Mais controle, continuidade no atendimento e menor perda por falhas internas.',actions:['Centralizar informaÃ§Ãµes comerciais','Definir responsÃ¡veis por oportunidade','Padronizar registros e etapas']},
acompanhar:{reading:'A empresa gera e organiza oportunidades, mas perde visibilidade durante o acompanhamento. O maior ganho virÃ¡ de saber quem precisa de retorno, qual negociaÃ§Ã£o estÃ¡ parada e qual deve ser o prÃ³ximo passo.',diagnosis:'Faltam rotinas e sinais claros para acompanhar oportunidades ao longo do processo.',impact:'Boas oportunidades podem esfriar por ausÃªncia de retorno ou falta de atenÃ§Ã£o no momento certo.',recommendation:'Implantar etapas comerciais, rotina de retornos e revisÃ£o periÃ³dica das oportunidades paradas.',benefit:'Menos esquecimentos, mais velocidade comercial e maior aproveitamento da demanda existente.',actions:['Definir etapas comerciais visÃ­veis','Criar rotina diÃ¡ria de retornos','Revisar oportunidades paradas semanalmente']},
converter:{reading:'O gargalo estÃ¡ na transformaÃ§Ã£o de oportunidades em vendas. A empresa precisa tornar qualificaÃ§Ã£o, prÃ³ximos passos e motivos de perda parte de um processo claro e acompanhado.',diagnosis:'As negociaÃ§Ãµes avanÃ§am mais pela experiÃªncia individual do que por um mÃ©todo comercial consistente.',impact:'A conversÃ£o oscila, perdas se repetem e o gestor nÃ£o consegue identificar o que precisa ser corrigido.',recommendation:'Padronizar qualificaÃ§Ã£o, prÃ³ximos passos, cadÃªncia de retorno e registro dos motivos de perda.',benefit:'ConversÃ£o mais previsÃ­vel, aprendizado contÃ­nuo e melhor desempenho da equipe.',actions:['Definir critÃ©rios de qualificaÃ§Ã£o','Padronizar prÃ³ximos passos','Registrar e analisar motivos de perda']},
crescer:{reading:'A operaÃ§Ã£o possui base para funcionar, mas ainda precisa transformar dados em previsibilidade. O foco deve estar em indicadores, metas e crescimento sustentÃ¡vel, reduzindo decisÃµes baseadas apenas na percepÃ§Ã£o.',diagnosis:'A empresa opera, porÃ©m ainda nÃ£o converte suas informaÃ§Ãµes em uma visÃ£o confiÃ¡vel do futuro.',impact:'Metas perdem forÃ§a, decisÃµes chegam tarde e o crescimento continua dependente do esforÃ§o do empresÃ¡rio.',recommendation:'Criar indicadores de oportunidades, conversÃ£o e resultados, com metas e uma rotina de anÃ¡lise.',benefit:'DecisÃµes mais rÃ¡pidas, maior controle e crescimento com previsibilidade.',actions:['Definir trÃªs indicadores essenciais','Estabelecer metas comerciais','Realizar anÃ¡lise semanal dos resultados']}};
export function maturity(p:number){if(p<=20)return['NÃ­vel 1 â€” OperaÃ§Ã£o sem visibilidade','As oportunidades existem, mas falta processo para acompanhar o que acontece.'];if(p<=40)return['NÃ­vel 2 â€” OperaÃ§Ã£o reativa','A empresa depende de esforÃ§o manual, memÃ³ria e aÃ§Ãµes isoladas.'];if(p<=60)return['NÃ­vel 3 â€” OperaÃ§Ã£o em organizaÃ§Ã£o','Existem controles, mas ainda hÃ¡ falhas de acompanhamento e padronizaÃ§Ã£o.'];if(p<=80)return['NÃ­vel 4 â€” OperaÃ§Ã£o controlada','HÃ¡ organizaÃ§Ã£o e visibilidade para acompanhar a maioria das oportunidades.'];return['NÃ­vel 5 â€” OperaÃ§Ã£o preparada para crescer','HÃ¡ processos, indicadores e capacidade de crescer com previsibilidade.']}
function balance(diff:number){return diff<=10?'Excelente':diff<=25?'Bom':diff<=40?'Regular':'CrÃ­tico'}
function risk(total:number,lowest:number,diff:number){const score=(100-total)*.4+(100-lowest)*.4+diff*.2;return score<20?'Baixo':score<40?'MÃ©dio':score<65?'Alto':'CrÃ­tico'}
export function calculate(a:Answers){const results:Result[]=pillars.map(p=>{const score=p.questions.reduce((s,_,i)=>s+(a[`${p.id}-${i}`]??0),0);return{id:p.id,label:p.label,score,percent:score*5}}),total=results.reduce((s,p)=>s+p.score,0),ordered=[...results].sort((a,b)=>a.percent-b.percent),difference=ordered[4].percent-ordered[0].percent,priorities=ordered.slice(0,3),level=maturity(total),main=intelligence[ordered[0].id];const recommendations=priorities.map(p=>({pillar:p.label,...intelligence[p.id]}));const weeks=priorities.map((p,i)=>({title:`Semana ${i+1} â€” ${p.label}`,items:intelligence[p.id].actions}));weeks.push({title:'Semana 4 â€” Consolidar',items:['Revisar os primeiros indicadores','Corrigir falhas percebidas','Definir o prÃ³ximo ciclo de evoluÃ§Ã£o']});const consultant=`Embora ${ordered[4].label.toLowerCase()} seja hoje uma forÃ§a da operaÃ§Ã£o, o diagnÃ³stico mostra que ${ordered[0].label.toLowerCase()} limita a capacidade de transformar esforÃ§o em resultado previsÃ­vel. Com um IEG de ${total}/100 e risco operacional ${risk(total,ordered[0].percent,difference).toLowerCase()}, o maior ganho nos prÃ³ximos meses virÃ¡ de ${main.recommendation.toLowerCase()}`;return{results,total,percent:total,maturity:level,lowest:ordered[0],highest:ordered[4],difference,priorities,balance:balance(difference),risk:risk(total,ordered[0].percent,difference),main,recommendations,weeks,consultant}}

