export const EVIDENCE_ENGINE_VERSION='1.0';
export const READINESS_ENGINE_VERSION='1.0';

export type Severity='CRITICO'|'ATENCAO'|'ESTRUTURADO';
export type Evidence={evidence_code:string;dimension:'ATRAIR'|'CONVERTER'|'CRESCER';capability:string;score:number;severity:Severity;fact:string;source_question:string;source_question_id:string;diagnostic_id?:string};
export type DiagnosticAnswer={pilar?:string;pergunta?:string;resposta_numerica?:number|null;valor?:number|null;question_id?:string};

type Definition={id:string;dimension:Evidence['dimension'];capability:string;prefix:string;question:string;facts?:string[];codes?:string[]};
const definitions:Definition[]=[
 {id:'atrair-0',dimension:'ATRAIR',capability:'RASTREABILIDADE_AQUISICAO',prefix:'ACQ_SOURCE',question:'Sua empresa sabe de quais canais vêm as oportunidades?'},
 {id:'atrair-1',dimension:'ATRAIR',capability:'EFICIENCIA_CANAIS',prefix:'ACQ_CHANNEL_EFFICIENCY',question:'Identifica quais ações geram melhores resultados?'},
 {id:'atrair-2',dimension:'ATRAIR',capability:'CLIENTE_IDEAL',prefix:'ACQ_IDEAL_CUSTOMER',question:'Existe definição do cliente ideal?'},
 {id:'atrair-3',dimension:'ATRAIR',capability:'MENSURACAO_AQUISICAO',prefix:'ACQ_COST_MEASUREMENT',question:'Mede o custo por oportunidade?'},
 {id:'atrair-4',dimension:'CONVERTER',capability:'INFORMACAO_INICIAL',prefix:'CV_INITIAL_INFORMATION',question:'Os contatos têm informações para iniciar o atendimento?'},
 {id:'atrair-5',dimension:'ATRAIR',capability:'DEMANDA',prefix:'ACQ_VOLUME',question:'Em que medida o volume de novas oportunidades comerciais é suficiente para atingir as metas de vendas da empresa?',codes:['ACQ_VOLUME_CRITICAL','ACQ_VOLUME_LOW','ACQ_VOLUME_PARTIAL','ACQ_VOLUME_ADEQUATE','ACQ_VOLUME_STRONG'],facts:['Volume de novas oportunidades é muito insuficiente para as metas.','Volume de novas oportunidades está muito abaixo da necessidade.','Volume de oportunidades ainda está abaixo da necessidade.','Volume de oportunidades geralmente atende à necessidade.','Volume de oportunidades é consistente e suficiente para as metas.']},
 {id:'atrair-6',dimension:'ATRAIR',capability:'PREVISIBILIDADE_AQUISICAO',prefix:'ACQ_PREDICTABILITY',question:'Em que medida a geração de novas oportunidades acontece de forma previsível?',codes:['ACQ_PREDICTABILITY_NONE','ACQ_PREDICTABILITY_LOW','ACQ_PREDICTABILITY_PARTIAL','ACQ_PREDICTABILITY_GOOD','ACQ_PREDICTABILITY_STRONG'],facts:['Geração de oportunidades sem previsibilidade.','Geração de oportunidades muito irregular.','Existe previsibilidade parcial na geração de oportunidades.','Existe boa previsibilidade na geração de oportunidades.','Existe processo contínuo e previsível de geração de oportunidades.']},
 {id:'atrair-7',dimension:'ATRAIR',capability:'ESTRATEGIA_AQUISICAO',prefix:'ACQ_STRATEGY',question:'Em que medida a empresa possui uma estratégia ativa para gerar novas oportunidades?',facts:['Estratégia de aquisição inexistente.','Aquisição depende de ações pontuais.','Existem ações de aquisição sem processo definido.','Existe estratégia de aquisição definida.','A estratégia de aquisição é estruturada, contínua e acompanhada.']},
 {id:'atrair-8',dimension:'ATRAIR',capability:'REATIVACAO_BASE',prefix:'ACQ_BASE_REACTIVATION',question:'Em que medida a empresa aproveita sua base atual de contatos e clientes para gerar novas oportunidades?',facts:['A base atual não é utilizada para gerar oportunidades.','A base é utilizada muito ocasionalmente.','O aproveitamento da base é parcial.','A base é trabalhada regularmente.','O aproveitamento da base é estruturado.']},
 {id:'organizar-0',dimension:'CONVERTER',capability:'CENTRALIZACAO',prefix:'CV_CENTRALIZATION',question:'As conversas ficam centralizadas?'},
 {id:'organizar-1',dimension:'CONVERTER',capability:'RESPONSABILIDADE',prefix:'CV_OWNERSHIP',question:'Cada oportunidade tem responsável?'},
 {id:'organizar-2',dimension:'CONVERTER',capability:'DISTRIBUICAO',prefix:'CV_DISTRIBUTION',question:'Existe processo de distribuição?'},
 {id:'organizar-3',dimension:'CONVERTER',capability:'HISTORICO',prefix:'CV_CUSTOMER_HISTORY',question:'A equipe vê o histórico do cliente?'},
 {id:'organizar-4',dimension:'CONVERTER',capability:'PADRAO_REGISTRO',prefix:'CV_RECORD_STANDARD',question:'Há padrão para registrar informações?'},
 {id:'acompanhar-0',dimension:'CONVERTER',capability:'CONTROLE_RETORNO',prefix:'CV_RETURN_CONTROL',question:'É possível saber quem aguarda retorno?'},
 {id:'acompanhar-1',dimension:'CONVERTER',capability:'VISAO_PIPELINE',prefix:'CV_PIPELINE_VISIBILITY',question:'Visualiza todas as oportunidades em andamento?'},
 {id:'acompanhar-2',dimension:'CONVERTER',capability:'ETAPAS_COMERCIAIS',prefix:'CV_SALES_STAGES',question:'Existem etapas comerciais definidas?'},
 {id:'acompanhar-3',dimension:'CONVERTER',capability:'OPORTUNIDADES_PARADAS',prefix:'CV_STALLED_OPPORTUNITIES',question:'Identifica oportunidades paradas?'},
 {id:'acompanhar-4',dimension:'CRESCER',capability:'RELATORIOS_AUTOMATIZADOS',prefix:'GR_AUTOMATED_REPORTS',question:'O gestor acompanha sem relatórios manuais?'},
 {id:'converter-0',dimension:'CONVERTER',capability:'QUALIFICACAO',prefix:'CV_QUALIFICATION',question:'Existe processo para qualificar oportunidades?'},
 {id:'converter-1',dimension:'CONVERTER',capability:'ROTINA_ACOMPANHAMENTO',prefix:'CV_FOLLOW_UP_ROUTINE',question:'Existe rotina de acompanhamento?'},
 {id:'converter-2',dimension:'CONVERTER',capability:'MOTIVOS_PERDA',prefix:'CV_LOSS_REASONS',question:'Registra motivos de perda?'},
 {id:'converter-3',dimension:'CONVERTER',capability:'MENSURACAO_CONVERSAO',prefix:'CV_CONVERSION_MEASUREMENT',question:'Mede a conversão em vendas?'},
 {id:'converter-4',dimension:'CONVERTER',capability:'PROXIMO_PASSO',prefix:'CV_NEXT_STEP',question:'A equipe sabe o próximo passo de cada negociação?'},
 {id:'converter-5',dimension:'CONVERTER',capability:'VELOCIDADE_ATENDIMENTO',prefix:'CV_RESPONSE_SPEED',question:'Em quanto tempo, normalmente, um novo contato comercial recebe a primeira resposta da empresa?'},
 {id:'crescer-0',dimension:'CRESCER',capability:'ACOMPANHAMENTO_INDICADORES',prefix:'GR_INDICATOR_TRACKING',question:'Acompanha indicadores regularmente?'},
 {id:'crescer-1',dimension:'CRESCER',capability:'METAS_RESULTADOS',prefix:'GR_GOALS',question:'Existe clareza de metas e resultados?'},
 {id:'crescer-2',dimension:'CRESCER',capability:'PREVISIBILIDADE_COMERCIAL',prefix:'GR_SALES_FORECAST',question:'Consegue prever oportunidades e vendas?'},
 {id:'crescer-3',dimension:'CRESCER',capability:'AUTONOMIA_OPERACIONAL',prefix:'GR_OPERATIONAL_AUTONOMY',question:'A operação cresce sem depender do empresário?'},
 {id:'crescer-4',dimension:'CRESCER',capability:'DECISAO_POR_DADOS',prefix:'GR_DATA_DECISIONS',question:'Usa dados para tomar decisões?'},
 {id:'crescer-5',dimension:'CRESCER',capability:'CENTRALIZACAO_INDICADORES',prefix:'GR_INDICATOR_CENTRALIZATION',question:'Em que medida a empresa consegue acompanhar os principais indicadores comerciais em um único lugar?'},
 {id:'crescer-6',dimension:'CRESCER',capability:'ROTINA_GESTAO',prefix:'GR_MANAGEMENT_ROUTINE',question:'Existe uma rotina de gestão para analisar resultados e definir ações de melhoria?'}
];

const normalize=(value:unknown)=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
export const evidenceSeverity=(score:number):Severity=>score<=1?'CRITICO':score===2?'ATENCAO':'ESTRUTURADO';
const stateCode=(score:number)=>['CRITICAL','LOW','PARTIAL','ADEQUATE','STRONG'][score];
const genericFact=(definition:Definition,score:number)=>`${definition.capability.replaceAll('_',' ').toLowerCase()}: ${score<=1?'estrutura crítica ou insuficiente':score===2?'estrutura parcial que exige atenção':'estrutura consistente'}.`;

function evidence(definition:Definition,score:number,diagnosticId?:string):Evidence{return{evidence_code:definition.codes?.[score]||`${definition.prefix}_${stateCode(score)}`,dimension:definition.dimension,capability:definition.capability,score,severity:evidenceSeverity(score),fact:definition.facts?.[score]||genericFact(definition,score),source_question:definition.question,source_question_id:definition.id,...(diagnosticId?{diagnostic_id:diagnosticId}:{})}}

export function evidenceFromAnswerMap(answers:Record<string,number|undefined>,diagnosticId?:string){return definitions.flatMap(definition=>{const score=answers[definition.id];return Number.isInteger(score)&&Number(score)>=0&&Number(score)<=4?[evidence(definition,Number(score),diagnosticId)]:[]})}

export function evidenceFromStoredAnswers(answers:DiagnosticAnswer[],diagnosticId?:string){return answers.flatMap(answer=>{const definition=definitions.find(item=>item.id===answer.question_id)||definitions.find(item=>normalize(item.question)===normalize(answer.pergunta));const raw=answer.resposta_numerica??answer.valor;return definition&&Number.isInteger(Number(raw))&&Number(raw)>=0&&Number(raw)<=4?[evidence(definition,Number(raw),diagnosticId)]:[]})}

export const READINESS_CAPABILITIES=['VELOCIDADE_ATENDIMENTO','CENTRALIZACAO','RESPONSABILIDADE','DISTRIBUICAO','HISTORICO','PADRAO_REGISTRO','CONTROLE_RETORNO','VISAO_PIPELINE'] as const;
export type ReadinessClass='BAIXA'|'MEDIA'|'ALTA';
export type Readiness={indicator_code:'ACQUISITION_READINESS';available:boolean;score_base:number|null;classification_before_limiters:ReadinessClass|null;classification:ReadinessClass|null;interpretation:string;components_used:{capability:string;score:number;max_score:4;fact:string}[];components_missing:string[];limiters:string[];evidence_engine_version:'1.0';readiness_engine_version:'1.0'};
const baseClassification=(score:number):ReadinessClass=>score<50?'BAIXA':score<75?'MEDIA':'ALTA';
const interpretation:Record<ReadinessClass,string>={BAIXA:'A operação apresenta fragilidades importantes para receber aumento de demanda sem elevar o risco de perda de oportunidades.',MEDIA:'A operação possui estrutura parcial para receber novas oportunidades, mas existem pontos que devem ser corrigidos ou acompanhados.',ALTA:'A operação apresenta boa estrutura para receber aumento de demanda, sem prejuízo dos pontos específicos que ainda possam exigir evolução.'};
export function acquisitionReadiness(evidences:Evidence[]):Readiness{const byCapability=new Map(evidences.map(item=>[item.capability,item])),components_used=READINESS_CAPABILITIES.flatMap(capability=>{const item=byCapability.get(capability);return item?[{capability,score:item.score,max_score:4 as const,fact:item.fact}]:[]}),components_missing=READINESS_CAPABILITIES.filter(capability=>!byCapability.has(capability)),available=components_used.length>0;if(!available)return{indicator_code:'ACQUISITION_READINESS',available:false,score_base:null,classification_before_limiters:null,classification:null,interpretation:'Informações insuficientes para calcular a Prontidão para Aquisição.',components_used,components_missing,limiters:[],evidence_engine_version:EVIDENCE_ENGINE_VERSION,readiness_engine_version:READINESS_ENGINE_VERSION};const score_base=Math.round(components_used.reduce((sum,item)=>sum+item.score,0)/(components_used.length*4)*100),before=baseClassification(score_base),limiters:string[]=[];let classification=before;const add=(capability:string,message:string)=>{const item=byCapability.get(capability);if(item&&item.score<=1){limiters.push(message);if(classification==='ALTA')classification='MEDIA'}};add('VELOCIDADE_ATENDIMENTO','Velocidade de atendimento crítica.');add('RESPONSABILIDADE','Responsabilidade pelas oportunidades crítica.');add('CONTROLE_RETORNO','Controle de retorno crítico.');if(components_used.filter(item=>item.score<=1).length>=3){limiters.push('Três ou mais componentes críticos.');classification='BAIXA'}return{indicator_code:'ACQUISITION_READINESS',available:true,score_base,classification_before_limiters:before,classification,interpretation:interpretation[classification],components_used,components_missing,limiters,evidence_engine_version:EVIDENCE_ENGINE_VERSION,readiness_engine_version:READINESS_ENGINE_VERSION}}

export function structuredOperationalContext(context:any){return{monthly_contact_volume:context?.volume_contatos||'',commercial_channels:Array.isArray(context?.canais)?context.canais:[],commercial_team_size:context?.quantidade_pessoas||'',current_tools:Array.isArray(context?.ferramentas)?context.ferramentas:[],current_providers:context?.ferramenta_atual?[context.ferramenta_atual]:[],tracked_indicators:Array.isArray(context?.indicadores)?context.indicadores:[]}}
