export const EVIDENCE_ENGINE_VERSION='1.0';
export const READINESS_ENGINE_VERSION='1.0';
export const ATTRACTION_NEED_ENGINE_VERSION='1.0';
export const CONVERSION_CAPACITY_ENGINE_VERSION='1.0';

export type Severity='CRITICO'|'ATENCAO'|'ESTRUTURADO';
export type Evidence={evidence_code:string;dimension:'ATRAIR'|'CONVERTER'|'CRESCER';capability:string;score:number;severity:Severity;fact:string;source_question:string;source_question_id:string;diagnostic_id?:string};
export type DiagnosticAnswer={pilar?:string;pergunta?:string;resposta_numerica?:number|null;valor?:number|null;question_id?:string};

type Definition={id:string;dimension:Evidence['dimension'];capability:string;prefix:string;question:string;facts?:string[];codes?:string[]};
const definitions:Definition[]=[
 {id:'atrair-0',dimension:'ATRAIR',capability:'RASTREABILIDADE_AQUISICAO',prefix:'ACQ_SOURCE',question:'Sua empresa sabe de quais canais vêm as oportunidades?'},
 {id:'atrair-1',dimension:'ATRAIR',capability:'EFICIENCIA_CANAIS',prefix:'ACQ_CHANNEL_EFFICIENCY',question:'Identifica quais ações geram melhores resultados?'},
 {id:'atrair-2',dimension:'ATRAIR',capability:'CLIENTE_IDEAL',prefix:'ACQ_IDEAL_CUSTOMER',question:'Existe definição do cliente ideal?'},
 {id:'atrair-3',dimension:'ATRAIR',capability:'MENSURACAO_AQUISICAO',prefix:'ACQ_COST_MEASUREMENT',question:'Mede o custo por oportunidade?'},
 {id:'atrair-4',dimension:'CONVERTER',capability:'INFORMACAO_INICIAL',prefix:'CV_INITIAL_INFORMATION',question:'Os contatos têm informações para iniciar o atendimento?'},
 {id:'atrair-5',dimension:'ATRAIR',capability:'DEMANDA',prefix:'ACQ_VOLUME',question:'Em que medida o volume de novas oportunidades comerciais é suficiente para atingir as metas de vendas da empresa?',codes:['ACQ_VOLUME_CRITICAL','ACQ_VOLUME_LOW','ACQ_VOLUME_PARTIAL','ACQ_VOLUME_ADEQUATE','ACQ_VOLUME_STRONG'],facts:['Volume de novas oportunidades é muito insuficiente para as metas.','Volume de novas oportunidades está muito abaixo da necessidade.','Volume de oportunidades ainda está abaixo da necessidade.','Volume de oportunidades geralmente atende à necessidade.','Volume de oportunidades é consistente e suficiente para as metas.']},
 {id:'atrair-6',dimension:'ATRAIR',capability:'PREVISIBILIDADE_AQUISICAO',prefix:'ACQ_PREDICTABILITY',question:'Em que medida a geração de novas oportunidades acontece de forma previsível?',codes:['ACQ_PREDICTABILITY_NONE','ACQ_PREDICTABILITY_LOW','ACQ_PREDICTABILITY_PARTIAL','ACQ_PREDICTABILITY_GOOD','ACQ_PREDICTABILITY_STRONG'],facts:['Geração de oportunidades sem previsibilidade.','Geração de oportunidades muito irregular.','Existe previsibilidade parcial na geração de oportunidades.','Existe boa previsibilidade na geração de oportunidades.','Existe processo contínuo e previsível de geração de oportunidades.']},
 {id:'atrair-7',dimension:'ATRAIR',capability:'ESTRATEGIA_AQUISICAO',prefix:'ACQ_STRATEGY',question:'Em que medida a empresa possui uma estratégia ativa para gerar novas oportunidades?',facts:['Estratégia de aquisição inexistente.','Aquisição depende de ações pontuais.','Existem ações de aquisição sem processo definido.','Existe estratégia de aquisição definida.','A estratégia de aquisição é estruturada, contínua e acompanhada.']},
 {id:'atrair-8',dimension:'ATRAIR',capability:'REATIVACAO_BASE',prefix:'ACQ_BASE_REACTIVATION',question:'Em que medida a empresa aproveita sua base atual de contatos e clientes para gerar novas oportunidades?',facts:['A base atual não é utilizada para gerar oportunidades.','A base é utilizada muito ocasionalmente.','O aproveitamento da base é parcial.','A base é trabalhada regularmente.','O aproveitamento da base é estruturado.']},
 {id:'organizar-0',dimension:'CONVERTER',capability:'CENTRALIZACAO',prefix:'CV_CENTRALIZATION',question:'As conversas ficam centralizadas?'},
 {id:'organizar-1',dimension:'CONVERTER',capability:'RESPONSABILIDADE',prefix:'CV_OWNERSHIP',question:'Cada oportunidade tem responsável?'},
 {id:'organizar-2',dimension:'CONVERTER',capability:'DISTRIBUICAO',prefix:'CV_DISTRIBUTION',question:'Existe processo de distribuição?'},
 {id:'organizar-3',dimension:'CONVERTER',capability:'HISTORICO',prefix:'CV_CUSTOMER_HISTORY',question:'A equipe vê o histórico do cliente?'},
 {id:'organizar-4',dimension:'CONVERTER',capability:'PADRAO_REGISTRO',prefix:'CV_RECORD_STANDARD',question:'Há padrão para registrar informações?'},
 {id:'acompanhar-0',dimension:'CONVERTER',capability:'CONTROLE_RETORNO',prefix:'CV_RETURN_CONTROL',question:'É possível saber quem aguarda retorno?'},
 {id:'acompanhar-1',dimension:'CONVERTER',capability:'VISAO_PIPELINE',prefix:'CV_PIPELINE_VISIBILITY',question:'Visualiza todas as oportunidades em andamento?'},
 {id:'acompanhar-2',dimension:'CONVERTER',capability:'ETAPAS_COMERCIAIS',prefix:'CV_SALES_STAGES',question:'Existem etapas comerciais definidas?'},
 {id:'acompanhar-3',dimension:'CONVERTER',capability:'OPORTUNIDADES_PARADAS',prefix:'CV_STALLED_OPPORTUNITIES',question:'Identifica oportunidades paradas?'},
 {id:'acompanhar-4',dimension:'CRESCER',capability:'RELATORIOS_AUTOMATIZADOS',prefix:'GR_AUTOMATED_REPORTS',question:'O gestor acompanha sem relatórios manuais?'},
 {id:'converter-0',dimension:'CONVERTER',capability:'QUALIFICACAO',prefix:'CV_QUALIFICATION',question:'Existe processo para qualificar oportunidades?'},
 {id:'converter-1',dimension:'CONVERTER',capability:'ROTINA_ACOMPANHAMENTO',prefix:'CV_FOLLOW_UP_ROUTINE',question:'Existe rotina de acompanhamento?'},
 {id:'converter-2',dimension:'CONVERTER',capability:'MOTIVOS_PERDA',prefix:'CV_LOSS_REASONS',question:'Registra motivos de perda?'},
 {id:'converter-3',dimension:'CONVERTER',capability:'MENSURACAO_CONVERSAO',prefix:'CV_CONVERSION_MEASUREMENT',question:'Mede a conversão em vendas?'},
 {id:'converter-4',dimension:'CONVERTER',capability:'PROXIMO_PASSO',prefix:'CV_NEXT_STEP',question:'A equipe sabe o próximo passo de cada negociação?'},
 {id:'converter-5',dimension:'CONVERTER',capability:'VELOCIDADE_ATENDIMENTO',prefix:'CV_RESPONSE_SPEED',question:'Em quanto tempo, normalmente, um novo contato comercial recebe a primeira resposta da empresa?'},
 {id:'crescer-0',dimension:'CRESCER',capability:'ACOMPANHAMENTO_INDICADORES',prefix:'GR_INDICATOR_TRACKING',question:'Acompanha indicadores regularmente?'},
 {id:'crescer-1',dimension:'CRESCER',capability:'METAS_RESULTADOS',prefix:'GR_GOALS',question:'Existe clareza de metas e resultados?'},
 {id:'crescer-2',dimension:'CRESCER',capability:'PREVISIBILIDADE_COMERCIAL',prefix:'GR_SALES_FORECAST',question:'Consegue prever oportunidades e vendas?'},
 {id:'crescer-3',dimension:'CRESCER',capability:'AUTONOMIA_OPERACIONAL',prefix:'GR_OPERATIONAL_AUTONOMY',question:'A operação cresce sem depender do empresário?'},
 {id:'crescer-4',dimension:'CRESCER',capability:'DECISAO_POR_DADOS',prefix:'GR_DATA_DECISIONS',question:'Usa dados para tomar decisões?'},
 {id:'crescer-5',dimension:'CRESCER',capability:'CENTRALIZACAO_INDICADORES',prefix:'GR_INDICATOR_CENTRALIZATION',question:'Em que medida a empresa consegue acompanhar os principais indicadores comerciais em um único lugar?'},
 {id:'crescer-6',dimension:'CRESCER',capability:'ROTINA_GESTAO',prefix:'GR_MANAGEMENT_ROUTINE',question:'Existe uma rotina de gestão para analisar resultados e definir ações de melhoria?'}
];

const normalize=(value:unknown)=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
export const evidenceSeverity=(score:number):Severity=>score<=1?'CRITICO':score===2?'ATENCAO':'ESTRUTURADO';
const stateCode=(score:number)=>['CRITICAL','LOW','PARTIAL','ADEQUATE','STRONG'][score];
const genericFact=(definition:Definition,score:number)=>`${definition.capability.replaceAll('_',' ').toLowerCase()}: ${score<=1?'estrutura crítica ou insuficiente':score===2?'estrutura parcial que exige atenção':'estrutura consistente'}.`;

function evidence(definition:Definition,score:number,diagnosticId?:string):Evidence{return{evidence_code:definition.codes?.[score]||`${definition.prefix}_${stateCode(score)}`,dimension:definition.dimension,capability:definition.capability,score,severity:evidenceSeverity(score),fact:definition.facts?.[score]||genericFact(definition,score),source_question:definition.question,source_question_id:definition.id,...(diagnosticId?{diagnostic_id:diagnosticId}:{})}}

export function evidenceFromAnswerMap(answers:Record<string,number|undefined>,diagnosticId?:string){return definitions.flatMap(definition=>{const score=answers[definition.id];return Number.isInteger(score)&&Number(score)>=0&&Number(score)<=4?[evidence(definition,Number(score),diagnosticId)]:[]})}

export function evidenceFromStoredAnswers(answers:DiagnosticAnswer[],diagnosticId?:string){return answers.flatMap(answer=>{const definition=definitions.find(item=>item.id===answer.question_id)||definitions.find(item=>normalize(item.question)===normalize(answer.pergunta));const raw=answer.resposta_numerica??answer.valor;return definition&&Number.isInteger(Number(raw))&&Number(raw)>=0&&Number(raw)<=4?[evidence(definition,Number(raw),diagnosticId)]:[]})}

export const READINESS_CAPABILITIES=['VELOCIDADE_ATENDIMENTO','CENTRALIZACAO','RESPONSABILIDADE','DISTRIBUICAO','HISTORICO','PADRAO_REGISTRO','CONTROLE_RETORNO','VISAO_PIPELINE'] as const;
export type ReadinessClass='BAIXA'|'MEDIA'|'ALTA';
export type Readiness={indicator_code:'ACQUISITION_READINESS';available:boolean;score_base:number|null;classification_before_limiters:ReadinessClass|null;classification:ReadinessClass|null;interpretation:string;components_used:{capability:string;score:number;max_score:4;fact:string}[];components_missing:string[];limiters:string[];evidence_engine_version:'1.0';readiness_engine_version:'1.0'};
const baseClassification=(score:number):ReadinessClass=>score<50?'BAIXA':score<75?'MEDIA':'ALTA';
const interpretation:Record<ReadinessClass,string>={BAIXA:'A operação apresenta fragilidades importantes para receber aumento de demanda sem elevar o risco de perda de oportunidades.',MEDIA:'A operação possui estrutura parcial para receber novas oportunidades, mas existem pontos que devem ser corrigidos ou acompanhados.',ALTA:'A operação apresenta boa estrutura para receber aumento de demanda, sem prejuízo dos pontos específicos que ainda possam exigir evolução.'};
export function acquisitionReadiness(evidences:Evidence[]):Readiness{const byCapability=new Map(evidences.map(item=>[item.capability,item])),components_used=READINESS_CAPABILITIES.flatMap(capability=>{const item=byCapability.get(capability);return item?[{capability,score:item.score,max_score:4 as const,fact:item.fact}]:[]}),components_missing=READINESS_CAPABILITIES.filter(capability=>!byCapability.has(capability)),available=components_used.length>0;if(!available)return{indicator_code:'ACQUISITION_READINESS',available:false,score_base:null,classification_before_limiters:null,classification:null,interpretation:'Informações insuficientes para calcular a Prontidão para Aquisição.',components_used,components_missing,limiters:[],evidence_engine_version:EVIDENCE_ENGINE_VERSION,readiness_engine_version:READINESS_ENGINE_VERSION};const score_base=Math.round(components_used.reduce((sum,item)=>sum+item.score,0)/(components_used.length*4)*100),before=baseClassification(score_base),limiters:string[]=[];let classification=before;const add=(capability:string,message:string)=>{const item=byCapability.get(capability);if(item&&item.score<=1){limiters.push(message);if(classification==='ALTA')classification='MEDIA'}};add('VELOCIDADE_ATENDIMENTO','Velocidade de atendimento crítica.');add('RESPONSABILIDADE','Responsabilidade pelas oportunidades crítica.');add('CONTROLE_RETORNO','Controle de retorno crítico.');if(components_used.filter(item=>item.score<=1).length>=3){limiters.push('Três ou mais componentes críticos.');classification='BAIXA'}return{indicator_code:'ACQUISITION_READINESS',available:true,score_base,classification_before_limiters:before,classification,interpretation:interpretation[classification],components_used,components_missing,limiters,evidence_engine_version:EVIDENCE_ENGINE_VERSION,readiness_engine_version:READINESS_ENGINE_VERSION}}

export const ATTRACTION_NEED_CAPABILITIES=['DEMANDA','PREVISIBILIDADE_AQUISICAO','ESTRATEGIA_AQUISICAO','REATIVACAO_BASE'] as const;
export const ATTRACTION_SUPPORT_CAPABILITIES=['RASTREABILIDADE_AQUISICAO','EFICIENCIA_CANAIS','CLIENTE_IDEAL','MENSURACAO_AQUISICAO'] as const;
export type AttractionNeed={indicator_code:'ATTRACTION_NEED';available:boolean;generation_maturity:number|null;need_score:number|null;classification_before_rules:ReadinessClass|null;classification:ReadinessClass|null;interpretation:string;components_used:{capability:string;score:number;max_score:4;fact:string}[];components_missing:string[];supporting_evidence:Evidence[];dominant_rules:string[];attraction_need_engine_version:'1.0';evidence_engine_version:'1.0'};
const needClassification=(score:number):ReadinessClass=>score<35?'BAIXA':score<65?'MEDIA':'ALTA';
const needInterpretation:Record<ReadinessClass,string>={ALTA:'A empresa apresenta necessidade relevante de ampliar ou tornar mais consistente a geração de oportunidades comerciais.',MEDIA:'A empresa gera oportunidades, mas existem sinais de instabilidade ou espaço relevante para melhorar a consistência da aquisição.',BAIXA:'O volume e a estrutura atual de geração de oportunidades apresentam boa aderência às necessidades comerciais informadas.'};
export function attractionNeed(evidences:Evidence[]):AttractionNeed{const byCapability=new Map(evidences.map(item=>[item.capability,item])),components_used=ATTRACTION_NEED_CAPABILITIES.flatMap(capability=>{const item=byCapability.get(capability);return item?[{capability,score:item.score,max_score:4 as const,fact:item.fact}]:[]}),components_missing=ATTRACTION_NEED_CAPABILITIES.filter(capability=>!byCapability.has(capability)),supporting_evidence=evidences.filter(item=>(ATTRACTION_SUPPORT_CAPABILITIES as readonly string[]).includes(item.capability));if(components_used.length<3)return{indicator_code:'ATTRACTION_NEED',available:false,generation_maturity:null,need_score:null,classification_before_rules:null,classification:null,interpretation:'Dados insuficientes para calcular a Necessidade de Atrair.',components_used,components_missing,supporting_evidence,dominant_rules:[],attraction_need_engine_version:ATTRACTION_NEED_ENGINE_VERSION,evidence_engine_version:EVIDENCE_ENGINE_VERSION};const rawMaturity=components_used.reduce((sum,item)=>sum+item.score,0)/(components_used.length*4)*100,generation_maturity=Math.round(rawMaturity),need_score=Math.round(100-rawMaturity),before=needClassification(need_score),dominant_rules:string[]=[];let classification=before;const demand=byCapability.get('DEMANDA')?.score,predictability=byCapability.get('PREVISIBILIDADE_AQUISICAO')?.score;if(demand!==undefined&&demand<=1){if(classification==='BAIXA')classification='MEDIA';dominant_rules.push('Demanda crítica impede classificação Baixa.')}if(demand!==undefined&&demand>=3){if(classification==='ALTA')classification='MEDIA';dominant_rules.push('Volume atual suficiente limita a necessidade ao nível Médio.')}if(demand!==undefined&&predictability!==undefined&&demand<=1&&predictability<=1){classification='ALTA';dominant_rules.push('Baixo volume combinado com baixa previsibilidade mantém a necessidade em nível Alto.')}if(components_used.length===4&&components_used.every(item=>item.score>=3)){classification='BAIXA';dominant_rules.push('Os quatro componentes apresentam estrutura forte, limitando a necessidade ao nível Baixo.')}return{indicator_code:'ATTRACTION_NEED',available:true,generation_maturity,need_score,classification_before_rules:before,classification,interpretation:needInterpretation[classification],components_used,components_missing,supporting_evidence,dominant_rules,attraction_need_engine_version:ATTRACTION_NEED_ENGINE_VERSION,evidence_engine_version:EVIDENCE_ENGINE_VERSION}}

export type AcquisitionStrategy={available:boolean;status:string;reading:string;need_classification:ReadinessClass|null;readiness_classification:ReadinessClass|null};
const acquisitionMatrix:Record<string,{status:string;reading:string}>={
 'ALTA|ALTA':{status:'EXPANDIR AQUISIÇÃO',reading:'Existe forte necessidade de ampliar a geração de oportunidades e a operação apresenta boa capacidade para absorver aumento de demanda.'},
 'ALTA|MEDIA':{status:'EXPANDIR COM AJUSTES',reading:'Existe necessidade relevante de ampliar a geração de oportunidades. A operação possui capacidade parcial e a expansão deve ser acompanhada da evolução dos pontos de atenção identificados.'},
 'ALTA|BAIXA':{status:'ESTRUTURAR PARA EXPANDIR',reading:'Existe forte necessidade de gerar novas oportunidades, porém a operação apresenta fragilidades que podem ampliar perdas caso a demanda cresça sem correções operacionais.'},
 'MEDIA|ALTA':{status:'OTIMIZAR AQUISIÇÃO',reading:'Existe espaço para ampliar ou estabilizar a aquisição e a operação possui boa capacidade para receber crescimento de demanda.'},
 'MEDIA|MEDIA':{status:'EVOLUIR EM CONJUNTO',reading:'A aquisição e a capacidade operacional apresentam oportunidades de evolução que devem avançar de forma coordenada.'},
 'MEDIA|BAIXA':{status:'ESTRUTURAR ANTES DE ACELERAR',reading:'Existe espaço para melhorar a aquisição, mas a prioridade operacional deve considerar as fragilidades na absorção das oportunidades.'},
 'BAIXA|ALTA':{status:'OTIMIZAR E MONITORAR',reading:'A geração atual de oportunidades apresenta boa aderência às necessidades e a operação possui capacidade consistente de atendimento.'},
 'BAIXA|MEDIA':{status:'FORTALECER OPERAÇÃO',reading:'A necessidade de ampliar aquisição é baixa. O principal espaço de evolução está na melhoria da operação comercial.'},
 'BAIXA|BAIXA':{status:'ESTRUTURAR OPERAÇÃO',reading:'A ampliação da aquisição não aparece como necessidade principal neste momento e existem fragilidades operacionais que merecem atenção.'}
};
export function acquisitionStrategy(need:AttractionNeed,readiness:Readiness):AcquisitionStrategy{const key=`${need.classification}|${readiness.classification}`,result=acquisitionMatrix[key];return result?{available:true,...result,need_classification:need.classification,readiness_classification:readiness.classification}:{available:false,status:'DADOS INSUFICIENTES',reading:'Não existem dados suficientes para realizar a leitura estratégica da aquisição.',need_classification:need.classification,readiness_classification:readiness.classification}}

export const CONVERSION_CAPACITY_CAPABILITIES=['QUALIFICACAO','ROTINA_ACOMPANHAMENTO','PROXIMO_PASSO','MOTIVOS_PERDA','MENSURACAO_CONVERSAO','ETAPAS_COMERCIAIS','CONTROLE_RETORNO','OPORTUNIDADES_PARADAS'] as const;
export type ConversionCapacity={indicator_code:'CONVERSION_CAPACITY';available:boolean;score_base:number|null;classification_before_limiters:ReadinessClass|null;classification:ReadinessClass|null;interpretation:string;components_used:{capability:string;score:number;max_score:4;fact:string}[];components_missing:string[];limiters:string[];fragile_process_rule:boolean;conversion_capacity_engine_version:'1.0';evidence_engine_version:'1.0'};
const conversionClassification=(score:number):ReadinessClass=>score<50?'BAIXA':score<75?'MEDIA':'ALTA';
const conversionInterpretation:Record<ReadinessClass,string>={ALTA:'A operação apresenta boa estrutura para conduzir oportunidades ao longo do processo comercial. Existem condições consistentes para qualificação, acompanhamento e avanço das negociações, sem prejuízo de pontos específicos que ainda possam evoluir.',MEDIA:'A operação possui processo comercial parcialmente estruturado. Existem condições para conduzir oportunidades, mas alguns pontos podem reduzir a consistência do acompanhamento e da conversão.',BAIXA:'A operação apresenta fragilidades importantes na condução das oportunidades. Falhas de qualificação, acompanhamento ou continuidade das negociações podem reduzir o aproveitamento comercial.'};
export function conversionCapacity(evidences:Evidence[]):ConversionCapacity{const byCapability=new Map(evidences.map(item=>[item.capability,item])),components_used=CONVERSION_CAPACITY_CAPABILITIES.flatMap(capability=>{const item=byCapability.get(capability);return item?[{capability,score:item.score,max_score:4 as const,fact:item.fact}]:[]}),components_missing=CONVERSION_CAPACITY_CAPABILITIES.filter(capability=>!byCapability.has(capability));if(components_used.length<6)return{indicator_code:'CONVERSION_CAPACITY',available:false,score_base:null,classification_before_limiters:null,classification:null,interpretation:'Dados insuficientes para calcular a Capacidade de Conversão.',components_used,components_missing,limiters:[],fragile_process_rule:false,conversion_capacity_engine_version:CONVERSION_CAPACITY_ENGINE_VERSION,evidence_engine_version:EVIDENCE_ENGINE_VERSION};const score_base=Math.round(components_used.reduce((sum,item)=>sum+item.score,0)/(components_used.length*4)*100),before=conversionClassification(score_base),limiters:string[]=[];let classification=before;const limitHigh=(capability:string,message:string)=>{const item=byCapability.get(capability);if(item&&item.score<=1){limiters.push(message);if(classification==='ALTA')classification='MEDIA'}};limitHigh('QUALIFICACAO','Qualificação comercial crítica impede classificação Alta.');limitHigh('ROTINA_ACOMPANHAMENTO','Ausência de rotina consistente de acompanhamento impede classificação Alta.');limitHigh('PROXIMO_PASSO','Ausência de próximos passos consistentes impede classificação Alta.');limitHigh('CONTROLE_RETORNO','Controle de retorno crítico impede classificação Alta.');if(components_used.filter(item=>item.score<=1).length>=3){limiters.push('Três ou mais componentes críticos limitam a capacidade ao nível Baixo.');classification='BAIXA'}const fragile_process_rule=(byCapability.get('ETAPAS_COMERCIAIS')?.score??5)<=1&&(byCapability.get('QUALIFICACAO')?.score??5)<=1&&(byCapability.get('ROTINA_ACOMPANHAMENTO')?.score??5)<=1;if(fragile_process_rule){limiters.push('Processo comercial básico ausente ou fortemente fragilizado.');classification='BAIXA'}return{indicator_code:'CONVERSION_CAPACITY',available:true,score_base,classification_before_limiters:before,classification,interpretation:conversionInterpretation[classification],components_used,components_missing,limiters,fragile_process_rule,conversion_capacity_engine_version:CONVERSION_CAPACITY_ENGINE_VERSION,evidence_engine_version:EVIDENCE_ENGINE_VERSION}}

export function structuredOperationalContext(context:any){return{monthly_contact_volume:context?.volume_contatos||'',commercial_channels:Array.isArray(context?.canais)?context.canais:[],commercial_team_size:context?.quantidade_pessoas||'',current_tools:Array.isArray(context?.ferramentas)?context.ferramentas:[],current_providers:context?.ferramenta_atual?[context.ferramenta_atual]:[],tracked_indicators:Array.isArray(context?.indicadores)?context.indicadores:[]}}
