import type {AttractionNeed,ConversionCapacity,GrowthManagementCapacity,Readiness,ReadinessClass} from './evidenceEngine';

export const STRATEGIC_ENGINE_VERSION='1.0';
export type StrategicDimension='ATRAIR'|'ABSORVER'|'CONVERTER'|'GERIR';
export type StrategicPriority=StrategicDimension|'OTIMIZAR'|'CONSOLIDAR';
export type AcquisitionMovement='ACELERAR'|'EXPANDIR_CONTROLADAMENTE'|'MANTER_OTIMIZAR'|'NAO_PRIORIZAR_EXPANSAO'|'ESTRUTURAR_ANTES_DE_ACELERAR';
export type AttentionDimension={dimension:StrategicDimension;classification:ReadinessClass;score:number;reason:string};
export type StrategicDecision={available:boolean;strategic_direction:string;primary_priority:StrategicPriority|null;parallel_priorities:StrategicDimension[];acquisition_movement:AcquisitionMovement|null;initial_acquisition_movement:AcquisitionMovement|null;management_rule_applied:boolean;main_risk:string;strategic_rationale:string;attention_dimensions:AttentionDimension[];rules_triggered:string[];incomplete_indicators:string[];engine_version:'1.0'};

type Inputs={need:AttractionNeed;readiness:Readiness;conversion:ConversionCapacity;management:GrowthManagementCapacity};
const scoreOf=(value:{need_score?:number|null;score_base?:number|null})=>Number(value.need_score??value.score_base??0);
const attentionReason:Record<StrategicDimension,string>={ATRAIR:'A necessidade de geração de oportunidades exige acompanhamento do movimento de aquisição.',ABSORVER:'A estrutura de atendimento e absorção pode elevar perdas se a demanda avançar sem controle.',CONVERTER:'Fragilidades no processo comercial podem reduzir o aproveitamento das novas oportunidades.',GERIR:'A gestão precisa ampliar visibilidade e previsibilidade para sustentar a evolução.'};
const capacityEntries=(inputs:Inputs)=>[{dimension:'ABSORVER' as const,value:inputs.readiness},{dimension:'CONVERTER' as const,value:inputs.conversion},{dimension:'GERIR' as const,value:inputs.management}];
const filledStrategicValue=(value:any)=>Array.isArray(value)||typeof value==='boolean'||typeof value==='number'?value!==undefined&&value!==null:String(value??'').trim().length>0;
export function normalizeStrategicDecision(calculated:StrategicDecision,persisted:any):StrategicDecision{const result:any={...(calculated||{})};if(!persisted||typeof persisted!=='object')return result;for(const [key,value] of Object.entries(persisted))if(filledStrategicValue(value))result[key]=value;return result}

function movement(need:ReadinessClass,readiness:ReadinessClass,conversion:ReadinessClass):AcquisitionMovement{if(need==='BAIXA')return'NAO_PRIORIZAR_EXPANSAO';if(need==='MEDIA')return readiness==='BAIXA'?'NAO_PRIORIZAR_EXPANSAO':'MANTER_OTIMIZAR';if(readiness==='BAIXA')return'ESTRUTURAR_ANTES_DE_ACELERAR';if(readiness==='MEDIA')return'EXPANDIR_CONTROLADAMENTE';return conversion==='BAIXA'?'EXPANDIR_CONTROLADAMENTE':'ACELERAR'}
function priority(need:ReadinessClass,readiness:ReadinessClass,conversion:ReadinessClass,management:ReadinessClass):StrategicPriority{if(readiness==='BAIXA'&&need==='ALTA')return'ABSORVER';if(readiness!=='BAIXA'&&conversion==='BAIXA')return'CONVERTER';if(readiness!=='BAIXA'&&conversion!=='BAIXA'&&management==='BAIXA')return'GERIR';if(need==='ALTA'&&readiness==='ALTA'&&conversion!=='BAIXA'&&management!=='BAIXA')return'ATRAIR';if(need==='MEDIA'&&![readiness,conversion,management].includes('BAIXA'))return'OTIMIZAR';if(need==='BAIXA'){if(readiness==='BAIXA')return'ABSORVER';if(conversion==='BAIXA')return'CONVERTER';if(management==='BAIXA')return'GERIR';return'CONSOLIDAR'}return need==='ALTA'?'ATRAIR':'CONSOLIDAR'}
function direction(need:ReadinessClass,readiness:ReadinessClass,conversion:ReadinessClass,management:ReadinessClass,finalMovement:AcquisitionMovement){const lows=[readiness,conversion,management].filter(item=>item==='BAIXA').length;if(need==='BAIXA')return lows?'FORTALECER OPERAÇÃO COMERCIAL':'CONSOLIDAR E OTIMIZAR';if(need==='MEDIA')return lows?'FORTALECER OPERAÇÃO COMERCIAL':'OTIMIZAR AQUISIÇÃO E CONVERSÃO';if(readiness==='BAIXA')return'ESTRUTURAR PARA EXPANDIR';if(readiness==='MEDIA')return'EXPANDIR COM CONTROLE';if(conversion==='BAIXA')return'EXPANDIR COM ESTRUTURAÇÃO COMERCIAL';if(finalMovement==='EXPANDIR_CONTROLADAMENTE'&&management==='BAIXA')return'EXPANDIR COM CONTROLE';return'EXPANDIR AQUISIÇÃO'}
function risk(readiness:ReadinessClass,conversion:ReadinessClass,management:ReadinessClass){if(readiness==='BAIXA')return'Perda de oportunidades com aumento da demanda.';if(conversion==='BAIXA')return'Baixo aproveitamento comercial das oportunidades geradas.';if(management==='BAIXA')return'Crescimento sem visibilidade e previsibilidade suficientes.';return'Não foi identificado risco estrutural crítico nas dimensões avaliadas.'}
function rationale(need:ReadinessClass,readiness:ReadinessClass,conversion:ReadinessClass,management:ReadinessClass,primary:StrategicPriority,movementValue:AcquisitionMovement){const needText=need==='ALTA'?'Existe forte necessidade de ampliar a geração de oportunidades.':need==='MEDIA'?'Existe espaço para estabilizar e otimizar a geração de oportunidades.':'A ampliação da geração de oportunidades não aparece como necessidade principal neste momento.';const structure=`A capacidade de absorção está ${readiness==='ALTA'?'bem estruturada':readiness==='MEDIA'?'parcialmente estruturada':'fragilizada'}, enquanto a conversão está em nível ${conversion==='ALTA'?'alto':conversion==='MEDIA'?'médio':'baixo'} e a gestão do crescimento em nível ${management==='ALTA'?'alto':management==='MEDIA'?'médio':'baixo'}.`;const priorityText=`Por isso, a prioridade estratégica experimental é ${primary==='ATRAIR'?'ampliar a aquisição':primary==='ABSORVER'?'fortalecer a absorção':primary==='CONVERTER'?'fortalecer a conversão':primary==='GERIR'?'fortalecer a gestão':primary==='OTIMIZAR'?'otimizar a operação':'consolidar a estrutura atual'}.`;const movementText=`A aquisição deve ${movementValue==='ACELERAR'?'ser acelerada':movementValue==='EXPANDIR_CONTROLADAMENTE'?'avançar de forma controlada':movementValue==='MANTER_OTIMIZAR'?'ser mantida e otimizada':movementValue==='ESTRUTURAR_ANTES_DE_ACELERAR'?'aguardar a estruturação das capacidades críticas antes de acelerar':'não ser priorizada para expansão'}.`;return[needText,structure,priorityText,movementText].join(' ')}

export function strategicDecision(inputs:Inputs):StrategicDecision{const incomplete=[!inputs.need.available&&'Necessidade de Atrair',!inputs.readiness.available&&'Prontidão para Aquisição',!inputs.conversion.available&&'Capacidade de Conversão',!inputs.management.available&&'Capacidade de Gestão do Crescimento'].filter(Boolean) as string[];if(incomplete.length)return{available:false,strategic_direction:'DADOS INSUFICIENTES',primary_priority:null,parallel_priorities:[],acquisition_movement:null,initial_acquisition_movement:null,management_rule_applied:false,main_risk:'Não foi possível determinar o risco principal.',strategic_rationale:'Não existem informações suficientes nas quatro dimensões necessárias para gerar uma direção estratégica confiável.',attention_dimensions:[],rules_triggered:['Dados insuficientes: '+incomplete.join(', ')],incomplete_indicators:incomplete,engine_version:STRATEGIC_ENGINE_VERSION};const need=inputs.need.classification!,readiness=inputs.readiness.classification!,conversion=inputs.conversion.classification!,management=inputs.management.classification!,initial=movement(need,readiness,conversion),management_rule_applied=initial==='ACELERAR'&&management==='BAIXA',finalMovement=management_rule_applied?'EXPANDIR_CONTROLADAMENTE':initial,primary=priority(need,readiness,conversion,management),parallel=capacityEntries(inputs).filter(item=>item.value.classification==='BAIXA'&&item.dimension!==primary).map(item=>item.dimension),attention=capacityEntries(inputs).filter(item=>item.value.classification==='BAIXA'||item.value.classification==='MEDIA'&&item.dimension==='ABSORVER'&&need==='ALTA').map(item=>({dimension:item.dimension,classification:item.value.classification!,score:scoreOf(item.value),reason:attentionReason[item.dimension]})),rules=[`Movimento inicial: ${initial}`,`Prioridade por precedência: ${primary}`];if(management_rule_applied)rules.push('Gestão baixa rebaixou aceleração para expansão controlada.');if(parallel.length)rules.push('Fragilidades paralelas: '+parallel.join(', '));return{available:true,strategic_direction:direction(need,readiness,conversion,management,finalMovement),primary_priority:primary,parallel_priorities:parallel,acquisition_movement:finalMovement,initial_acquisition_movement:initial,management_rule_applied,main_risk:risk(readiness,conversion,management),strategic_rationale:rationale(need,readiness,conversion,management,primary,finalMovement),attention_dimensions:attention,rules_triggered:rules,incomplete_indicators:[],engine_version:STRATEGIC_ENGINE_VERSION}}
