import type {StrategicIntervention} from './strategicInterventionEngine';
import {resolveCommercialPrice,type CommercialSolution} from './commercialPricingResolver';

export type LinkType='PRINCIPAL'|'COMPLEMENTAR'|'PRE_REQUISITO'|'EVOLUCAO_FUTURA';
export type StrategicSolutionLink={id?:string;intervention_code:string;solucao_id:string;tipo_vinculo:LinkType;ordem:number;ativo:boolean;observacao_interna?:string|null};
export type ResolvedStrategicSolution={solucao_id:string;solution:CommercialSolution;tipo_vinculo:LinkType;link_types:LinkType[];ordem:number;source_interventions:string[];origem:'MOTOR_ESTRATEGICO'|'DEPENDENCIA';selected:boolean;future:boolean;dependencies:string[];pricing:ReturnType<typeof resolveCommercialPrice>;parametros_snapshot:Record<string,any>};

const linkRank:Record<LinkType,number>={PRE_REQUISITO:0,PRINCIPAL:1,COMPLEMENTAR:2,EVOLUCAO_FUTURA:3};
const array=(value:any)=>Array.isArray(value)?value:[];

function dependencyIds(solution:CommercialSolution){return array(solution.dependencias_estruturadas).filter((item:any)=>item?.tipo==='solucao'&&typeof item.recurso_id==='string').map((item:any)=>item.recurso_id)}

export function resolveStrategicSolutions(input:{interventions:StrategicIntervention[];links:StrategicSolutionLink[];catalog:CommercialSolution[];valor_ui:number;generated_at?:string}){
 const activeCodes=new Set(array(input.interventions).map(item=>item.intervention_code)),catalog=new Map(input.catalog.map(item=>[item.id,item])),missing=input.interventions.filter(item=>!input.links.some(link=>link.ativo&&link.intervention_code===item.intervention_code)).map(item=>({intervention_code:item.intervention_code,title:item.title,dimension:item.dimension})),grouped=new Map<string,{solution:CommercialSolution;links:StrategicSolutionLink[];source:Set<string>;origin:'MOTOR_ESTRATEGICO'|'DEPENDENCIA'}>();
 for(const link of input.links.filter(item=>item.ativo&&activeCodes.has(item.intervention_code))){const solution=catalog.get(link.solucao_id);if(!solution||solution.ativo===false)continue;const current=grouped.get(solution.id)||{solution,links:[],source:new Set<string>(),origin:'MOTOR_ESTRATEGICO' as const};current.links.push(link);current.source.add(link.intervention_code);grouped.set(solution.id,current)}
 const queue=[...grouped.values()];
 for(let index=0;index<queue.length;index++)for(const dependencyId of dependencyIds(queue[index].solution)){const dependency=catalog.get(dependencyId);if(!dependency||dependency.ativo===false||grouped.has(dependencyId))continue;const value={solution:dependency,links:[] as StrategicSolutionLink[],source:new Set(queue[index].source),origin:'DEPENDENCIA' as const};grouped.set(dependencyId,value);queue.push(value)}
 const generatedAt=input.generated_at||new Date().toISOString(),solutions=[...grouped.values()].map(group=>{const types=group.links.map(link=>link.tipo_vinculo),type:LinkType=group.origin==='DEPENDENCIA'?'PRE_REQUISITO':types.sort((a,b)=>linkRank[a]-linkRank[b])[0]||'PRE_REQUISITO',future=type==='EVOLUCAO_FUTURA',pricing=resolveCommercialPrice(group.solution,input.valor_ui),dependencies=dependencyIds(group.solution),source=[...group.source],order=group.links.length?Math.min(...group.links.map(link=>link.ordem)):0;return{solucao_id:group.solution.id,solution:group.solution,tipo_vinculo:type,link_types:[...new Set(types.length?types:[type])],ordem:order,source_interventions:source,origem:group.origin,selected:!future,future,dependencies,pricing,parametros_snapshot:{flow:'ESTRATEGICO_3_0',solution_id:group.solution.id,solution_code:group.solution.codigo||null,solution_name:group.solution.nome,tipo:group.solution.tipo,ui_utilizada:pricing.ui_utilizada,valor_ui_utilizado:pricing.valor_ui_utilizado,valor_implantacao_calculado:pricing.valor_implantacao,valor_mensal_utilizado:pricing.valor_mensal,fonte_mensalidade:pricing.fonte_mensalidade,source_interventions:source,tipo_vinculo:type,dependencias_resolvidas:dependencies,generated_at:generatedAt}} satisfies ResolvedStrategicSolution}).sort((a,b)=>linkRank[a.tipo_vinculo]-linkRank[b.tipo_vinculo]||a.ordem-b.ordem||a.solution.nome.localeCompare(b.solution.nome,'pt-BR'));
 return{solutions,unmapped_interventions:missing,totals:{implantacao:solutions.filter(item=>item.selected).reduce((sum,item)=>sum+item.pricing.valor_implantacao,0),mensal:solutions.filter(item=>item.selected).reduce((sum,item)=>sum+item.pricing.valor_mensal,0)}};
}

