import type {ActionHorizon,StrategicAction,StrategicActionPlan} from './strategicActionPlanEngine';

export const STRATEGIC_EXECUTION_PLAN_VERSION='1.0';
export type ExecutionPlanStatus='DRAFT'|'PUBLISHED'|'SUPERSEDED';
export type ExecutionActionStatus='PLANNED'|'IN_PROGRESS'|'COMPLETED'|'CANCELLED';
export type ExecutionActionSource='ENGINE'|'CONSULTANT';
export type ExecutionActionOrigin='ENGINE'|'MANUAL'|'CONTEXTUAL';
export type AgreedAction={id?:string;source_type:ExecutionActionSource;action_origin?:ExecutionActionOrigin;source_action_code:string|null;contextual_action_key?:string|null;recommended:StrategicAction|null;strategic_dimension?:string|null;agreed_title:string;agreed_objective:string;agreed_indicator:string;agreed_target:string;responsible:string;due_date:string;agreed_horizon:ActionHorizon;status:ExecutionActionStatus;consultant_notes:string;strategic_change_reason:string;start_condition:string;completed_at:string|null};

export function agreedFromEngine(action:StrategicAction):AgreedAction{return{source_type:'ENGINE',action_origin:'ENGINE',source_action_code:action.action_code,contextual_action_key:null,recommended:{...action},agreed_title:action.title,agreed_objective:action.expected_result,agreed_indicator:action.tracking_indicator,agreed_target:'',responsible:'',due_date:'',agreed_horizon:action.horizon,status:'PLANNED',consultant_notes:'',strategic_change_reason:'',start_condition:action.horizon==='QUANDO_ESTIVER_PRONTO'?'Avançar após redução das fragilidades prioritárias da operação.':'',completed_at:null}}
export function manualAction(horizon:ActionHorizon='AGORA'):AgreedAction{return{source_type:'CONSULTANT',action_origin:'MANUAL',source_action_code:null,contextual_action_key:null,recommended:null,agreed_title:'',agreed_objective:'',agreed_indicator:'',agreed_target:'',responsible:'',due_date:'',agreed_horizon:horizon,status:'PLANNED',consultant_notes:'',strategic_change_reason:'',start_condition:'',completed_at:null}}
export function originalRecommendations(plan:StrategicActionPlan){return plan.all_actions.map(action=>({...action}))}
export function validateAction(action:AgreedAction){const errors:string[]=[];if(!action.agreed_title.trim())errors.push('Ação sem título.');if(!action.agreed_objective.trim())errors.push('Ação sem objetivo.');if(!action.agreed_horizon)errors.push('Ação sem horizonte.');if(action.source_type==='ENGINE'&&action.recommended&&action.agreed_horizon!==action.recommended.horizon&&!action.strategic_change_reason.trim())errors.push('Informe o motivo da alteração estratégica.');if(action.source_type==='CONSULTANT'&&action.source_action_code)errors.push('Ação do consultor não pode possuir código do Motor.');return errors}
export function priorityCoverage(actions:AgreedAction[],primaryPriority?:string|null){const primary=String(primaryPriority||'').trim().toUpperCase();if(!primary)return true;return actions.some(action=>action.status!=='CANCELLED'&&String(action.strategic_dimension||action.recommended?.dimension||'').trim().toUpperCase()===primary)}
export function validatePublication(actions:AgreedAction[],context:{primaryPriority?:string|null;priorityCoverageJustification?:string|null}={}){const errors=actions.length?actions.flatMap(validateAction):['Inclua ao menos uma ação no Plano.'];if(!priorityCoverage(actions,context.primaryPriority)&&!String(context.priorityCoverageJustification||'').trim())errors.push('Inclua ao menos uma ação relacionada à prioridade principal ou registre uma justificativa explícita para sua ausência.');const warnings:string[]=[];const withoutResponsible=actions.filter(action=>!action.responsible.trim()).length,withoutDue=actions.filter(action=>action.agreed_horizon!=='QUANDO_ESTIVER_PRONTO'&&!action.due_date).length,withoutTarget=actions.filter(action=>action.agreed_indicator.trim()&&!action.agreed_target.trim()).length;if(withoutResponsible)warnings.push('Existem '+withoutResponsible+' ações sem responsável definido.');if(withoutDue)warnings.push('Existem '+withoutDue+' ações aplicáveis sem prazo definido.');if(withoutTarget)warnings.push('Existem '+withoutTarget+' ações sem meta acordada.');return{errors,warnings}}
export function executionSummary(actions:AgreedAction[]){return{total:actions.length,now:actions.filter(action=>action.agreed_horizon==='AGORA').length,later:actions.filter(action=>action.agreed_horizon==='DEPOIS').length,whenReady:actions.filter(action=>action.agreed_horizon==='QUANDO_ESTIVER_PRONTO').length,responsibles:actions.filter(action=>action.responsible.trim()).length,dueDates:actions.filter(action=>action.agreed_horizon!=='QUANDO_ESTIVER_PRONTO'&&action.due_date).length,applicableDueDates:actions.filter(action=>action.agreed_horizon!=='QUANDO_ESTIVER_PRONTO').length,targets:actions.filter(action=>action.agreed_target.trim()).length,applicableTargets:actions.filter(action=>action.agreed_indicator.trim()).length}}
export function setActionStatus(action:AgreedAction,status:ExecutionActionStatus,now=new Date().toISOString()):AgreedAction{return{...action,status,completed_at:status==='COMPLETED'?(action.completed_at||now):null}}
