import type {StrategicDecision,StrategicDimension} from './strategicEngine';
import type {PreservedStrength,StrategicIntervention,StrategicInterventions} from './strategicInterventionEngine';

export const STRATEGIC_ACTION_PLAN_ENGINE_VERSION='1.0';
export type ActionHorizon='AGORA'|'DEPOIS'|'QUANDO_ESTIVER_PRONTO';
type ActionDefinition={action_code:string;intervention_code:string;capability:string;dimension:StrategicDimension;title:string;what_to_do:string;expected_result:string;tracking_indicator:string;initial_target:string|null;target_type:'PERCENTAGE'|'COUNT'|'BOOLEAN'|null;execution_notes:string;engine_version:'1.0'};
export type StrategicAction={action_code:string;intervention_code:string;capability:string;dimension:StrategicDimension;title:string;what_to_do:string;expected_result:string;tracking_indicator:string;initial_target:string|null;target_type:ActionDefinition['target_type'];horizon:ActionHorizon;priority_level:StrategicIntervention['priority_level'];source_intervention:string;source_evidence_code:string;source_question_id:string;strategic_priority_source:string;depends_on_actions:string[];severity:StrategicIntervention['severity'];evidence_score:number};
export type HiddenAction={action_code:string;title:string;horizon:ActionHorizon;reason:'limite do card'|'intervenção não selecionada para exibição'};
export type StrategicActionPlan={strategic_direction:string;primary_priority:StrategicDecision['primary_priority'];acquisition_movement:StrategicDecision['acquisition_movement'];now_actions:StrategicAction[];later_actions:StrategicAction[];when_ready_actions:StrategicAction[];all_actions:StrategicAction[];hidden_actions:HiddenAction[];strengths_to_preserve:PreservedStrength[];action_plan_summary:string;total_actions:number;engine_version:'1.0'};

const a=(action_code:string,intervention_code:string,capability:string,dimension:StrategicDimension,title:string,what_to_do:string,expected_result:string,tracking_indicator:string,initial_target:string|null=null,target_type:ActionDefinition['target_type']=null,execution_notes=''):ActionDefinition=>({action_code,intervention_code,capability,dimension,title,what_to_do,expected_result,tracking_indicator,initial_target,target_type,execution_notes,engine_version:STRATEGIC_ACTION_PLAN_ENGINE_VERSION});
export const ACTION_CATALOG:ActionDefinition[]=[
 a('ACT_ABS_FIRST_RESPONSE','INT_ABS_RESPONSE_SPEED','VELOCIDADE_ATENDIMENTO','ABSORVER','Padronizar a primeira resposta','Definir e aplicar um padrão para a resposta inicial aos novos contatos comerciais.','Reduzir atrasos e perdas no primeiro contato.','Tempo médio até a primeira resposta.'),
 a('ACT_ABS_CENTRALIZATION','INT_ABS_CENTRALIZATION','CENTRALIZACAO','ABSORVER','Centralizar as conversas comerciais','Definir um ponto central de acompanhamento para as conversas comerciais.','Assegurar continuidade e visibilidade do atendimento.','Percentual de conversas acompanhadas no fluxo central.'),
 a('ACT_ABS_OWNERSHIP','INT_ABS_OWNERSHIP','RESPONSABILIDADE','ABSORVER','Definir responsáveis pelas oportunidades','Estabelecer a regra para atribuir um responsável a cada oportunidade ativa.','Eliminar oportunidades sem responsável definido.','Percentual de oportunidades ativas com responsável.'),
 a('ACT_ABS_DISTRIBUTION','INT_ABS_DISTRIBUTION','DISTRIBUICAO','ABSORVER','Padronizar a distribuição de oportunidades','Definir critérios e rotina para distribuir novas oportunidades entre os responsáveis.','Tornar a distribuição consistente e verificável.','Percentual de oportunidades distribuídas conforme o padrão.'),
 a('ACT_ABS_HISTORY','INT_ABS_HISTORY','HISTORICO','ABSORVER','Consolidar o histórico do cliente','Definir quais interações e informações devem compor o histórico comercial de cada cliente.','Garantir contexto para a continuidade do relacionamento.','Percentual de oportunidades com histórico atualizado.'),
 a('ACT_ABS_RECORD_STANDARD','INT_ABS_RECORD_STANDARD','PADRAO_REGISTRO','ABSORVER','Padronizar o registro comercial','Definir e aplicar as informações mínimas obrigatórias para registrar cada oportunidade.','Aumentar consistência e confiabilidade dos registros.','Percentual de registros preenchidos conforme o padrão.'),
 a('ACT_ABS_RETURN_CONTROL','INT_ABS_RETURN_CONTROL','CONTROLE_RETORNO','ABSORVER','Implantar rotina de controle de retornos','Definir como cada retorno será registrado, acompanhado e concluído.','Reduzir contatos sem continuidade e retornos fora do momento esperado.','Percentual de retornos previstos acompanhados.'),
 a('ACT_ABS_PIPELINE','INT_ABS_PIPELINE','VISAO_PIPELINE','ABSORVER','Consolidar a visão do pipeline','Organizar as oportunidades ativas em uma visão única por etapa e situação.','Permitir acompanhamento contínuo das oportunidades em andamento.','Percentual de oportunidades ativas visíveis no pipeline.'),
 a('ACT_CONV_QUALIFICATION','INT_CONV_QUALIFICATION','QUALIFICACAO','CONVERTER','Definir critérios de qualificação','Estabelecer e aplicar critérios para qualificar e priorizar oportunidades.','Concentrar o esforço comercial nas oportunidades com maior aderência.','Percentual de oportunidades avaliadas pelos critérios definidos.'),
 a('ACT_CONV_FOLLOW_UP','INT_CONV_FOLLOW_UP','ROTINA_ACOMPANHAMENTO','CONVERTER','Estabelecer rotina de acompanhamento','Definir uma cadência de acompanhamento das oportunidades até sua conclusão.','Aumentar continuidade e disciplina no processo comercial.','Percentual de oportunidades acompanhadas dentro da rotina.'),
 a('ACT_CONV_NEXT_STEP','INT_CONV_NEXT_STEP','PROXIMO_PASSO','CONVERTER','Definir o próximo passo das negociações','Registrar para cada negociação a próxima ação, o responsável e sua sequência.','Evitar negociações sem direcionamento claro.','Percentual de negociações ativas com próximo passo definido.'),
 a('ACT_CONV_STAGES','INT_CONV_STAGES','ETAPAS_COMERCIAIS','CONVERTER','Definir etapas e critérios de avanço','Estruturar as etapas do processo comercial e os critérios para avançar entre elas.','Tornar o processo comercial visível e consistente.','Percentual de oportunidades classificadas em uma etapa válida.'),
 a('ACT_CONV_STALLED','INT_CONV_STALLED','OPORTUNIDADES_PARADAS','CONVERTER','Criar rotina de identificação de oportunidades paradas','Definir o critério de oportunidade parada e revisar periodicamente os casos identificados.','Permitir ação antes que oportunidades sejam perdidas por falta de evolução.','Quantidade de oportunidades paradas revisadas.'),
 a('ACT_CONV_LOSS_REASON','INT_CONV_LOSS','MOTIVOS_PERDA','CONVERTER','Padronizar registro dos motivos de perda','Definir e aplicar um padrão para registrar o motivo de perda de cada oportunidade encerrada sem venda.','Identificar os principais fatores responsáveis pela perda de oportunidades comerciais.','Percentual de oportunidades perdidas com motivo registrado.','>= 90%','PERCENTAGE'),
 a('ACT_CONV_MEASUREMENT','INT_CONV_MEASUREMENT','MENSURACAO_CONVERSAO','CONVERTER','Implantar mensuração da conversão comercial','Definir como a conversão será calculada e acompanhada entre as etapas comerciais.','Permitir análise consistente da transformação de oportunidades em vendas.','Taxa de conversão por etapa e taxa de conversão final.'),
 a('ACT_GROWTH_REPORTS','INT_GROWTH_REPORTS','RELATORIOS_AUTOMATIZADOS','GERIR','Estruturar acesso recorrente aos relatórios','Definir quais relatórios precisam estar disponíveis e como serão consultados na gestão.','Reduzir dependência de consolidações manuais.','Frequência de atualização dos relatórios necessários.'),
 a('ACT_GROWTH_GOALS','INT_GROWTH_GOALS','METAS_RESULTADOS','GERIR','Definir metas e resultados comerciais','Formalizar metas, resultados esperados e critérios de acompanhamento.','Criar direção comum para a operação comercial.','Percentual de indicadores prioritários com meta definida.'),
 a('ACT_GROWTH_PREDICTABILITY','INT_GROWTH_PREDICTABILITY','PREVISIBILIDADE_COMERCIAL','GERIR','Estruturar projeção comercial','Definir uma rotina para projetar oportunidades, vendas e variações relevantes.','Aumentar previsibilidade sobre os resultados comerciais.','Diferença entre resultado projetado e realizado.'),
 a('ACT_GROWTH_AUTONOMY','INT_GROWTH_AUTONOMY','AUTONOMIA_OPERACIONAL','GERIR','Distribuir responsabilidades operacionais','Definir responsabilidades, decisões e rotinas que não devem depender exclusivamente do gestor.','Aumentar autonomia e continuidade da operação.','Quantidade de rotinas críticas com responsável definido.'),
 a('ACT_GROWTH_DATA_DECISIONS','INT_GROWTH_DATA_DECISIONS','DECISAO_POR_DADOS','GERIR','Criar rotina de decisão baseada em dados','Definir quais dados serão considerados nas decisões e registrar as ações resultantes.','Aumentar consistência das decisões comerciais.','Percentual de reuniões de gestão com indicadores analisados.'),
 a('ACT_GROWTH_INDICATOR_CENTRALIZATION','INT_GROWTH_INDICATOR_CENTRALIZATION','CENTRALIZACAO_INDICADORES','GERIR','Consolidar indicadores comerciais','Organizar os indicadores prioritários em uma visão única de acompanhamento.','Facilitar a leitura integrada do desempenho comercial.','Percentual de indicadores prioritários disponíveis na visão consolidada.'),
 a('ACT_GROWTH_ROUTINE','INT_GROWTH_ROUTINE','ROTINA_GESTAO','GERIR','Estabelecer rotina de gestão comercial','Definir uma cadência para analisar resultados, decidir ações e acompanhar sua execução.','Criar disciplina de gestão e melhoria contínua.','Percentual de reuniões de gestão realizadas conforme a cadência.'),
 a('ACT_ACQ_TRACEABILITY','INT_ACQ_TRACEABILITY','RASTREABILIDADE_AQUISICAO','ATRAIR','Padronizar identificação da origem das oportunidades','Definir e aplicar um padrão para registrar a origem de cada oportunidade.','Permitir rastrear quais fontes geram oportunidades comerciais.','Percentual de oportunidades com origem identificada.'),
 a('ACT_ACQ_CHANNEL_EFFICIENCY','INT_ACQ_CHANNEL_EFFICIENCY','EFICIENCIA_CANAIS','ATRAIR','Comparar a eficiência dos canais','Definir critérios para comparar os canais pela qualidade e pelos resultados das oportunidades geradas.','Identificar os canais com maior contribuição comercial.','Resultado comercial por canal de aquisição.'),
 a('ACT_ACQ_IDEAL_CUSTOMER','INT_ACQ_IDEAL_CUSTOMER','CLIENTE_IDEAL','ATRAIR','Definir critérios do cliente ideal','Consolidar características que indiquem aderência, potencial e prioridade comercial.','Orientar aquisição e qualificação para perfis com maior potencial.','Percentual de oportunidades aderentes ao perfil definido.'),
 a('ACT_ACQ_MEASUREMENT','INT_ACQ_MEASUREMENT','MENSURACAO_AQUISICAO','ATRAIR','Estruturar mensuração do custo por oportunidade','Definir quais investimentos e oportunidades serão considerados no cálculo de aquisição.','Permitir acompanhar a eficiência econômica da geração de oportunidades.','Custo por oportunidade gerada.'),
 a('ACT_ACQ_DEMAND','INT_ACQ_DEMAND','DEMANDA','ATRAIR','Definir plano de geração de demanda','Estabelecer a necessidade de oportunidades e as frentes de atuação para produzir demanda consistente.','Aproximar o volume de oportunidades das metas comerciais.','Quantidade de oportunidades qualificadas geradas.'),
 a('ACT_ACQ_PREDICTABILITY','INT_ACQ_PREDICTABILITY','PREVISIBILIDADE_AQUISICAO','ATRAIR','Estruturar previsibilidade da aquisição','Definir uma rotina para acompanhar volume, origem e estabilidade da geração de oportunidades.','Reduzir oscilações e aumentar previsibilidade da aquisição.','Variação do volume de oportunidades entre períodos.'),
 a('ACT_ACQ_STRATEGY','INT_ACQ_STRATEGY','ESTRATEGIA_AQUISICAO','ATRAIR','Definir estratégia contínua de aquisição','Formalizar objetivos, públicos, frentes de atuação e critérios de acompanhamento da aquisição.','Transformar ações pontuais em uma estratégia contínua e acompanhada.','Percentual de ações de aquisição vinculadas à estratégia definida.'),
 a('ACT_ACQ_REACTIVATION','INT_ACQ_REACTIVATION','REATIVACAO_BASE','ATRAIR','Criar rotina de reativação da base','Definir critérios e cadência para retomar contatos e clientes com potencial de nova oportunidade.','Aproveitar melhor a base existente para gerar oportunidades.','Quantidade de oportunidades originadas pela reativação da base.')
];

const actionByIntervention=new Map(ACTION_CATALOG.map(item=>[item.intervention_code,item]));
const actionByCapability=new Map(ACTION_CATALOG.map(item=>[item.capability,item]));
const horizonOrder:Record<ActionHorizon,number>={AGORA:0,DEPOIS:1,QUANDO_ESTIVER_PRONTO:2};
const priorityOrder:Record<StrategicIntervention['priority_level'],number>={P1:0,P2:1,P3:2,P4:3};
const severityOrder:Record<StrategicIntervention['severity'],number>={CRITICO:0,ATENCAO:1,ESTRUTURADO:2};
const acquisitionCodes=new Set(ACTION_CATALOG.filter(item=>item.dimension==='ATRAIR').map(item=>item.intervention_code));
const dimensionCopy:Record<string,string>={ATRAIR:'aquisição',ABSORVER:'absorção das oportunidades',CONVERTER:'conversão comercial',GERIR:'gestão do crescimento'};

function actionHorizon(intervention:StrategicIntervention,decision:StrategicDecision):ActionHorizon{
 if(acquisitionCodes.has(intervention.intervention_code)){
  if(decision.acquisition_movement==='ESTRUTURAR_ANTES_DE_ACELERAR')return'QUANDO_ESTIVER_PRONTO';
  if(decision.acquisition_movement==='ACELERAR')return'AGORA';
  return'DEPOIS';
 }
 return intervention.priority_level==='P1'?'AGORA':'DEPOIS';
}
function planSummary(decision:StrategicDecision,now:StrategicAction[],later:StrategicAction[],whenReady:StrategicAction[]){
 const focus=dimensionCopy[String(decision.primary_priority)]||'capacidade operacional prioritária',start=now.length?'O plano começa pelo fortalecimento da '+focus+', priorizando as fragilidades identificadas.':'O plano começa pela consolidação da capacidade estratégica prioritária.',laterText=later.length?'As capacidades complementares e paralelas devem evoluir na sequência, sem substituir o foco inicial.':'',acquisition=decision.acquisition_movement==='ESTRUTURAR_ANTES_DE_ACELERAR'?'A expansão da aquisição deve avançar somente após a redução das fragilidades prioritárias da operação.':decision.acquisition_movement==='EXPANDIR_CONTROLADAMENTE'?'As ações de aquisição podem avançar de forma controlada na sequência, sem substituir as prioridades atuais.':decision.acquisition_movement==='ACELERAR'?'A aquisição pode avançar no horizonte atual, preservando as ações críticas da prioridade principal.':decision.acquisition_movement==='MANTER_OTIMIZAR'?'A aquisição deve ser mantida e otimizada na sequência.':'A expansão da aquisição não deve ser priorizada neste momento.';
 return[start,laterText,whenReady.length||decision.acquisition_movement?acquisition:''].filter(Boolean).join(' ');
}

export function strategicActionPlan(decision:StrategicDecision,interventions:StrategicInterventions):StrategicActionPlan{
 const all:StrategicAction[]=[],unmapped:HiddenAction[]=[];
 for(const intervention of interventions.all_interventions){
  const definition=actionByIntervention.get(intervention.intervention_code);
  if(!definition){unmapped.push({action_code:intervention.intervention_code,title:intervention.title,horizon:actionHorizon(intervention,decision),reason:'intervenção não selecionada para exibição'});continue}
  const depends_on_actions=intervention.depends_on.flatMap(capability=>{const dependency=actionByCapability.get(capability);return dependency?[dependency.action_code]:[]});
  all.push({action_code:definition.action_code,intervention_code:intervention.intervention_code,capability:intervention.capability,dimension:intervention.dimension,title:definition.title,what_to_do:definition.what_to_do,expected_result:definition.expected_result,tracking_indicator:definition.tracking_indicator,initial_target:definition.initial_target,target_type:definition.target_type,horizon:actionHorizon(intervention,decision),priority_level:intervention.priority_level,source_intervention:intervention.title,source_evidence_code:intervention.source_evidence_code,source_question_id:intervention.source_question_id,strategic_priority_source:intervention.strategic_priority_source,depends_on_actions,severity:intervention.severity,evidence_score:intervention.evidence_score});
 }
 all.sort((left,right)=>horizonOrder[left.horizon]-horizonOrder[right.horizon]||priorityOrder[left.priority_level]-priorityOrder[right.priority_level]||severityOrder[left.severity]-severityOrder[right.severity]||left.evidence_score-right.evidence_score||ACTION_CATALOG.findIndex(item=>item.action_code===left.action_code)-ACTION_CATALOG.findIndex(item=>item.action_code===right.action_code));
 const hidden:HiddenAction[]=[...unmapped],markHidden=(items:StrategicAction[])=>{for(const item of items)hidden.push({action_code:item.action_code,title:item.title,horizon:item.horizon,reason:'limite do card'})},limit=(horizon:ActionHorizon)=>{const candidates=all.filter(item=>item.horizon===horizon),visible=candidates.slice(0,3);markHidden(candidates.slice(3));return visible},now=limit('AGORA'),laterCandidates=all.filter(item=>item.horizon==='DEPOIS'),laterAcquisition=laterCandidates.filter(item=>item.dimension==='ATRAIR'),laterOperational=laterCandidates.filter(item=>item.dimension!=='ATRAIR'),later=laterAcquisition.length&&laterOperational.length?[...laterOperational.slice(0,2),laterAcquisition[0]]:laterCandidates.slice(0,3),laterVisible=new Set(later.map(item=>item.action_code)),whenReady=limit('QUANDO_ESTIVER_PRONTO');
 markHidden(laterCandidates.filter(item=>!laterVisible.has(item.action_code)));
 return{strategic_direction:decision.strategic_direction,primary_priority:decision.primary_priority,acquisition_movement:decision.acquisition_movement,now_actions:now,later_actions:later,when_ready_actions:whenReady,all_actions:all,hidden_actions:hidden,strengths_to_preserve:interventions.strengths_to_preserve.slice(0,3),action_plan_summary:planSummary(decision,now,later,whenReady),total_actions:all.length,engine_version:STRATEGIC_ACTION_PLAN_ENGINE_VERSION};
}
