import type {StrategicIntervention} from './strategicInterventionEngine';
import {resolveCommercialPrice,type CommercialSolution} from './commercialPricingResolver';
import {commercialDependencyRules,resolveCommercialDependencies,type DependencyRequirement} from './commercialDependencyResolver';
export type LinkType='PRINCIPAL'|'COMPLEMENTAR'|'PRE_REQUISITO'|'EVOLUCAO_FUTURA';
export type StrategicSolutionLink={id?:string;intervention_code:string;solucao_id:string;tipo_vinculo:LinkType;ordem:number;ativo:boolean;observacao_interna?:string|null};
export type ResolvedStrategicSolution={solucao_id:string;solution:CommercialSolution;tipo_vinculo:LinkType;link_types:LinkType[];ordem:number;source_interventions:string[];origem:'MOTOR_ESTRATEGICO'|'DEPENDENCIA';selected:boolean;future:boolean;dependencies:string[];parent_solution_ids:string[];dependency_source:string[];obrigatoriedade:DependencyRequirement|null;dependency_group?:'RECURSO_IMPLANTACAO';pricing:ReturnType<typeof resolveCommercialPrice>;parametros_snapshot:Record<string,any>};
const rank:Record<LinkType,number>={PRE_REQUISITO:0,PRINCIPAL:1,COMPLEMENTAR:2,EVOLUCAO_FUTURA:3},list=(v:any):any[]=>Array.isArray(v)?v:[];
export function resolveStrategicSolutions(input:{interventions:StrategicIntervention[];links:StrategicSolutionLink[];catalog:CommercialSolution[];valor_ui:number;generated_at?:string}){
 const activeCodes=new Set(list(input.interventions).map(x=>x.intervention_code)),catalog=new Map(input.catalog.map(x=>[x.id,x])),missing=input.interventions.filter(x=>!input.links.some(l=>l.ativo&&l.intervention_code===x.intervention_code)).map(x=>({intervention_code:x.intervention_code,title:x.title,dimension:x.dimension})),direct=new Map<string,{solution:CommercialSolution;links:StrategicSolutionLink[];source:Set<string>}>();
 for(const link of input.links.filter(x=>x.ativo&&activeCodes.has(x.intervention_code))){const solution=catalog.get(link.solucao_id);if(!solution||solution.ativo===false)continue;const current=direct.get(solution.id)||{solution,links:[],source:new Set<string>()};current.links.push(link);current.source.add(link.intervention_code);direct.set(solution.id,current)}
 const types=new Map([...direct].map(([id,g])=>[id,g.links.map(x=>x.tipo_vinculo).sort((a,b)=>rank[a]-rank[b])[0]||'PRE_REQUISITO'])),roots=[...direct.keys()].filter(id=>types.get(id)!=='EVOLUCAO_FUTURA'),derived=resolveCommercialDependencies({selectedSolutionIds:roots,catalog:input.catalog}),generatedAt=input.generated_at||new Date().toISOString(),rows:any[]=[];
 for(const[id,g]of direct){const linkTypes=g.links.map(x=>x.tipo_vinculo),type=types.get(id)!,dependency=derived.find(x=>x.recurso_id===id);rows.push({solucao_id:id,solution:g.solution,tipo_vinculo:type,link_types:[...new Set(linkTypes)],ordem:Math.min(...g.links.map(x=>x.ordem)),source_interventions:[...g.source],origem:'MOTOR_ESTRATEGICO',selected:type!=='EVOLUCAO_FUTURA',future:type==='EVOLUCAO_FUTURA',dependencies:commercialDependencyRules(g.solution).map(x=>x.recurso_id),parent_solution_ids:dependency?.parent_solution_ids||[],dependency_source:dependency?.dependency_source||[],obrigatoriedade:dependency?.obrigatoriedade||null})}
 for(const item of derived)if(!direct.has(item.recurso_id))rows.push({solucao_id:item.recurso_id,solution:item.solution,tipo_vinculo:'PRE_REQUISITO',link_types:['PRE_REQUISITO'],ordem:item.ordem,source_interventions:[],origem:'DEPENDENCIA',selected:item.obrigatoriedade==='OBRIGATORIA',future:false,dependencies:commercialDependencyRules(item.solution).map(x=>x.recurso_id),parent_solution_ids:item.parent_solution_ids,dependency_source:item.dependency_source,obrigatoriedade:item.obrigatoriedade,dependency_group:item.solution.tipo.includes('Implantação')?'RECURSO_IMPLANTACAO':undefined});
 const solutions:ResolvedStrategicSolution[]=rows.map(row=>{const pricing=resolveCommercialPrice(row.solution,input.valor_ui);return{...row,pricing,parametros_snapshot:{flow:'ESTRATEGICO_3_0',origem:row.origem,solution_id:row.solution.id,solution_code:row.solution.codigo||null,solution_name:row.solution.nome,tipo:row.solution.tipo,parent_solution_ids:row.parent_solution_ids,dependency_source:row.dependency_source,obrigatoriedade:row.obrigatoriedade,ui_utilizada:pricing.ui_utilizada,valor_ui_utilizado:pricing.valor_ui_utilizado,valor_implantacao_calculado:pricing.valor_implantacao,valor_mensal_utilizado:pricing.valor_mensal,fonte_mensalidade:pricing.fonte_mensalidade,source_interventions:row.source_interventions,tipo_vinculo:row.tipo_vinculo,dependencias_resolvidas:row.dependencies,generated_at:generatedAt}}}).sort((a,b)=>rank[a.tipo_vinculo]-rank[b.tipo_vinculo]||a.ordem-b.ordem||a.solution.nome.localeCompare(b.solution.nome,'pt-BR'));
 return{solutions,unmapped_interventions:missing,totals:{implantacao:solutions.filter(x=>x.selected).reduce((s,x)=>s+x.pricing.valor_implantacao,0),mensal:solutions.filter(x=>x.selected).reduce((s,x)=>s+x.pricing.valor_mensal,0)}};
}

