const URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const headers=()=>({'Content-Type':'application/json',apikey:KEY!,Authorization:`Bearer ${KEY}`});
export const JOURNEY_STAGES=['Diagnóstico Concluído','Reunião Agendada','Reunião Realizada','Plano Estratégico em Elaboração','Plano Estratégico Concluído','Proposta Liberada','Aceite Realizado','Aguardando Pagamento','Pagamento Confirmado','Kickoff','Implantação','Cliente Ativo'];
async function request(path:string,init:RequestInit={}){const r=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:{...headers(),...(init.headers||{})},cache:'no-store'});if(!r.ok)throw new Error(await r.text());const body=await r.text();return body?JSON.parse(body):null}
export async function diagnosticContext(diagnosticoId?:string|null,empresaId?:string|null){let diagnostic:any;if(diagnosticoId)diagnostic=(await request(`diagnosticos?id=eq.${encodeURIComponent(diagnosticoId)}&select=*&limit=1`))?.[0];if(!diagnostic&&empresaId)diagnostic=(await request(`diagnosticos?empresa_id=eq.${encodeURIComponent(empresaId)}&select=*&order=created_at.desc&limit=1`))?.[0];return{diagnostic,diagnosticoId:diagnostic?.id||diagnosticoId,empresaId:diagnostic?.empresa_id||empresaId}}
export async function advanceJourney(input:{diagnosticoId?:string|null;empresaId?:string|null;status:string;title?:string;description?:string;manual?:boolean}){const c=await diagnosticContext(input.diagnosticoId,input.empresaId);if(!c.diagnosticoId||!c.empresaId)throw new Error('Diagnóstico ou empresa não encontrado para atualizar a jornada.');await request(`diagnosticos?id=eq.${encodeURIComponent(c.diagnosticoId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:input.status,updated_at:new Date().toISOString()})});await request('diagnostico_status_historico',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({diagnostico_id:c.diagnosticoId,status:input.status})});await request('dossie_eventos',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({empresa_id:c.empresaId,diagnostico_id:c.diagnosticoId,tipo:input.manual?'Ajuste manual':'Jornada',titulo:input.title||(input.manual?'Etapa alterada manualmente pelo Usuário Master':input.status),descricao:input.description||`Jornada atualizada para ${input.status}.`,data_evento:new Date().toISOString(),concluido:true})});return c}
export async function ensurePlan(diagnosticoId:string,empresaId:string){const existing=(await request(`planos_estrategicos?diagnostico_id=eq.${encodeURIComponent(diagnosticoId)}&select=*&limit=1`))?.[0];if(existing)return existing;const d=(await request(`diagnosticos?id=eq.${encodeURIComponent(diagnosticoId)}&select=*&limit=1`))?.[0];const payload={empresa_id:empresaId,diagnostico_id:diagnosticoId,status:'Rascunho',resumo:d?.parecer||'',situacao_atual:`IEG atual: ${d?.pontuacao_geral||0}/100. Nível: ${d?.nivel_maturidade||'a definir'}. Maior força: ${d?.maior_pilar||'a definir'}. Principal gargalo: ${d?.menor_pilar||'a definir'}.`,prioridades:Array.isArray(d?.plano_acao)?d.plano_acao.map((x:any)=>x.title).filter(Boolean).join('\n'):''};return(await request('planos_estrategicos',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)}))?.[0]}
export async function updatePlanJourney(diagnosticoId:string,action:'start'|'complete'|'release'){const c=await diagnosticContext(diagnosticoId);if(!c.diagnostic)throw new Error('Diagnóstico não encontrado.');const plan=await ensurePlan(c.diagnosticoId!,c.empresaId!);const status=action==='start'?'Plano Estratégico em Elaboração':action==='complete'?'Plano Estratégico Concluído':'Proposta Liberada';if(action==='complete'&&(!plan.resumo||!plan.objetivos||!plan.prioridades))throw new Error('Preencha Resumo Executivo, Objetivos e Prioridades antes de concluir o plano.');const changes:any={status:action==='start'?'Em Consolidação':action==='complete'?'Plano Concluído':'Plano Liberado ao Cliente',updated_at:new Date().toISOString()};if(action==='release'){changes.liberado_cliente=true;changes.liberado_em=new Date().toISOString()}await request(`planos_estrategicos?id=eq.${plan.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(changes)});return advanceJourney({diagnosticoId:c.diagnosticoId,empresaId:c.empresaId,status,title:status,description:action==='release'?'Plano, proposta e documentos liberados para análise do cliente.':undefined})}

