import Link from "next/link";
import type { ReactNode } from "react";
import { brandLogo } from "@/components/brand";
import { LandingMotion } from "@/components/landing/LandingMotion";
import styles from "./AcquisitionLanding.module.css";

const problems = ["Leads chegam e ficam sem retorno.", "Cada vendedor acompanha os clientes de um jeito.", "Você não sabe quantas oportunidades estão realmente abertas.", "Não consegue identificar com clareza de onde vêm as melhores vendas.", "Investe para gerar demanda, mas perde visibilidade depois que o lead entra.", "Sabe que existem gargalos, mas não sabe o que atacar primeiro."];
const pillars = [["Atrair", "Gerar oportunidades de forma consistente."], ["Converter", "Atender, acompanhar e transformar oportunidades em vendas."], ["Crescer", "Medir resultados, ganhar previsibilidade e evoluir a operação."]];
const deliverables = ["Índice Escala Growth — IEG", "Nível atual da operação", "Maior força", "Principal gargalo", "Análise dos pilares", "Direção estratégica recomendada"];
const steps = [["01", "Responda ao diagnóstico", "Conte como sua operação comercial funciona hoje por meio de uma análise estruturada."], ["02", "Receba sua análise na hora", "Assim que finalizar, seu Diagnóstico Escala Growth fica disponível online com seu resultado, forças, gargalos e estágio atual da operação. Você pode consultar, imprimir e começar a utilizar as informações imediatamente."], ["03", "Entenda o próximo passo", "Com o diagnóstico em mãos, você identifica o que merece prioridade e ganha uma direção mais clara para evoluir sua operação comercial."]];
const audience = ["Empresas que já recebem oportunidades", "Possuem atendimento ou vendas estruturadas de alguma forma", "Querem organizar melhor o processo comercial", "Precisam acompanhar leads e oportunidades", "Querem entender seus gargalos antes de investir mais em aquisição", "Precisam de mais clareza sobre onde priorizar esforços"];
const faqs = [["O que é o Diagnóstico Escala Growth?", "É uma análise estruturada da operação comercial que identifica forças, gargalos e prioridades nos pilares Atrair, Converter e Crescer."], ["Recebo o resultado na hora?", "Sim. Ao finalizar, o resultado fica disponível online imediatamente."], ["Posso imprimir meu diagnóstico?", "Sim. O diagnóstico gerado fica disponível para consulta e impressão."], ["Quanto tempo leva para responder?", "O tempo varia conforme as respostas, mas o preenchimento normalmente leva apenas alguns minutos."], ["O diagnóstico é uma proposta comercial?", "Não. O diagnóstico é uma análise da operação. Qualquer proposta é tratada separadamente e somente quando houver aderência."], ["Preciso instalar alguma ferramenta?", "Não. O diagnóstico é realizado online e não exige instalação de software."], ["O que acontece depois do resultado?", "Você já pode utilizar as informações para compreender prioridades. Se fizer sentido, poderá avançar posteriormente para uma análise estratégica com a Escala Vendas."]];

export function AcquisitionLanding() {
  return <div className={styles.page} data-landing-page><LandingMotion />
    <header className={styles.header}><div><Link href="/" aria-label="Escala Vendas — início"><img src={brandLogo} alt="Escala Vendas" /></Link><Link className={styles.headerCta} href="/diagnostico">Fazer Diagnóstico</Link></div></header>
    <main>
      <section className={styles.hero} aria-labelledby="acquisition-title"><div className={styles.heroInner}><div className={styles.heroCopy}><span className={styles.eyebrow}>Diagnóstico Escala Growth</span><h1 id="acquisition-title">O problema pode não ser falta de leads.<em>Pode ser o que acontece depois que eles chegam.</em></h1><p>Descubra onde sua operação comercial está perdendo força entre atrair oportunidades, convertê-las em vendas e crescer com mais controle.</p><Cta label="Fazer meu Diagnóstico Escala Growth" /><small>Online <b>•</b> Resultado imediato <b>•</b> Diagnóstico disponível para impressão</small></div><ResultPreview /></div></section>

      <section className={styles.softSection} aria-labelledby="problem-title"><div className={styles.inner}><Heading eyebrow="O problema" id="problem-title">Sua empresa gera oportunidades. Mas consegue acompanhar todas elas?</Heading><div className={styles.problemGrid} data-reveal-group="problems">{problems.map((item,index)=><article key={item}><span>0{index+1}</span><p>{item}</p></article>)}</div></div></section>

      <section className={styles.turnSection} aria-labelledby="turn-title"><div className={styles.inner}><Heading eyebrow="Uma mudança de perspectiva" id="turn-title">Gerar mais leads para uma operação que perde oportunidades pode apenas aumentar o desperdício.</Heading><p className={styles.leadText}>Antes de acelerar a aquisição, é preciso entender o que acontece entre a chegada de uma oportunidade e a venda.</p><div className={styles.pillarFlow} data-reveal-group="pillars">{pillars.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className={styles.diagnosticSection} aria-labelledby="diagnostic-title"><div className={styles.inner}><div className={styles.diagnosticCopy} data-reveal><Heading eyebrow="Diagnóstico Escala Growth" id="diagnostic-title">Descubra onde sua operação comercial precisa evoluir.</Heading><p>O Diagnóstico Escala Growth analisa pontos importantes da sua operação comercial e identifica forças, gargalos e prioridades para evolução.</p><p><strong>Ao concluir, seu diagnóstico é gerado imediatamente.</strong> Você visualiza seu resultado online, conhece seu IEG, identifica forças e gargalos e pode imprimir o diagnóstico para utilizar na análise da sua operação.</p><blockquote>Terminou. Recebeu. Já pode usar.</blockquote><Cta label="Quero fazer meu diagnóstico" /></div><ul className={styles.deliverables} data-reveal-group="deliverables">{deliverables.map(item=><li key={item}><span>✓</span>{item}</li>)}</ul></div></section>

      <section className={styles.resultSection} aria-labelledby="result-title"><div className={styles.inner}><Heading eyebrow="Exemplo de visualização" id="result-title">Uma entrega clara para começar a agir.</Heading><div className={styles.resultDemo} data-reveal><ResultPreview /><div><span>Leitura imediata</span><h3>Forças, gargalos e direção em uma única análise.</h3><p>A representação é ilustrativa. Seu resultado será calculado exclusivamente a partir das respostas fornecidas no diagnóstico.</p></div></div></div></section>

      <section className={styles.stepsSection} aria-labelledby="steps-title"><div className={styles.inner}><Heading eyebrow="Como funciona" id="steps-title">Em poucos passos você entende melhor sua operação comercial.</Heading><ol className={styles.steps} data-reveal-group="steps">{steps.map(([number,title,text],index)=><li key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p>{index===1&&<strong>Terminou. Recebeu. Já pode usar.</strong>}</li>)}</ol></div></section>

      <section className={styles.thinkingSection} aria-labelledby="thinking-title"><div className={styles.inner}><Heading eyebrow="Nossa forma de pensar" id="thinking-title">Não começamos pela ferramenta. Começamos pelo problema.</Heading><p>CRM, IA, automação, tráfego e tecnologia podem ser importantes. Mas só fazem sentido quando resolvem uma necessidade real da operação.</p><ol className={styles.thinkingFlow}>{["Estratégia","Processos","Tecnologia","Implantação","Evolução"].map(item=><li key={item}>{item}</li>)}</ol></div></section>

      <section className={styles.audienceSection} aria-labelledby="audience-title"><div className={styles.inner}><Heading eyebrow="Para quem é" id="audience-title">O Diagnóstico Escala Growth faz mais sentido para empresas que já possuem uma operação comercial ativa.</Heading><ul className={styles.audienceGrid} data-reveal-group="audience">{audience.map(item=><li key={item}><span>✓</span>{item}</li>)}</ul><p className={styles.note}>Se sua empresa ainda não possui uma operação comercial ou geração mínima de oportunidades, algumas análises podem ter menor aderência ao momento atual.</p></div></section>

      <section className={styles.authoritySection}><div className={styles.inner} data-reveal><img src={brandLogo} alt="Escala Vendas" /><p>O Método Escala Growth foi desenvolvido pela Escala Vendas para transformar diagnóstico comercial em direção estratégica e execução.</p></div></section>

      <section className={styles.faqSection} aria-labelledby="faq-title"><div className={styles.inner}><Heading eyebrow="Perguntas frequentes" id="faq-title">Antes de começar</Heading><div className={styles.faqList}>{faqs.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>

      <section className={styles.finalCta} aria-labelledby="final-title"><div><h2 id="final-title">Antes de investir para trazer mais oportunidades, descubra o que acontece com as que já chegam.</h2><p>Faça o Diagnóstico Escala Growth e tenha uma visão mais clara dos pontos que merecem prioridade na sua operação comercial.</p><Cta label="Fazer meu Diagnóstico Escala Growth" /><small>Resultado online e disponível imediatamente após a conclusão.</small></div></section>
    </main>
    <footer className={styles.footer}><div><p><strong>Escala Vendas LTDA</strong><br />CNPJ: 60.328.666/0001-03<br /><a href="mailto:contato@escalavendas.com.br">contato@escalavendas.com.br</a></p><nav><Link href="/">Voltar para o site da Escala Vendas</Link><Link href="/diagnostico">Diagnóstico</Link></nav></div></footer>
  </div>;
}

function Cta({ label }: { label: string }) { return <Link className={styles.primaryButton} href="/diagnostico">{label}</Link>; }
function Heading({ eyebrow,id,children }: { eyebrow:string;id:string;children:ReactNode }) { return <div className={styles.heading} data-reveal><span className={styles.eyebrow}>{eyebrow}</span><h2 id={id}>{children}</h2></div>; }
function ResultPreview() { return <aside className={styles.preview} aria-label="Exemplo ilustrativo de resultado"><div><span>Índice Escala Growth</span><small>Exemplo visual</small></div><strong>IEG</strong><h2>Uma visão integrada da operação.</h2><dl><div><dt>Maior força</dt><dd>Converter</dd></div><div><dt>Principal gargalo</dt><dd>Crescer</dd></div><div><dt>Direção</dt><dd>Evoluir com controle</dd></div></dl><p>Valores ilustrativos — não representam um diagnóstico real.</p></aside>; }
