import {isMaster} from '../../../lib/access';
const SUPABASE_URL=process.env.SUPABASE_URL;
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const ADMIN_KEY=process.env.CONSULTORIA_ACCESS_KEY;
const ANON_KEY=process.env.SUPABASE_ANON_KEY;
const headers=()=>({'Content-Type':'application/json','apikey':SERVICE_KEY!,'Authorization':`Bearer ${SERVICE_KEY}`});
function ready(){return SUPABASE_URL&&SERVICE_KEY}
async function currentUser(req:Request){const token=req.headers.get('cookie')?.match(/escala_session=([^;]+)/)?.[1];if(!token||!SUPABASE_URL||!ANON_KEY)return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:ANON_KEY,Authorization:`Bearer ${token}`}});return r.ok?r.json():null}
async function admin(req:Request){if(ADMIN_KEY&&req.headers.get('authorization')===`Bearer ${ADMIN_KEY}`)return true;return isMaster(req)}
async function canDelete(req:Request){const user=await currentUser(req);if(!user)return false;const env=(process.env.ADMIN_EMAILS||process.env.CONSULTORIA_ADMIN_EMAIL||'').toLowerCase().split(',').map(x=>x.trim()).filter(Boolean);if(env.includes(String(user.email||'').toLowerCase()))return true;const r=await fetch(`${SUPABASE_URL}/rest/v1/configuracoes?select=email&limit=1`,{headers:headers()});const rows=r.ok?await r.json():[];return String(rows[0]?.email||'').toLowerCase()===String(user.email||'').toLowerCase()}
export async function POST(req:Request){if(!ready())return Response.json({error:'Persistência não configurada'},{status:503});const payload=await req.json();if(payload.action==='duplicate'){if(!await admin(req))return Response.json({error:'Não autorizado'},{status:401});const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/duplicar_diagnostico_growth`,{method:'POST',headers:headers(),body:JSON.stringify({original_id:payload.id})});return new Response(await r.text(),{status:r.status,headers:{'Content-Type':'application/json; charset=utf-8'}})}const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/registrar_diagnostico_growth`,{method:'POST',headers:headers(),body:JSON.stringify({payload})});return new Response(await r.text(),{status:r.status,headers:{'Content-Type':'application/json; charset=utf-8'}})}
export async function GET(req:Request){if(!await admin(req))return Response.json({error:'Não autorizado'},{status:401});if(!ready())return Response.json({error:'Persistência não configurada'},{status:503});const url=new URL(req.url),id=url.searchParams.get('id');const select='*,empresas(*),responsaveis(*),resultados_pilares(*),respostas(*),respostas_abertas(*),planos_estrategicos(*),diagnostico_status_historico(*)';const q=id?`id=eq.${encodeURIComponent(id)}&select=${select}`:`select=id,empresa_id,responsavel_id,data_diagnostico,pontuacao_geral,nivel_maturidade,maior_pilar,menor_pilar,potencial_crescimento,status,registro_status,sequencia,tipo_avaliacao,created_at,empresas(id,nome,segmento,consultor_responsavel,status_implantacao,meta_ieg),responsaveis(nome)&order=created_at.desc`;const r=await fetch(`${SUPABASE_URL}/rest/v1/diagnosticos?${q}`,{headers:headers(),cache:'no-store'});return new Response(await r.text(),{status:r.status,headers:{'Content-Type':'application/json; charset=utf-8'}})}
export async function PATCH(req:Request){if(!await admin(req))return Response.json({error:'Não autorizado'},{status:401});if(!ready())return Response.json({error:'Persistência não configurada'},{status:503});const {id,status,registro_status,observacoes,plano,certificado_emitido}=await req.json();const changes:any={updated_at:new Date().toISOString()};if(status!==undefined)changes.status=status;if(registro_status!==undefined)changes.registro_status=registro_status;if(certificado_emitido!==undefined){changes.certificado_emitido=certificado_emitido;changes.certificado_emitido_em=certificado_emitido?new Date().toISOString():null}if(Object.keys(changes).length>1){const r=await fetch(`${SUPABASE_URL}/rest/v1/diagnosticos?id=eq.${id}`,{method:'PATCH',headers:{...headers(),'Prefer':'return=minimal'},body:JSON.stringify(changes)});if(!r.ok)return new Response(await r.text(),{status:r.status})}if(status||registro_status){await fetch(`${SUPABASE_URL}/rest/v1/diagnostico_status_historico`,{method:'POST',headers:headers(),body:JSON.stringify({diagnostico_id:id,status:registro_status||status})})}if(observacoes!==undefined||plano){await fetch(`${SUPABASE_URL}/rest/v1/planos_estrategicos?diagnostico_id=eq.${id}`,{method:'PATCH',headers:{...headers(),'Prefer':'return=minimal'},body:JSON.stringify({...plano,observacoes,updated_at:new Date().toISOString()})})}return Response.json({ok:true})}
export async function DELETE(req:Request){if(!await canDelete(req))return Response.json({error:'Apenas o administrador pode excluir diagnósticos.'},{status:403});const id=new URL(req.url).searchParams.get('id');if(!id)return Response.json({error:'Diagnóstico não informado.'},{status:400});const r=await fetch(`${SUPABASE_URL}/rest/v1/diagnosticos?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{...headers(),Prefer:'return=minimal'}});if(!r.ok)return new Response(await r.text(),{status:r.status});return Response.json({ok:true})}

