import {isMaster} from '../../../lib/access';
import {composeGrowthProject} from '../../../lib/motor-growth';
import {pendingDefinitions} from '../../../lib/intelligent-pendencies';
import {resolveCanonicalExistingResources} from '../../../lib/existingResourceResolver';

const SUPABASE_URL=process.env.SUPABASE_URL;
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const METHOD_VERSION_FALLBACK='2.6';
const headers=()=>({'Content-Type':'application/json',apikey:SERVICE_KEY!,Authorization:`Bearer ${SERVICE_KEY}`});
async function db(path:string,init?:RequestInit){if(!SUPABASE_URL||!SERVICE_KEY)throw new Error('Supabase não configurado.');const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{...headers(),...(init?.headers||{})},cache:'no-store'});if(!response.ok)throw new Error(await response.text());const text=await response.text();return text?JSON.parse(text):[]}
const array=(value:any):any[]=>Array.isArray(value)?value:[];
const names=(items:any[])=>items.map(item=>item.nome||item.nome_snapshot).filter(Boolean);
const createSchedule=(motor:any)=>motor.schedule.map((phase:any)=>`${phase.fase}\n${phase.items.map((item:any)=>`• ${item.nome}`).join('\n')||'Nenhum item novo.'}`).join('\n\n');
const createNextSteps=(motor:any)=>array(motor.documentaryNextSteps).map((item:any)=>`• ${item.acao}`).join('\n');

async function syncGrowthProject(empresaId:string,motor:any,usuario:string){
 const marketing=pendingDefinitions(array(motor.strategic)).find(item=>item.codigo==='MARKETING_PARAMETROS');
 if(!marketing)return{project_id:null,marketing_pendency:false};
 let project=(await db(`projetos_evolucao?empresa_id=eq.${encodeURIComponent(empresaId)}&status=eq.Rascunho&select=*&order=updated_at.desc&limit=1`))[0];
 if(!project){project=(await db('projetos_evolucao',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({empresa_id:empresaId,nome:'Projeto de Evolução — Motor de Crescimento',tipo:'Inclusão de novo recurso',descricao:'Projeto preparado automaticamente a partir das recomendações estratégicas do Método Escala Growth.',objetivo:`Evoluir a prioridade ${motor.objective}.`,status:'Rascunho',valor_implantacao_adicional:0,implantacao_modalidade:'Sem cobrança',mensalidade_atual:0,mensalidade_adicional:0,desconto_recorrente:0,exige_contrato:false,exige_aditivo:false,exige_aceite:true,exige_pagamento:false,forma_cobranca:'Sem cobrança imediata',formalizacao:'Termo de adesão ao Método Escala Growth',checklist:{marketing_parametros:false},criado_por:usuario,responsavel_atualizacao:usuario})}))[0]}
 const marketingResources=array(motor.strategic).filter((item:any)=>marketing.solutions.includes(item.nome));
 for(const item of marketingResources)await db('projeto_evolucao_recursos?on_conflict=projeto_evolucao_id,recurso_id,movimento',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({projeto_evolucao_id:project.id,recurso_id:item.id,nome_snapshot:item.nome,tipo_snapshot:item.tipo||'Implantação',movimento:'Adicionar',valor_implantacao:0,valor_mensal:Number(item.valor_mensal||0),classificacao:'Recomendado',origem:item.origem||'Motor de Decisão',peso:Math.min(10,Math.max(1,Number(item.peso||1))),fase:'Recomendações Estratégicas'})});
 const existing=(await db(`pendencias_inteligentes?projeto_evolucao_id=eq.${encodeURIComponent(project.id)}&codigo=eq.MARKETING_PARAMETROS&select=*&limit=1`))[0],completed=existing?.status==='Concluída',now=new Date().toISOString(),checklist={...(project.checklist||{}),marketing_parametros:completed};
 await db('pendencias_inteligentes?on_conflict=projeto_evolucao_id,codigo',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({empresa_id:empresaId,projeto_evolucao_id:project.id,codigo:marketing.codigo,titulo:marketing.titulo,categoria:marketing.categoria,rota_configuracao:marketing.rota,solucoes_origem:marketing.solutions,status:completed?'Concluída':'Pendente',concluida_em:completed?existing.concluida_em:null,concluida_por:completed?existing.concluida_por:null,updated_at:now})});
 await db(`projetos_evolucao?id=eq.${encodeURIComponent(project.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({checklist,responsavel_atualizacao:usuario,updated_at:now})});
 return{project_id:project.id,marketing_pendency:true,marketing_pendency_status:completed?'Concluída':'Pendente'};
}

async function context(empresaId:string){
 const id=encodeURIComponent(empresaId);
 const [companies,diagnostics,plans,meetings,catalog,situations,history,methodVersions]=await Promise.all([
  db(`empresas?id=eq.${id}&select=id,nome,status_implantacao&limit=1`),db(`diagnosticos?empresa_id=eq.${id}&select=*&order=created_at.desc&limit=1`),db(`planos_estrategicos?empresa_id=eq.${id}&select=*&order=created_at.desc&limit=1`),db(`reunioes_estrategicas?empresa_id=eq.${id}&select=*&order=created_at.desc&limit=1`),db('catalogo_recursos?ativo=eq.true&select=*'),db(`situacoes_comerciais_versoes?empresa_id=eq.${id}&vigente=eq.true&select=*&limit=1`),db(`regeneracoes_metodo?empresa_id=eq.${id}&select=*&order=created_at.desc`),db('metodo_growth_versoes?atual=eq.true&select=*&order=publicada_em.desc&limit=1')
 ]);
 const diagnostic=diagnostics[0],plan=plans[0],meeting=meetings[0]||{},current=situations[0],meetingData=meeting.dados_reuniao||{};
 const [diagnosticAnswers,diagnosticOpenAnswers,diagnosticPillars]=diagnostic?.id?await Promise.all([db(`respostas?diagnostico_id=eq.${encodeURIComponent(diagnostic.id)}&select=pilar,pergunta,resposta_numerica`),db(`respostas_abertas?diagnostico_id=eq.${encodeURIComponent(diagnostic.id)}&select=pergunta,resposta`),db(`resultados_pilares?diagnostico_id=eq.${encodeURIComponent(diagnostic.id)}&select=pilar,percentual`)]):[[],[],[]];
 const platform=meeting.situacao_plataforma||meetingData.situacao_plataforma||{},nullableBoolean=(value:any)=>value===true||String(value).toLowerCase()==='sim'?true:value===false||String(value).toLowerCase()==='não'||String(value).toLowerCase()==='nao'?false:null,platformHasMarketing=['Google Ads','Meta Ads'].some(key=>{const value=platform[key];return value===true||(value&&typeof value==='object')||Boolean(String(value||'').trim()&&!['não','nao','false','inativo','não possui','nao possui'].includes(String(value).trim().toLowerCase()))});
 const adaptiveRecommendations=array(meetingData.diagnostico_validado?.recomendacoes_adaptativas),existingResources=resolveCanonicalExistingResources({catalog,commercialResources:current?.recursos,adaptiveRecommendations});
 const motor=composeGrowthProject({catalog,activeResources:names(array(current?.recursos)),existingResources,priority:diagnostic?.menor_pilar||'Organizar',baseClient:(meeting.tipo_relacionamento||meetingData.tipo_relacionamento)==='Cliente da Base',signals:{pillarScores:Object.fromEntries(array(diagnosticPillars).map((item:any)=>[item.pilar,Number(item.percentual)])),questionScores:array(diagnosticAnswers).map((item:any)=>({pilar:item.pilar,pergunta:item.pergunta,valor:Number(item.resposta_numerica)})),openAnswers:array(diagnosticOpenAnswers),meetingPriority:meeting.prioridades_confirmadas||meetingData.prioridades_confirmadas||meetingData.validacoes_reuniao?.prioridades?.resposta,approvedRecommendations:meeting.recomendacoes_aprovadas||meetingData.recomendacoes_aprovadas,removedRecommendations:meeting.recomendacoes_removidas||meetingData.recomendacoes_removidas,newRecommendations:meeting.novas_recomendacoes||meetingData.novas_recomendacoes,possui_marketing:platformHasMarketing?true:nullableBoolean(meetingData.possui_marketing),possui_agencia:nullableBoolean(meetingData.possui_agencia),realiza_campanhas:nullableBoolean(meetingData.realiza_campanhas)}});
 const currentMethod=methodVersions[0]||{nome:'Método Escala Growth',versao:METHOD_VERSION_FALLBACK,novidades:[]},planMethodVersion=plan?.metodo_versao||history[0]?.metodo_versao||'2.3',executionStarted=['Método iniciado','Cliente Ativo','Implantação concluída'].some(status=>String(companies[0]?.status_implantacao||diagnostic?.status||'').includes(status));
 return{company:companies[0],diagnostic,plan,meeting,motor,existingResources,history,method:{current:currentMethod,plan_version:planMethodVersion,update_available:planMethodVersion!==currentMethod.versao,execution_started:executionStarted,last_update:history[0]||null}};
}

export async function GET(req:Request){try{if(!await isMaster(req))return Response.json({error:'Acesso exclusivo do Usuário Master.'},{status:403});const empresaId=new globalThis.URL(req.url).searchParams.get('empresa_id');if(!empresaId)return Response.json({companies:await db('empresas?select=id,nome&order=nome')});return Response.json(await context(empresaId))}catch(error:any){return Response.json({error:error?.message||'Não foi possível carregar a Central de Regeneração.'},{status:500})}}

export async function POST(req:Request){
 try{
  if(!await isMaster(req))return Response.json({error:'Acesso exclusivo do Usuário Master.'},{status:403});
  const body=await req.json(),empresaId=String(body.empresa_id||''),tipo=String(body.tipo||'Plano Estratégico'),motivo=String(body.motivo||'Atualização para a versão mais recente do Método Escala Growth.');
  if(!empresaId)return Response.json({error:'Selecione uma empresa.'},{status:400});
  if(body.gerar_parecer_ia)return Response.json({error:'A geração de parecer por IA ainda não está configurada. Preserve o parecer atual ou registre um novo parecer manualmente.'},{status:409});
  const ctx=await context(empresaId);
  if(!ctx.diagnostic)return Response.json({error:'A empresa não possui diagnóstico para regeneração.'},{status:409});
  if(!ctx.plan)return Response.json({error:'A empresa não possui Plano Estratégico para regeneração.'},{status:409});
  if(ctx.method.execution_started&&!body.confirm_active)return Response.json({error:'Este projeto já iniciou sua execução utilizando a versão atual do método. Recomendamos criar um novo Projeto de Evolução ao invés de atualizar o Plano Estratégico.',code:'ACTIVE_PROJECT_CONFIRMATION'},{status:409});
  const METHOD_VERSION=ctx.method.current.versao||METHOD_VERSION_FALLBACK,previousMethodVersion=ctx.method.plan_version||'2.3';
  const previous={...ctx.plan},recommendations=names(ctx.motor.strategic),mandatory=names(ctx.motor.mandatory),future=names(ctx.motor.future);
  const next={...previous,prioridades:ctx.motor.objective,cronograma:body.atualizar_cronograma===false?previous.cronograma:createSchedule(ctx.motor),proximos_passos:body.atualizar_recomendacoes===false?previous.proximos_passos:createNextSteps(ctx.motor),parecer_consultor:body.manter_parecer===false?null:previous.parecer_consultor,metodo_nome:ctx.method.current.nome||'Método Escala Growth',metodo_versao:METHOD_VERSION,metodo_aplicado_em:new Date().toISOString(),updated_at:new Date().toISOString()};delete next.id;delete next.created_at;
  const comparison={novos_recursos:mandatory.filter(item=>!String(previous.proximos_passos||'').includes(item)),novas_recomendacoes:recommendations.filter(item=>!String(previous.proximos_passos||'').includes(item)),evolucoes_futuras:future,proximos_passos_estruturados:ctx.motor.documentaryNextSteps,mudancas:[previous.prioridades!==next.prioridades?'Prioridade estratégica recalculada':null,previous.cronograma!==next.cronograma?'Cronograma atualizado':null,previous.proximos_passos!==next.proximos_passos?'Recomendações atualizadas':null,body.manter_parecer!==false?'Parecer final preservado':null].filter(Boolean)};
  const versions=await db(`plano_estrategico_versoes?diagnostico_id=eq.${encodeURIComponent(ctx.diagnostic.id)}&select=versao&order=versao.desc&limit=1`),documentVersion=Number(versions[0]?.versao||0)+1;
  await db('plano_estrategico_versoes',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({plano_id:ctx.plan.id,diagnostico_id:ctx.diagnostic.id,versao:documentVersion,consultor:body.usuario||'Usuário Master',conteudo:next,status:next.status||'Em Consolidação',motivo,metodo_versao:METHOD_VERSION,comparacao:comparison})});
  await db(`planos_estrategicos?id=eq.${encodeURIComponent(ctx.plan.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(next)});
  const projectSync=await syncGrowthProject(empresaId,ctx.motor,body.usuario||'Usuário Master');
  const version=Math.max(0,...ctx.history.filter((item:any)=>item.tipo===tipo).map((item:any)=>Number(item.versao||0)))+1;
  await db('regeneracoes_metodo',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({empresa_id:empresaId,diagnostico_id:ctx.diagnostic.id,plano_id:ctx.plan.id,tipo,versao:version,metodo_versao:METHOD_VERSION,versao_metodo_anterior:previousMethodVersion,versao_metodo_nova:METHOD_VERSION,motivo,usuario:body.usuario||'Usuário Master',opcoes:body,versao_anterior:previous,versao_nova:next,comparacao:comparison})});
  await db('dossie_eventos',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({empresa_id:empresaId,diagnostico_id:ctx.diagnostic.id,tipo:'Atualização do Método',titulo:`${tipo} atualizado`,descricao:`O ${tipo} foi atualizado da versão ${previousMethodVersion} para a versão ${METHOD_VERSION} do Método Escala Growth.`,data_evento:new Date().toISOString(),concluido:true})});
  return Response.json({ok:true,version,document_version:documentVersion,previous_method_version:previousMethodVersion,method_version:METHOD_VERSION,comparison,plan:next,project_sync:projectSync,message:`${tipo} atualizado para o Método Escala Growth ${METHOD_VERSION}.`});
 }catch(error:any){return Response.json({error:error?.message||'Não foi possível concluir a regeneração.'},{status:500})}
}
