const SUPABASE_URL=process.env.SUPABASE_URL,SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY,ANON_KEY=process.env.SUPABASE_ANON_KEY;
const headers=()=>({'Content-Type':'application/json','apikey':SERVICE_KEY!,'Authorization':`Bearer ${SERVICE_KEY}`});
async function user(req:Request){const token=req.headers.get('cookie')?.match(/escala_session=([^;]+)/)?.[1];if(!token||!SUPABASE_URL||!ANON_KEY)return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:ANON_KEY,Authorization:`Bearer ${token}`}});return r.ok?r.json():null}
async function get(path:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
async function isAdmin(req:Request){const u=await user(req);if(!u)return false;const email=String(u.email||'').toLowerCase(),env=(process.env.ADMIN_EMAILS||process.env.CONSULTORIA_ADMIN_EMAIL||'').toLowerCase().split(',').map(x=>x.trim()).filter(Boolean);if(env.includes(email))return true;try{const c=await get('configuracoes?select=email&limit=1');return String(c[0]?.email||'').toLowerCase()===email}catch{return false}}
export async function GET(req:Request){try{if(!await isAdmin(req))return Response.json({error:'Acesso exclusivo do administrador.'},{status:403});const [parameters,resources]=await Promise.all([get('parametros_comerciais?select=*&limit=1'),get('catalogo_recursos?select=*&order=categoria,nome')]);return Response.json({parameters:parameters[0],resources})}catch(e:any){return Response.json({error:e?.message||'Não foi possível carregar os parâmetros.'},{status:500})}}
export async function POST(req:Request){try{if(!await isAdmin(req))return Response.json({error:'Acesso exclusivo do administrador.'},{status:403});const body=await req.json();if(body.action==='parameters'){const data={valor_ui:Number(body.valor_ui),desconto_pix:Number(body.desconto_pix),prazo_contratual:Number(body.prazo_contratual),validade_proposta:Number(body.validade_proposta),reajuste_anual:Number(body.reajuste_anual||0),updated_at:new Date().toISOString()};const rows=await get('parametros_comerciais?select=id&limit=1');const url=rows[0]?`parametros_comerciais?id=eq.${rows[0].id}`:'parametros_comerciais';const r=await fetch(`${SUPABASE_URL}/rest/v1/${url}`,{method:rows[0]?'PATCH':'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify(data)});if(!r.ok)return new Response(await r.text(),{status:r.status});return Response.json({ok:true,parameters:(await r.json())[0]})}if(body.action==='resource'){const allowed=['codigo','categoria','nome','descricao','tipo','ui','responsavel','prioridade','observacoes','ativo'];const data=Object.fromEntries(allowed.filter(k=>body[k]!==undefined).map(k=>[k,k==='ui'?Number(body[k]):body[k]]));data.updated_at=new Date().toISOString();const r=await fetch(`${SUPABASE_URL}/rest/v1/catalogo_recursos${body.id?`?id=eq.${body.id}`:''}`,{method:body.id?'PATCH':'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify(data)});if(!r.ok)return new Response(await r.text(),{status:r.status});return Response.json({ok:true,resource:(await r.json())[0]})}return Response.json({error:'Ação inválida.'},{status:400})}catch(e:any){return Response.json({error:e?.message||'Não foi possível salvar.'},{status:500})}}
export async function DELETE(req:Request){if(!await isAdmin(req))return Response.json({error:'Acesso exclusivo do administrador.'},{status:403});const id=new URL(req.url).searchParams.get('id');if(!id)return Response.json({error:'Recurso não informado.'},{status:400});const r=await fetch(`${SUPABASE_URL}/rest/v1/catalogo_recursos?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...headers(),Prefer:'return=minimal'},body:JSON.stringify({ativo:false,updated_at:new Date().toISOString()})});return r.ok?Response.json({ok:true}):new Response(await r.text(),{status:r.status})}

