import {isMaster} from '../../../lib/access';
const SUPABASE_URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const headers=()=>({'Content-Type':'application/json','apikey':KEY!,'Authorization':`Bearer ${KEY}`});
async function get(path:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
async function write(path:string,method:string,data:any){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers:{...headers(),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(data)});if(!r.ok)throw new Error(await r.text());return r.json()}
async function audit(entidade:string,entidade_id:string|null,acao:string,dados:any){await write('commercial_audit_log','POST',{entidade,entidade_id,acao,dados})}
export async function GET(req:Request){try{if(!await isMaster(req))return Response.json({error:'Acesso exclusivo do Usuário Master.'},{status:403});const url=new URL(req.url),companyId=url.searchParams.get('empresa'),projectId=url.searchParams.get('projeto');if(companyId&&projectId){const [companies,projects,plans,diagnostics]=await Promise.all([get(`empresas?id=eq.${encodeURIComponent(companyId)}&select=id,nome,consultor_responsavel&limit=1`),get(`projetos_evolucao?id=eq.${encodeURIComponent(projectId)}&empresa_id=eq.${encodeURIComponent(companyId)}&select=*,projeto_evolucao_recursos(*)&limit=1`),get(`planejamentos_campanhas?empresa_id=eq.${encodeURIComponent(companyId)}&projeto_evolucao_id=eq.${encodeURIComponent(projectId)}&select=*&order=plataforma`),get(`diagnosticos?empresa_id=eq.${encodeURIComponent(companyId)}&select=status&order=created_at.desc&limit=1`)]),project=projects[0],marketingNames=['google ads','meta ads','landing page','campanhas whatsapp'],eligible=(project?.projeto_evolucao_recursos||[]).filter((item:any)=>item.implantar_nesta_fase===true&&(item.parametros_snapshot?.abre_planejamento_operacional===true||marketingNames.some(name=>String(item.nome_snapshot||'').toLowerCase().includes(name))));return Response.json({operational:true,company:companies[0],project,eligible,plans,kickoff:['Kickoff','Kickoff realizado','Implantação','Implantação em andamento','Implantação concluída','Cliente Ativo'].includes(diagnostics[0]?.status)})}const [parameters,resources,marketing]=await Promise.all([get('parametros_comerciais?select=*&limit=1'),get('catalogo_recursos?select=*&order=tipo,categoria,nome'),get('marketing_parametros?select=*&order=plataforma')]);return Response.json({parameters:parameters[0],resources,marketing})}catch(e:any){return Response.json({error:e?.message||'Não foi possível carregar os parâmetros.'},{status:500})}}
export async function POST(req:Request){try{
 if(!await isMaster(req))return Response.json({error:'Acesso exclusivo do Usuário Master.'},{status:403});
 const body=await req.json();
 if(body.action==='parameters'){
  const data={valor_ui:Number(body.valor_ui),desconto_pix:Number(body.desconto_pix),prazo_contratual:12,validade_proposta:Number(body.validade_proposta),reajuste_indice:['IPCA','IGP-M'].includes(body.reajuste_indice)?body.reajuste_indice:'IPCA',reajuste_periodicidade:Number(body.reajuste_periodicidade||12),reajuste_mes_base:Number(body.reajuste_mes_base||1),juros_atraso:body.juros_atraso===''?null:Number(body.juros_atraso),dias_tolerancia:body.dias_tolerancia===''?null:Number(body.dias_tolerancia),updated_at:new Date().toISOString()};
  if(data.valor_ui<=0)return Response.json({error:'O Valor da UI deve ser maior que zero.'},{status:400});
  const rows=await get('parametros_comerciais?select=id&limit=1'),result=await write(rows[0]?`parametros_comerciais?id=eq.${rows[0].id}`:'parametros_comerciais',rows[0]?'PATCH':'POST',data);
  await audit('parametros_comerciais',result[0]?.id||null,'Configurações financeiras atualizadas',data);
  return Response.json({ok:true,parameters:result[0]});
 }
 if(body.action==='resource'){
  const type=['Implantação','Mensalidade','Implantação + Mensalidade'].includes(body.tipo)?body.tipo:'Implantação';
  const classification=['Obrigatória','Complementar','Opcional'].includes(body.classificacao_comercial)?body.classificacao_comercial:'Opcional';
  const hasImplementation=type!=='Mensalidade',hasMonthly=type!=='Implantação';
  if(!body.codigo?.trim()||!body.categoria?.trim()||!body.nome?.trim())return Response.json({error:'Código, categoria e nome são obrigatórios.'},{status:400});
  if(hasImplementation&&Number(body.ui)<=0)return Response.json({error:'Informe uma UI maior que zero para soluções com implantação.'},{status:400});
  if(hasMonthly&&(body.valor_mensalidade_padrao===''||body.valor_mensalidade_padrao==null||Number(body.valor_mensalidade_padrao)<0))return Response.json({error:'Informe o valor de mensalidade padrão do serviço.'},{status:400});
  const hasOrder=body.ordem_implantacao!==''&&body.ordem_implantacao!=null,hasWeek=String(body.semana_sugerida||'').trim()!=='',hasDuration=body.tempo_medio_implantacao!==''&&body.tempo_medio_implantacao!=null;
  if(hasImplementation&&(!hasOrder||!hasWeek||!hasDuration))return Response.json({error:'Ordem, semana e tempo médio são obrigatórios para soluções com implantação.'},{status:400});
  if(hasOrder&&(!Number.isInteger(Number(body.ordem_implantacao))||Number(body.ordem_implantacao)<1))return Response.json({error:'A Ordem de implantação deve ser um número inteiro maior que zero.'},{status:400});
  if(hasWeek&&!(/^Semana [1-9][0-9]*$/.test(String(body.semana_sugerida))||body.semana_sugerida==='Personalizado'))return Response.json({error:'Informe uma Semana sugerida válida.'},{status:400});
  if(hasDuration&&(!Number.isInteger(Number(body.tempo_medio_implantacao))||Number(body.tempo_medio_implantacao)<=0))return Response.json({error:'O tempo médio deve ser um número inteiro maior que zero.'},{status:400});
  const toLines=(value:any)=>Array.isArray(value)?value.map(String).map(x=>x.trim()).filter(Boolean):String(value||'').split(/\r?\n/).map(x=>x.replace(/^[-•*✓✔☑\s]+/,'').trim()).filter(Boolean);
  const related=Array.isArray(body.recursos_relacionados)?body.recursos_relacionados.filter((id:any)=>typeof id==='string'&&id!==body.id):[];
  const dependencyRules=toLines(body.dependencias_condicoes||body.dependencias).map((descricao:string)=>({tipo:'condicao',descricao}));
  const dependencySolutions=Array.isArray(body.dependencias_solucoes)?body.dependencias_solucoes.filter(Boolean).map((recurso_id:string)=>({tipo:'solucao',recurso_id})):[];
  const completion=toLines(body.criterios_conclusao||body.criterio_conclusao).map((titulo:string)=>({titulo,obrigatorio:true}));
  const duration=hasImplementation?Number(body.tempo_medio_implantacao):null;
  const usesRecommendedInvestment=body.utiliza_investimento_recomendado===true;
  const createsPending=body.gera_pendencias===true;
  if(usesRecommendedInvestment&&(!Number.isFinite(Number(body.investimento_minimo_recomendado))||Number(body.investimento_minimo_recomendado)<0))return Response.json({error:'O investimento mínimo recomendado deve ser igual ou superior a zero.'},{status:400});
  const data:any={codigo:String(body.codigo).trim(),categoria:String(body.categoria).trim(),nome:String(body.nome).trim(),descricao:body.descricao||null,beneficios:toLines(body.beneficios),objetivo_padrao:body.objetivo_padrao||null,resultado_esperado:body.resultado_esperado||null,criterios_recomendacao:toLines(body.criterios_recomendacao),quando_recomendar:body.quando_recomendar||null,quando_nao_recomendar:body.quando_nao_recomendar||null,entregas_padrao:toLines(body.entregas_padrao),recursos_envolvidos:toLines(body.recursos_envolvidos),recursos_relacionados:related,pre_requisitos:body.pre_requisitos||null,criterio_conclusao:completion.map((x:any)=>x.titulo).join('\n')||null,criterios_conclusao:completion,ordem_implantacao:hasImplementation?Number(body.ordem_implantacao):null,semana_sugerida:hasImplementation?String(body.semana_sugerida):null,duracao_padrao:duration,dependencias:dependencyRules.map((x:any)=>x.descricao).join('\n')||null,dependencias_estruturadas:[...dependencySolutions,...dependencyRules],descricao_tecnica:body.descricao_tecnica||null,tipo:type,classificacao_comercial:classification,ui:hasImplementation?Number(body.ui):null,valor_mensal:hasMonthly?Number(body.valor_mensalidade_padrao):null,valor_avulso:null,valor_implantacao_padrao:hasImplementation&&body.valor_implantacao_padrao!==''&&body.valor_implantacao_padrao!=null?Number(body.valor_implantacao_padrao):null,valor_mensalidade_padrao:hasMonthly?Number(body.valor_mensalidade_padrao):null,utiliza_plataforma_nimble:body.utiliza_plataforma_nimble===true,responsavel:body.responsavel||null,observacoes:body.observacoes||null,tempo_medio_implantacao:duration,treinamento_obrigatorio:body.treinamento_obrigatorio===true,gera_pendencias:createsPending,codigo_pendencia_padrao:createsPending?(body.codigo_pendencia_padrao||null):null,titulo_pendencia_padrao:createsPending?(body.titulo_pendencia_padrao||null):null,rota_configuracao_padrao:createsPending?(body.rota_configuracao_padrao||null):null,abre_planejamento_operacional:body.abre_planejamento_operacional===true,permite_executor_terceiro:body.permite_executor_terceiro!==false,permite_equipe_interna:body.permite_equipe_interna!==false,impacta_financeiro:body.impacta_financeiro!==false,impacta_cronograma:body.impacta_cronograma!==false,impacta_implantacao:body.impacta_implantacao!==false,cria_checklist:body.cria_checklist===true,disponivel_evolucao_futura:body.disponivel_evolucao_futura!==false,utiliza_investimento_recomendado:usesRecommendedInvestment,investimento_minimo_recomendado:usesRecommendedInvestment?Number(body.investimento_minimo_recomendado||0):0,observacoes_estrategicas:body.observacoes_estrategicas||null,ativo:body.ativo!==false,updated_at:new Date().toISOString()};
  const result=await write(`catalogo_recursos${body.id?`?id=eq.${body.id}`:''}`,body.id?'PATCH':'POST',data);
  await audit('catalogo_recursos',result[0]?.id||body.id||null,body.id?'Serviço atualizado':'Serviço criado',data);
  return Response.json({ok:true,resource:result[0]});
 }
 if(body.action==='marketing'){for(const p of body.platforms||[]){const serviceName=p.plataforma==='Google Ads'?'Gestão Google Ads':'Gestão Meta Ads',service=(await get('catalogo_recursos?nome=eq.'+encodeURIComponent(serviceName)+'&tipo=eq.Mensalidade&select=id&limit=1'))[0],data={plataforma:p.plataforma,codigo:p.codigo,servico_id:service?.id||p.servico_id||null,objetivo_padrao:p.objetivo_padrao||null,regiao_atuacao:p.regiao_atuacao||null,publico_alvo:p.publico_alvo||null,verba_recomendada:Number(p.verba_recomendada||0),verba_aprovada:Number(p.verba_aprovada||0),landing_page_url:p.landing_page_url||null,conta_google_ads:p.plataforma==='Google Ads'?(p.conta_google_ads||null):null,conta_meta_ads:p.plataforma==='Meta Ads'?(p.conta_meta_ads||null):null,status_campanha:p.status_campanha||'Planejamento',observacoes_operacionais:p.observacoes_operacionais||null,ativo:p.ativo!==false,updated_at:new Date().toISOString()};await write('marketing_parametros?on_conflict=plataforma','POST',data);await audit('marketing_parametros',service?.id||null,'Configuração operacional atualizada',{plataforma:p.plataforma,status_campanha:data.status_campanha})}const projectId=String(body.projeto_evolucao_id||''),companyId=String(body.empresa_id||''),now=new Date().toISOString();if(projectId&&companyId){const snapshot={platforms:body.platforms,objetivo:(body.platforms||[]).map((p:any)=>p.objetivo_padrao).filter(Boolean).join(' · '),regiao:(body.platforms||[]).map((p:any)=>p.regiao_atuacao).filter(Boolean).join(' · '),verba_sugerida:(body.platforms||[]).reduce((total:number,p:any)=>total+Number(p.verba_recomendada||0),0),prazo:'Durante a implantação',observacoes:(body.platforms||[]).map((p:any)=>p.observacoes_operacionais).filter(Boolean).join('\n')};await write(`pendencias_inteligentes?projeto_evolucao_id=eq.${encodeURIComponent(projectId)}&codigo=eq.MARKETING_PARAMETROS`,'PATCH',{status:'Concluída',dados_configuracao:snapshot,concluida_em:now,concluida_por:'Usuário Master',updated_at:now});await audit('pendencias_inteligentes',projectId,'Pendência de Marketing concluída',snapshot)}return Response.json({ok:true,pendency_completed:Boolean(projectId&&companyId)})}
 if(body.action==='campaign-planning'){const projectId=String(body.projeto_evolucao_id||''),companyId=String(body.empresa_id||''),now=new Date().toISOString();if(!projectId||!companyId)return Response.json({error:'Empresa e projeto são obrigatórios.'},{status:400});const project=(await get(`projetos_evolucao?id=eq.${encodeURIComponent(projectId)}&empresa_id=eq.${encodeURIComponent(companyId)}&select=id,status&limit=1`))[0];if(!project)return Response.json({error:'Projeto não localizado.'},{status:404});if(!['Kickoff realizado','Implantação concluída','Cliente Ativo'].includes(project.status))return Response.json({error:'O Planejamento Operacional será liberado após o Kickoff.'},{status:409});for(const p of body.plans||[]){const checklist=p.checklist||{},complete=['objetivo_confirmado','publico_definido','regiao_definida','contas_informadas','landing_configurada','conversoes_configuradas','pronta_publicacao'].every(key=>checklist[key]===true),data={empresa_id:companyId,projeto_evolucao_id:projectId,recurso_id:p.recurso_id||null,plataforma:p.plataforma,objetivo:p.objetivo||null,investimento_recomendado:Number(p.investimento_recomendado||0),investimento_aprovado:Number(p.investimento_aprovado||0),executor:p.executor||null,publico_alvo:p.publico_alvo||null,regiao_atuacao:p.regiao_atuacao||null,landing_page_url:p.landing_page_url||null,conta_google_ads:p.conta_google_ads||null,conta_meta_ads:p.conta_meta_ads||null,conversoes:p.conversoes||null,pixel:p.pixel||null,catalogo:p.catalogo||null,whatsapp:p.whatsapp||null,responsavel_configuracao:p.responsavel_configuracao||'Equipe de Implantação',prazo:p.prazo||null,status:p.status||'Planejamento',observacoes:p.observacoes||null,checklist,concluido_em:complete?now:null,updated_at:now};await write('planejamentos_campanhas?on_conflict=projeto_evolucao_id,recurso_id,plataforma','POST',data)}const allComplete=(body.plans||[]).length>0&&(body.plans||[]).every((p:any)=>['Publicada','Otimização','Finalizada'].includes(p.status));await write(`pendencias_inteligentes?projeto_evolucao_id=eq.${encodeURIComponent(projectId)}&codigo=eq.MARKETING_PARAMETROS`,'PATCH',{titulo:'Planejamento Operacional das Campanhas',status:allComplete?'Concluída':'Pendente',concluida_em:allComplete?now:null,concluida_por:allComplete?'Usuário Master':null,updated_at:now});await audit('planejamentos_campanhas',projectId,'Planejamento operacional atualizado',{quantidade:(body.plans||[]).length,concluido:allComplete});return Response.json({ok:true,pendency_completed:allComplete})}
 return Response.json({error:'Ação inválida.'},{status:400});
}catch(e:any){return Response.json({error:e?.message||'Não foi possível salvar.'},{status:500})}}
export async function DELETE(req:Request){try{if(!await isMaster(req))return Response.json({error:'Acesso exclusivo do Usuário Master.'},{status:403});const id=new URL(req.url).searchParams.get('id');if(!id)return Response.json({error:'Serviço não informado.'},{status:400});await write(`catalogo_recursos?id=eq.${encodeURIComponent(id)}`,'PATCH',{ativo:false,updated_at:new Date().toISOString()});await audit('catalogo_recursos',id,'Serviço arquivado',{});return Response.json({ok:true})}catch(e:any){return Response.json({error:e?.message||'Não foi possível arquivar.'},{status:500})}}

