import {access} from '@/lib/access';
import {STRATEGIC_EXECUTION_PLAN_VERSION,validatePublication} from '@/lib/strategicExecutionPlan';
import {ensureDiagnosticEngineResultsPersisted,EngineMaterializationError} from '@/lib/diagnosticEnginePersistenceServer';

const SUPABASE_URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const headers=()=>({apikey:KEY!,Authorization:'Bearer '+KEY,'Content-Type':'application/json'});
const ready=()=>Boolean(SUPABASE_URL&&KEY);
async function master(req:Request){return (await access(req))?.role==='master'}
async function rows(path:string,options:RequestInit={}){const response=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...options,headers:{...headers(),...(options.headers||{})},cache:'no-store'}),text=await response.text();if(!response.ok)throw new Error(text||'O banco de dados não confirmou a operação.');if(!text.trim())return[];try{return JSON.parse(text)}catch(error){console.error('[strategic-execution-plan] Resposta inválida do Supabase',{path,status:response.status,contentType:response.headers.get('content-type'),error});throw new Error('O banco de dados retornou uma resposta inválida.') }}
async function history(planId:string,event_type:string,description:string,actor:string,metadata:any={}){await rows('strategic_execution_plan_history',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({plan_id:planId,event_type,description,actor,metadata})})}
async function bundle(plan:any){if(!plan)return null;const [actions,events]=await Promise.all([rows('strategic_execution_plan_actions?plan_id=eq.'+encodeURIComponent(plan.id)+'&select=*&order=created_at'),rows('strategic_execution_plan_history?plan_id=eq.'+encodeURIComponent(plan.id)+'&select=*&order=created_at.desc')]);return{...plan,actions,history:events}}

export async function GET(req:Request){try{if(!ready())return Response.json({error:'Persistência não configurada.'},{status:503});if(!await master(req))return Response.json({error:'Não autorizado.'},{status:401});const query=new URL(req.url).searchParams,diagnosticId=query.get('diagnostico_id'),planId=query.get('plan_id');if(!diagnosticId&&!planId)return Response.json({error:'Informe o diagnóstico.'},{status:400});const plans=await rows('strategic_execution_plans?'+(planId?'id=eq.'+encodeURIComponent(planId):'diagnostico_id=eq.'+encodeURIComponent(diagnosticId!))+'&select=*&order=version_number.desc');return Response.json({plan:await bundle(plans[0]),versions:plans})}catch(error:any){return Response.json({error:error?.message||'Não foi possível abrir o Plano Estratégico Executável.'},{status:500})}}

export async function POST(req:Request){try{if(!ready())return Response.json({error:'Persistência não configurada.'},{status:503});const profile=await access(req);if(profile?.role!=='master')return Response.json({error:'Não autorizado.'},{status:401});const body=await req.json(),actor=profile.email||'Usuário Master';
 if(body.operation==='ensure-action-plan'){
  const diagnostics=await rows('diagnosticos?id=eq.'+encodeURIComponent(body.diagnostico_id)+'&select=id,empresa_id,relatorio_snapshot&limit=1'),diagnostic=diagnostics[0];
  if(!diagnostic)return Response.json({error:'Diagnóstico não localizado.'},{status:404});
  try{const result=await ensureDiagnosticEngineResultsPersisted(diagnostic.id,diagnostic.relatorio_snapshot,async()=>rows('respostas?diagnostico_id=eq.'+encodeURIComponent(diagnostic.id)+'&select=*'),async report=>{const saved=await rows('diagnosticos?id=eq.'+encodeURIComponent(diagnostic.id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({relatorio_snapshot:report,updated_at:new Date().toISOString()})});if(!saved[0])throw new Error('Não foi possível confirmar a persistência canônica das engines.')});return Response.json({action_plan:result.actionPlan,relatorio_snapshot:result.report,materialized:result.changed,materialized_layers:result.materializedLayers,persistence_debug:result.debug,source:result.changed?'CANONICAL_ENGINE_MATERIALIZATION_1.0':'PERSISTED'})}catch(error:any){if(error instanceof EngineMaterializationError)return Response.json({error:error.message,missing_layer:error.layer,missing_inputs:error.missingInputs},{status:409});throw error}
 }
 if(body.operation==='initialize'){const existing=await rows('strategic_execution_plans?diagnostico_id=eq.'+encodeURIComponent(body.diagnostico_id)+'&select=*&order=version_number.desc&limit=1');if(existing[0])return Response.json({plan:await bundle(existing[0])});const payload={empresa_id:body.empresa_id,diagnostico_id:body.diagnostico_id,version_number:1,status:'DRAFT',strategic_direction:body.strategic_direction,primary_priority:body.primary_priority,acquisition_movement:body.acquisition_movement,action_plan_source_version:body.action_plan_source_version||'1.0',feature_version:STRATEGIC_EXECUTION_PLAN_VERSION,consultant:actor};const created=(await rows('strategic_execution_plans',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)}))[0];await history(created.id,'PLAN_CREATED','Plano Executável criado como rascunho.',actor);return Response.json({plan:await bundle(created)})}
 const current=(await rows('strategic_execution_plans?id=eq.'+encodeURIComponent(body.plan_id)+'&select=*&limit=1'))[0];if(!current)return Response.json({error:'Plano não localizado.'},{status:404});
 if(body.operation==='new-version'){if(current.status!=='PUBLISHED')return Response.json({error:'A nova versão deve partir de uma versão publicada.'},{status:409});const latest=(await rows('strategic_execution_plans?diagnostico_id=eq.'+encodeURIComponent(current.diagnostico_id)+'&select=version_number&order=version_number.desc&limit=1'))[0],copy={empresa_id:current.empresa_id,diagnostico_id:current.diagnostico_id,version_number:Number(latest?.version_number||current.version_number)+1,status:'DRAFT',strategic_direction:current.strategic_direction,primary_priority:current.primary_priority,acquisition_movement:current.acquisition_movement,action_plan_source_version:current.action_plan_source_version,feature_version:STRATEGIC_EXECUTION_PLAN_VERSION,general_consultant_notes:current.general_consultant_notes,consultant:actor},created=(await rows('strategic_execution_plans',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(copy)}))[0],oldActions=await rows('strategic_execution_plan_actions?plan_id=eq.'+encodeURIComponent(current.id)+'&select=*&order=created_at');if(oldActions.length)await rows('strategic_execution_plan_actions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(oldActions.map((item:any)=>{const{id,created_at,updated_at,...rest}=item;return{...rest,plan_id:created.id}}))});await history(created.id,'VERSION_CREATED','Versão '+created.version_number+' criada a partir da versão '+current.version_number+'.',actor,{source_plan_id:current.id});return Response.json({plan:await bundle(created)})}
 if(current.status!=='DRAFT')return Response.json({error:'Versões publicadas são imutáveis. Crie uma nova versão.'},{status:409});const actions=Array.isArray(body.actions)?body.actions:[];
 if(body.operation==='publish'){const validation=validatePublication(actions);if(validation.errors.length)return Response.json({error:validation.errors.join(' '),warnings:validation.warnings},{status:422})}
 const previous=await rows('strategic_execution_plan_actions?plan_id=eq.'+encodeURIComponent(current.id)+'&select=*');await rows('strategic_execution_plan_actions?plan_id=eq.'+encodeURIComponent(current.id),{method:'DELETE',headers:{Prefer:'return=minimal'}});if(actions.length){const payload=actions.map((item:any)=>({plan_id:current.id,source_type:item.source_type,source_action_code:item.source_action_code||null,recommended_snapshot:item.recommended||item.recommended_snapshot||null,agreed_title:item.agreed_title,agreed_objective:item.agreed_objective||null,agreed_indicator:item.agreed_indicator||null,agreed_target:item.agreed_target||null,responsible:item.responsible||null,due_date:item.due_date||null,agreed_horizon:item.agreed_horizon,status:item.status||'PLANNED',consultant_notes:item.consultant_notes||null,strategic_change_reason:item.strategic_change_reason||null,start_condition:item.start_condition||null,completed_at:item.status==='COMPLETED'?(item.completed_at||new Date().toISOString()):null}));await rows('strategic_execution_plan_actions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)})}
 const published=body.operation==='publish',snapshot=published?{strategic_direction:current.strategic_direction,primary_priority:current.primary_priority,acquisition_movement:current.acquisition_movement,general_consultant_notes:body.general_consultant_notes||'',actions,version_number:current.version_number}:null,changes:any={general_consultant_notes:body.general_consultant_notes||null,updated_at:new Date().toISOString()};if(published)Object.assign(changes,{status:'PUBLISHED',published_at:new Date().toISOString(),published_by:actor,published_snapshot:snapshot});const updated=(await rows('strategic_execution_plans?id=eq.'+encodeURIComponent(current.id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(changes)}))[0];if(published)await rows('strategic_execution_plans?diagnostico_id=eq.'+encodeURIComponent(current.diagnostico_id)+'&status=eq.PUBLISHED&id=neq.'+encodeURIComponent(current.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'SUPERSEDED',updated_at:new Date().toISOString()})});const previousCodes=new Set(previous.map((item:any)=>item.source_action_code||item.agreed_title)),nextCodes=new Set(actions.map((item:any)=>item.source_action_code||item.agreed_title));for(const code of nextCodes)if(!previousCodes.has(code))await history(current.id,'ACTION_INCLUDED','Ação incluída no Plano.',actor,{reference:code});for(const code of previousCodes)if(!nextCodes.has(code))await history(current.id,'ACTION_REMOVED','Ação retirada do Plano.',actor,{reference:code});await history(current.id,published?'PLAN_PUBLISHED':'DRAFT_SAVED',published?'Plano publicado e snapshot imutável registrado.':'Rascunho salvo.',actor,{warnings:body.warnings||[]});const savedPlan=await bundle(updated);return Response.json({ok:true,message:published?'Plano publicado com sucesso.':'Rascunho salvo com sucesso.',plan_id:updated.id,version:updated.version_number,status:updated.status,plan:savedPlan},{status:200})
 }catch(error:any){return Response.json({error:error?.message||'Não foi possível salvar o Plano Estratégico Executável.'},{status:500})}}
