import {access} from '@/lib/access';

const URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const headers=()=>({apikey:KEY!,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'});
async function db(path:string,init:RequestInit={}){const response=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:{...headers(),...(init.headers||{})},cache:'no-store'}),text=await response.text();if(!response.ok)throw new Error(text||'O banco não confirmou a operação.');return text?JSON.parse(text):[]}
const clearConclusion=(value:any)=>{const copy=structuredClone(value||{});delete copy.concluida_em;copy.status='Em preparação';if(copy.validacoes_reuniao?.conclusao){const conclusion={...copy.validacoes_reuniao.conclusao};delete conclusion.resumo_executivo;delete conclusion.concluida_em;copy.validacoes_reuniao={...copy.validacoes_reuniao,conclusao:conclusion}}return copy};

export async function GET(req:Request){try{if((await access(req))?.role!=='master')return Response.json({error:'Não autorizado.'},{status:401});const diagnosticId=new URL(req.url).searchParams.get('diagnostico_id');if(!diagnosticId)return Response.json({error:'Informe o diagnóstico.'},{status:400});const rounds=await db(`reunioes_estrategicas?diagnostico_id=eq.${encodeURIComponent(diagnosticId)}&select=id,tipo,status,data,realizada_em,revisao_origem_id,revisao_numero,revisao_motivo,revisao_criada_por,revisao_criada_em,consultor&order=created_at.asc`);return Response.json({rounds})}catch(error:any){return Response.json({error:error?.message||'Não foi possível consultar as revisões.'},{status:500})}}

export async function POST(req:Request){try{const profile=await access(req);if(profile?.role!=='master')return Response.json({error:'Não autorizado.'},{status:401});const body=await req.json(),sourceId=String(body.reuniao_id||''),reason=String(body.motivo||'').trim();if(!sourceId)return Response.json({error:'Informe a reunião estratégica de origem.'},{status:400});const source=(await db(`reunioes_estrategicas?id=eq.${encodeURIComponent(sourceId)}&select=*&limit=1`))[0];if(!source)return Response.json({error:'Reunião estratégica de origem não localizada.'},{status:404});if(source.status!=='Realizada')return Response.json({error:'A Nova Revisão Estratégica deve partir de uma reunião ou revisão concluída.'},{status:409});const rounds=await db(`reunioes_estrategicas?diagnostico_id=eq.${encodeURIComponent(source.diagnostico_id)}&select=revisao_numero`),number=Math.max(1,...rounds.map((item:any)=>Number(item.revisao_numero||1)))+1,now=new Date().toISOString(),meetingData=clearConclusion(source.dados_reuniao),payload={empresa_id:source.empresa_id,diagnostico_id:source.diagnostico_id,tipo:'Revisão Estratégica',responsavel:source.responsavel,responsavel_nome:source.responsavel_nome,consultor:source.consultor||profile.email,status:'Agendada',data:now.slice(0,10),hora:now.slice(11,16),duracao:source.duracao||60,observacoes:source.observacoes,dados_reuniao:meetingData,consultant_initial_hypothesis:source.consultant_initial_hypothesis,prepared_specific_questions:source.prepared_specific_questions,consultant_notes:source.consultant_notes,autosave_version:0,revisao_origem_id:source.id,revisao_numero:number,revisao_motivo:reason||null,revisao_criada_por:profile.email,revisao_criada_em:now,created_at:now,updated_at:now},created=(await db('reunioes_estrategicas',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)}))[0];await db('reuniao_estrategica_historico',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({empresa_id:source.empresa_id,diagnostico_id:source.diagnostico_id,reuniao_id:created.id,acao:`Revisão Estratégica #${number} criada`,responsavel:profile.email,status:'Agendada',snapshot:{revisao_origem_id:source.id,revisao_numero:number,motivo:reason||null,criada_em:now}})});await db('dossie_eventos',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({empresa_id:source.empresa_id,diagnostico_id:source.diagnostico_id,tipo:'Revisão Estratégica',titulo:`Revisão Estratégica #${number} criada`,descricao:reason||'Nova rodada de validação criada a partir da reunião anterior.',data_evento:now,concluido:false})});return Response.json({ok:true,revision:created,message:`Revisão Estratégica #${number} criada. Os dados anteriores foram carregados como ponto de partida.`},{status:201})}catch(error:any){return Response.json({error:error?.message||'Não foi possível criar a Nova Revisão Estratégica.'},{status:500})}}
