import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import { LandingMotion } from "./LandingMotion";
import { InstitutionalFaq } from "./InstitutionalFaq";
import { PublicHeader } from "./PublicHeader";
import { WebchatWidget } from "./WebchatWidget";
import styles from "./LandingPage.module.css";

const problems = ["Clientes sem retorno", "Atendimento desorganizado", "Falta de processo comercial", "Oportunidades sem acompanhamento", "Pouca visibilidade sobre o funil", "Dificuldade para saber o que realmente virou venda"];
const toolSolutions = [["CRM", "Organize oportunidades, histórico, responsáveis e etapas comerciais."], ["Agente de Inteligência Artificial", "Automatize atendimento, qualificação, consultas e ações."], ["Automação de Atendimento", "Organize canais, respostas, distribuição e encaminhamentos."], ["Automação de Processos", "Reduza tarefas manuais e conecte etapas da operação."], ["Integração entre Sistemas", "Faça seus sistemas trocarem informações e executarem processos de forma integrada."]];
const toolStages = [["01", "Entendemos a necessidade", "Um questionário rápido nos ajuda a compreender o cenário e preparar uma configuração inicial."], ["02", "Preparamos a solução", "Estruturamos os recursos e a configuração mais adequada para a necessidade apresentada."], ["03", "Validamos com você", "Na reunião, revisamos a solução, ajustamos o escopo e apresentamos o investimento."], ["04", "Implantamos", "Com a solução aprovada, iniciamos a implantação e a configuração dos recursos."]];
const pillars = [["Atrair", "Entender como a empresa gera oportunidades e cria demanda."], ["Converter", "Organizar atendimento, qualificação e transformação de oportunidades em vendas."], ["Crescer", "Medir resultados, ganhar previsibilidade e evoluir a operação comercial."]];
const consultingStages = [["01", "Diagnóstico", "Analisamos a operação e calculamos seu Índice Escala Growth."], ["02", "Estratégia", "Interpretamos o diagnóstico, definimos prioridades e estruturamos o plano."], ["03", "Implantação", "Transformamos o plano acordado em processos, tecnologia e execução."], ["04", "Evolução", "Acompanhamos indicadores e orientamos as próximas decisões."]];
const technologyBrands = [{ name: "Meta", src: "/technology-meta.png", width: 738, height: 414 }, { name: "WhatsApp", src: "/technology-whatsapp.jpg", width: 1920, height: 1080 }, { name: "Google", src: "/technology-google.png", width: 597, height: 335 }, { name: "OpenAI", src: "/technology-openai.png", width: 738, height: 414 }, { name: "Nimble", src: "/technology-nimble.png", width: 368, height: 112 }];
const benefits = ["Oportunidades mais organizadas", "Processos comerciais mais claros", "Melhor acompanhamento dos leads", "Maior visibilidade sobre o funil", "Indicadores para tomada de decisão", "Melhor entendimento da origem das oportunidades", "Capacidade de identificar gargalos", "Tecnologia utilizada de forma estratégica", "Evolução acompanhada ao longo do projeto"];
const faqs = [
  ["Qual a diferença entre Implantação de Ferramentas e Consultoria de Crescimento Comercial?", "A Implantação é para empresas que já sabem qual capacidade precisam colocar em funcionamento. A Consultoria começa entendendo a operação, identificando gargalos e definindo prioridades antes da execução."],
  ["Preciso fazer o Diagnóstico Growth para contratar uma ferramenta?", "Não. Se sua empresa já sabe o que precisa implantar, pode seguir diretamente pelo fluxo de Implantação de Ferramentas."],
  ["Já sei que preciso de um CRM ou Agente de IA. Como funciona?", "Você informa sua necessidade, nós preparamos uma configuração inicial e, em reunião, validamos o escopo, os recursos e o investimento antes da implantação."],
  ["Não sei exatamente o que minha empresa precisa. Por onde começo?", "Comece pela Consultoria de Crescimento Comercial. O Diagnóstico Growth ajuda a localizar os principais gargalos e orientar o próximo passo."],
  ["A Escala Vendas trabalha apenas com tecnologia?", "Não. Conectamos estratégia, processos e tecnologia. A ferramenta é aplicada quando contribui para resolver uma necessidade real da operação."],
  ["É possível contratar Consultoria e Implantação de Ferramentas juntas?", "Sim. Quando o plano da Consultoria exige novas capacidades, a implantação pode fazer parte do projeto acordado."],
  ["Como funciona a implantação?", "Entendemos a necessidade, preparamos a solução, validamos o escopo e o investimento com você e então iniciamos a configuração dos recursos aprovados."],
  ["Como funciona o acompanhamento da Consultoria?", "A evolução é acompanhada por ações, responsáveis, prazos e indicadores, respeitando o plano acordado e o momento da empresa."],
];

export function LandingPage() { return <div className={styles.landingPage} data-landing-page>
  <LandingMotion /><PublicHeader />
  <main>
    <section className={styles.heroSection} aria-labelledby="landing-title"><div className={styles.heroContentNew}><div className={styles.heroCopy}><span className={styles.eyebrow}>Escala Vendas</span><h1 id="landing-title">Estratégia e tecnologia para sua empresa <em>vender melhor.</em></h1><p className={styles.heroLead}>A Escala Vendas ajuda empresas a organizar sua operação comercial, implantar as ferramentas certas e construir processos mais eficientes para vender e atender melhor.</p></div><div className={styles.heroChoices} aria-label="Escolha o caminho mais adequado para sua empresa"><ServiceChoice eyebrow="Implantação de Ferramentas" title="Já sabe o que precisa implantar?" text="CRM, Inteligência Artificial, automações e integrações para organizar e melhorar sua operação Comercial e de Atendimento." href="/implantacao-ferramentas" cta="Implantar ferramentas" /><ServiceChoice eyebrow="Consultoria de Crescimento Comercial" title="Quer melhorar suas vendas?" text="Entendemos sua operação, identificamos os principais gargalos e construímos com você um caminho para vender melhor e crescer com mais controle." href="/escala-growth" cta="Melhorar minhas vendas" note="Método Escala Growth" /></div></div></section>

    <section id="implantacao" className={styles.toolsSection}><div className={styles.sectionInner}><Heading eyebrow="Implantação de Ferramentas" id="tools-title" title="Tecnologia para organizar a operação e ganhar capacidade de execução."><p>Para empresas que já sabem o que precisam e querem colocar a solução para funcionar com segurança, integração e acompanhamento.</p></Heading><div className={styles.toolSolutionGrid} data-reveal-group="tools">{toolSolutions.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className={styles.sectionAction}><Link className={styles.primaryButton} href="/implantacao-ferramentas">Conhecer Implantação de Ferramentas</Link></div><div className={styles.technologyBrands} data-reveal><span className={styles.eyebrow}>Tecnologias que utilizamos</span><p>Um ecossistema de tecnologias consolidadas para conectar atendimento, gestão, automação, aquisição e inteligência.</p><ul aria-label="Tecnologias utilizadas">{technologyBrands.map(brand=><li key={brand.name}><Image src={brand.src} alt={brand.name} width={brand.width} height={brand.height} sizes="(max-width: 560px) 42vw, (max-width: 1080px) 28vw, 190px" /></li>)}</ul></div></div></section>

    <section className={styles.toolProcessSection}><div className={styles.sectionInner}><Heading eyebrow="Como funciona" id="tool-process-title" title="Você já sabe o que precisa. Nós ajudamos a transformar isso em uma solução." /><ol className={styles.stageFlow} data-reveal data-reveal-group="tool-stages">{toolStages.map(([number,title,text])=><li key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></li>)}</ol><div className={styles.sectionAction}><Link className={styles.primaryButton} href="/implantacao-ferramentas/diagnostico">Quero implantar ferramentas</Link></div></div></section>

    <section id="empresa" className={styles.problemSection}><div className={styles.sectionInner}><Heading eyebrow="O problema que resolvemos" id="problem-title" title="Mais oportunidades não resolvem uma operação comercial desorganizada."><p>Empresas podem perder vendas mesmo quando existe demanda. O problema aparece quando os contatos chegam por diferentes canais, o atendimento não segue um processo claro e ninguém consegue acompanhar cada oportunidade até a decisão.</p></Heading><ul className={styles.problemGrid} data-reveal-group="problems">{problems.map((item,i)=><li key={item}><span>0{i+1}</span><strong>{item}</strong></li>)}</ul><div className={styles.bridgeStatement} data-reveal><strong>Alguns problemas exigem tecnologia.<br />Outros exigem estratégia.<br />Muitas vezes, os dois.</strong></div></div></section>

    <section id="consultoria" className={styles.methodSection}><div className={styles.sectionInner}><Heading eyebrow="Consultoria de Crescimento Comercial" id="consulting-title" title="Quando o problema não está claro, começamos entendendo a operação."><p>A Consultoria de Crescimento Comercial utiliza o Método Escala Growth para identificar onde sua operação está perdendo força, definir prioridades e construir um caminho para melhorar vendas e crescimento.</p><strong className={styles.brandArchitecture}>Escala Vendas é a empresa. Escala Growth é o método utilizado pela Consultoria.</strong></Heading><div className={styles.pillarGrid} data-reveal-group="pillars">{pillars.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className={styles.methodSupport}>O Método orienta a análise da operação comercial, identifica prioridades e transforma essas prioridades em um plano de evolução executável.</p><div className={styles.dualActions}><Link className={styles.lightButton} href="/escala-growth">Conhecer a Consultoria</Link><Link className={styles.outlineLightButton} href="/diagnostico">Fazer Diagnóstico Growth</Link></div></div></section>

    <section id="como-atuamos" className={styles.stagesSection}><div className={styles.sectionInner}><Heading eyebrow="Jornada da Consultoria de Crescimento Comercial" id="stages-title" title="Do diagnóstico à evolução da operação comercial." /><ol className={styles.stageFlow} data-reveal data-reveal-group="stages">{consultingStages.map(([number,title,text])=><li key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></div></section>
    <section className={styles.benefitsSection}><div className={styles.sectionInner}><Heading eyebrow="O que muda na prática" id="benefits-title" title="Mais clareza para acompanhar a operação e decidir o próximo passo." /><ul className={styles.benefitList} data-reveal-group="benefits">{benefits.map(item=><li key={item}><span>✓</span>{item}</li>)}</ul></div></section>

    <section id="quem-conduz" className={styles.aboutSection}><div className={styles.sectionInner}><div className={styles.aboutCopy} data-reveal data-reveal-direction="left"><span className={styles.eyebrow}>Quem conduz</span><h2>Experiência para conectar estratégia, processos e tecnologia.</h2><p>A Escala Vendas atua na organização e evolução de operações comerciais, conectando estratégia, processos e tecnologia para ajudar empresas a acompanhar melhor suas oportunidades e estruturar seu crescimento.</p><blockquote>Tecnologia para organizar.<br />Pessoas para vender.</blockquote></div><aside className={styles.consultantCard} data-reveal data-reveal-direction="right"><div className={styles.consultantPhotoFrame}><Image className={styles.consultantPhoto} src="/teofilo-oliveira-fagundes.jpg" alt="Teófilo Oliveira Fagundes, fundador e consultor da Escala Vendas." width={1200} height={1500} sizes="(max-width: 820px) calc(100vw - 56px), 420px" /></div><div className={styles.consultantContent}><h3>Teófilo Oliveira Fagundes</h3><strong>Fundador e Consultor — Escala Vendas</strong><p>Experiência em vendas consultivas aplicada à evolução de operações comerciais.</p></div></aside></div></section>

    <section id="faq" className={styles.faqSection}><div className={styles.faqInner}><Heading eyebrow="Perguntas frequentes" id="faq-title" title="Escolha o caminho certo para sua empresa." /><InstitutionalFaq items={faqs} /></div></section>
    <section className={styles.finalCta}><div data-reveal><span className={styles.eyebrowLight}>Seu próximo passo</span><h2>Qual é o próximo passo da sua empresa?</h2><p>Escolha o caminho que mais combina com o momento atual da sua operação.</p><div className={styles.finalActions}><Link className={styles.lightButton} href="/implantacao-ferramentas">Quero implantar ferramentas</Link><Link className={styles.outlineLightButton} href="/escala-growth">Quero melhorar minhas vendas</Link></div></div></section>
  </main>
  <footer id="contato" className={styles.footer}><div className={styles.footerInner}><div><strong>Escala Vendas LTDA</strong><p>CNPJ: 60.328.666/0001-03</p><p>Rua Marechal Deodoro, 450, sala 505<br />Centro · Curitiba – PR · CEP 80010-010</p></div><div><strong>Soluções</strong><a href="#implantacao">Implantação de Ferramentas</a><a href="#consultoria">Consultoria Comercial</a><Link href="/escala-growth">Método Escala Growth</Link><Link href="/diagnostico">Diagnóstico</Link></div><WebchatWidget /><nav aria-label="Acesso"><strong>Acesso</strong><Link href="/login">Área do Cliente</Link><a href="mailto:contato@escalavendas.com.br">Contato</a><a href="#empresa">Empresa</a></nav></div><p className={styles.copyright}>© {new Date().getFullYear()} Escala Vendas. Todos os direitos reservados.</p></footer>
</div> }

function ServiceChoice({eyebrow,title,text,href,cta,note}:{eyebrow:string;title:string;text:string;href:string;cta:string;note?:string}){return <article><span>{eyebrow}</span><h2>{title}</h2><p>{text}</p>{note&&<small>{note}</small>}<Link href={href}>{cta}<b aria-hidden="true">→</b></Link></article>}
function Heading({eyebrow,id,title,children}:{eyebrow:string;id:string;title:string;children?:ReactNode}){return <div className={styles.sectionHeading} data-reveal><span className={styles.eyebrow}>{eyebrow}</span><h2 id={id}>{title}</h2>{children}</div>}
