import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import { LandingMotion } from "./LandingMotion";
import { InstitutionalFaq } from "./InstitutionalFaq";
import { PublicHeader } from "./PublicHeader";
import { WebchatWidget } from "./WebchatWidget";
import styles from "./LandingPage.module.css";

const problems = ["Clientes sem retorno", "Atendimento desorganizado", "Falta de processo comercial", "Oportunidades sem acompanhamento", "Pouca visibilidade sobre o funil", "Dificuldade para saber o que realmente virou venda"];
const pillars = [["Atrair", "Como sua empresa gera oportunidades e cria demanda de forma consistente."], ["Converter", "Como atende, qualifica, acompanha e transforma oportunidades em vendas."], ["Crescer", "Como mede resultados, ganha previsibilidade e evolui a operação comercial."]];
const stages = [["01", "Diagnóstico", "Analisamos como a empresa atrai, atende, acompanha e converte oportunidades e calculamos seu Índice Escala Growth."], ["02", "Estratégia", "Na Reunião Estratégica, interpretamos o diagnóstico, definimos prioridades e estruturamos um Plano Estratégico de evolução."], ["03", "Implantação", "Transformamos o plano em execução, estruturando processos, tecnologia, automações, aquisição, mensuração e os recursos definidos para o projeto."], ["04", "Evolução", "Acompanhamos indicadores, execução e evolução da operação para que novas decisões sejam tomadas com base em dados e resultados."]];
const capabilities: [string, string[]][] = [
  ["Organização comercial", ["Processos", "Funil e pipelines", "CRM", "Gestão de oportunidades"]],
  ["Atendimento e relacionamento", ["Organização dos canais", "Atendimento e qualificação", "Acompanhamento", "Automações"]],
  ["Aquisição", ["Geração de demanda", "Google Ads e Meta Ads", "Landing Pages", "Estratégias de aquisição"]],
  ["Integração", ["APIs", "Webhooks", "Integrações entre sistemas", "Automação de fluxos"]],
  ["Mensuração", ["Dashboards", "Indicadores", "Origem das oportunidades", "Acompanhamento do funil"]],
  ["Capacitação", ["Processos", "Uso das soluções implantadas", "Orientação da equipe", "Evolução operacional"]],
];
const technology = [["Atendimento e relacionamento", "WhatsApp Oficial, Instagram Direct, Facebook Messenger, Webchat e canais digitais integrados."], ["Gestão comercial", "CRM, pipelines, gestão de oportunidades e acompanhamento comercial."], ["Inteligência e automação", "Agentes de IA, automações, fluxos inteligentes, qualificação e apoio ao atendimento."], ["Integração", "APIs, Webhooks e integrações entre sistemas."], ["Aquisição", "Google Ads, Meta Ads e Landing Pages."], ["Gestão e mensuração", "Dashboards, indicadores, origem das oportunidades e acompanhamento de resultados."]];
const technologyBrands = [
  { name: "Meta", src: "/technology-meta.png", width: 738, height: 414 },
  { name: "WhatsApp", src: "/technology-whatsapp.jpg", width: 1920, height: 1080 },
  { name: "Google", src: "/technology-google.png", width: 597, height: 335 },
  { name: "OpenAI", src: "/technology-openai.png", width: 738, height: 414 },
  { name: "Nimble", src: "/technology-nimble.png", width: 368, height: 112 },
];
const benefits = ["Oportunidades mais organizadas", "Processos comerciais mais claros", "Melhor acompanhamento dos leads", "Maior visibilidade sobre o funil", "Indicadores para tomada de decisão", "Melhor entendimento da origem das oportunidades", "Capacidade de identificar gargalos", "Tecnologia utilizada de forma estratégica", "Evolução acompanhada ao longo do projeto"];
const faqs = [
  ["O que é o Método Escala Growth?", "É o método utilizado pela Escala Vendas para diagnosticar a operação comercial, identificar prioridades e transformar a análise em um plano de evolução executável."],
  ["A Escala Vendas é uma empresa de software?", "Não. A Escala Vendas organiza e evolui operações comerciais conectando estratégia, processos, tecnologia, implantação e acompanhamento. A tecnologia é um meio para executar a estratégia."],
  ["Preciso trocar as ferramentas que minha empresa já utiliza?", "Não necessariamente. Primeiro entendemos a estrutura atual e o problema. Os recursos existentes podem ser mantidos, integrados ou evoluídos conforme a necessidade identificada."],
  ["A Escala Vendas também faz a implantação?", "Sim, quando a implantação faz parte do escopo contratado. O plano pode envolver processos, tecnologia, automações, aquisição, mensuração, integrações e capacitação."],
  ["O Diagnóstico já é uma proposta comercial?", "Não. O Diagnóstico identifica forças, gargalos e prioridades. Uma proposta é estruturada posteriormente, quando houver aderência e um escopo definido."],
  ["A tecnologia é obrigatória em todos os projetos?", "Não. A tecnologia entra quando ajuda a resolver o problema identificado e a executar a estratégia com mais organização, integração e informação."],
  ["Como funciona o acompanhamento depois da implantação?", "A evolução é acompanhada por indicadores, execução e novas decisões, respeitando o escopo e o momento da operação comercial."],
  ["Qual é o primeiro passo?", "O primeiro passo é realizar o Diagnóstico Escala Growth para compreender como a operação funciona hoje e quais pontos merecem prioridade."],
];

export function LandingPage() {
  return <div className={styles.landingPage} data-landing-page>
    <LandingMotion /><PublicHeader />
    <main>
      <section className={styles.heroSection} aria-labelledby="landing-title"><div className={styles.heroContent}>
        <div className={styles.heroCopy}><span className={styles.eyebrow}>Escala Vendas</span><h1 id="landing-title">Toda empresa cresce quando consegue acompanhar <em>cada oportunidade.</em></h1><p className={styles.heroLead}>A Escala Vendas organiza operações comerciais unindo estratégia, processos e tecnologia para transformar oportunidades em crescimento com mais controle e previsibilidade.</p><p className={styles.heroComplement}>Antes de buscar mais leads, é preciso entender como sua empresa atrai, atende, acompanha e converte as oportunidades que já chegam.</p><div className={styles.heroButtons}><a className={styles.primaryButton} href="#metodo">Conheça o Método Escala Growth</a><Link className={styles.secondaryButton} href="/diagnostico">Faça seu Diagnóstico</Link></div></div>
        <aside className={styles.heroStatement}><span>Estratégia comercial aplicada</span><h2>Organizar antes de acelerar.</h2><p>Entender o cenário, definir prioridades e implantar os recursos certos para que cada oportunidade possa ser acompanhada.</p><div className={styles.statementLine}><i /><strong>Estratégia</strong><i /><strong>Execução</strong><i /><strong>Evolução</strong></div></aside>
      </div></section>

      <section className={styles.problemSection} aria-labelledby="problem-title"><div className={styles.sectionInner}><Heading eyebrow="O problema que resolvemos" id="problem-title" title="Mais oportunidades não resolvem uma operação comercial desorganizada."><p>Empresas podem perder vendas mesmo quando existe demanda. O problema aparece quando os contatos chegam por diferentes canais, o atendimento não segue um processo claro e ninguém consegue acompanhar cada oportunidade até a decisão.</p></Heading><ul className={styles.problemGrid} data-reveal-group="problems">{problems.map((item, i) => <li key={item}><span>0{i + 1}</span><strong>{item}</strong></li>)}</ul><p className={styles.sectionConclusion} data-reveal>Antes de vender mais, é preciso vender melhor.</p></div></section>

      <section id="empresa" className={styles.visionSection} aria-labelledby="vision-title"><div className={styles.sectionInner}><Heading eyebrow="Nossa visão" id="vision-title" title="Crescimento comercial exige mais do que gerar leads."><p>Gerar demanda é importante. Mas crescimento sustentável depende da capacidade de transformar cada oportunidade em um processo que possa ser acompanhado, medido e melhorado.</p><p>Por isso, a Escala Vendas trabalha conectando estratégia, processos, tecnologia, implantação e acompanhamento. Primeiro entendemos o problema. Depois definimos o caminho. Só então utilizamos os recursos necessários para colocar a estratégia em prática.</p></Heading><ol className={styles.visionFlow} data-reveal data-reveal-group="vision">{["Estratégia", "Processos", "Tecnologia", "Implantação", "Acompanhamento"].map((item,index) => <li key={item}><span>0{index+1}</span><strong>{item}</strong></li>)}</ol></div></section>

      <section id="metodo" className={styles.methodSection} aria-labelledby="method-title"><div className={styles.sectionInner}><Heading eyebrow="Método Escala Growth" id="method-title" title="Um método para entender onde sua operação está e definir o próximo passo."><p>O Escala Growth é o método utilizado pela Escala Vendas para diagnosticar a operação comercial, identificar prioridades e transformar análise em um plano de evolução executável.</p><strong className={styles.brandArchitecture}>Escala Vendas é a empresa. Escala Growth é o método.</strong></Heading><div className={styles.pillarGrid} data-reveal-group="pillars">{pillars.map(([title, text], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section id="como-atuamos" className={styles.stagesSection} aria-labelledby="stages-title"><div className={styles.sectionInner}><Heading eyebrow="Como atuamos" id="stages-title" title="Da análise à evolução da operação comercial." /><ol className={styles.stageFlow} data-reveal data-reveal-group="stages">{stages.map(([number, title, text]) => <li key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></div></section>

      <section className={styles.capabilitySection} aria-labelledby="capability-title"><div className={styles.sectionInner}><Heading eyebrow="Da estratégia à execução" id="capability-title" title="Planejamento só gera valor quando consegue sair do papel."><p>A Escala Vendas não encerra o trabalho na recomendação. Quando a implantação faz parte do projeto contratado, estruturamos os recursos necessários para colocar o plano definido em funcionamento.</p></Heading><div className={styles.capabilityGrid} data-reveal-group="capabilities">{capabilities.map(([title, items]) => <article key={title}><h3>{title}</h3><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></article>)}</div><p className={styles.subtleNote}>As soluções dependem das necessidades identificadas e do escopo contratado. Nem todos os recursos fazem parte de todos os projetos.</p></div></section>

      <section id="tecnologia" className={styles.technologySection} aria-labelledby="technology-title"><div className={styles.sectionInner}><div className={styles.technologyIntro} data-reveal><span className={styles.eyebrowLight}>Tecnologia</span><h2 id="technology-title">Estratégia define o caminho.<br />Tecnologia dá escala à execução.</h2><p>Não começamos escolhendo ferramentas. Primeiro entendemos o problema, definimos prioridades e estruturamos a estratégia. A tecnologia entra para organizar processos, conectar canais, automatizar tarefas, acompanhar oportunidades e gerar informação para decisões melhores.</p></div><div className={styles.technologyGrid} data-reveal-group="technology">{technology.map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div><blockquote data-reveal>A tecnologia certa é aquela que resolve o problema certo.</blockquote><div className={styles.technologyBrands} data-reveal><span className={styles.eyebrowLight}>Tecnologias que utilizamos</span><p>Um ecossistema de tecnologias consolidadas para conectar atendimento, gestão, automação, aquisição e mensuração.</p><ul aria-label="Tecnologias utilizadas">{technologyBrands.map(brand => <li key={brand.name}><Image src={brand.src} alt={brand.name} width={brand.width} height={brand.height} sizes="(max-width: 560px) 42vw, (max-width: 1080px) 28vw, 190px" /></li>)}</ul></div></div></section>

      <section className={styles.benefitsSection} aria-labelledby="benefits-title"><div className={styles.sectionInner}><Heading eyebrow="O que muda na prática" id="benefits-title" title="Mais clareza para acompanhar a operação e decidir o próximo passo." /><ul className={styles.benefitList} data-reveal-group="benefits">{benefits.map(item => <li key={item}><span>✓</span>{item}</li>)}</ul></div></section>

      <section id="quem-conduz" className={styles.aboutSection} aria-labelledby="about-title"><div className={styles.sectionInner}><div className={styles.aboutCopy} data-reveal data-reveal-direction="left"><span className={styles.eyebrow}>Quem conduz</span><h2 id="about-title">Experiência para transformar estratégia em execução.</h2><p>A Escala Vendas atua na organização e evolução de operações comerciais, conectando estratégia, processos e tecnologia para ajudar empresas a acompanhar melhor suas oportunidades e estruturar seu crescimento.</p><blockquote>Tecnologia para organizar.<br />Pessoas para vender.</blockquote></div><aside className={styles.consultantCard} data-reveal data-reveal-direction="right"><div className={styles.consultantPhotoFrame}><Image className={styles.consultantPhoto} src="/teofilo-oliveira-fagundes.jpg" alt="Teófilo Oliveira Fagundes, fundador e consultor da Escala Vendas." width={1200} height={1500} sizes="(max-width: 820px) calc(100vw - 56px), 420px" /></div><div className={styles.consultantContent}><h3>Teófilo Oliveira Fagundes</h3><strong>Fundador e Consultor — Escala Vendas</strong><p>Experiência em tecnologia, gestão de projetos e vendas consultivas aplicada à evolução de operações comerciais.</p></div></aside></div></section>

      <section id="faq" className={styles.faqSection} aria-labelledby="faq-title"><div className={styles.faqInner}><Heading eyebrow="Perguntas frequentes" id="faq-title" title="Entenda como a Escala Vendas atua." /><InstitutionalFaq items={faqs} /></div></section>
      <section className={styles.finalCta} aria-labelledby="final-cta-title"><div data-reveal><span className={styles.eyebrowLight}>Seu próximo passo</span><h2 id="final-cta-title">Toda oportunidade conta.</h2><p>Descubra como sua operação comercial está estruturada hoje e quais pontos merecem prioridade para evoluir.</p><div className={styles.finalActions}><Link className={styles.lightButton} href="/diagnostico">Fazer meu Diagnóstico Escala Growth</Link></div></div></section>
    </main>
    <footer id="contato" className={styles.footer}><div className={styles.footerInner}><div><strong>Escala Vendas LTDA</strong><p>CNPJ: 60.328.666/0001-03</p><p>Rua Marechal Deodoro, 450, sala 505<br />Centro · Curitiba – PR · CEP 80010-010</p></div><div><strong>Contato</strong><a href="mailto:contato@escalavendas.com.br">contato@escalavendas.com.br</a><nav><a href="#empresa">Empresa</a><a href="#metodo">Método</a><a href="#como-atuamos">Como atuamos</a><a href="#tecnologia">Tecnologia</a></nav></div><WebchatWidget /><nav aria-label="Acesso"><strong>Acesso</strong><Link href="/diagnostico">Diagnóstico</Link><Link href="/login">Área do cliente</Link></nav></div><p className={styles.copyright}>© {new Date().getFullYear()} Escala Vendas. Todos os direitos reservados.</p></footer>
  </div>;
}

function Heading({ eyebrow, id, title, children }: { eyebrow: string; id: string; title: string; children?: ReactNode }) {
  return <div className={styles.sectionHeading} data-reveal><span className={styles.eyebrow}>{eyebrow}</span><h2 id={id}>{title}</h2>{children}</div>;
}
